### ISSUE TITLE
patchEntity add 

### ISSUE THREAD

**Issue by lucasthibau** [cakephp/cakephp#10106]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)
* CakePHP Version: 3.4

Before you save an array is necessary to treat the data with patchEntity, but in this array you need to set each index so it saves the data, what if the patchEntity does it automatcally with an boolean value?

Today we have to do this:

```php
$arr = ['index1' => 'value1', 'index2' => 'value2'];
$var = $this->Model->patchEntity($entity, $arr);
//return an object
```

I immagined the following:

```php
$arr = ['value1', 'value2'];
$var = $this->Model->patchEntity($entity, $arr, true);
//return the same object as before
```

**Comment by markstory** [comment]
In the proposed change, how do you know which attributes are being updated?

**Comment by lucasthibau** [comment]
In the same order as the database tables, or model.

**Comment by ADmad** [comment]
Relying on field order is a bad idea.

**Comment by lucasthibau** [comment]
That's why you can set it to true or false.

**Comment by markstory** [comment]
I'm not not a big fan of methods with bool flags in general. I'm also not a fan of implicit ordering that can change behavior when the existing associative array is easy to understand and simple to operate.

In what kind of scenarios do you find yourself needing this behavior?

**Comment by lucasthibau** [comment]
I just imagined one simple way to do the same thing on tables with lots of columns. The user should decide if use it or no, the default remain as it is and implicit.

**Comment by inoas** [comment]
I don't think it is a good idea because it is easily misused being lazy instead of explicit. Then later on it becomes error prone. There are for sure reasons (say big bulks of well ordered data) but you can easily transform arrays and/or push them through an anon function.

It could be a good community plugin @ https://github.com/FriendsOfCake/awesome-cakephp

**Comment by lucasthibau** [comment]
I agree that it can become a problem in the future, but I still think it's a good ideia, if well used.

**Comment by ADmad** [comment]
@lucasthibau You can implement this feature for yourself by adding a `AppTable::patchEntity()` and making all your table extend `AppTable` instead of `Table`.

Closing as implementing this feature in core itself is not a good idea and it can easily lead to problem due to implicit reliance on specific ordering.
