### ISSUE TITLE
'cake plugin assets copy' doesn't update assets

### ISSUE THREAD

**Issue by siran** [cakephp/cakephp#10151]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.13
* Platform and Target: doesn't really matter

### What you did
I ran `$ bin/cake plugin assets copy`

### What happened
The assets of the plugins whose folders didn't yet existed in webroot/{plugin} were copied, but if the folder of the plugin already existed in webroot the assets weren't updated (or at least a message like ``Copied assets to directory  ...` wasn't shown.

### What you expected to happen
I expected for all assets to be updated in their corresponding webroot/{plugin} folders

**Comment by siran** [comment]
updated...

**Comment by mirko-pagliai** [comment]
This is quite difficult and it is for this reason that it is better to make symbolic links and that the copy is only an alternative when you can not create symbolic links.

We should check the correspondence file by file. Or calculate the checksum of the directories and, if they do not match, delete and re-create the copy.

But I repeat: we should use symbolic links in order to avoid all this.

**Comment by ADmad** [comment]
We could add an `--overwrite` flag.

**Comment by ADmad** [comment]
@siran Would you like to submit a patch adding the new flag as suggested?

**Comment by siran** [comment]
@ADmad  I agree with the flag. That is basically what I currently do: "repeal and replace" haha. That can take a while, but I would love to help. 
@mirko-pagliai I understand the symbolic link solution. I would use it if the system I'm working had support for it. I currently can't count on mod_rewirte not symbolic links :/
