### ISSUE TITLE
Some of the changes should be considered in version cake 4.x

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10202]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

I am a Chinese and my english is very bad; now I try to express my feelings after using cake3 and cake2;

 > I do not think cake is a fashionable php framework like laravel and symfony. Defects need to be improved。

## Add dependency injection
Di is now a necessary part of the modernization framework and has been implemented in yii2, laravel, symfony.
When I read the cake source, I often see a lot of static classes like `App::path() App::core, Plugin::path, Cache::write, Cache::read, Log::info`. This lack of design aesthetic.  I think that all classes should be not designed to be static except for factory classes and factory methods. The core of cake should introduce the concept of dependency injection, register all components as services,
```
$container->get ('cache')->write, $container->get ('log')->write
```

## Support multiple application namespace

In a project I often need to create multiple independent applications, such as `MainApplication`, `AdminApplication`, `ApiApplication`, and now I can only put them in the App namespace using Prefix distinction, in fact, I hope that these three Can be independent of each other, not just the controller, the model and view are separated too,  I think the concept of symfony bundle is very good, cake can learn from.

PS: Plugin means additional functionality, but these three parts as important, so I feel through the plugin to achieve very strange. I do not know who I should put in the `plugins` who should stay in `src`

## Improve routing.

1. Arguments are confusing, 
```
$routes->connect('/posts/:id', [‘controller’=>'Posts', 'action'=>'view'], [
   '_name' => 'post_view',
   'id' => '\d+',
   'pass' => ['id'],
   'host' => 'foor.domian.com',
   'methods' => [Http::POST, HTTP::PUT, ...']
]);
```
Argument 3 is really a mess. `options` is not everything, It should be divided into defaults, requrements, options, host, method

2.Routing parameter delimiter defect
like：
PS:I want it match `/images/2017/0101/foo.jpg/thumbnail/500x300`
```
$routes->connect('/images/:file/thumbnail/:widthx:height', ...]);
```
<b>`/:widthx:height`</b>, Routing will mistake the variable name `width`  and `widthx`
I recommend using {}， Change to '/images/:file/thumbnail/{width}x{height}'

## Add third-party template engine support
You know, a lot of template engines like twig are really great

## Follow the psr standard
You know that psr does not recommend the `_method` naming method for private and protected methods. (method name should be a verb，But you often see `Request::data(),App::path ()`)
and add PSR6 support for caching

## Remove all constants
Maybe `$kernel->getAppPath(), $kernel->getCachePath() `  more readable 

finally,  Cake4 should be a disruptive version. Not just cake3++

**Comment by slince** [comment]
Cake4 should be more design.

PS: I suggest that developers learn symfony, symfony really is very great, it has a lot of very fashionable concept.

**Comment by inoas** [comment]
> Support multiple application namespace

Now with PSR-7 middleware (similar to Rails' Rack) couldn't we create something like Rails Engines. Basically make plugins able to be stand-alone applications (if desired so)?

Ref: http://guides.rubyonrails.org/engines.html (Rails Engine)
Ref: https://www.amberbit.com/blog/2015/10/15/rails-mountable-engines/ (Rails Engine)
Ref: http://stackoverflow.com/questions/8997468/rails-engine-vs-rack-application (Rack App vs Rails Engine App)

* * *

> finally, Cake4 should be a disruptive version. Not just cake3++

_If_ you mean it should break BC everywhere even on its public interfaces, that is AFAIK not what has been communicated so far.

Personally I am torn, a big drawback of picking frameworks over selecting libraries and gluing them together is that once a major iteration of a framework is being released you may have troubles upgrading your application. So I like the conservative approach of 1.x/2.x and then 3.x/4.x.

However I just hope 4.x will not receive many new features but have a shorter "feature-adding" lifetime so that we will see 5.x soon and 4.x (which is basically a cleaned up 3.x) live alongside 5.x (which would be a "disruptive" version) - But that's just my wishes.

* * *

About PSR: I think there are those standards that will really improve interoperability (like PSR-7) and those just being cosmetic. I don't see a big benefit of adopting a cosmetics-standard that is not a clear/straightforward/100%-improvement, personally.

**Comment by markstory** [comment]
> Add dependency injection

All of the cake static classes allow dependency injection into each of the specific service locators. I'm not convinced that a global generic service locator (as shown in your example) is a good idea. It makes reading code harder, and impairs auto-completion in IDEs. With that said I'm open to discussing how we can fix specific places where dependencies cannot be injected.

> Support multiple application namespace

How would this differ from an application split into multiple plugins that co-exist in the same source repository? Conceptually that sounds similar to symfony bundles.

> Improve routing.

I completely agree that the current routing 'options' is messy. It is something I would like to fix in future versions. I feel like it can be done in a backwards compatible way though.

> Add third-party template engine support

There are existing plugins that support templating languages like twig. Are you looking for a more native integration into the framework? I personally use Twig in all of my projects, but I know there are many folks who prefer native PHP for their templating. We'd need to support both for quite sometime.

> Follow the psr standard

We do. The `_` on methods are 'should' not 'must'. Unfortunately adopting PSR-2 was done partway through the development of 3.0, and breaking compatibility on a large number of methods for cosmetic reasons was not something I felt was a wise decision.

> Remove all constants

Why? the readability argument feels very subjective. 

> finally, Cake4 should be a disruptive version. Not just cake3++

Given the feedback we've received about how hard the upgrade from 2.x to 3.x was, I get the feeling that the community is not interested in another burn everything type upgrade which is why we're trying to make the 3.x -> 4.0 migration similar to the symfony 2 -> symfony 3 migration which was pretty straightforward from what I've read. Large breaking change releases take a really long time to develop, test and adopt often leading to fragmented communities. Given that we're still in the midst of the 2 -> 3 upgrade it seems irresponsible to queue up yet another painful upgrade.

**Comment by slince** [comment]
@markstory  
> How would this differ from an application split into multiple plugins that co-exist in the same source repository? Conceptually that sounds similar to symfony bundles.

> PS: Plugin means additional functionality, but these three parts as important, so I feel through the plugin to achieve very strange. I do not know who I should put in the plugins who should stay in src

If I can put the “plugin“ in `src` directory is better;  Maybe cake should not limit the directory where the plugin is located

> Why? the readability argument feels very subjective.

- Readability, 
- Constant increases the coupling of the code;
- You know some cake core package will use constants. It would be very difficult to use the package independently.

PS: Cake core should not use any constant, app can.

> Add third-party template engine support

Twig and native can support, cakecan choose the renderer according to the template extension

> Add dependency injection
- Di container is the trend，cake should keep pace with the times
- Static class is a good way to solve dependencies, but what is the difference with functional programming?

> finally, Cake4 should be a disruptive version. Not just cake3++
You understand wrong, I mean cake core reconstruction but api keep backward compatible

**Comment by robertpustulka** [comment]
@markstory @slince 

Regarding DI. How about something in between. To have a SL/container(s) for global CakePHP "tools":

```php
$cakeApp->getEventManager() // Global EventManger instance
$cakeApp->getConfigure() // not static Configure
$cakeApp->getCache('month') // configured CacheEngine?
$cakeApp->getLog('console') // configured LogEngine
...
```
These could have correct type hinting.

We even don't need to provide our DI (there are lot's of them) but instead could allow to inject instances using setters.

Currently if you want to use the ORM outside CakePHP you depend on cakephp/core anyway and usually log or cache. Which means you're stuck with those old school "global" static service locators in your modern and well designed app :)

**Comment by markstory** [comment]
> Which means you're stuck with those old school "global" static service locators in your modern and well designed app :)

Not at all. One could put the TableLocator into their DI container and use just that.

If `$cakeApp` had service locators, how would that object be made available in controllers/shells?

**Comment by sdustinh** [comment]
A slimming of the framework combined with officially supported plugins for opt-in framework features would be a nice middle ground that would satisfy all. If you didn't want DI beyond what was provided you just would not require the plugin.

**Comment by slince** [comment]
@markstory  @robertpustulka 
> If $cakeApp had service locators, how would that object be made available in controllers/shells?

I think it can be obtained directly in the basic controller class and shell class 
```
//Get Application Core in controller or shell
$this->getKernel(); //le $cakeApp

//Get Di container in controller or shell
$this->getKernel()->getContainer(); 

//Get cache in controller or shell
$this->getKernel()->getCache();  //Alias $this->getKernel()->getContainer()->get('cache');

//Get log in controller or shell
$this->getKernel()->getLog();  //Alias $this->getKernel()->getContainer()->get('log');
```
PS： Note that cache and log must be designed as static classes and pre-registered as a service in bootstrap.php

**Comment by thinkingmedia** [comment]
I've used DI in Java, C++, C#, NodeJS and AngularJS. I even made one quickly in TypeScript. So I'm all in favor of the design pattern.

Let's keep in mind that this is **PHP** we're talking about. Dependency injection works *best* when it's transparent to the developer, and you don't have to do things like `$container->get('thing')`. Once you force a developer to do something like that, then they have deeply coupled all their code tightly to the DI framework. It becomes excessively difficult to remove the DI later or replace it with another implementation.

I've seen DI frameworks hurt many C# projects because of tight coupling.

Languages like C#, JavaScript and TypeScript allow you to add DI transparently to a class. Some DI engines inject directly to the constructor, and others inject directly to properties. It's all done via run-time class inspections.

Implementing a DI that works transparently in PHP using reflection would result in the slowly of web server's performance, and further complicated by the fact that PHP doesn't support typed properties or run-time annotations, or the adding of custom annotations. These are core language features that make DI so much easier to work.

But the most concerning thing I fear of DI in PHP is the need to bootstrap containers for every single web request. This is PHP we're talking about. It's not a server environment with persistent objects. Every time Apache or Nginx gets a HTTP request the entire Cake framework starting from `index.php` is executed. You would have to come up with a DI design that equals number of executed operations as the current 3.4 version of Cake. I don't think that's possible.

There is nothing stopping you from using DI in Cake 3.4 for your own classes.

What I recommend is any improvements to the middleware that would allow you to couple to a DI framework of your choice. Now that could be done for 3.5 without impacting performance, but I'm not sure if it is BC friendly.

Here are some DI frameworks for you to try.

http://php-di.org/
http://pimple.sensiolabs.org/

I would re-visit DI when newer versions of PHP come out. I suspect that support for annotations will be added sometime in the near future, and then we'll have the tools we need to do it right.

**Comment by slince** [comment]
@thinkingmedia  I have implemented the di container in my project; [https://github.com/slince/di](https://github.com/slince/di)
i recommend cake in the core implementation; i think too much static class is a typical lack of design, which is opportunistic;

About the use of di in the php framework, you can refer to these：

Symfony: [https://github.com/symfony/dependency-injection](https://github.com/symfony/dependency-injection)
laravel: [https://github.com/illuminate/container](https://github.com/illuminate/container)
Yii2: [https://github.com/yiisoft/yii2/tree/master/framework/di](https://github.com/yiisoft/yii2/tree/master/framework/di)
AuraPHP [https://github.com/auraphp/Aura.Di](https://github.com/auraphp/Aura.Di)
Fuel [https://github.com/fuelphp/dependency](https://github.com/fuelphp/dependency)
ZF2 [https://github.com/zendframework/zend-di](https://github.com/zendframework/zend-di)

You know, php is fast enough, php application performance bottleneck is io not php itself;
If the reflection really affects performance, then php should not release the feature.

**Comment by robertpustulka** [comment]
BTW, PSR-11 [has been accepted](php-fig/fig-standards#890).

**Comment by burzum** [comment]
@slince I'm using CakePHP over 9 years now and *never* missed DI. I just did a short exploration trip into it and ended up asking myself "Why do you want something you never needed in Cake?". At the end of the day it's - besides technical arguments - a matter of the personal preference. I never got in love with Symfony / Laravel because of it's configuration over convention approach and DI it always felt [like this](http://webodysseum.com/wp-content/uploads/2013/02/Telephone-Wires-over-New-York-03.jpg) to me compared to CakePHP. It's a good framework it's just not my cup of tea that matches my taste.

Also you forgot these plugins for CakePHP in your list:

* https://github.com/rochamarcelo/cake-pimple-di
* https://github.com/lorenzo/piping-bag
* https://github.com/jameswatts/cake-dependency (Cake2)

So if you want it just pick one or create your own, I doubt it's hard to add DI functionality if you really need or want it.

And I agree with @thinkingmedia awesome comment. 👍

**Comment by dereuromark** [comment]
Some of the initial issues pointed out are either void (already done/existing) as pointed out or not too relevant IMO.

I would like to add a IMO way more relevant point towards hexagonal architecture for 4.0+:

### Separation of communication and business layer

Yeah, we don't do that much in Cake yet, or at least only on one front: the controllers.
What many forget is that Shells and Tasks are also a part of the "Communication" layer.
And if you look into the current shells they are cluttered with many lines of business logic.

Since our models (=Tables) are already too persist-related for many, they put everything inside those communication layer classes. We just don't offer a more strict separation of those layers.

So how it should maybe be in 4.x:
Shells and tasks are the controllers and components of the CLI. They contain only delegating glue code and (re)use business classes. Then the business logic itself then calls the persistence layer where needed.
This way that logic can also be easier shared between CLI and Web.

Those business layer classes do not necessarily have to be models, but then they must also be Factory created. Forcing a `new Something()` is counterproductive here.
DI was already a topic, either way, we should only ever force people to use "new ..." for Value objects as per Martin Fowler, never for (testable) business classes and alike.

Status Quo: Extracting i18n via shell is all business logic in a shell or task. One has to execute the Task class via hacks in the controller to allow non CLI import. Same for pretty much all shells, even though most contain quite generic code that could very well be relevant for non-CLI. There are quite a few projects where people would like to share more of this business logic. This is currently prevented inside the core.

Further advantages:
- Separation of concern
- True slim "communication layer" approach
- Keeping infrastructure and low level details out of that business logic
- Reusability/Testability

**Comment by robertpustulka** [comment]
I like the idea. I was wondering if we could start doing this for 3.x. It would be a new layer so no breaking changes are needed I believe. And it would make transition to 4.0 easier in the future.

**Comment by burzum** [comment]
@dereuromark while I agree with what you wrote, what stops a developer from doing this already?

We've put several folders inside the Model folder because we didn't wanted to clutter the top level namespace of the app and have folders like "SearchIndex", "SmartAd", "JobPackage", "Navigation"... that hold classes that implement logic and additional objects that hold the data but don't require a DB table.

The only "new" thing I see in your wall of text is the proposal of having factories for everything.

> Status Quo: Extracting i18n via shell is all business logic in a shell or task. One has to execute the Task class via hacks in the controller to allow non CLI import. Same for pretty much all shells, even though most contain quite generic code that could very well be relevant for non-CLI. There are quite a few projects where people would like to share more of this business logic. This is currently prevented inside the core.

The code could be simply refactored. No big deal? We already minimise the code in our shells and try to have classes that implement the logic in a way they can be used virtually everywhere. That makes testing also a lot easier than trying to test a shell.

**Comment by dereuromark** [comment]
I Talk about core code as leading example. Currently that is Not even Close the case. And you know it.

**Comment by robertpustulka** [comment]
Yes, I agree there could be some general pattern for Business layer. If we suggested the "CakePHP way" of implementing business logic, this could help developers write better code.

**Comment by swijsen** [comment]
https://github.com/cakephp/cakephp/issues/11260

**Comment by dereuromark** [comment]
@swijsen Please don't comment on long closed issues, and please don't just leave these breadcrumbs and links without further specification and content.
