### ISSUE TITLE
Unnecessary joins when using deleteAll()

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#10318]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 2.8.9
* Platform and Target: Linux, MySQL, Apache.

### What you did
```
$this->recursive = -1;
$this->deleteAll($conditions);
```

### What happened
The records were deleted but while deleting SELECT query was generated with unnecessary joins. I discovered that that is caused by hard coded `'recursive' => 0` in Model::deleteAll(). Those extra joins are not necessary and may affect the performance.

### What you expected to happen
I would expect that the recursive value set before the call to deleteAll() would be respected.

**Comment by dereuromark** [comment]
It is a well known issue that in 2.x a lot of more joins are done for updateAll() and deleteAll() than necessary usually. It is partially also because it is harder to inspect the conditions and query and thus by default assumes those joins are necessary.

I recommend using updateAllJoinless() and deleteAllJoinless() from [Shim plugin](https://github.com/dereuromark/cakephp-shim/blob/2.x/docs/Model.md#updatealldeleteall) here, since those then flawlessly upgrade itself to 3.x updateAll() and deleteAll(). They completely reset the joins internally.

**Comment by markstory** [comment]
We could take the min of `$this->recursive` and `0`. That would make it easier for developers to turn off the joins as needed.

**Comment by dereuromark** [comment]
Based on the effect it can have on existing apps relying on the current behavior this would be safer to go into 2.10 then.

**Comment by markstory** [comment]
Closing as a pull request is open.

**Comment by sebastienbarre** [comment]
@bancer @dereuromark @markstory Oh man this *definitely* needs to be added to the migration guide, this change is wreaking havoc in our application.

Our `AppModel` has `public $recursive = -1;` so that we are in better control of the joins, but many of our `deleteAll()` are now failing because `$conditions` has conditions on *associated* models, which were brought in automatically by the previous implementation, where `'recursive' => 0`. 

While your fix is "the right thing to do", there was an assumption that `deleteAll()` was bringing associations in. Fixing this is not going to be elegant, something like:
```
    $old_recursive = $this->recursive;
    $this->recursive = 0;
    $this->deleteAll($conditions, true, true); // run the callbacks()
    $this->recursive = $old_recursive;
```

Just FYI :)

**Comment by markstory** [comment]
Hmm. We could revert the changes as the performance improvement has also caused existing code to break, which I don't think is ok for 2.x

**Comment by sebastienbarre** [comment]
Even with the workaround I mentioned below, temporarily setting `$this->recursive = 0`, I'm also concerned that the callbacks triggered by `deleteAll()` may run into some code that will have a `find()`, which will then retrieve or affect more data than usual (since `$recursive` is now 0 instead of our `AppModel::$recursive = -1`). Tricky....

**Comment by ADmad** [comment]
I too think reverting the change would be the right thing to do.

**Comment by inoas** [comment]
There could be a Configure or `AppModel` flag that is set to recursive = 0 by default and could be overwritten and read by `deleteAll()`.

**Comment by dereuromark** [comment]
For those, that want the performance gain and be 3.x upgrade compatible, they can just do what I have been doing (and communicating) the last 3 years :)
https://github.com/dereuromark/cakephp-shim/blob/2.x/docs/Model.md#updatealldeleteall
Shim plugin's `deleteAllJoinless()`.

This keeps the old behavior for those that need it, and allows for using the new 3.x way in a non BC breaking and very explicit way. Once you migrate the major, you just str_replace those back to just deleteAll() :)

**Comment by tersmitten** [comment]
This is how our `deleteAll` looks like:

```
/**
 * A wrapper for deleteAll, with support for recursive to make automatically joins optional.
 *
 * @param mixed $conditions Conditions to match
 * @param bool $cascade Set to true to delete records that depend on this record
 * @param bool $callbacks Run callbacks
 * @param int $recursive (Optional) Overrides the default recursive level
 * @return bool True on success, false on failure
 * @see Model::deleteAll
 */
	public function deleteAll($conditions, $cascade = true, $callbacks = false, $recursive = null) {
		if (!isset($recursive)) {
			$recursive = $this->recursive;
		}

		if (empty($conditions)) {
			return false;
		}

		$db = $this->getDataSource();

		if (!$cascade && !$callbacks) {
			return $db->delete($this, $conditions);
		}

		$ids = $this->find('all', array_merge([
			'fields' => "{$this->alias}.{$this->primaryKey}",
			'order' => false,
			'group' => "{$this->alias}.{$this->primaryKey}",
			'recursive' => $recursive], compact('conditions'))
		);

		if ($ids === false || $ids === null) {
			return false;
		}

		$ids = Hash::extract($ids, "{n}.{$this->alias}.{$this->primaryKey}");
		if (empty($ids)) {
			return true;
		}

		if ($callbacks) {
			$_id = $this->id;
			$result = true;
			foreach ($ids as $id) {
				$result = $result && $this->delete($id, $cascade);
			}

			$this->id = $_id;
			return $result;
		}

		foreach ($ids as $id) {
			$this->_deleteLinks($id);
			if ($cascade) {
				$this->_deleteDependent($id, $cascade);
			}
		}

		return $db->delete($this, [$this->alias . '.' . $this->primaryKey => $ids]);
	}
```

**Comment by bancer** [comment]
>     $old_recursive = $this->recursive;
>     $this->recursive = 0;
>     $this->deleteAll($conditions, true, true); // run the callbacks()
>     $this->recursive = $old_recursive;

@sebastienbarre Wouldn't that be a simple fix in `AppModel::deleteAll()`?

**Comment by ADmad** [comment]
@bancer The point is no fix should be required. Any change should not break existing apps.

**Comment by bancer** [comment]
Maybe simply add `$recursive` parameter to `deleteAll` method?

**Comment by tersmitten** [comment]
@bancer See https://github.com/cakephp/cakephp/issues/10318#issuecomment-317404580
