### ISSUE TITLE
$this->request->here and $this->request->getRequestTarget() is not equal

### ISSUE THREAD

**Issue by ictgtvt** [cakephp/cakephp#10444]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.
* Platform and Target: Apache, PHP 7.0, Mysql

### What you did
Access url: https://abc.com/controller/action?param=a

Use: `$this->request->here` will return: `/controller/action`
Use: `$this->request->getRequestTarget()` will return '/controller/action?param=a'

### What happened
Use: `$this->request->here` will return: `/controller/action`
Use: `$this->request->getRequestTarget()` will return '/controller/action?param=a'

### What you expected to happen
Use: `$this->request->here` will return: `/controller/action`
Use: `$this->request->getRequestTarget()` will return '/controller/action'

What i found in PHPDoc,
/**
     * The full address to the current request
     *
     * @var string
     * @deprecated 3.4.0 This public property will be removed in 4.0.0. Use getRequestTarget() instead.
     */
public $here;

**Comment by markstory** [comment]
The getRequestTarget() method has an expected behaviour defined in the PSR7  standards which is why it includes the query string. This behaviour is similar to the here() method on the request. The here property and method do different things for historical reasons. The closest approximation of the here property would be `request->getUri()->getPath()`. I can update the doc block to indicate that.

**Comment by markstory** [comment]
API doc block updated now.

**Comment by ictgtvt** [comment]
Thank you.
