### ISSUE TITLE
CakePHP 2.x : duplicate paths in App::path

### ISSUE THREAD

**Issue by sulian** [cakephp/cakephp#10478]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

----

* CakePHP Version: 2.x
* Platform and Target: Linux Debian / Apache server.

----

I want to get the list of plugins. I use App::path('plugins') and the result is a duplicate list of my plugins : 

````
array(
    'plugin1',
    'plugin1',
    'plugin2',
    'plugin2'
);
````

in ``_packageFormat()``, the ``static::$_packageFormat``array contains theses values for Vendor & Plugin : 

- App . 'Plugin' . DS
- ROOT . DS . 'plugins' . DS
- dirname(dirname(CAKE)) . DS . 'plugins' . DS

Problem : sometime, ``ROOT . DS . 'plugins' . DS`` is the same as ``dirname(dirname(CAKE)) . DS . 'plugins' . DS``

In my case, App::path('plugins') returns : 

````
Array(
    [0] => blabla/california/app/Plugin
    [1] => blabla/california/plugins
    [2] => blabla/california/plugins
)
````

**Comment by markstory** [comment]
If you have duplicate paths you'll get duplicate results. Is there a reason you don't remove the duplicate paths?

**Comment by sulian** [comment]
Hi @markstory, you're right : I can remove duplicate paths so that's what I did. In fact, every time, I use ``App::path('plugins') `` or ``App::path('plugins') App::path('vendors')``, I know I have duplicate paths, the problem is why this **core** function return duplicate paths ?

CakePHP must check if ``ROOT . DS . 'plugins' . DS`` path is the same as ``dirname(dirname(CAKE)) . DS . 'plugins' . DS`` path and in this case, remove one of them

**Comment by markstory** [comment]
>  I know I have duplicate paths, the problem is why this core function return duplicate paths ?

For backwards compatibility reasons. CakePHP 2.x supports a number of installation scenarios, and to accommodate all those install setups we have to maintain the path sets that enable all those installation types, which can result in duplicate paths depending on the install setup. This has proven to be a bad idea long term, which is why in 3.x we only support composer based installation.

Closing this issue as the duplicate results can be addressed by changing application configuration.

**Comment by sulian** [comment]
Ok for me
