### ISSUE TITLE
Cakephp 3.x do not trim text fields on save in DB

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#10575]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.5

### What you did
In Cakephp 2.x when some data is saved in the database, trim is automatically done in all text fields. I would like to know if there is any native configuration to do this in Cake 3.x, and if not, why?

### What happened
When I save a text field with the content "      some text    " it is not trimmed automatically.

### What you expected to happen
That Cakephp trim text fields by default

**Comment by dereuromark** [comment]
I dont think there ever was such a feature.
It usually is project specific if or when such trimming should occur.
I use and recommend a [component solution](https://github.com/dereuromark/cakephp-tools/blob/master/src/Controller/Component/CommonComponent.php#L28-L36) that properly trims your incoming data so that validation can work as it is expected to.

But I think this always has been outside of the core scope so far.

**Comment by ADmad** [comment]
> In Cakephp 2.x when some data is saved in the database, trim is automatically done in all text fields.

Nope, it never did.

> I would like to know if there is any native configuration to do this in Cake 3.x, and if not, why?

There is none, because such "auto magical" features often leave devs scratching their head when data gets implicitly manipulated by core.

You can easily add such a feature by using a custom behavior for example. Closing as such a feature is unlikely to ever end up in core.
