### ISSUE TITLE
BelongsToMany::link has defects

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#10665]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.6

### What you did

- `Users` ManyToMany `Roles`
-  set `saveStrategy` = 'append'
-  set (user_id, role_id) as primary key for join table `users_roles`
- code
```php
        $user1 = $this->Users->get(1);
        $user2 = $this->Users->get(2);

        $role1 = $this->loadModel('Roles')->get(1);
        $role2 = $this->loadModel('Roles')->get(2);

        $result1 = $this->Users->Roles->link($user1, [$role1, $role2]);
        $result2 = $this->Users->Roles->link($user2, [$role1]);
        debug($result1);
        debug($result2);
```
### What happened
Output true; but the join table has only two records;

| user_id | role_id|
| --- | --- |
| 1 | 1 |
| 1 | 2 |

If add field `id` and set `id`  as pk, the result is:

| id | user_id | role_id |
| --- | --- | ---|
|  1  | 2 | 1 |
|  2   |  1 | 2 |

**Comment by markstory** [comment]
I will take a look.

**Comment by markstory** [comment]
Pull request open now.

**Comment by fquffio** [comment]
Just to let you know, commit b94a3c7 actually breaks things in a scenario where a single junction table is used for several associations, and a "discriminator" column is in the primary key and is used to tell one association from the others.

For instance, if one has a junction table with three columns:
 - `user_id`: foreign key to users table
 - `place_id`: foreign key to places table
 - `type`: one of `works_at`, `lives_in`, `usually_haves_breakfast_at`

In this case, you must manually set all these three columns in order for things to work, otherwise the whole primary key will be unset, thus `type` will become null. Before 3.4.8, just setting `type` did work, since the association took care of setting `user_id` and `place_id` correctly without touching `type`.

Since this is quite an uncommon scenario I'm not sure if it should be considered an issue, as fixing it would likely add complexity not needed by most users, but maybe somebody else is having an headache with the same problem. 😉
