### ISSUE TITLE
Add Users to CakePHP

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#10717]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.x && 3.x
* Platform and Target: LAMP

### What you did

I tried to install a blog plugin and forum plugin

### What happened

Massive amount of custom code

### What you expected to happen

Plug and Play

if CakePHP had users or even just a users interface, my life would be so much more simple, and I have a strong feeling that there would be a ton more plugins out there, and out of all the plugins I know that cost money, there is only one for CakePHP that stands out and its a users plugin, thats because CakePHP is missing users, and no one is going to build a plugin based off of that guys user table, and really likely not anyone's user plugin, as nice as that would be, I just dont see it happening...  The user's interface and base table at the very least needs to be created by cake so it can be extended by everyone, I truly feel like its the way to go, just my two cents

**Comment by inoas** [comment]
There are users plugins - see awesome cakephp list.

This is nothing that should be in the core as there are often different requirements, imho.

**Comment by markstory** [comment]
What would you be looking for in a core implementation of users? In the future authentication and authorization will be plugin based (see [cakephp/authentication](https://github.com/cakephp/authentication)). That plugin contains an 'IdentityInterface' which is about as far as we've gotten in describing a user.  We've not built out the authorization plugin yet, but it is in the early planning stages.

**Comment by dereuromark** [comment]
A framework is not a CMS. It is generic because it cannot assume the many different use cases there are to having "users".
Please refer to the existing users plugins out there already if you want something out of the box.
But for the framework anything more concrete than what already exists is out of scope IMO.

**Comment by hagen00** [comment]
Agreed, no need for a users plugin as far as I'm concerned. This is not a CMS.

**Comment by jeffreyroberts** [comment]
Im simply saying at the very least, provide a basic user interface, so that there is a common denominator between users plugins which would ease the development of other plugins since they could program to the interface and not the users plugin directly. I think it would help greatly in getting more plug and play out of the box plugins contributed to the community

**Comment by markstory** [comment]
@jeffreyroberts What would you see being in that common interface?

**Comment by jeffreyroberts** [comment]
id, name, password, email

That should cover register, login, password recovery, and satisfy the needs of most plugins. If I were to write forum plugin now, I could create another table for any user info the forum needs and link it back to the users table with user_id. If all user plugins implement those four fields, then everyone will know how to interact with the user table, most importantly the ability to link back to the user table with user_id

**Comment by jeffreyroberts** [comment]
If you still dont want to implement the users, and allow plugins to do that, then thats totally cool, just create an abstract class for user plugin developers to extend for their user model/controller

**Comment by jeffreyroberts** [comment]
Im actually writing in the forum now a post about Interfaces and Abstract classes and the understanding of them in terms of Plugins that I have developed over the years writing plugins for desktop applications

**Comment by jeffreyroberts** [comment]
http://discourse.cakephp.org/t/dashboard-sidebar-navigation-user-and-plugin-interfaces/2669

**Comment by jeffreyroberts** [comment]
Give them interfaces and they will program =]

**Comment by chrisShick** [comment]
@jeffreyroberts why wouldn't you just extend the application skeleton? 
Regarding your discource post, extending the application skeleton would prevent you from having to rewrite a lot of things. 
Here is a good [link](http://josediazgonzalez.com/2015/12/09/customizing-your-app-template/) that explains what I am talking about.

**Comment by jeffreyroberts** [comment]
Thanks for the link, ya, I have extended and rewrote and had a lot of fun with the skeleton, im just now starting to dig into 3.x, looking forward to it, some of these problems might have been solved, we will find out, but ya, @ forum post, we need a dashboard interface and a dashboard plugin interface defined by the cake core so that i can use whats his faces dashboard with that other guys dashboard plugin

**Comment by jeffreyroberts** [comment]
and you know whats really cool, dashboard plugins that define their own interfaces so they can have plugins too, and what would be really sweet is a package and package manager interface(s) so that the dashboard plugin could have its own package manager, but now im just going overboard lol

**Comment by ADmad** [comment]
For quick "standard" admin user interface checkout friendsofcake/crud-view.

**Comment by jeffreyroberts** [comment]
oh ya, and @chrisShick everytime ive done that so far ive used a paid template, and licensing doesnt transfer typically, anywho, next one is absolutely going to be AdminLTE on github, woot

**Comment by inoas** [comment]
As for the abstract user model - aaide the fields above - an is_enabled or is_active bool might be okay for general consensus.

As for the backend interface interoperability maybe sonething like debugkits toolbar 'plugging' may work?

**Comment by burzum** [comment]
@jeffreyroberts which paid users plugin are you talking about? There is exactly one I know and the code is... not good. A few good ones that are pretty much independent from anything is probably the CRUD plugin with their users addon, my own user tools plugin and probably the CakeDC plugin. Not sure if the last one features a configurable field map or if you're bound to user their users table.

I've spend some time thinking about giving a better way to access the user, because I know the common use case that you have to rely on that the user id is available through `$this->Auth->user('id')`. If people don't use the Auth system, well, their fault, you can't do anything about that. But you could make the `id` key configurable, so if somebody is using something else than `id` he can change the config. You could map other fields as well via config in your plugin as well.

So I like your request to add an interface, but I disagree with some of your wishes. We had a long discussion about making the user data an object or not, it came down to not use one because the kind of data can be very different. *But* I would not mind implementing an object that is basically similar the Entity object and implements *one* method: `getIdentifer()` To fetch the unique id of the user. With the id you can get *everything* else and don't make assumptions on other possible fields. There are for example apps that don't have an email but only username and password. There are pure API apps where the "user" is just a token that gets resolved to some kind of identity.

@markstory we have a ResultInterface for the result of an authentication process but we don't have an IdentityInterface. An identity is simply an array or null. How about adding and object that can be accessed like an array but provides a method `getIdentifer()`? So IdentityInterface + a basic Identity class. The service (or another place, need to look it up first) could have the option `identityClass` and a method `setIdentityClass()`. How does that sound?

**Comment by markstory** [comment]
> An identity is simply an array or null. How about adding and object that can be accessed like an array but provides a method getIdentifer()? So IdentityInterface + a basic Identity class. 

I'm OK with that. I think you've pointed out a key point which is that 'user' is very context dependent and a user in an LDAP / OAuth consumer is going to be very different that a local database user. I agree that only prescribing the `getIdentifier()` is about the only common thing we could hope to have.

**Comment by burzum** [comment]
@markstory we can resolve the issue with different fields by providing a mapping and a generic get() method. My only problem right now is where to best create the identity object. I think the best place would be the service so far. Your input please?

**Comment by markstory** [comment]
I think putting the identity into the result object makes sense, but you're right that getting the right object inside the result is hard. One option could be to provide a callable 'factory' that is required to return an object implementing the interface. Something like

```php
$authService->identityResolver(function ($user) {
  // convert user data into IdentityInterface.
  return new IdentityInterfaceImplementation($user);
});
```

This would let the IdentifierCollection to convert the result of the identifier into an identity. Do you think this could work?

**Comment by burzum** [comment]
@markstory check the PR https://github.com/cakephp/authentication/pull/129 I've taken your idea of the callback but solved it a little different. I think this works fine, the authenticators return a raw result (array identity), the service turns it where needed into an identity.

**Comment by burzum** [comment]
@markstory @jeffreyroberts I think we can close this now as it's implemented in the authentication plugin? @jeffreyroberts would you please review what we've done there and give us your feedback if this is sufficient for you?

**Comment by jeffreyroberts** [comment]
you guys have gone above and beyond, thank you so much, I am going over the docs now, and will begin to work with the plugin this evening, thank you so much, I will be in touch with feedback soon
