### ISSUE TITLE
[RFC] gettext - fallback to defined language

### ISSUE THREAD

**Issue by nicolabeghin** [cakephp/cakephp#10794]
This is a (multiple allowed):

* [x] feature-discussion (RFC)

* CakePHP Version: ALL
* Platform and Target: ALL

### What you did
Created a folder like 

- app/Locale/eng/LC_MESSAGES/default.po
- app/Locale/ita/LC_MESSAGES/default.po

Please note: only a subset of translations in the italian default.po

### What happened
When accessing the app in italian, missing translations were not taken up from the english default.po

### What you would like to happen
When accessing the app in italian, missing translations should be taken up from a given fallback languages (ie the english one).

**Comment by markstory** [comment]
Where would the fallback languages be defined?

**Comment by nicolabeghin** [comment]
I would follow an approach like the TranslateBehavior with an array of languages, or a list of fallback languages. More practically, a global Configure::write('Config.language.fallback', array('it' =>'en'))

**Comment by markstory** [comment]
I am guessing your message strings are not acceptable fallbacks? That is generally how I have approached fallback messages in the past. The message id is the fallback.

1.x is no longer supported or maintained, so I wouldn't recommend building patches for it.We are also not likely to merge new features into 2.x unless there is an equivalent feature in 3.x.

**Comment by nicolabeghin** [comment]
I understand. Do you have any hint on how to approach this, the cake-way?

**Comment by ravage84** [comment]
@nicolabeghin as @markstory mentioned the easiest way is to use the actual fallback text (translation) as text (placeholder) to be translated.
So instead of ``__('hotProductOfTheMonthTitle')`` you use ``__('Our hot product of the month')`` as translation string.  So it would show ``Our hot product of the month`` as text on an Italian page, when the Italian translation is missing.
Certainly, this is not very flexible.

@markstory couldn't @nicolabeghin implement a [Translator](https://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html#creating-your-own-translators) of his own to achieve what he wants?

**Comment by markstory** [comment]
@ravage84 Yes that would work in 3.x. In 2.x its a more hairy problem.

**Comment by nicolabeghin** [comment]
Thanks for the hints. Given that right now I need to focus on 2.x, any other suggested approach? I'm still trying to get my head around if it's possible at all with the standard gettext functions.

**Comment by ADmad** [comment]
Closing as 2.x won't be getting any new features and in 3.x the fallback feature can be acheived with a custom `Translator` class.
