### ISSUE TITLE
3.next - Add Content-Security-Policy support to SecurityHeadersMiddleware

### ISSUE THREAD

**Issue by sukihub** [cakephp/cakephp#10806]
3.5 will have SecurityHeadersMiddleware (#10474) which currently does not handle Content-Security-Policy header. It seems like a nice thing to have, since it's supported by all browsers and can help protect website users against XSS & stuff :) Rails people also think it's a good idea: https://github.com/twitter/secureheaders

There's already a nice little PSR7 compatible library that can help with this: https://github.com/paragonie/csp-builder

It would also be nice to be able to dynamically change security headers in actions (especially in case of CSP). People from [Twitter think so](https://github.com/twitter/secureheaders/blob/master/docs/per_action_configuration.md) and also people from GitHub:

> Historically, it has been relatively tedious to make dynamic changes to our policy per endpoint (i.e. we didn’t do it). But, with some recent development by @oreoshake to the Secure Headers library, it is now much easier for us going forward. For example, connections to api.braintreegateway.com only occur on payment related pages. We can now enforce a unique exception to our policy, appending the third-party host only on pages that need to connect to the payment endpoint. Over time we hope to lock down other unique connection endpoints using dynamic CSP policies.

(source: https://githubengineering.com/githubs-csp-journey/)

So I'm thinking that some SecurityHeaders component could do the trick.

Or does the whole security headers thing sound more like a library than Cake's core?

**Comment by ADmad** [comment]
Refs #7518

Also there's https://github.com/TheFRedFox/cakephp-csp so perhaps you could contribute to that plugin.

**Comment by markstory** [comment]
CSP is pretty complicated, and using a standalone library like the one you linked to or TheFredFox's might be simpler for now.

**Comment by oreoshake** [comment]
:wave: I acknowledge that this is probably not my place to say anything since I am not a PHP developer, but as someone with many years of CSP experience I would strongly urge adoption into the core framework. I would also suggest a default policy to be used for *new* applications. I have seen the "default effect" show great returns *specifically* with CSP.

That being said, I know next to nothing about PHP culture and if this philosophy jives! 

I can elaborate if there's interest but I'm not here to stand on a soapbox.

**Comment by burzum** [comment]
@oreoshake what would you suggest as default policy? And what is best practice here?

**Comment by oreoshake** [comment]
>> I would strongly urge adoption into the core framework.

> For what reason? I'm just curious.

To make people *opt-out* of the protection it provides instead of requiring people to take extra steps (which they likely will never do). By providing a reasonable policy out of the box, many people can develop without even thinking about CSP.  

CSP is easy to build into an app from the beginning but it's one of the most difficult and painful things to bolt on after the fact. Start compliant/secure, relax as needed.

I've been trying to integrate secure_headers into rails core for the same reason.

> @oreoshake what would you suggest as default policy? And what is best practice here?

I [worked with the authors of hanami](https://github.com/hanami/hanami/pull/604) to come up with [a default policy](https://github.com/hanami/hanami/blob/23b9562f44e1185ab561bab842af0cb8ff217671/spec/support/shared_examples/cli/generate/app.rb#L272) (note: the policy does allow jsonp, which is not ideal). There some historical context in that thread as well. I believe the policy is reasonable, pretty "secure," and should work with any app given some reasonable pre-conditions (e.g. not using inline scripts in the framework).

Another framework, sinatra, at least [provides an API](https://github.com/sinatra/sinatra/blob/85dd923cc02fc21bb14f1deb24eb415c48c297b0/rack-protection/lib/rack/protection/content_security_policy.rb) for setting the header (but doesn't apply a default policy).

I'd bet that hanami and sinatra apps have a significantly higher rate of CSP adoption simply because the pieces are available without extra effort.

**Comment by burzum** [comment]
@oreoshake thanks for that answer. 👍 I'm all in for implementing what I suggested before then plus a default config and adding it to cakephp/app. I'll start working on this when @markstory tells me we're OK to do so.

**Comment by markstory** [comment]
I don't think we would be adding any value to the paragonie/csp library so there is no need to fork it. Defaulting to a safe start makes sense to me and resonates with the goals we have for CakePHP. 

Enabling CSP by default in new applications sounds like a good approach. In the past other csp attempts have not fared as well because the potential for breaking existing applications was too high. Unfortunately without significant breaking changes to Formhelper we would need to leave inline JS enabled.

**Comment by inoas** [comment]
Are the changes related to Delete-Buttons Inline-Javascript only?
What about having a small XHR request and a true delete-view in future?

**Comment by burzum** [comment]
@markstory so we just suggest paragonie/csp in our composer.json, add a section to the manual and add the default config file for it to the app repository?

**Comment by markstory** [comment]
@burzum That is one option. We could go further and add a middleware that sets up CSP headers if people think its a good idea.

**Comment by burzum** [comment]
@markstory I think we should pick the lib instead of re-inventing the wheel. We can wrap it in a middleware and simply call it there, see https://github.com/paragonie/csp-builder#inject-a-csp-header-into-a-psr-7-message.

**Comment by inoas** [comment]
https://github.com/oscarotero/psr7-middlewares is another candidate, even if we only pick csp, however it will be ported to psr-15 (should we target that, too for 4.0?)

**Comment by markstory** [comment]
@burzum I'm fine with using a library. Would this be an app level dependency or a dependency for cake?

**Comment by burzum** [comment]
@markstory if we just suggest it it would be app, otherwise cake.

**Comment by markstory** [comment]
Ok. Where would you want to put the middleware?

**Comment by burzum** [comment]
@markstory good question, Http or Middleware? I don't mind putting it in any of both.

**Comment by inoas** [comment]
Playing the devils advocate I looked for alternative to paragonie/csp-builder because it got only 5 contributers, oscarotero/psr7-middlewares got 24 - while I am a fan of do-not-reinvent-the-wheel - this reminds me of Carbon/Chronos quite a bit.

**Comment by burzum** [comment]
@inoas the repository you suggest is just a huge collection of wrapper middlewares around other libraries. Ironically they use csp-builder as well. 😆 

https://github.com/oscarotero/psr7-middlewares#cors
> To use the **neomerx/cors-psr7** library:

https://github.com/oscarotero/psr7-middlewares#csp
> To use the **paragonie/csp-builder** library to add the Content-Security-Policy header to the response.

**Comment by cnizzardini** [comment]
Curious what the status of this is? I am currently determining how I want to handle CSP in an application I am building.

**Comment by markstory** [comment]
@cnizzardini There is a [csp middleware](https://github.com/cakephp/cakephp/blob/4.x/src/Http/Middleware/CspMiddleware.php) coming in 4.x.
