### ISSUE TITLE
Use Console namespace without all framework

### ISSUE THREAD

**Issue by lira92** [cakephp/cakephp#10965]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.8

### What you did
A package read-only like a CakePHP ORM to use Console lib of CakePHP without framework.

**Comment by markstory** [comment]
Totally something I would like to see as well. We made good progress on this in 3.5, and part of 3.6 will like be creating a sub split for Console.

**Comment by dereuromark** [comment]
Is this complete now in 4.x? Can we close this?

**Comment by markstory** [comment]
I'd like to finalize this by adding a console split and ensuring that it works.

**Comment by ndm2** [comment]
I just started trying to create a console application outside of the environment of a CakePHP application, and my observations so far are:

* `CommandRunner::loadRoutes()` will cause an exception when the router hasn't been initialized.
* I had to remove the default commands / use a new command collection.
* The default `HelpCommand` is very CakePHP centric, I had to reimplement it in order to avoid constants like `APP_DIR` being required, and references to the `cake` console being output.
* The `VersionCommand` is just confusing, it makes it look like that's the version of the application, it had to go too.
* There seems to be no way to define the default command, it seems hardcoded to `help`.
* Command auto/discovery is very CakePHP centric, the command scanner doesn't have a public API for scanning directories, scanning the "app" requires the `App.namespace` option to be configured.
* While one can inject anything into a command manually, having access to the root name (without having to split the name, which feels a little awkward) as well a reference to the application inside of commands might come handy.
* Not being able to access the command collection via the application object feels weird at times, but that might just be me being used to Symfony consoles.

**Comment by markstory** [comment]
@ndm2 Thank you for taking the time to try using the console library on its own.

> CommandRunner::loadRoutes() will cause an exception when the router hasn't been initialized.

Sounds like this method should be ensuring the `Router` exists first.

> The default HelpCommand is very CakePHP centric, I had to reimplement it in order to avoid constants like APP_DIR being required, and references to the cake console being output.

The references to `cake` can be replaced with the root command name from the collection. That should solve the visual problems.

> Command auto/discovery is very CakePHP centric, the command scanner doesn't have a public API for scanning directories, scanning the "app" requires the App.namespace option to be configured.

Yes it is. I didn't have a good idea of how we could do discovery on an arbitrary application structure. Scanning a single directory could be a good place to start though.

> While one can inject anything into a command manually, having access to the root name (without having to split the name, which feels a little awkward) as well a reference to the application inside of commands might come handy.

Having access to the root command is doable. I'm reluctant to exposing an application in commands as I feel that will encourage service locator patterns where I would rather encourage dependency injection into either the constructor or `execute()`.

> Not being able to access the command collection via the application object feels weird at times, but that might just be me being used to Symfony consoles.

Could retaining an instance of the command collection in the `console()` hook help here?

**Comment by ndm2** [comment]
> I'm reluctant to exposing an application in commands as I feel that will encourage service locator patterns where I would rather encourage dependency injection into either the constructor or `execute()`.

Sorry, that's pretty much what I ment, injection, but automatically :) In my app I'm injecting the application reference into the command constructor.

> Could retaining an instance of the command collection in the `console()` hook help here?

I'm not sure what exactly you mean by that? What I've done now is creating a command collection in the application's constructor, so that it in case neccesary, it can be modified early on, and even from the outside.

Here's a stripped down version of the test app:


```php
namespace NDM\Mixer\Console;

use Cake\Console\CommandCollection;
use Cake\Core\ConsoleApplicationInterface;
use Cake\Routing\Router;
use NDM\Mixer\Command\HelpCommand;
use NDM\Mixer\Command\VersionCommand;
use Jean85\Version;

class ConsoleApplication implements ConsoleApplicationInterface
{
    protected $_commands;
    protected $_name;
    protected $_version;

    public function getCommands()
    {
        return $this->_commands;
    }

    public function getName()
    {
        return $this->_name;
    }

    public function getVersion()
    {
        return $this->_version;
    }

    public function __construct($name, Version $version, CommandCollection $commands = null)
    {
        $this->_name = $name;
        $this->_version = $version;
        if ($commands === null) {
            $commands = new CommandCollection();
        }
        $this->_commands = $commands;
    }

    public function bootstrap()
    {
        Router::reload();
    }

    public function console($commands)
    {
        if (!$this->_commands->has('help')) {
            $this->_commands->add('help', new HelpCommand($this));
        }

        if (!$this->_commands->has('version')) {
            $this->_commands->add('version', new VersionCommand($this));
        }

        return $this->_commands;
    }
}
```

```php
namespace NDM\Mixer\Console;

use NDM\Mixer\Command\ConfigCommand;
use NDM\Mixer\Command\InitializeCommand;
use Jean85\PrettyVersions;

class MixerConsole extends ConsoleApplication
{
    protected $_targetPath;

    public function getTargetPath()
    {
        return $this->_targetPath;
    }

    public function __construct($targetPath)
    {
        $this->_targetPath = $targetPath;

        parent::__construct('mixer', PrettyVersions::getVersion('ndm/mixer'));
    }

    public function console($commands)
    {
        $commands = parent::console($commands);

        $commands->add('init', new InitializeCommand($this));
        $commands->add('config', new ConfigCommand($this));
        // ...

        return $commands;
    }
}
```

```php
use Cake\Console\CommandRunner;
use NDM\Mixer\Console\MixerConsole;

$app = new MixerConsole($root . DIRECTORY_SEPARATOR);

$runner = new CommandRunner($app, $app->getName());
exit($runner->run($argv));
```

**Comment by markstory** [comment]
How your constructor holds onto the command collection is what I was suggesting, but in the `console()` hook method. Using a custom constructor works well too though.

**Comment by markstory** [comment]
There will be a standalone console package in 4.0.
