### ISSUE TITLE
Email sent goes to recipients Spam/Junk

### ISSUE THREAD

**Issue by cliffordusidamen** [cakephp/cakephp#11037]
Every time i sent email via cake it goes into the recipients Spam/Junk folder.

**Comment by markstory** [comment]
How is this caused by CakePHP. Email deliverability is a complex topic with many moving parts. What makes you think the issue is in CakePHP and not somewhere else?

**Comment by Benfarhat** [comment]
Your problem is not caused by CakePHP.
To validate all your email and prevent your problem, you must contact your internet provider (or administrator of your organisation) and ask him to add in your DNS an [SPF ](https://en.wikipedia.org/wiki/Sender_Policy_Framework) record for your mail server (it's a simple task that takes 5 minutes). 

An SPF record improve security and help by saying to the receiver: "if a mail from @example.com come from the server with this ip adress 10.11.12.13, it's ok, i got it in a SPF record and the sender is the real one (and not a spoofer), if there is no SPF record, i can't validate this mail and it's better and more safety for you (the receiver and not the sender) to consider this message like a spam!

Implementing SPF is a good begining but it won't solve all of your delivery problems, in a professional environment, to improve your delivery rates and prevent abuse like spoofing mail, you should add DKIM and DMARC layers.

You can check your server with this [tool](https://mxtoolbox.com/SuperTool.aspx)

**Comment by cliffordusidamen** [comment]
Thanks Benfarhat

**Comment by cliffordusidamen** [comment]
Thanks
