### ISSUE TITLE
Auto load entity associations without method "contain"

### ISSUE THREAD

**Issue by slince** [cakephp/cakephp#11183]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

```php

$user = $this->loadModel('Users')->get(1);

dump($user->profile);
dump($user->tags);
dump($user->tags->where(['name' => 'cake']));
dump($user->group->users);
```

The above code is very clear. developers can easily get entity association even if forgot "contain " the association when get the entity.

**Comment by markstory** [comment]
It looks like you're describing lazy-loaded associations. We've intentionally avoided lazy-loading functionality, and it is not something I anticipate will be added to the ORM. 

Having used lazy-loading in SQLAlchemy and Rails it certainly does make code easier to read and write, but results in punishingly bad performance in most scenarios. We already support 'eager lazy' associations via [loadInto()](https://api.cakephp.org/3.5/class-Cake.ORM.Table.html#_loadInto) this approach lets you load additional associations on-demand, so if you forget a contain() option you can get the additional data you need.

**Comment by ADmad** [comment]
You might also want to checkout https://github.com/jeremyharris/cakephp-lazyload

**Comment by slince** [comment]
@markstory  hi, looks  good. however
```php
$user = $this->loadModel('Users')->get(1, [
   'contain' => ['Profiles']
]);

$this->loadModel('Users')->loadInto($user, ['Profiles']);
```
The `$user` already contains `$profile`, however ORM will query database again to obtain `$profile`. i think it should be avoided.


@ADmad  hi, 
That is what I want. but I can not use an unreliable library in production environment.

**Comment by dakota** [comment]
@slince 

The lazy eager-loader intentionally doesn't check if the association has been loaded as you can use it to "refresh" a loaded association. If you only want to load if it isn't already loaded, then wrap it in a `if` statement.

That library is incredibly reliable, not sure where you get that it isn't? I've been using it in production for years, and if you read the book you'll see it's actually recommended (https://book.cakephp.org/3.0/en/orm/entities.html#lazy-loading-associations) for lazy loading.

Lazy loading is something that should definitely not be included in the ORM, especially since it is so easy to include it if you need it.

Also, if your developers forge" to contain an association, then it is trivial for them to go back and add it in. It's not like you can't change already written lines of code 😃

**Comment by lorenzo** [comment]
Thanks for the suggestion. Given that there is already 2 ways of doing this, one of them being a officially recommended plugin, I'm closing this issue.

The plugin functionality will not be added to the core for the reasons explained above by other members of the team.

**Comment by ADmad** [comment]
> That is what I want. but I can not use an unreliable library in production environment.

It's developed and maintained by a core dev. So it's the most reliable thing you get since that feature isn't going to be added to core :slightly_smiling_face:

**Comment by slince** [comment]
@dakota 

> That library is incredibly reliable, not sure where you get that it isn't? 

Hi, i think that library has too little stars (just 25, I even have more than 100 stars.. :grimacing:) and is not maintained by [CakeDC](https://github.com/cakedc) or [FriendsOfCake](https://github.com/friendsofcake)

@ADmad  OK,  I will try that If I have free time.

**Comment by dakota** [comment]
> i think that library has too little stars

You do know that reliability is not a popularity contest?

> is not maintained by CakeDC or FriendsOfCake

Why should that matter? Do you only use software that is written/maintained by Microsoft (Or Apple, or Linus)?

**Comment by slince** [comment]
@dakota 
> You do know that reliability is not a popularity contest

I know, but more stars mean more people use, the author is more willing to spend time to solve the bug and add some features.  

> Do you only use software that is written/maintained by Microsoft

Of course not, but their softwares is more reliable. If there is a choice, I will give priority to them

You know  there are too many zombie llibraries. :smile:

**Comment by josegonzalez** [comment]
@slince for reference, @jeremyharris is one of the CakePHP core developers, and everyone responding to you thus far in this issue is also a core developer. Not sure if we can more highly recommend something than we already have....

**Comment by slince** [comment]
Hi there

I still recommend implementing this in version 4.0 and I found a pretty interesting project 
[https://nextras.org/orm/docs/3.0/](https://nextras.org/orm/docs/3.0/)

According to the document：

```php
$authors = $orm->authors->findAll();
foreach ($authors as $author) {
    echo $author->name;

    foreach ($author->books as $book) {
        echo $book->title;
        echo $book->translator->name;

        foreach ($book->tags as $tag) {
            echo $tag->name;
        }
    }
}
```
Only four queries will be generated.  So performance issues can be avoided with the right design. 😄 

And i have studied the library [https://github.com/jeremyharris/cakephp-lazyload](https://github.com/jeremyharris/cakephp-lazyload) , i think its implementation may not be correct,

**Comment by slince** [comment]
@all

**Comment by dereuromark** [comment]
This seems to go more in the direction of active record rather than a clean repository/entity pattern.
I don't think this is the general direction modern libraries (apart from laravel) would like to see things going.
If you want to implement, there are already existing plugin solutions, but the core should probably not adapt this pattern out of the box.

I think we should close this as works-for-me at this time.

**Comment by ADmad** [comment]
@slince Please avoid using `@all`, everyone participating in the discussion already gets a notification when a new comment is made.

**Comment by slince** [comment]
Hi 
@dereuromark  
> active record rather than a clean repository/entity pattern

Not really，doctrine also achive this, but we know doctrine is not AR design.

> there are already existing plugin solutions

Very difficult.  like [ https://github.com/jeremyharris/cakephp-lazyload]( https://github.com/jeremyharris/cakephp-lazyload),  It is based on recursive queries， but this can cause poor performance problems


@ADmad 

ok,  In fact I do not understand this。。

**Comment by lorenzo** [comment]
@slince Thanks for the suggestion. As explained before, we have decided that the philosophy behind Cake's ORM is to be explicit about what is loaded. This has better opportunities for optimisations, batching and is more clear what is loaded and where.

The project in  https://github.com/jeremyharris/cakephp-lazyload provides a way to conveniently load data, when performance or clarity is not a concern.

Since this issue is closed and there is already a decision made about the direction of the ORM, I'm locking this thread so only administrators can update it.

If you feel that the lazy-load project could be improved, please contribute there.
