### ISSUE TITLE
RFC 3.6: Deprecate property access on BehaviorRegistry

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#11245]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

### What you did

Currently people use
```php
$searchManager = $this->behaviors()->Search->searchManager();
// or
$searchManager = $this->behaviors()->get('Search')->searchManager();
```
The latter is bad, because it cannot be auto-discovered by the IDE (I didnt find any way), magic string issues on top.
The former falls in line of direct (public) property access, which is somewhat discouraged now.

I propose to deprecate at least the property one in favor of a consistent method access to behaviors:
```php
$searchManager = $this->behaviors()->search()->searchManager();
```

//EDIT now
```php
$searchManager = $this->behaviors()->getSearch()->searchManager();
```

It can, with some effort, made auto-discoverable for IDEs, thus providing typehinting, clickability, etc.
We can keep the magic string getter if needed as 2nd solution, but usually it is better to not have too many ways to do the same thing IMO.

//cc @davidyell

**Comment by dereuromark** [comment]
If anyone is interested, this generated (by IdeHelper for example) file enables IDE support for the new syntax:

```
namespace Cake\ORM;

exit('Only for code completion');

abstract class BehaviorRegistry extends \Cake\Core\ObjectRegistry {

	/**
	 * Search.Search behavior
	 *
	 * @var \Search\Model\Behavior\SearchBehavior
	 */
	public $Search;

	/**
	 * @return \Search\Model\Behavior\SearchBehavior
	 */
	public function search() {
		return $this->Search;
	}

}
```

**Comment by ADmad** [comment]
I don't like this idea. Accessing behavior instances as function feels wrong. Also there's potential of clashing with actual functions. For eg. since there is a function `ObjectRegistry::reset()` you wouldn't be able to accessing a behavior named `Reset` through your proposal.

**Comment by dereuromark** [comment]
We are also accessing behaviors() and other classes this way, perfectly fine IMO.
The class issue sure is sth that needs to be considered, though.

**Comment by dereuromark** [comment]
Actually, by suffixing the type it would work fine:

    ->searchBehavior()->

etc
This would also make it more speaking.

**Comment by ADmad** [comment]
`->behaviors()->searchBehavior()` is unnecessarily redundant. IDE auto completing is nice to have but we shouldn't be uglifying code just for that purpose. Not everyone uses IDEs.

**Comment by dereuromark** [comment]
The primary reason is still go
a) not use property access
b) not use magic string access

both is the actual ugly part here :)
The method one is the elegant one, and just happens to also support IDEs better.
Redundancy is irrelevant IMO, but if you have a better I am happy to hear it.

**Comment by dereuromark** [comment]
PS: No one says you cannot continue to use the get + magic string access btw, but people that want the auto-typehinting and no magic string access are at least able to use it.

**Comment by davidyell** [comment]
I don't like accessing the behaviour as a function, or as a magic property.

I much prefer using the `->get()` method for a number of reasons. The first one is that the code is easier to read, and thus reason about, due to the word 'get' showing that it will return an instance of a behaviour from the collection, as inferred by its context. The code reads as a sentence which makes logical sense to me.

I also know, by reading the `behaviours()` method that it returns a collection, and thus will have a consistent interface for how I interact with it. As such a get method in a collection, to me, makes perfect sense as I am getting something from the collection.

The third reason I like the get method is that it actually exists. I can go and read the code, which means that when I'm reading the source code to find out what a method is doing, the code is right there for me to read. Which again, makes it easier to reason about. I often get frustrated with magic methods for this reason, because the code doesn't actually exist, leading to a dead end in the code.

The last reason is that a getter infers functionality, it tells me I can get something. A property infers that I can both read and write to that property. Which means something like this should be okay `$this->behaviors()->Search = new Search()`. Now, I haven't checked, but that doesn't seem right to me, as I'm now changing the internal state of the collection by direct assignment. At least with a get and set pattern, the allowed api is inferred from the method name and signature.

**Comment by dereuromark** [comment]
@davidyell I think you confused a few things now.
The property I suggest to deprecated and remove in favor of an optional and clean non magic string access. If you rather use the get() you can do that, you need manual inline annotations here however, otherwise you gain nothing and only lose.

We could also think about 

    getSearch()

as alternative to

    searchBehavior()

This would eliminate the "redundancy" issue mentioned above.

**Comment by dereuromark** [comment]
I modified the PR according to the feedback: https://github.com/cakephp/cakephp/pull/11246

**Comment by dereuromark** [comment]
In light of https://github.com/dereuromark/cakephp-ide-helper/pull/56 - and that both magic property and magic method access work fine here in IDEs - I will close for now. No immediate problem to be solved.
