### ISSUE TITLE
Passing array as parameter of errors() for validation

### ISSUE THREAD

**Issue by dividedbynothing** [cakephp/cakephp#11348]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.2
* Platform and Target:  XAMPP win32-7.0.8-0-VC14 (PHP 7 on Windows 10)

### What you did
Tried to pass array of two field names to errors() to validate only those two form fields against the model (not validate all fields, just these 2 fields).  As per the API document [here.](https://api.cakephp.org/3.5/class-Cake.Datasource.EntityInterface.html#_errors)

The model has 4 fields for validation.  I only want to validate two at this point.

In controller action:
`$data = $this->request->data;`
This results in:
`['number' => '102','color' => 'blue']`

Then...
`$keys = array_keys($data);`
This results in:
`[
(int) 0 => 'number',
(int) 1 => 'color']`
Then...
`$errors =  $this->Items->newEntity($this->request->data)->errors($keys);`

### What happened
All 4 fields in the model requiring validation were validated, not just 'number' and 'color'.

### What you expected to happen
Only the 2 fields passed to errors() in the array $keys should have been validated.

Note that if I hard code one field name as a string, such as:
`$errors =  $this->Items->newEntity($this->request->data)->errors('number');`
That works correctly and validates just that field.
If I hard code an array, such as:
`$errors =  $this->Items->newEntity($this->request->data)->errors(['number','color']);`
That validates ALL 4 validation fields from the model, not just the 2 defined fields.

Is this a bug, part of errors() deprecation, or am I missing something.

**Comment by cholthi** [comment]
Not sure  errors() method can do what you're  trying use it for

On 20 Oct 2017 9:05 pm, "dividedbynothing" <notifications@github.com> wrote:

This is a (multiple allowed):

   -

   bug
   -

   enhancement
   -

   feature-discussion (RFC)
   -

   CakePHP Version: 3.5.2
   -

   Platform and Target: XAMPP win32-7.0.8-0-VC14 (PHP 7 on Windows 10)

What you did

Tried to pass array of two field names to errors() to validate only those
two form fields against the model (not validate all fields, just these 2
fields). As per the API document here.
<https://api.cakephp.org/3.5/class-Cake.Datasource.EntityInterface.html#_errors>

The model has 4 fields for validation. I only want to validate two at this
point.

In controller action:
$data = $this->request->data;
This results in:
['number' => '102','color' => 'blue']

Then...
$keys = array_keys($data);
This results in:
[ (int) 0 => 'number', (int) 1 => 'color']
Then...
$errors = $this->Items->newEntity($this->request->data)->errors($keys);
What happened

All 4 fields in the model requiring validation were validated, not just
'number' and 'color'.
What you expected to happen

Only the 2 fields passed to errors() in the array $keys should have been
validated.

Note that if I hard code one field name as a string, such as:
$errors = $this->Items->newEntity($this->request->data)->errors('number');
That works correctly and validates just that field.
If I hard code an array, such as:
$errors = $this->Items->newEntity($this->request->data)->errors(['
number','color']);
That validates ALL 4 validation fields from the model, not just the 2
defined fields.

Is this a bug, part of errors() deprecation, or am I missing something.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cakephp/cakephp/issues/11348>, or mute the thread

**Comment by markstory** [comment]
> Only the 2 fields passed to errors() in the array $keys should have been validated.

This isn't how the errors() works. It lets you set error messages into the entity marking the passed fields as invalid. It does not change how request data is validated. When you use `errors('field')` you are reading the validation errors already set in the entity, not changing which fields will be validated.

**Comment by dividedbynothing** [comment]
Thank you for the responses.  I will close this.
