### ISSUE TITLE
SecurityComponent blocks formaction attribute

### ISSUE THREAD

**Issue by stefanniedermaier** [cakephp/cakephp#11427]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.5.5

### What you did
I'm creating a form via `FormHelper` and having an ajax-Submit to the Form-Action and another Submit for a different URL
```html
<form method="post" accept-charset="utf-8" role="form" action="/url1">
    [...]
    <button type="button" onClick="javascript:sendViaAjaxToFormAction(this)">
    <input formtarget="_blank" formaction="/url2" id="preview" value="Preview" type="submit">
    <div class="hidden">
        <input name="_Token[fields]" autocomplete="off" value="..." type="hidden">
        <input name="_Token[unlocked]" autocomplete="off" value="" type="hidden">
        <input name="_Token[debug]" autocomplete="off" value="..." type="hidden">
    </div>
</form>
```

### What happened
Ajax works fine, but the second submit using a different formaction gets blocked by SecurityComponent `URL mismatch in POST data`

### What you expected to happen
I would expect that both - action and formaction - pass SecurityComponent

**Comment by markstory** [comment]
The URL is a key component in the security token generation. By submitting a form to a different URL than was originally intended is supposed to cause a validation failure as you are tampering with the form. SecurityComponent cannot tell the difference between the URL being changed maliciously or intentionally by client side code.

**Comment by markstory** [comment]
Closing as changing the form submission URL qualifies as form tampering and the token validation should fail (as it is).

**Comment by stefanniedermaier** [comment]
I know that the URL is a key component of the security token generation, but i don't fully commit to your point of view. Maybe we should see this as feature request/enhancement and not as a defect.

The form won't be submitted to an URL that wasn't originally intended. The whole form is created via `FormHelper` and should be submittable to two different URLs. For this i'm using standard HTML features, which aren't compatible to `SecurityComponent`. This use case isn't common and isn't often used, but sometimes i have to use this HTML feature.

What i think of is maybe to add the feature to use multiple valid URLs for SecurityComponent by injecting the different URLs from all submit-elements via `FormHelper` (maybe `HtmlHelper` too) and checking for all of them in `SecurityComponent`.

**Comment by markstory** [comment]
> Maybe we should see this as feature request/enhancement and not as a defect.

I'm open to that.

> The form won't be submitted to an URL that wasn't originally intended. The whole form is created via FormHelper and should be submittable to two different URLs. 

How would you incorporate the 2 options into a single hash that can be verified on both URLs without requiring persistent state?

> This use case isn't common and isn't often used, but sometimes i have to use this HTML feature.

The infrequency of use is one of the reasons I'm reluctant to add support for something like this. If it is not being used it is adding complexity and increases the cost of future changes.

**Comment by diegosardina** [comment]
Could it be reopened?

Having multiple submit buttons that post to different actions helps to simplify big and complex forms.

Also having support for formmethod would be nice.

**Comment by markstory** [comment]
@diegosardina Only if you are interested in implementing it. This issue sat for two years previously.

**Comment by diegosardina** [comment]
As you said a persistent place is required to store all the action urls to hash later, this is not ideal because of the complexity behind it.

In my opinion this kind of prevention must be revaluated, because hashing of form fields is an already strong fingerprint for form security. It could be made optional with 'extraSecurity' => true.

I don't understand the rationale described [here](https://github.com/cakephp/cakephp/commit/f23d811ff59c50ef278e98bb75f4ec1e7e54a5b3), because the attack to be effective must be done between two forms that have identical fields.

On slack they pointed me out that one may change the action from /entity/edit to /admin/entity/edit, however this argument didn't convince me, for the following reasons:
1) Usually an admin url is with an appended random string, so the attacker has to guess the right url,
2) admin forms often have more fields compared to the non-admin ones, the hash will be different,
3) with proper auth and acl, an admin url is not accessible by normal users.

In my opinion this prevention is not worthy due to the limitation it causes, especially considering the evolution of web development (such formaction attribute).

Or am I missing something obvious?

**Comment by markstory** [comment]
> Usually an admin url is with an appended random string, so the attacker has to guess the right url,

I've never done that before so I don't know how 'usual' that practice is.

> admin forms often have more fields compared to the non-admin ones, the hash will be different,

This isn't how form tampering prevention works though. We can't know the hash of the expected fields. Instead we can only hash that the form still contains all the fields it did when it was created. If those fields overlap with another action then the forms can be cross posted creating a vector for tampering.

> with proper auth and acl, an admin url is not accessible by normal users.

One could argue that with 'proper' auth and acl, form tampering prevention isn't necessary at all.

**Comment by diegosardina** [comment]
> 
> I've never done that before so I don't know how 'usual' that practice is.
> 
It is the first countermeasure against /admin bruteforcing scripts

> 
> This isn't how form tampering prevention works though. 
> 
I oversimplified it just for the sake of brevity

> 
> One could argue that with 'proper' auth and acl, form tampering prevention isn't necessary at all.
>
I didn't mean that, but of course the example they gave with /admin doesn't apply because it's often (I would say _always_) protected.

If this is the only use case, it is an over prevention that is limiting many other use cases that are useful (and now part of the html5). Just for the record I saw only CakePHP that prevents a different url in the action.

>
> This issue sat for two years previously.
>

The fact that nobody in these years was interested to it: not many people are aware of new html5 features and not many are interested in using them to improve their code.

**Comment by diegosardina** [comment]
What about allowing suburls or whitelisting a controller? By default or throught an option like ->allowSuburls() (not the best name, just to give the idea).

The url to hash will be /invoices/ for example and all actions:
/invoices/add
/invoices/addItem
/invoices/recalculate
etc..

will be accepted since they share the same prefix

**Comment by markstory** [comment]
I'm ok with an opt-in relaxing of token verification. I'm not sure how you would go about implementing that based on how the current hashing works, but an opt-in mode that relaxes the accepted URLs sounds good to me.

**Comment by diegosardina** [comment]
> I'm not sure how you would go about implementing that based on how the current hashing works

I don't know CakePHP internals. Is it troublesome to implement?

For now I'm using unlockedActions but it also disables other protections :-(

**Comment by markstory** [comment]
> I don't know CakePHP internals. Is it troublesome to implement?

The current hashing takes the fields, url, sessionid, combines them and hashes them. With relaxed urls there would need to be additional checks against the url prefix and ensuring that the hash inputs are consistent between the form generation and validation.
