### ISSUE TITLE
Add $query->whereApplicable() ?

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/cakephp#11576]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

What do you all think about having something like this:

```php
$query->find()->whereApplicable(['SomeTable.some_field_that_might_exist' => 'asdf']);
```

The idea is that it will simply return the query object unaltered if the column doesn't exist instead of throwing an exception. Obviously I can just check this before making the query, but it would be useful to have for something like a search feature, where you know that for instance `created` and `modified` *usually exist* on your tables, but might not, and you want to have some kind of base query modifier for search that can be extended per table without fear of an exception being thrown when those fields don't exist (aren't applicable).

I think `$query->find()->first()` vs. `$query->find()->firstOrFail()` is analogous in that we have the option to throw the exception there, or just return an empty result set.  I'd like to do the same when the *schema* is not applicable as opposed to the records themselves not existing.  Is this a useful idea, or should the developer just do this check themselves?  Would something like this be an abuse of the ORM or otherwise not worth pursuing?

**Comment by inoas** [comment]
On the left-hand side could be more than just vanilla identifiers.
I'd say just make a conditional check against the table object if the field exists in the schema in your user land code?

**Comment by thinkingmedia** [comment]
I don't think the failure you're referencing happens when the query is being built, but later when the SQL driver tries to compile the query. The difficulty here as @inoas as stated is that everything is converted into a hierarchy of expression objects. So the context of making something optional gets lost easily or very difficult to track.

You have a could of other options to handle this case:

- check your schema before adding the where
- create your own expression object that optionally applies the rules if the field identifier exists.
- for tables missing columns add alias columns via select with default values that apply the conditions

**Comment by markstory** [comment]
I'd like to know a bit more on how this would actually work? Right now it looks like you're wanting the ORM to check the provided conditions against the schema, and drop those conditions if the columns are not available to the query. Is that a fair description?

**Comment by kevinquinnyo** [comment]
@markstory that is correct, but the more I think about this, the less use-cases I can think of for it.

Currently I was able to simply inspect the schema with `Table::getSchema()` and it's really not an unreasonable amount of work to do, whereas I imagine it would be an unreasonably hard feature to support in the ORM.

Basically I just don't think it's as useful as I did when I opened the issue and have had a chance to think about it a bit more.
