### ISSUE TITLE
All shells fails to run when there is a typo in another shell

### ISSUE THREAD

**Issue by xavifr** [cakephp/cakephp#11637]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.10
* Platform and Target: Linux server

### What you did
I left a typo in a test shell (TestShell.php).

### What happened
cake binary stop working at all

### What you expected to happen
I think that all other shells should continue working and only fail test shell

### How to Reproduce
It can be reproduced in a minute creating an empty project from composer baking two shells and adding a typo in one of them.

`cd /opt`
`composer create-project --prefer-dist cakephp/app test2`
`cd test2`
`composer update`
`cp config/app.default.php config/app.php`
`./bin/cake bake shell test1`
`./bin/cake bake shell test2`
`echo "typo" >> src/Shell/Test2Shell.php`
`./bin/cake`

### Output
`Exception: syntax error, unexpected end of file in [/opt/test2/src/Shell/Test2Shell.php, line 37]`

**Comment by ADmad** [comment]
Well it's just `./bin/cake` which is generating error, since it runs command shell which loads and lists all available shells. Running a specific shell like `./bin/cake foo` should still work run just fine.

In PHP 7 we can catch fatal errors. So perhaps wrap the line to create shell instance in `CommandTask::getShell()` in a try catch block?

**Comment by xavifr** [comment]
I got the same error running test1 shell

```shell
$ php bin/cake.php test1
Exception: syntax error, unexpected end of file in [/opt/test2/src/Shell/Test2Shell.php, line 37]
$ ./bin/cake test2
Exception: syntax error, unexpected end of file in [/opt/test2/src/Shell/Test2Shell.php, line 37]
```

**Comment by ADmad** [comment]
Okay, that's pretty bad.

**Comment by markstory** [comment]
We have to load all the available commands in order to dispatch the correct command/shell.

**Comment by dereuromark** [comment]
I think expecting all files to be valid syntax (no "syntax error" issues) can be expected IMO.
Doesn't mean the commands are running fine, but at least from a compiler perspective that should be able to be required.
It also does output concrete help (fix issue in Test2Shell.php, line 37), so that sounds fair eough.

**Comment by xavifr** [comment]
I agree that it is supposed you must leave the code clean before a release, but sometimes there could be errors or you can forgot something in a test or unused shell. In those situations all other shells stop working at all.

I've checked in cakephp 2.x and a typo in a shell doesn't affects the other ones.

**Comment by markstory** [comment]
> I've checked in cakephp 2.x and a typo in a shell doesn't affects the other ones.

Yes. 2.x uses a completely different shell dispatching implementation, so there will be difference in behavior.

**Comment by dereuromark** [comment]
This sounds at this point more a developer issue than a core one. Closing as we cannot do anything here, the code must at least be valid syntax.
