### ISSUE TITLE
issue intl in xampp for cakephp

### ISSUE THREAD

**Issue by testmode123** [cakephp/cakephp#11652]
I Have installed xampp latest version with PHP7.2.1 in windows.
And Then Composer also installed.
then  CakePHP 3.5 installed but there is error show with "You must enable the intl extension to use CakePHP."

BUT... BUT...
I searched for an error on google and there is show that.....
i did extension=intl uncommented.
i did extension=mbstring uncommented.
i did icu*.dll files copy from c:\xampp\php to c:\xampp\apache\bin. And xampp restart.

but again CakePHP 3.5 installed but there is error show with "You must enable the intl extension to use CakePHP."

I tried to solve this error. But I don't have a proper solution for this error.

Please help me.

**Comment by inoas** [comment]
This is not a support system. Try one of these:

http://discourse.cakephp.org/
https://stackoverflow.com/tags/cakephp
https://webchat.freenode.net/?channels=cakephp
https://cakesf.herokuapp.com/

p.s.: I'd simply recommend using a vagrant solution like puphpet.com or homestead or a docker solution instead of xampp.

**Comment by ajagarcia19** [comment]
Try running xampp as an administrator everytine you are using your server. 

From xampp console, ensure that both apache and mysql are setup as service. 

Reboot your computer and don't forget to run xampp as an administrator.
