### ISSUE TITLE
TreeBehavior::afterDelete: child node callbacks not executed

### ISSUE THREAD

**Issue by techlands** [cakephp/cakephp#11742]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.10.7
* Platform and Target: all

### What you did
Using TreeBehavior with another behavior results in afterDelete not being called on other behaviors when TreeBehavior is deleting child nodes.

### What happened
TreeBehavior::afterDelete uses Model::deleteAll with the default $callbacks = false argument causing callbacks not to fire when deleting child nodes.

### What you expected to happen
Patching lib/Cake/Model/Behavior/TreeBehavior.php with below fixes the issue. This could also be enhanced with an additional setting for TreeBehavior that can enable/disable using callbacks when deleting child nodes.

```
201c201,203
< 			$Model->deleteAll($scope);
---
> 			$Model->Behaviors->disable('Tree');
> 			$Model->deleteAll($scope, true, true);
> 			$Model->Behaviors->enable('Tree');
```

**Comment by josegonzalez** [comment]
We have supported 2.x since October 2011 and have [clearly communicated](https://bakery.cakephp.org/2017/07/22/cakephp_2100_released.html) that it will receive only bug and security fixes from June 2017 going forward. We both cannot accept any pull requests or issues which:

- backport 3.x features to 2.x
- add/request new functionality for 2.x

Doing so will unfortunately increase our maintenance overhead. We appreciate your participation in the CakePHP project, but as a group of volunteers contributing their spare time for free there's only so much we can do, and at the moment we are focused on maintaining 3.x and moving towards 4.x.

What I would suggest in this case is vendoring or subclassing the TreeBehavior within your project and using it there. As we are only applying security patches and bug fixes, upgrading to the latest 2.x patch release should result in a fairly minimal amount of work.

Thanks for understanding.
