### ISSUE TITLE
Simple Query::where() syntax

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#11745]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.x

A discussion about `where` syntax in ORM

Current syntax
```php
$articles->find()->where(['id' => 3]);
```

could be
```php
$articles->find()->where('id', 3);
```

My "problem" is in the `['field' => 'value']` syntax and "heavy" to write and read

**Comment by dereuromark** [comment]
While you find it heavy to write, most find it consistent.
What about all the other methods, which also accept an array?

It will also increase the cycl. complexity of the methods' internals.
More if/else that can make the method buggy or introduce unexpected side-effects.

Last but not least, in light of PHP7.1 we try to actually go to a more strict API in general, to add more typehints and not less. So what you are suggesting means we cannot array typehint here which is a step backwords, rather than forward. Methods should always have as least possible types  (besides nullable) as possible.
It would have to be its own method name (e.g. whereSingle() or sth), but is that really worth it?

I am :-1: as the current consistent API makes it actually easier to work with as you know what to expect.

**Comment by inoas** [comment]
Well `where()` can do a lot more like having expressions on the left side.
However what about `whereColumn($column, $valueOrExpression)` or `whereField($field, $valueOrExpression)` or `whereProperty($property, $valueOrEpxression)` (all the same just different name). The column/field/property must then be an aliased field and exactly that, nothing else.

```php
$query->whereField('User.username', 'mark')
```

The query builder can easily check if those fields exist without any magic and can even do early type comparison (e.g. if casting the 2nd param is lossless or already the correct type).

**Comment by markstory** [comment]
We could also have `addWhere()` to support this new argument set. I would prefer to avoid  overloading the parameters of `where()` further, but agree that in simple cases the current syntax is a bit clunky.

**Comment by dereuromark** [comment]
I strongly advise against overloading `andWhere($conditions, $types = [])` as well.
This introduces a code smell.
If anything, I would agree that `whereField()` could be done, but do we then also need yet another `andWhereProperty()`?
If we start this, then people also would want `orWhere()` in a similar fashion. 
Same for `group()` (`groupField()`), having, andHaving, orHaving etc.

`order()` already exists by the way (`orderAsc($field...`, `orderDesc($field...`).

**Comment by inoas** [comment]
@markstory `addWhere()` implies that multiple concatted `where()` actually overwrite/replace each other. But as it is a builder object that's not the case.

So `whereField()` makes more sense I suppose.

p.s.: wasn't `andWhere()` and `orWhere()` to go down the toilet anyway for good reasons?

**Comment by dereuromark** [comment]
@ionas: Only orWhere() is deprecated. If we go with whereField() at least andWhereField() seems to be a method that will have to be added for consistency.

**Comment by Erwane** [comment]
Nice discussion :)

I completely understand your point of view @dereuromark about typehints and complexity.
Introducing new methods could be the right way but introduce new complexity (more methods to knowns for developers).

I've just checked the Laravel documentation about Eloquent (not saying they do it better, different approach)

<https://laravel.com/docs/5.6/queries#where-clauses>

Something like that is really ... eloquent ;)
```php
$users = DB::table('users')
                    ->where('votes', '>', 100)
                    ->orWhere('name', 'John')
                    ->get();
```

It's a **huge** work to revamp a code (and compatibility problem) but i love cake for simplicity and said to myself ... "arrrhh, an array again" and want to discuss about that :)

**Comment by saeideng** [comment]
I no fun with `orWhere()` / `andWhere()` for this case

**Comment by inoas** [comment]
@Erwane well Eloquent is not strict for its types but needs to juggle... is the 2nd param an operator? Is it a value? Then I wonder what happens if you place an expression on the left side instead of a simple field? Last but not least that orWhere() design is **horrible** and ultra error prone. `orWhere()` should either take a closure which expects an array of where conditions or the array syntax as the current `where()` does.

Now again, if you have a lot of simple cases I can see that you don't want to type brackets and I can see that field == value is what one wants to type. So we could also do `->equals($field, $value)`
Something similar afaik already works as in form of `->newExpr()->eq('field', $value)` - equals() would then just be a wrapper for that. However it moves away from the where semantics... so I'd still prefer `whereField()`...

**Comment by lorenzo** [comment]
Is it actually heavy to read? I actually find it quite clear. If you wanted to type less, we could offer some specialised methods like:

- `whereEq($a, $b)`
- `whereIn($a, $b)`
...

I would not add many of those, to be hones. I find the array conditions to be the most flexible option of all. At some point I toyed with the idea of proving functions instead. Like:

```
use \Cake\ORM\Query\eq

$query->where(eq('field', $vaue))
```

**Comment by markstory** [comment]
@lorenzo We could start with just `whereEq()` and `whereIn()`. I think those address many of the scenarios where you want to constrain by a single field. More methods can always be added later on.

**Comment by dereuromark** [comment]
Sounds like a good compromise.
People who want the sugar, can include it easily, the others don't have more API "noise" in the default Query object.

**Comment by saeideng** [comment]
for me 
`where(['id' => 3]);` is very clear than ` where('id', 3);`
I really no like ` where('id', 3);`
if you need this 
there is other name  :)
`when('id', 3)`

**Comment by Erwane** [comment]
`whereEq('field', 'value')` and `whereIn('field', ['array', 'of', 'data'])` sounds very good

Thanks ;)

**Comment by burzum** [comment]
If we implement `whereIn()`, can we accept int and string as well and put it into an array? I had more than one time the case that I needed to switch between a simple `=` and `IN` because the input could be both, array or single int (an id).

**Comment by inoas** [comment]
Just case them to array.

Personally I'd rather see `whereStringIn()` and `whereIntIn()` which strictly accepts array of type.

**Comment by dereuromark** [comment]
```
$data = ['array', 'of', 'data'];
$data = 'string';
// should both work with
whereIn('field', $data);
```

otherwise the whole check logic will have to be in controller and co again, which is pointless.

**Comment by burzum** [comment]
I usually agree to that methods shouldn't take a ton of different types but there are cases where it makes sense. It's mostly due to the lack of php of being able to accept different method signatures like in c# where you can have method(int foo) and method(string foo, bool bar) and depending on the arguments it calls the right method. I hope we'll see the same behavior of php in a future version.

**Comment by inoas** [comment]
You have to do no checks. If you expect data to be of multiple types you can simply cast them.

Having worked with 7.1/7.2 lately in production, the more strict you are throughout all layers, the more bugs you catch early.

**Comment by inoas** [comment]
Also we can have a convenient weak-type `whereIn()` right now and if I really have the desires I can create a separate PR to have `whereStringIn()` / `whereIntIn()` / `whereFloatIn()` and `whereDecimalIn()`.

**Comment by dereuromark** [comment]
I would say: prepare your data beforehand, and please avoid providing too many methods here on the interface level.
Let's keep things simple.

**Comment by inoas** [comment]
I disagree strongly. Many specific and strict methods is the way to go. Little complex, weak methods is the 💯 % the wrong way.
Let's keep things simple.
