### ISSUE TITLE
I18n/Time::timeAgoInWords() produces wrong results in April

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#11908]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.x
* Platform and Target: Win, OSX, Linux

### What you did

Adde this case for testing the issue I experienced in our app.

```php
    public function testWrongTimeCase()
    {
        Time::setTestNow('2018-04-12 14:00:00');
        $date = new Time('2018-04-11 13:00:00');
        $result = $date->timeAgoInWords();
        $this->assertEquals('1 day ago', $result);
        Time::setTestNow(null);
    }
```

### What happened

```sh
1) Cake\Test\TestCase\I18n\TimeTest::testWrongTimeCase
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1 day ago'
+'5 days'
```

### What you expected to happen

That it's one day ago. 😄 

### Additional information

This is a problem because the date in entities is returned as a I18n/Time object:

```sh
        'start_date' => object(Cake\I18n\Time) {

                'time' => '2012-12-19T14:19:41+00:00',
                'timezone' => 'UTC',
                'fixedNowTime' => false

        },
```

**Comment by ADmad** [comment]
> This is a problem because the date in entities is returned as a I18n/Time object:

If you have set the field type as "date" in db then you should get a `Cake\I18n\FrozenDate` or `Cake\I18n\Date` instance, not `Cake\I18n\Time`.

**Comment by dereuromark** [comment]
We should deprecated Time in favor of FrozenTime. The same test with the latter passes.

**Comment by markstory** [comment]
Sounds like the testnow is not being used and the issue has nothing to do with April. What is `Time` in that method?

**Comment by burzum** [comment]
@markstory it's `\Cake\I18n\Time` and you can copy and paste the test I pasted and put it in the core tests. The test is for the core, not from our app.

**Comment by chinpei215** [comment]
Related code:
https://github.com/cakephp/cakephp/blob/bca167d7c7904f04787b5128b671d0cf8dc3de53/src/I18n/RelativeTimeFormatter.php#L96
https://github.com/cakephp/cakephp/blob/bca167d7c7904f04787b5128b671d0cf8dc3de53/src/I18n/RelativeTimeFormatter.php#L365

Whereas Time::setTestNow() is called in the problematic code, RelativeTimeFormatter::timeAgoInWords() uses FrozenTime::now() internally. Since Time and FrozenTime are derived from different parents - MutableDateTime and Chronos, [static::$testNow](https://github.com/cakephp/chronos/blob/a036d3e53d0f4c06767c66ae45c1f0a8c77f811a/src/Traits/TestingAidTrait.php#L29) will be different instances.

As a result, RelativeTimeFormatter returned `5 days` that the diff between `2018-04-06` (The day you ran the test) and `2018-04-11`, as FrozenTime::now() is not fixed to `2018-04-12 14:00:00`. If you ran the same test tomorrow, you will get `4 days`.

My suggestion is to use a static storage or a singletone to store the *now* instead of static::$testNow:
```php
public static function setTestNow($testNow = null)
{
    Configure::write('Test.now', is_string($testNow) ? static::parse($testNow) : $testNow);
}
```

**Comment by chinpei215** [comment]
Using Configure class is not good idea as chronos seems to not depend on CakePHP. Having some storage in the Chronos itself may be better:
```php
public static function setTestNow($testNow = null)
{
    $storage = SomeStorage::getInstance();
    $storage->setTestNow($testNow);
}
```

**Comment by markstory** [comment]
Having all the test 'nows' point to the same value could work if we separate dates and datetimes. Sharing one single value will likely break existing use cases.

**Comment by chinpei215** [comment]
I didn't think it was an intented behavior. But I am not sure what the benefit is. It could happens only in test cases, but never happens in the real world. When `Time::now()` returns `2018-04-12 14:00:00` in the real world, `FrozenTime::now()` should also return `2018-04-12 14:00:00`. If people have test cases which depend on the current behavior, that means that the code is not tested well.

**Comment by lorenzo** [comment]
Can we introduce a helper function in tests like mockNow() and have it set the time to all known subclasses?

**Comment by chinpei215** [comment]
Where do we put the helper function on? If we put it on the `Cake\TestSuite\TestCase`, people cannot use the function without CakePHP.

**Comment by markstory** [comment]
@lorenzo we have setTestNow in a trait. That trait could reference an existing class via a hardcoded name. That would keep the api the same and fix the behaviour issues we are having.

**Comment by markstory** [comment]
Pull request up for Chronos that solves this.
