### ISSUE TITLE
Config or constant to define default entity class, default table class, default validator /validation class

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#12119]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.6

### What you did
I'm using own entity class (\App\Model\Entity\Entity extends \Cake\ORM\Entity) as parent for all entities 
and ownr table class (\App\Model\Table\Table extends \Cake\ORM\Table) as parent for all tables

### What happened
Join models by default are created as \Cake\ORM\Entity (hardcoded in Table::getEntityClass),
and also Cake\ORM\Table is hardcoded in Cake\ORM\Association::_getClassName()
$_validatorClass = '\Cake\Validation\Validator' is hardcoded in ValidatorAwareTrait

### What you expected to happen
Maybe it will be good idea to have some config where it will be possible to change these default classes?

**Comment by andrii-pukhalevych** [comment]
What is preferred place to define default table/entity/validator/validation class?
It can be new section in app.php or some bootstrap code.

**Comment by jimbo2150** [comment]
Theoretically (I've not tried it), you could map the CakePHP classes to another using [class_alia](https://www.php.net/manual/en/function.class-alias.php) (PHP 5.3+) then alias your class as the CakePHP class. For instance, you could alias `\Cake\ORM\Entity` as `\CakeCore\ORM\Entity` then aliasp `\App\Model\Entity\Entity` as `\Cake\ORM\Entity` which extends `\CakeCore\ORM\Entity` in your bootstrap.

**Comment by ADmad** [comment]
What you need is already possible with the use of table locator and factory.

In your `\App\Model\Table\Table` set the `$_entityClass` and `$_validatorClass` class properties to the default entity class and default validator class you want.

Extend `Cake\ORM\Locator\TableLocator` and override relevant parts to return instance of your `\App\Model\Table\Table` class as fallback class instead of `Cake\ORM\Table`. Then use `FactoryLocator::set()` to set your custom locator for `Table` type.
