### ISSUE TITLE
Query object should implement Countable

### ISSUE THREAD

**Issue by asgraf** [cakephp/cakephp#12267]
This is a bug/enchantment
### What you did
````PHP
//Relevant controller code
$items = $this->SomeModel->find('all')->where(['active'=>true]);

$this->set('items',$items);
````
````PHP
//Relevant element code
foreach($items as $index=>$item) {
    if($index==0) {//first item
    //some irrelevant code for first item 
    }

    $last_item_index = count($items)-1;
    if($index==$last_item_index) {
    //some irrelevant code for last item 
    }

    //some other irrelevant code
}
````

### What happened
````
Warning: count(): Parameter must be an array or an object that implements Countable
````

### What you expected to happen
count($items) should return number of $items

**Comment by saeideng** [comment]
why not `count($items->toList())`

**Comment by Asgraf** [comment]
> why not count($items->toList())

1) Because standard PHP array does not have have ->toList() method.
This particular Element should work the same way regardless if $items variable contains an array, Query, ResultSet or other array-comptatible object. 
Yes, it is possible to make if-else for every variable type but i would like to keep code DRY.

2) This particular code comes from cakephp 2.x application that im currently porting to cakephp 3.x
Since in cakephp 2.x Model->find() always returned standard arrays not uncommon thing is to find usages of count($items) in 2.x ctp files
Making Query object implement Countable interface would spare adding extra code in many ctp files that happened to use count() function (when porting them to 3.x)

**Comment by markstory** [comment]
Have you tried 

```php
$items = $query->all();
$count = count($items);
foreach ($item in $items) {

}
```

The `ResultSet` object implements `Countable`.

**Comment by lorenzo** [comment]
We can't implement `Countable` for Queries, unfortunately. There are 2 reasons:

* In order to implement countable, we need to have a `count` method in the query, but it already exists. It has a different signature to what the interface requires, so PHP would not accept it.
* The `count()` method in the query returns the result of `SELECT COUNT(...)`, which in your case is not what you would need. This opens up the question, what is the acceptable result for `count` in a query?

I would rather add more method to the `Collection` library so this type of patterns are pleasant to write, especially in views.

**Comment by lorenzo** [comment]
ah, true, I thought it was still receiving a parameter. In any case, the method is already being used for something completely different to what you want

**Comment by Asgraf** [comment]
> method is already being used for something completely different to what you want

The only difference i had found in documentation is the fact that the `$query->count()` ignores the pagination clauses (limit, offset, page).
Why this pagination clause ignoring in `$query->count()` is even a case?
Should not pagination logic be part of a Paginator?
IMHO i think Paginator should remove those pagination clauses from Query clone before calling `$query->count()` instead of count method ignoring those clauses.
Pagination clauses stripping could be extracted to separate method `stripPaginationClauses()` so the old count() behavior could be easy recovered like this:
````php
$query = $this->SomeModel->find()->limit(10);

//should not ignore limit clause for compatibility with count($query)
$number_of_entities_in_foreach =  $query->count();

//old behavior, limit clause ignored
$number_of_maching_rows_in_table =  $query->stripPaginationClauses()->count();
````

**Comment by lorenzo** [comment]
The count is implemented that way so you can get the total number of rows for a particular query. It also does more than just stripping the `limit` and `offset`.

@Asgraf I don't want to say that your idea is bad, but I think we are at a point where discussing this will not takes us anywhere further. This is the current API we have and we are committed to it until at least `5.0`, so changing the `count()` method to do something different could take a lot of time and effort by the community to change the already existed usages.

**Comment by Asgraf** [comment]
Ok, i understand.
Lets mark this issue as my `5.0` proposal then :wink:

**Comment by saeideng** [comment]
> I think template files should not be a place for checking ORM related stuff.

just needs a `toList()` in controller 
```php
$items = $this->SomeModel->find('all')->where(['active'=>true]);

$this->set('items',$items->toList());
```

**Comment by Asgraf** [comment]
Calling toList() or all() causes instant execution of SQL query
Calling it in controller causes unnesesary slowdown if element is not displayed and passed $items variable not used.
Passing Query object has advantage of lazy SQL execution.
(if element is not displayed and passed $items variable not used, no SQL is executed at all)
