### ISSUE TITLE
The YEAR field type for Mysql

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#12514]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5

### What you did
Added YEAR mysql column.

```sql
	`start_year` year(4) NOT NULL,
	`end_year` year(4) NOT NULL,
```

The [YEAR field type](https://dev.mysql.com/doc/refman/5.6/en/year.html) allows one to store a year in a field, and have this field default to the current year.

### What happened
Value is returned as string.

### What you expected to happen
Value is returned as integer.
Mysql YEAR data type is handled like this:
https://github.com/cakephp/phinx/commit/1eb069a500e9b78a442e01cd83ba6b6a80ae1855

**Comment by andruhapx** [comment]
@ADmad Because values are always 4 digits

**Comment by markstory** [comment]
Because the `YEAR` type isn't implemented in any other supported database it is not likely to get its own abstract schema type. We could map this column type to the `integer` abstract type but that will result in schema generated by fixtures using `int(4)` instead of `YEAR`.

**Comment by andruhapx** [comment]
@markstory Mapping column type to the `integer` is enough, better is `smallint(4) unsigned`.
That will result less memory consumption because int will be used instead of string, also marshalling will set correct values only.
I already did 
`$this->getSchema()->addColumn('year', ['type'=>TableSchema::TYPE_SMALLINTEGER, 'length'=>4, 'unsigned'=>true])` 
in my table initialization, but general field type support via framework will be great.

**Comment by markstory** [comment]
If you're interested in making it happen you could open a pull request for `3.next` to change the mappings in the MySQL schema dialect.

**Comment by ADmad** [comment]
Closing as there was no follow up pull request and general lack of interest.
