### ISSUE TITLE
SecurityComponent's messages are not translatable

### ISSUE THREAD

**Issue by dmromanov** [cakephp/cakephp#12637]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: master.
* Platform and Target: any.

### What you did
1. Disabled debug mode
2. Extracted all app's and CakePHP's translatable strings. Translated them into russian.
3. Enabled and triggered a SecurityComponent's error by altering a form.

Or

2. Add `$this->Security->requireSecure();`
3. Try to open the app with HTTP instead of HTTPS.

Or trigger any other security error.

### What happened
Message "The request has been black-holed" was displayed to end-user as is.
![image](https://user-images.githubusercontent.com/299059/46864034-c76f4180-ce21-11e8-8d5c-0c4683de3c58.png)

### What you expected to happen
SecurityComponent's message to be wrapped with GetText function, so it could be extracted and translated.

**Comment by markstory** [comment]
All of the core provided exceptions and their messages are not translated and likely won't be as adding translation calls in the exceptions created too many cross package dependencies. Why would these exceptions be treated differently?

**Comment by dmromanov** [comment]
Sorry, by all messages I was meaning a specific message: "The request has been black-holed". Because all security messages can be limited to the message I have previously mentioned.

I expect the message to be translatable, because security exceptions can be easily triggered (e.g. requireSecure()), the message is displayed to end user, just like any other error message in CakePHP (e.g. page not found, unauthorized) and the latter are translatable.

I have corrected the report's body. I hope it will make it clearer now.

**Comment by ravage84** [comment]
> Try to open the app with HTTP instead of HTTPS.
> Message "The request has been black-holed" was displayed to end-user as is.

I don't think this is really a helpful behavior in this case. I would use a more specific message in that case, detailing why it was black-holed. Certainly, one doesn't want to leak all his internal security rules, but this one is a general enough one to state what the problem is.

It looks we are always throwing the default exception message here:

https://github.com/cakephp/cakephp/blob/2341c3cd7c32e315c2d54b625313ef55a86ca9cc/src/Controller/Component/SecurityComponent.php#L214

@dmromanov  but it seems you can override the behavior using ``SecurityComponent::blackHole()`` like this:

https://book.cakephp.org/3.0/en/controllers/components/security.html#handling-blackhole-callbacks

@markstory what do you think about adding a template to the app skeleton for black holed requests? That template could have ``__()`` wrapped texts.

**Comment by ravage84** [comment]
@markstory I had another look at how one could translate the displayed error message of a blackholed request.

I found the following:

1.  Custom error handler middleware, e.g. in ``ErrorHandlerMiddleware::handleException()``
1. Custom exception renderer, e.g. around ``ExceptionRenderer::render()``
1. Custom error400.ctp template, e.g. around ``h($message)``
1. Custom blackhole callback handling, as documented in  https://book.cakephp.org/3.0/en/controllers/components/security.html#handling-blackhole-callbacks

Since I think the last one is the most appropriate one, I came to the conclusion that this issue is once again mainly a documentation issue.

That's why I proposed changes to the related example in the docs in cakephp/docs#5884

**Comment by dmromanov** [comment]
> But it seems you can override the behavior using SecurityComponent::blackHole()
Of course, I can override the method, but it's not too practical: I'll have to redefine this method in every project where the language will be different from English, and I'll also have to keep into my mind with information about this .

The point is, if I call `cake i18n extract`, I expect to get a dictionary of *all* possible messages that CakePHP can produce before I encountered them in runtime.

So I expect the message "The request has been black-holed" to be wrapped in the translation function GetText `__()`.

**Comment by ravage84** [comment]
> I expect to get a dictionary of all possible messages that CakePHP can produce before I encountered them in runtime.

@dmromanov I understand that the current behavior of the Framework does not satisfy your expectations. You want to be able to easily, in a "don't repeat yourself"-way, translate exceptions produced by the framework.
To my experience one should __not__ show exception messages, even translated, to their users. Exceptions are for developers, to help them debug problem, not for users to make sense of.

In your case, I guess the most sensible way to translate the exceptions coming from the framework is by using one of the four methods I listed above and extract that code to a plugin, which you can reuse.
