### ISSUE TITLE
regression in 3.7.0 viewVars cannot be read without deprecation warning

### ISSUE THREAD

**Issue by markusramsak** [cakephp/cakephp#12790]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.0

### What you did
`if (isset($this->viewVars['viewVariable'])) {  }`
or
`echo $this->viewVars['viewVariable'];`

### What happened
deprecation warning

### What you expected to happen
no deprecation warning

I agree that direct access to the viewVars array is not perfect but could we at least add a method like:
`getViewVar(string $name)` 
or simply
`get(string $name)`

to get the value of the view var in the controller?

**Comment by ADmad** [comment]
CakePHP itself does not generate any deprecation warning when accessing `$this->viewVars`, I presume it's your IDE which does.

If you want to avoid those warning you can use `$this->viewBuilder()->setVar()` to set view var and `$this->viewBuilder()->getVar()` to access it.

**Comment by markusramsak** [comment]
Everywhere in controller I now use `$this->viewBuilder()->setVar()` instead of `$this->set()`, so I can use $this->viewBuilder()->getVar() in the controller or a component or trait to check or change the variables passed to the View.

**Comment by tfont** [comment]
This needs to be re-open.
@ADmad completely misunderstood the problem here.

`$this->viewVars['viewVariable']` retrieves the active controller instance of variables.

Using `$this->viewBuilder()->setVar()` is for creating a new instance of the views, therefore this does not solve the problem. As @markusramsak is trying to retrieve the active/current variables of a controller.

Example:
```php
$this->ExampleController= new ExampleController();

$old  = $this->InternalFinancings->viewVars['isTrue'];
$new  = $this->InternalFinancings->viewBuilder()->getVar('isTrue');
$build = $this->InternalFinancings->viewBuilder()->build();
$vars  = $this->InternalFinancings->viewBuilder()->getVars();

dd([$old, $new, $build, $vars]);
```

Will output:
<pre>[
	(int) 0 => true,
	(int) 1 => null,
	(int) 2 => [],
	(int) 3 => object(App\View\AppView)
]
</pre>

This is not correct.

**Comment by ADmad** [comment]
> $this->viewVars['viewVariable'] retrieves the active controller instance of variables.

Well yea, `$viewVars` is just a controller property (available through the `ViewVarsTrait`).

> Using $this->viewBuilder()->setVar() is for creating a new instance of the views, therefore this does not solve the problem. 

Even `Controller::$viewVars` are eventually used when creating new View instance. The only difference is through `View::setVar()` the view vars are encapsulated in the `ViewBuilder`.

`ViewBuilder` is meant to be a data transfer object which stores all options and variables to be used by the View. It was an oversight (or rather a restriction due to backwards compatibility concerns) to keep `Controller::$viewVars` property. We intend to fix that in 4.x which is why `Controller::$viewVars` is marked as deprecated to deter people from accessing the property directly.

In your code example is your issue with the fact that `$this->ExampleController->viewBuilder()->getVar('isTrue')` returns `null`?

That's because there is no call to `$this->ExampleController->viewBuilder()->setVar()` earlier.

We could probably solve that by making `Controller::set()` call `viewBuilder()->getVar()` internally. So that value set by `$controller->set()` can be retrieved by `$controller->viewBuilder()->get()`. I am pretty sure that was though of earlier, don't remember why it isn't done.

**Comment by markusramsak** [comment]
Ich migrated all my projects to use `$this->ExampleController->viewBuilder()->setVar()` instead of `$this->ExampleController->set()` without any exception and then all my problems have been solved. I think it is a good idea to make `$this->ExampleController->set()` call `$this->ExampleController->viewBuilder()->setVar()` internally. I searched in the CakePHP core to find any drawbacks for this and I haven't found any. I also migrated some bigger projects with more than 50000 lines of code without any problems so far. I have done the changes more than 8 months ago - no problems so far.
