### ISSUE TITLE
Exeption in json route no render json (cakephp 3.7)

### ISSUE THREAD

**Issue by ozee31** [cakephp/cakephp#12834]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1 : 1f6fd21ca27ffc88fa88506a400b94a809e29254
* Platform and Target: apache php 7.0.12

### What you did
In fresh cakephp 3.7.1 install, I create an API.

In my route.php
```php
Router::scope('/', function (RouteBuilder $routes) {
    $routes->setExtensions(['json']);
	//...
});
```

In AppController
```php
public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler', [
            'enableBeforeRedirect' => false,
        ]);
        $this->loadComponent('Flash');

        /*
         * Enable the following component for recommended CakePHP security settings.
         * see https://book.cakephp.org/3.0/en/controllers/components/security.html
         */
        //$this->loadComponent('Security');
    }
```

My TestController
```php
<?php
namespace App\Controller;

use Cake\Http\Exception\NotFoundException;

class TestController extends AppController
{
    public function success()
    {
        $this->set([
            'test' => true,
            '_serialize' => ['test']
        ]);
    }

    public function error()
    {
        throw new NotFoundException();
    }
}
```

A simple view for test
```
<script>
    fetch('/Test/error.json')
    fetch('/Test/success.json')
</script>
```

### What happened

* /Test/success.json
![success](https://user-images.githubusercontent.com/5025797/50347527-1e864680-0536-11e9-89a7-9a5a0bf473a5.png)

* /Test/error.json
![error](https://user-images.githubusercontent.com/5025797/50347663-9f454280-0536-11e9-8f75-83783c58a351.png)

### What you expected to happen

I would like, as with cakephp 3.6 for error.json

![error2](https://user-images.githubusercontent.com/5025797/50347733-f5b28100-0536-11e9-91c5-3412eb20eb67.png)

**Comment by markstory** [comment]
Looks like this issue was caused by changes in #11978. The `ExceptionRenderer` is now passed the request instead of it being retrieved from `Router` via `getRequest(true)` as it was in 3.6.

Because your request is using a `.json` extension the request that ends up in `ExceptionRenderer` doesn't have routing applied and the parsed extension is not present. The same problem does not occur if a request is sent with `Accept: application/json` in the headers. I've got an idea on how to fix this and should have a pull request up soon.
