### ISSUE TITLE
TimeHelper adds an extra year when outputting date on New Year's Eve

### ISSUE THREAD

**Issue by PhantomWatson** [cakephp/cakephp#12872]
This is a:

* [x] bug

* CakePHP Version: 3.7.2

### What you did
```
$problemDate = new \Cake\I18n\FrozenTime('2018-12-31T02:39:55+00:00');
$format = 'MMMM d, YYYY';
$timezone = new DateTimeZone('-0400');
for ($n = -2; $n <= 2; $n++) {
    $date = $problemDate->addDay($n);
    $formatted = $this->Time->format($date, $format, null, $timezone);
    echo $date->i18nFormat() . ' is converted to ' . $formatted . '<br />';
}
```

### What happened
```
12/29/18, 2:39 AM is converted to December 28, 2018 <-- Subtracting one day is expected
12/30/18, 2:39 AM is converted to December 29, 2018
12/31/18, 2:39 AM is converted to December 30, 2019 <-- Adding one year is not
1/1/19, 2:39 AM is converted to December 31, 2019
1/2/19, 2:39 AM is converted to January 1, 2019
```

### What you expected to happen
I expected December **2018** dates to be output, not December 2019.

**Comment by ndm2** [comment]
That's the expected behavior, as `YYYY` doesn't refer to the regular year, but to the ISO week-numbering year, which will give you 2019 as the week that `12/31/18` points to, spans into the next year, or more specifically, because that week includes January the 1st that is still a weekday  (Monday to Friday), thus it's being treated as the first week of 2019 according to the ISO week rules.

Long story short, use `yyyy` instead, see also
**http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details**.

**Comment by PhantomWatson** [comment]
Oh wow, this has been an enlightening day. Thanks!

**Comment by ndm2** [comment]
You're welcome :)
