### ISSUE TITLE
Return what is actually stored cake 3 and 4

### ISSUE THREAD

**Issue by jimgwhit** [cakephp/cakephp#13170]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: YOUR WEB-SERVER, DATABASE AND OTHER RELEVANT INFO AND HOW THE REQUEST IS BEING MADE, HERE.

### What you did
To Cakephp team:

First see:  https://discourse.cakephp.org/t/cake-php-3-7-date/6001/6

I just tested the same query in laravel 5.8 and cakephp 4:

### cakephp 4

```
    public function itest()
    {
        $this->autoRender = false;
        $petid = 9;
        $pet = TableRegistry::getTableLocator()->get('Pets');
            $data = $pet
                    ->find()
                    ->where(['petid' => $petid])
                    ->first();
            $testdate = $data->odate;
            $json = json_encode($testdate);
            echo $json;
            exit();
    }

}

```

### Returns:
```ruby
"1998-09-02T00:00:00+00:00"
```

### Laravel 5.8

```
    public function itest()
    {
        $petid = 9;
        $pet = Pet::find($petid);
        $testdate = $pet->odate;
        $json = json_encode($testdate);
        echo $json;
        exit();
    }
```

### returns
```ruby
"1998-09-02"
```

Why is the orm and query builder manipulated to return what you wanted it to return instead of a value that is stored.

I am not trying to cut anyone down, but I just don't understand the core team manipulating users stored data.

In this case 1998-09-02 is what's actually stored.

And I am not new to this stuff, I am currently number 14 on laravels top 50, I have used it since ver 4.2, and have used cakephp for some apps.

Why do you determine what's returned instead of just letting mysql and pdo do their job.

### What you expected to happen
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

Cakephp let pdo and mysql do their job, and not return a format you decide on.

How did you decide on that anyway?

**Comment by josegonzalez** [comment]
As a convenience feature, the ORM maps column types to specific classes. That is done automatically, though if the user wishes, they may specify a specific type for a given column.

In this case, we appear to be mapping the `datetime` column to a [DateTimeType](https://github.com/cakephp/cakephp/blob/master/src/Database/Type/DateTimeType.php) instance.

We're super-unlikely to change the output here - the serialization has been the same for our ORM for a very long time, and going backwards to the raw string type would essentially be what we did in pre-3.x era. If you wish to have a different serialization, you can:

- [Map a custom type](https://book.cakephp.org/3.0/en/orm/database-basics.html#data-types) to `datetime` columns in your app schema. I think you can subclass the Date(Time) ones and override the `jsonSerialize` method to do what you want.
- [Use the database layer directly](https://book.cakephp.org/3.0/en/orm/database-basics.html#executing-queries).
- Modify the query results in your after-find using [MapReduce](https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#map-reduce) statements.
- Use another ORM. I know of several folks using Doctrine in their CakePHP apps. You are free to use Eloquent in your apps too.
- Use PDO instead of our ORM. PDO is a lightweight wrapper around database connections and queries, while our ORM is exactly that - an Object Relational Mapper. It's heavyweight, and adds a lot more functionality to the query model that you cannot easily do with a simple string.

Hope this makes sense.

**Comment by jimgwhit** [comment]
> while our ORM is exactly that - an Object Relational Mapper. It's heavyweight, and adds a lot more functionality to the query model that you cannot easily do with a simple string.

You do realize that cakes orm is just active record right.  And any orm code is converted to normal sql and pdo at runtime.

Hibernate and doctrine are orm's.

> It's heavyweight

No it's just active record shortcuts, like in asp.net.  Linq to sql is also converted to normal sql at runtime.

Are you on the core team?

You should understand active record a little better if answering issues.  Honest I am not trying to offend you.  I know better because I have been doing this stuff since the late 1980's, but a new to cake person might believe the orm is heavyweight.

But I see as usual, no changes to returning wrong data will even be looked at.

Yet laravel, yi2, doctrine, jdbc, asp.net with linq, native sql server, mysql, heck the rest of the World returns correct data.

So cakephp orm and query builder is the only ones in the World that will not return what is actually stored.

Thanks for the rely.

**Comment by ADmad** [comment]
Casting a `I18n\Date` or `I18n\FrozenDate` instance to string gives only the date part. So it's reasonable for one to expect similar behavior when json encoding the instance too.

@jimgwhit To achieve what you want all you is easy enough. Just set the json encoding format for `Date` and `FrozenDate` classes by adding the following statements to your bootstrap file:

 ```
\Cake\I18n\Date::setJsonEncodeFormat('yyyy-MM-dd')`;
\Cake\I18n\FrozenDate::setJsonEncodeFormat('yyyy-MM-dd')`;
```

**Comment by ADmad** [comment]
Returning only the date part by default when JSON encoding the date instances is something I would like to happen in CakePHP 4. Existing behavior is not intuitive. Hence opening the ticket to get opinions from others.

**Comment by dereuromark** [comment]
I agree that a date could be formatted back to exactly this by default as all other info is misleading (from the outside it looks like gained precision = datetime). It really only has info about the date part which should then also be the result on echo/json_encode() here.

**Comment by dereuromark** [comment]
Fixed in linked PR. Thank you for bringing this to our attention.
