### ISSUE TITLE
Subdomains with Middleware

### ISSUE THREAD

**Issue by assisjeferson** [cakephp/cakephp#13430]
I had implemented prefix subdomains using https://github.com/cakephp/cakephp/issues/7140#issuecomment-127076842 with CakePHP 3.5 version.

Today I upgrade to version 3.8, when I run the application it's work perfectly, but when I run tests dont reconize the route

In my test case:
```php
$this->configRequest([
    'headers' => [
        'HOST' => 'api.domain'
        ]
    ]);
```

Result 
```php
1) App\Test\TestCase\Controller\Api\EventsControllerTest::testIndex
Possibly related to Cake\Routing\Exception\MissingControllerException: "Controller class Events could not be found."
```

I try fix that passing prefix to request in RoutingMiddleware
```php
$host = $request->getUri()->getHost();

list($prefix) = DashedRoute::getPrefixAndHost($host);

if (!empty($prefix)) {
    $params['prefix'] = $prefix;
}
```

Work well when I test a route without param, but when I need test a route with a `param` it dont work, `Route::parseRequest()` get other `_matchRoute`

Result running application:
```php
Cake\Http\ServerRequest Object
(
    [params:protected] => Array
        (
            [id] => 3
            [pass] => Array
                (
                    [0] => 3
                )

            [controller] => Events
            [action] => view
            [_method] => GET
            [prefix] => api
            [plugin] => 
            [_matchedRoute] => /events/:id
            [_ext] => 
        )
```

Result running tests:
```php
Cake\Http\ServerRequest Object
(
    [params:protected] => Array
        (
            [controller] => Events
            [action] => view
            [pass] => Array
                (
                    [0] => 1
                )

            [plugin] =>
            [_matchedRoute] => /:controller/:action/*
            [_ext] =>
            [prefix] => api
        )
```
How I can fix that?

**Comment by markstory** [comment]
Is `request->host()` correct in your route classes/middleware?

**Comment by assisjeferson** [comment]
Yeah, I configured in local the domain api.domain

In `routes.php`

```php
Router::scope('/', ['prefix' => 'api'], function($routes) {
....
});
```

Only if I pass the absolute route this error occurs

```php
public function testDetail() {
	$result = $this->get('/events/1');
	...
}
```

When I try like that, the test unit work well
```php
public function testDetail() {
        $result = $this->get([
            'controller' =>'Events',
            'action' => 'index',
            1
            ]);
```

But another mistake happens when I try get nested route
```php
// Teste case request
$result = $this->get([
    'controller' =>'Tickets',
    'action' => 'index',
    1
    ]);

// Route 
$routes->resources('Events', [
        'only' => [ 'index', 'view' ],
    ],
    function ($routes) {
        $routes->resources('Tickets', [
            'only' => [ 'index' ]
            ]);
    });
```

In this case I can't get `param`

**Comment by markstory** [comment]
@assisjeferson How would I go about reproducing the problem you have? Would you be able to make a gist or sample repository that lets me see the problem you're having? Right now I only have small bits of what is going on and I don't think I'd be able to reproduce the problem.

**Comment by assisjeferson** [comment]
Sure, as follows the link required: https://gist.github.com/assisjeferson/c892cb3ca3c59d9360671d1c6cc7c4b9

**Comment by markstory** [comment]
Thank you. I'll try reproducing in the next few days.

**Comment by markstory** [comment]
Thanks for providing your gist. I wired it into a sample application I have, and found a few problems in the code you've provided. Your `PrefixedRouteTrait` contains some suspicious code:

```php
    public static function getPrefixAndHost($host = []) {
        if(is_array($host)) {
            if (empty($context['_host'])) {
                $request = Router::getRequest(true) ?: ServerRequestFactory::fromGlobals();
                $host = $request->host();
            } else {
                $host = $context['_host'];
            }
        }
```

In this block there is no `$context` variable so the code will continually fall back to a new request generated from globals as you are also using `Router::setRequestContext()` which doesn't interact with `Router::getRequest()`. Instead you should use `Router::pushRequest($request)`. Looking at the host calculation I saw that the host was continually incorrect.

I encountered the following notice errors in your code:

```
Warning Error: explode() expects parameter 2 to be string, array given in [/Users/markstory/Sites/cakephp-app/src/Routing/PrefixedRouteTrait.php, line 46]

Notice Error: Array to string conversion in [/Users/markstory/Sites/cakephp-app/src/Routing/PrefixedRouteTrait.php, line 88]
```

These seem relevant and probably something to fix.

You should ensure that you are passing the application into your `SubdomainMiddleware` constructor as it subclasses `RoutingMiddleware` and that class now requires an application instance.

You are using the `__construct` method of `TestCase` instead you should implement `setUp()` to configure request headers and ensure you're calling `parent::setUp()`.

Given the number of errors in the provided code I'm going to assume the issue is in your application code/how you're using CakePHP.
