### ISSUE TITLE
belongsTo association with strategy=select

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/cakephp#13467]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.

### What you did
In table: defined belongsTo association with strategy=select
In controller: feetched results without assoc foreign key in select expression:
`$this->Table->find()->select(['id', 'name'])->contain(['Assoc'])->first();`

### What happened
I got results from primary table, but property with assoc entity is null.

### What you expected to happen
`RuntimeException` is thrown with message `'Could not find primary key value for source entity'`.

It works only when I specify assoc foreign key in select expression or skip select:
`$this->Table->find()->select(['id', 'name', 'assoc_id'])->contain(['Assoc'])->first();`
`$this->Table->find()->contain(['Assoc'])->first();`

**Comment by ADmad** [comment]
This is expected. You need to either explicitly select the foreign key field too or enable auto fields for the query using `Query::enableAutoFields()`.

**Comment by andrii-pukhalevych** [comment]
`Query::enableAutoFields()` on main query enabled all fields, not only 'assoc_id'.
enableAutoFields in query builder on contain does not help:

```
$this->Table->find()->select(['id', 'name'])
	->contain(['Assoc'=>function (Query $query) { 
		return $query->enableAutoFields(); 
	}])
	->first();
```

**Comment by andrii-pukhalevych** [comment]
@ADmad why do not generate exception to prevent errors, like in `BelongsToMany::replaceLinks()` ?

**Comment by markstory** [comment]
I got around to looking at this tonight and emitting an error is not simple. The reasoning is that we cannot easily tell the difference between no results and an invalid query.

When the query is built, we cannot check for selected columns when the contain is declared as this valid query:

```php
$query->contain('Authors')
 ->select(['id', 'title', 'author_id'])
```

would be considered invalid when contain() is called. Then during query execution we cannot easily infer whether fields were not selected, or the results just 'missed'. For example if the source query results in 0 rows, or the association keys are nullable raising an exception would be incorrect. Because the foreign key is not part of the select the ORM doesn't attempt to load the association as it has no foreign key data.

I'll take another look into whether or not we can append the required foreign key fields when the contain is defined.

**Comment by othercorey** [comment]
> Then during query execution we cannot easily infer whether fields were not selected, or the results just 'missed'. For example if the source query results in 0 rows, or the association keys are nullable raising an exception would be incorrect. Because the foreign key is not part of the select the ORM doesn't attempt to load the association as it has no foreign key data.

Are you saying the PDO excludes nullable foreign key fields?  I don't think 0 rows represents an invalid query unless you can select 0 fields, which you shouldn't be able to.  If there are no rows, then the conditions are excluding results which would exclude the association anyway.

Validating on declaration would be impossible and writing something to validate before execution would be a large expression tree traversal.  I think validating results is the only possible solution.

**Comment by markstory** [comment]
> Are you saying the PDO excludes nullable foreign key fields? 

Not in PDO, but when we are collecting foreign key values to prepare the conditions for the association query. Having no foreign key values is a valid state as all selected rows could have nulls in the foreign key.

I agree that validating during query building is not a tractable solution. Validating in result generation is also difficult because of billable associations. I will explore how adding foreign keys would work. This wouldn't prevent fields being restricted after the contain() call unfortunately, but could help mitigate how frequently this comes up.

**Comment by andrii-pukhalevych** [comment]
But foreign key is not null. It is not present in primary records if it was not specified in select clause.
So checking using array_key_exists after fetching primary rows should help here.

**Comment by markstory** [comment]
@andrii-pukhalevych Yes, your foreign key is not null, but belongsTo associations *can be* null which is the complicatation I was referencing earlier.

**Comment by markstory** [comment]
I found a way to check for missing keys when building the external association loaders. It runs some risk of breaking application code, but the queries it will fail on weren't working anyways.
