### ISSUE TITLE
4.x - mail() expects parameter 5 to be string, null given

### ISSUE THREAD

**Issue by karmicdice** [cakephp/cakephp#13548]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0-beta.
* Platform and Target: Ubuntu 18.04, PHP7.3, Apache2.

### What you did
```
            $data = $this->request->getData();
            $email = new \Cake\Mailer\Email();
            $email->setTo('test@karmicdice.com', 'Karmicdice');
            $email->setSubject('Test 4x');
            $email->setEmailFormat('html');
            $email->setProfile(['template' => 'testtemplate']);
            $email->setSender('no-reply@karmicdice.com', 'KD Dev');
            $email->setViewVars($data);
            $email->send('enquiry');
```

In testtemplate.php

```
<p>Name: <?= $name ?></p>
<p>Email: <?= $email ?></p>
<p>Message: <?= $message ?></p>
```

### What happened
`mail() expects parameter 5 to be string, null given`

![Error in mail function]
(https://i.imgur.com/zDmLGrp.png)

### What you expected to happen
Send email!

**Comment by karmicdice** [comment]
```
'EmailTransport' => [
        'default' => [
            'className' => Smtp::class,
            /*
             * The following keys are used in SMTP transports:
             */
            'host' => 'ssl://karmicdice.com',
            'port' => 465,
            'timeout' => 90,
            'username' => 'no-reply@karmicdice.com',
            'password' => 'Naaa!NotFallingForThis',
            'client' => null,
            // 'tls' => null,
            'url' => env('EMAIL_TRANSPORT_DEFAULT_URL', null),
        ],
    ],
```

**Comment by jimbo2150** [comment]
Bit of a confusing message to be sure - maybe add something to the effect of `if( is_string($params) === false && $this->getConfig('username', null) !== null )` with a "did you mean to use the SMTP transport" message?

Additionally - in the `send` method, I see a number of `$this->_config` being used (also appears repeatedly in SmtpTransport), should those not be `$this->getConfig(...)` since `AbstractTransport` uses `InstanceConfigTrait`?
