### ISSUE TITLE
4x. Bake

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/cakephp#13757]
This is a (multiple allowed):

* [x] bug

Please consider my steps:
(windows 10, chrome, mysql, all with the latest update)

1. Download cake4-beta4
2. unzip, composer update, config / app (db, user, pass) etc
3. cake server
ok (+/-)

4. bin \ cake bake all --everything (wow… very fast !!)
5. chrome, localhost: 8765 / Pessoas
…
image error error3.png.

Such a table does not exist. It really does not exist. Refers to only one field (error3-1.png).
And he has done this several times, referring to several 'tables' that don't really exist (no indexes, no foreign keys, nothing).
It should leave the field as it is, without referring to any tables.
Probably I must have forgotten something about cakephp's right way of doing things, I don't know.

![erro3](https://user-images.githubusercontent.com/50879411/66875447-b735f900-ef84-11e9-9ee6-71b18ed5990f.png)
![erro3-1](https://user-images.githubusercontent.com/50879411/66875448-b735f900-ef84-11e9-99a9-c521c910b056.png)

**Comment by markstory** [comment]
The field ends in `_id` which bake treats as a conventions based foreign key field. While bake does use foreign keys to find referenced tables, it doesn't use them to find foreign key fields. You will need to update your models after they are generated to remove generated associations that don't exist.

**Comment by dereuromark** [comment]
What if we only baked the ones where the tables actually exist?

**Comment by LordSimal** [comment]
As markstory already described the problem here is, that CakePHP recognizes your field "responsavel_menor_id" as a foreign key for a 1:N (or N:M) connection between your current table and a table called "responsavel_menor".

Therefore cake bake automatically generates model, controller and template in that matter, that it ready out the data from the connected table, which in your example (probably) doesn't exists.

The SQL for your Database-Structure would help us here as well to give you better support.

Otherwise see CakePHP Naming Conventions here: https://book.cakephp.org/3.0/en/intro/conventions.html

**Comment by LordSimal** [comment]
@dereuromark I would rather add an option to the cake command to show the automatically detected connections in the current database structure and therefore making debugging these easier.

Something like:
Book has one Publisher
Publisher has many Stores (and therefore Stores belongs to Publisher)
Book has and belongs to many Authors

In this step we can probably check for automatically generated connections, which are probably not satisfied and notify the user about that.

**Comment by markstory** [comment]
> What if we only baked the ones where the tables actually exist?

What is those associations are in another connection?

**Comment by LuizMarin** [comment]
thanks you for explanation
