### ISSUE TITLE
Multiple orWhere w/ notMatching Results in Unexpected Query

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/cakephp#13797]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1
* Platform and Target: LAMP

### What you did
I am attempting the following code

    $menuNotifications = TableRegistry::get('AdminLTE.AdminLTEMenuNotifications');
    $linkNotifications = $menuNotifications->find('all', ['contain' => 'AdminLTEMenuNotificationLogs']);
    $linkNotifications->select(['total' => $linkNotifications->func()->sum('notification_count')])
            ->where(['destination' => 'User', 'AdminLTEMenuNotifications.user_id' => $user_id, 'menu_title' => $menuItem['link'], 'menu_group' => $menuItem['link']])
            ->orWhere(['destination' => 'Global', 'menu_title' => $menuItem['link'], 'menu_group' => $menuItem['link']])
            ->orWhere(['destination' => 'Role', 'role_id' => $role, 'menu_title' => $menuItem['link'], 'menu_group' => $menuItem['link']]);
    $linkNotifications->notMatching('AdminLTEMenuNotificationLogs', function (\Cake\ORM\Query $query) use($user_id) {
            return $query->where(['AdminLTEMenuNotificationLogs.user_id' => $user_id]);
        });
    die(debug($linkNotifications));

### What happened
     SELECT (SUM(notification_count)) AS `total` FROM admin_l_t_e_menu_notifications AdminLTEMenuNotifications LEFT JOIN admin_l_t_e_menu_notification_logs AdminLTEMenuNotificationLogs ON (AdminLTEMenuNotificationLogs.user_id = :c0 AND AdminLTEMenuNotifications.id = (AdminLTEMenuNotificationLogs.admin_l_t_e_menu_notification_id)) WHERE (((destination = :c1 AND AdminLTEMenuNotifications.user_id = :c2 AND menu_title = :c3 AND menu_group = :c4) OR (destination = :c5 AND menu_title = :c6 AND menu_group = :c7) OR destination = :c8 OR role_id = :c9 OR menu_title = :c10 OR menu_group = :c11) AND (AdminLTEMenuNotificationLogs.id) IS NULL)

### What you expected to happen
Note the following snippet from the above query...

    OR destination = :c8 OR role_id = :c9 OR menu_title = :c10 OR menu_group = :c11

I would expect that to be like the first orWhere statement, which would make the above snippet look like

    OR (destination = :c8 AND role_id = :c9 AND menu_title = :c10 AND menu_group = :c11)

I am really sorry if this is just something I am doing wrong, but I don't think it is, the first orWhere statement in my code comes out as I would expect in the query, but the second orWhere statement does not... Any ideas?

**Comment by garas** [comment]
`Query::orWhere()` was deprecated because it creates hard to predict SQL. Use `Query::where()` instead as it has more predictable and easier to understand behavior.

In your case, it could be 
```
->where([
     'OR' => [
          ['destination' => 'User', 'AdminLTEMenuNotifications.user_id' => $user_id],
          ['destination' => 'Global'],
          ['destination' => 'Role', 'role_id' => $role],
     ],
     // Common conditions
     'menu_title' => $menuItem['link'],
     'menu_group' => $menuItem['link'],
]);
```

Also read https://book.cakephp.org/3.0/en/orm/query-builder.html#advanced-conditions for more options

--- 

This is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the CakePHP framework. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:

* [The CakePHP Manual](https://book.cakephp.org)
* [The CakePHP online API](https://api.cakephp.org)
* [CakePHP Official Forum](https://discourse.cakephp.org)
* [Stackoverflow](https://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](https://cakesf.herokuapp.com/) or [#cakephp](https://webchat.freenode.net/?channels=#cakephp) on irc.freenode.net
