### ISSUE TITLE
Add Text::contains() method to check if particular word is exists in the given string

### ISSUE THREAD

**Issue by ishanvyas22** [cakephp/cakephp#13905]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Provide convenient method `contains()` in `\Cake\Utility\Text` class know if particular word, character exists in provided string. It is useful for most use cases when you want to just check if something is exists or not.

I'd happy to submit a pull requests if core teams approves this.

Thanks.

**Comment by markstory** [comment]
What would this do that strpos() doesn't?

**Comment by AdrienLZ** [comment]
@markstory 
```php
$haystack = "CakePHP"
$needle = "Cak"

echo strpos('CakePHP', 'Cak') // Return 0 (so "false"..)
```

I guess ..

**Comment by jimbo2150** [comment]
Depends on what kind of implementation you are looking for. `strpos` matches any string within another string, but if you are looking for a specific word (not just a string of characters) within another string, that implementation is different.

For example, looking for "crackers" in a string will match within "... eating some crackers is...", but will also match within "...set off firecrackers at night..." since "firecrackers" contains the string "crackers" even though you may not have intended it to match.

However,

```php
$word = 'crackers';
$subject = '...set off firecrackers at night...';
$matches = preg_match('\b' . preg_quote($word) . '\b', $subject) === 1;
```

would not match since "crackers" with a leading and ending word boundary is not found, but
 

```php
$word = 'crackers';
$subject = '... eating some crackers is...';
$matches = preg_match('\b' . preg_quote($word) . '\b', $subject) === 1;
```

would match since the string "crackers" does exist with a leading and ending word boundary.

**Comment by markstory** [comment]
@jimbo2150 That's a good point is the intent of the proposed method to find words or partial string matches? `strpos` has a goofy return value, but it is a common part of PHP that I'm not sure we *should* provide a wrapper for. Word detection isn't as easily achieved with basic PHP functions.

**Comment by ishanvyas22** [comment]
> What would this do that strpos() doesn't?

There are multiple benefits to this function instead of strpos():

- strpos() returns non-boolean values, while with this function we can return strict boolean values only
- Readability is main, `Text::contains('world', 'Hello world')` is nice to look at than `strpos('world', 'Hello world')` and in case of condition it will be `if (strpos('world', 'Hello world') !== false)` which is much more difficult to understand to the devs 

- We can also add third option to give user ability to check case-insensitive check using stripos()

**Comment by ishanvyas22** [comment]
Also @jimbo2150 has good point, but for exact word checking, we can move this to another function. But for now it will be only for the particular string instead of exact word.

**Comment by othercorey** [comment]
I agree with @markstory that it feels weird to have a function that literally only calls the equivalent php function. All of the other text utility functions perform some sort of processing.

I think do better with a package specifically designed for string utilities like https://github.com/danielstjules/Stringy.  This has a `containsAny` function.

**Comment by markstory** [comment]
To clarify I am not against adding sugar methods like this, I just wanted to better understand what the intent was behind the proposed method.

**Comment by ADmad** [comment]
I too am not in favour of adding wrapper methods for `strpos()/stripos()`.

**Comment by othercorey** [comment]
> To clarify I am not against adding sugar methods like this, I just wanted to better understand what the intent was behind the proposed method.

If we add it, I think mimicking `containsAny()` would be more useful.

**Comment by ndm2** [comment]
```php
function low($str) {
    return strtolower($str);
}
```

never forget...

**Comment by ishanvyas22** [comment]
> > To clarify I am not against adding sugar methods like this, I just wanted to better understand what the intent was behind the proposed method.
> 
> If we add it, I think mimicking `containsAny()` would be more useful.

Yes @othercorey , we can have `string|array` into second param to check accordingly.

**Comment by othercorey** [comment]
Is there a reason you can't use a string helper library for something like this?

**Comment by ishanvyas22** [comment]
Yes, because I don't want to install any third party package every time I want to use these types of basic functions. I prefer that framework would provide such basic helper functions to directly use it into the app.

Also it saves me lot of time of searching third party libs just for the development/readability convenience. I would be ensured that it would have been well tested, would not be abandoned.

If Text class is not responsible for this we should add new dedicated class for this type of functions. It's up to you guys.

**Comment by othercorey** [comment]
I am sure others have a different opinion, but I don't see the benefit of adding one random helper.

The nice thing about a string/text helper library is it provides most of what you would need.  So, that means less searching and fewer ticket/requests for adding them.  CakePHP would have to add a suite of functions.

There are some very popular libraries out there.  I'm not sure how avoiding them is beneficial.  Having a never abandoned package is a hard requirement.  Even cakephp will drop support for versions and php releases.

**Comment by jimbo2150** [comment]
I agree with @othercorey. The framework is for writing apps rapidly and not providing for every single case. The utility libraries are meant to provide for common tasks that are not very trivial to use when using the core PHP.

For instance, Cake provides the HTTP client since requests are often made by apps but is very simple and is really just a cURL wrapper. I often pull in Guzzle and use the more advanced features that cURL offers and it will fall back to other methods - like PHP streams - in the event the the library is not present.

When it comes to finding a string inside another, `strpos`, `stripos`, and the other varieties are very easy to use and providing a wrapper would do nothing more than make it more readable (I do agree with @ishanvyas22 on that point). However it is also trivial to add your own utility class and load it into your app:

```php
namespace customApp\Utility;

use Cake\Utility\Text as CakeTextUtility;

class Text extends CakeTextUtility {

    public static function contains($haystack, $needle, $caseInsensitive = false) {
        return ($caseInsentive ?
            stripos($haystack, $needle) :
            strpos($haystack, $needle)
        ) !== false;
    }

}
```

then add it to your composer autoload and in your app:

```php

use customApp\Utility\Text;

class someController {

    public function someMethod() {
        // $textToTest defined somewhere...
        if( Text::contains( $textToTest, 'eureka' ) ) {
            die("I've found it!");
        }
    }
    
}

```

If you want to do something more advanced (like checking for words instead of simple string matches that I mentioned above) you could include a third-party text utility library and use it in your code directly or add to/modify your wrapper utility to simplify its use for your own needs.

**Comment by ADmad** [comment]
I agree with @othercorey and @jimbo2150 :slightly_smiling_face:.

P. S. @jimbo2150 You have a typo in your GH profile, it says "Web Deceloper" instead of "Web Developer" :slightly_smiling_face:.

**Comment by othercorey** [comment]
Doesn't look like this has support.
