### ISSUE TITLE
Missing move() method in File utilities

### ISSUE THREAD

**Issue by ishanvyas22** [cakephp/cakephp#14042]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Add move() method in File.php to move a particular file from one location to another. Same like Folder::move().

**Comment by markstory** [comment]
The `File` class is deprecated so we aren't likely to add new features to it. Instead you could use `rename()`

**Comment by ishanvyas22** [comment]
Any particular reason, why are we deprecating the folder and files classes?

**Comment by markstory** [comment]
The SplFileInfo and SplFileObject classes do most of what File does and the various file system iterators can replicate the most useful parts of Folder.

These classes were deprecated primarily because our perception was that they aren't used frequently and that the split classes cover most usage. The deprecation  can always be reversed if there are scenarios we have missed or missing features in the php provided interfaces.

**Comment by ADmad** [comment]
Also if one needs an abstraction layer for the file / folder operations then you can use `symfony/filesystem` and `symfony/folder` libs. These libs are already pulled into each app as indirect dependencies. Cake's plugin installer requires composer which in turn requires those libs.

**Comment by jimbo2150** [comment]
Recommend adding that info to the File & Folder deprecation block in the cookbook documentation so people know SPL or another library should be used as a replacement.

**Comment by ishanvyas22** [comment]
@ADmad: Thank you sharing these amazing packages.

I agree with @jimbo2150, alternatives should be given in the docs. Also when using any of these methods the deprecation warnings should be triggered.

**Comment by othercorey** [comment]
Docs fixed with https://github.com/cakephp/docs/pull/6338.
