### ISSUE TITLE
AUTH PLAIN only smtp servers cannot be used

### ISSUE THREAD

**Issue by wnhre2ur8cxx8** [cakephp/cakephp#14634]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.8.6
* Platform and Target: doesnt matter

### What you did
Use the framework to send mails via smtp on server that only allow AUTH PLAIN authentification

### What happened
`535 5.7.8 Error: authentication failed: Invalid authentication mechanism`

### What you expected to happen
A mail should have been sent.

Possible duplicate: #13708 

There are multiple providers out there that only allow AUTH PLAIN. It should be supported, there is no reason why this is limited.

Relevant code: https://api.cakephp.org/3.8/source-class-Cake.Mailer.Transport.SmtpTransport.html#252-279

**Comment by garas** [comment]
`AUTH LOGIN`  is described as [obsolete](https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml).

`AUTH PLAIN` provides same security level, is common and is likely available if server support `AUTH LOGIN`. It could use 1 step login procedure instead of 3 steps, which could save some time.

So I think it is worth switching to `AUTH PLAIN`.

Simple switch would be to always use `AUTH PLAIN`, but it is not completely BC safe.

Another option is first try `AUTH PLAIN`, then retry with `AUTH LOGIN` if error `504 5.7.4 Unrecognized Authentication Type` received.

More complex path would be parse `EHLO` response line `AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH` to select known mechanism.

**Comment by othercorey** [comment]
> So I think it is worth switching to `AUTH PLAIN`.
> 
> Simple switch would be to always use `AUTH PLAIN`, but it is not completely BC safe.

Seems like switching to AUTH PLAIN should be safe.

**Comment by ADmad** [comment]
Given that `AUTH LOGIN` is obsolete perhaps this should be fixed for 3.8, unless 3.9.0 is going to be our next release.

**Comment by othercorey** [comment]
We'll probably do a 3.8 release just for the docbloc fixes so might as well.

**Comment by wnhre2ur8cxx8** [comment]
I did a small hack to get it running for now. Take a look and/or take the code if you want: https://github.com/cakephp/cakephp/compare/master...wnhre2ur8cxx8:smtp_auth_plain

**Comment by ADmad** [comment]
> Another option is first try AUTH PLAIN, then retry with AUTH LOGIN if error 504 5.7.4 Unrecognized Authentication Type received.

Following diff implements above (diff is against `master`).

https://gist.github.com/ADmad/6727d9c4be5cb58a021ce808228f0e2b

**Comment by markstory** [comment]
@wnhre2ur8cxx8 Would you be able to test the patch that ADmad put together?

**Comment by wnhre2ur8cxx8** [comment]
> @wnhre2ur8cxx8 Would you be able to test the patch that ADmad put together?

Just did, the patch works as intended for my PLAIN only setup.
