### ISSUE TITLE
Problem with executed newlines in translator/gettext

### ISSUE THREAD

**Issue by Manuel1948** [cakephp/cakephp#14664]
* [x] bug
* CakePHP Version: 3.5.18
* Platform and Target: Windows Server 2012 R2 + XAMPP + PHP 7.0.24

### Problem
I have a gettext statement "__('bla')" inside a javascript block loaded by cakephp with newlines in it, when translating the phrase in another language, the newlines are executed by PHP and do not come back as \n, so in website the \n is a newline. The funny thing is I have a similar example and there is no problem, but I don't know exactly what is causing this issue.

Poedit:
![image](https://user-images.githubusercontent.com/17245982/83562056-3464ad00-a519-11ea-87d2-0b21f23aad5d.png)

PHP-Code:
![image](https://user-images.githubusercontent.com/17245982/83562928-ac7fa280-a51a-11ea-9912-b68af55a2980.png)

HTML-Code untranslated (expect this behaviour, but in German):
![image](https://user-images.githubusercontent.com/17245982/83561975-0bdcb300-a519-11ea-9ee2-60546926e184.png)

HTML-Code translated:
![image](https://user-images.githubusercontent.com/17245982/83562123-4d6d5e00-a519-11ea-83e7-a6d5754a3e84.png)

Sry if I waste your time and this is not a bug, but only a user mistake.

**Comment by markstory** [comment]
Sounds like you might have incorrectly encoded newlines in one of the strings.

**Comment by Manuel1948** [comment]
> Sounds like you might have incorrectly encoded newlines in one of the strings.

So where should I start to look, because it doesn't matter if I save the translation with \n or \\n because both will be converted to a newline, I dont get it, this must be a PHP problem...

**Comment by jimbo2150** [comment]
Because of how the files are filtered you need to have 4 escape characters in front of your special designation (`\\\\n`) instead of the two (`\\n`) you have within your translated string. Leave your translation function call alone `__('bla\n')` and just make the change to the translated text with poedit, or whichever translation file editor you are using. Then make sure to clear your cache `bin/cake cache clear_all` and it should produce the desired output.

**Comment by Manuel1948** [comment]
Thank you I will try it, the strange thing is, that I have plenty other
examples where I don't need 4 backslashes, but maybe it is the use of __()
inside a Html->scriptBlock?

Jim Robinson <notifications@github.com> schrieb am Mi., 3. Juni 2020, 01:26:

**Comment by jimbo2150** [comment]
It doesn't have to do with `scriptBlock`. You have to ovecome two filters. The first is with the MO translation file. It will escape the first two backslashes (`\\\\n` becomes `\\n`). Then Cake passes the result through `stripcslashes` which will recognize and convert `\n` to an actual line feed but is escaped since the parsed `\\n` contains the necessary escape character.

Not sure what other examples you have but would work that way in all cases where the `\n` needs to be preserved unless you are using a custom parser (the MO escape would still apply).

**Comment by Manuel1948** [comment]
> It doesn't have to do with `scriptBlock`. You have to ovecome two filters. The first is with the MO translation file. It will escape the first two backslashes (`\\\\n` becomes `\\n`). Then Cake passes the result through `stripcslashes` which will recognize and convert `\n` to an actual line feed but is escaped since the parsed `\\n` contains the necessary escape character.
> 
> Not sure what other examples you have but would work that way in all cases where the `\n` needs to be preserved unless you are using a custom parser (the MO escape would still apply).

Thank you for your help, the 4 backslashes are working. So only for understanding, why the other example is working without this need, I will post it here:

`<td class="actions">
                    <?php
                        //this string is also InspectionInstitutions\view.ctp
                        $confirm = __('Are you sure you want to delete this inspection institution ({0})?\n\n'
                                . '_____________________WARNING_____________________\n\n'
                                . 'This will also delete all related:\n'
                                . '{1} (+Details), {2}, {3}\n\n'
                                . 'and all relationships to:\n'
                                . '{4}, {5}\n'
                                . '___________________________________________________', $inspectionInstitution->name, __('Inspections'), __('Users'), __('Notes'), __('Inspection Types'), __('Farms'));
                        ?>
                        <?= $this->AclCheck->postLink(__('Delete'), ['action' => 'delete', $inspectionInstitution->id], ['escape' => false, 'confirm' => $confirm, 'class' => 'icon-delete'], true) ?>`

**Is it because I have escape => false that I don't need the 4 backslashes?**

**Comment by jimbo2150** [comment]
You are comparing apples to oranges and has to do with how the browsers process different constructs.

The `escape` option is only applied to the URL so it does not apply to this case since the translation is not being used within the URL.

The confirm message as part of the html link method is set as an HTML attribute, so if you pass in a value with the additional escapes it will appear with the escaped `\n` characters intact, but without the additional escapes in the translation the `\n`s are converted to an actual line returns and the browser will appropriately use the line return when used within HTML (though not as a BR tag) or JS.

Comparably, if you include an actual line return (not the `\n` special designation) within a `script` tag it is not seen the same thing. The `script` tag is a special construct where the browser stops being a browser and starts being a scripting language. It looks at the contents as strictly JavaScript. A line return is considered just that - a new line and likely part of a new command. If you tried to execute the part of the script that included actual line breaks within the string I suspect nothing would happen and there would likely be a syntax error registered in the browser's console (open up the browser's developer tools and look at the console).

**Comment by jimbo2150** [comment]
I meant that Cake is using `stripcslashes` internally on the translations as they are pulled out of the MO file.

When passed to a script block those `\n`s get automatically converted to line feeds but in the context of a script block that is a syntax error which is why you need the extra escapes. Alternatively you could leave your translations alone (no extra escapes) and pass it through a filter to replace the line feeds with `\n`s. Its really up to you how you want the conversion to happen.

Within the context of a HTML attribute it is just a line feed and the browser will handle it appropriately for use in JS so the additional escapes are not necessary.

**Comment by garas** [comment]
It is actually a bug in `MoParser`. It shouldn't use `stripcslashes` because it is binary format and special characters are stored as is.

There are different results when using translations from .po and .mo.

- `__("a\nb")` result is `"translated a\nb"` for both .po and .mo with new line in output.
- `__("a\\nb")` result is `"translated a\\nb"` for .po with `\` in output, but  `"translated-a\nb"` for .mo with new line in output.

**Comment by jimbo2150** [comment]
I did think it was a bit odd that it was being done on both files but didn't know if it was an actual bug since it could easily be worked around. Any specific reason there is no native `gettext` implementation? If not, I can go ahead and work on that tomorrow.

**Comment by garas** [comment]
Native `gettext` caches .mo file in memory and needs to restart webserver to load updated .mo file.

**Comment by markstory** [comment]
> Any specific reason there is no native gettext implementation? If not, I can go ahead and work on that tomorrow.

It is often not available as well.

**Comment by ADmad** [comment]
Sorry for prematurely closing the issue.
