### ISSUE TITLE
No error when save hasMany association if value is not array

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#14677]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0
* Platform and Target: Windows, Nginx, PHP 7.3, SQL Server

### What you did
`Article` hasMany `Comment`
Create `Article` entity with below data
```
$data = [
    'field' => 'value',
    'comments' => [
        'not_array_value',
    ],
];
```

### What happened
No error occurred

### What you expected to happen
Validation error on `comments` value

**Comment by markstory** [comment]
What validation error would you expect to see? The marshaller ignores association data that isn't shaped in a way that can be converted into entities.

**Comment by mcsknp** [comment]
It should be `'not_array_value' is invalid data for entity`.
If there are some reason to ignore this data, is there a way to add this rule to validation function?

When Article has at least 1 comment, I added `$validation->notEmptyArray('comments')` but it can't validate this case.

**Comment by markstory** [comment]
>  If there are some reasons to ignore this data, is there a way to add this rule to validation function?

Association properties that are not arrays are ignored because there is no way for the marshaller to convert that data into an entity. Ignoring this data has consistent behavior with with other 'extra' fields that are not assignable to the entities.

> When Article has at least 1 comment, I added $validation->notEmptyArray('comments') but it can't validate this case.

This rule won't work as the array is not empty. You would need to add a custom validation rule that checks that the array is not empty and contains a list of associative arrays that might be comments.

**Comment by mcsknp** [comment]
I found that below code will check content is array or not. And it's worked. Thank you!
```
$validator->addNestedMany('comments', new Validator());
```
