### ISSUE TITLE
Passing data as rule providers via `Validator::setProvider()`?

### ISSUE THREAD

**Issue by ndm2** [cakephp/cakephp#14703]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x / 4.x

---

In the [**Using Custom Validation Rules**](https://book.cakephp.org/3/en/core-libraries/validation.html#using-custom-validation-rules) ([**4.x**](https://book.cakephp.org/4/en/core-libraries/validation.html#using-custom-validation-rules)) section of the docs, there's an example that shows using an array as a validation rule provider to pass additional data into the validator.

According to the API docs, that's not supported, as [**`Validator::setProvider()`**](https://github.com/cakephp/cakephp/blob/3.8.12/src/Validation/Validator.php#L251) expects `object|string`, and there's also no tests for that use case.

Either the API docs need to be updated, or the Cookbook... or both, detailing that providers don't necessarily have to be _validation rule_ providers. Or maybe there should be an additional feature specifically ment for exposing arbitrary data to the validation rules.

**Comment by ADmad** [comment]
Based on following code one can't set a provider as an array. You would end up with `array{array, string}` on line 124 which is not a valid callable. So that e.g. needs to be removed.

https://github.com/cakephp/cakephp/blob/e6a6342dd238ea0eed656808262cfc02ef44a0f2/src/Validation/ValidationRule.php#L123-L125

**Comment by markstory** [comment]
> Either the API docs need to be updated, or the Cookbook... or both, detailing that providers don't necessarily have to be validation rule providers. Or maybe there should be an additional feature specifically meant for exposing arbitrary data to the validation rules.

This behavior was documented in cakephp/docs#3817 and because of that could be in use by a few applications. 

The code as it is documented *works* as long as you never try to actually use the provider as a rule provider. Given that this behavior is untested it is likely to break in the future. Would shimming bare arrays into ArrayObject instances be a path forward that folks would be open to?

**Comment by ADmad** [comment]
Jeez, that's an awful hack. I vote to get rid of it in 4.1.

**Comment by markstory** [comment]
We could add a deprecation when an object is not received. Userland code could start using the ArrayObject approach to keep similar behavior.

**Comment by ADmad** [comment]
Fixed in #15462
