### ISSUE TITLE
Paginate on Collection instead of ResultSet

### ISSUE THREAD

**Issue by Erwane** [cakephp/cakephp#14741]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4

### Context
My project require a very and slow complex query (500ms). With pagination and count: 1second.
My plan is : make a quick query and build a collection, formatted as i want, very fast with PHP, and paginate on that collection.

First, I suggest PaginatorComponent require a `Cake\Datasource\PaginatorInterface` instead of `Cake\Datasource\Paginator`.
Second, `Cake\Datasource\PaginatorInterface::paginate()` method will return a `Cake\Collection\CollectionInterface` instead of `Cake\Datasource\ResultSetInterface`.

In that way, I think we can make Pagination on Collection, by using `count` and `take` Collection methods
In controller, we can create Collection (from query and PHP) and pass it to `PaginatorComponent::paginate()`, it return a CollectionInterface with only X element and set `paginParams` for PaginationHelper.

**Comment by ADmad** [comment]
With CakePHP 4.1 (which will have a stable release soon) you can also try this [WindowFunctionPaginator](https://github.com/swiffer/FastPaginate), if you are using a database which support window functions.

**Comment by ADmad** [comment]
> Why it's impossible to "LowLevel" the requirement of PaginatorComponent to PaginatorInterface and CollectionInterface ?

`PaginatorComponent` is now just a convenience wrapper for the paginator and in order to maintain backwards compatible API it needs to use `Paginator` (which has additional methods) instead of `PaginatorInterface`. You can make your custom paginator class which implements `PaginatorInterface` and use it directly as shown [here](https://book.cakephp.org/4/en/views/cells.html#paginating-data-inside-a-cell).

As for `ResultSetInterface` vs `CollectionInterface`; since `PaginatorInterface::paginate:()` takes a `RepositoryInterface` or `QueryInterface` instance as argument returning a `ResultSetInterface` instance is the most logical thing.

Since you don't want to use `Paginator` class nor return `RepositoryInterface` there really is no benefit implementing the `PaginatorInterface` for your use case. Just implement your own class which creates the collection you want and generates the same params array as returned by `Paginator::getPagingParams()` and set it to `paging` request attribute.

**Comment by ADmad** [comment]
The framework tries to provide features required by a good majority of it's users, not try to solve every edge case usage such as yours.

**Comment by othercorey** [comment]
Closing as it looks like a custom solution is best. Users are free to submit PRs if they want to try and include something.
