### ISSUE TITLE
[4.1.0] Contain is case sensitive now

### ISSUE THREAD

**Issue by nook24** [cakephp/cakephp#14770]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0
* Platform and Target: PHP 7.2.24-0ubuntu0.18.04.6

### What you did
Since CakePHP 4.1 the `contain()` method is case sensitive which breaks all my contain calls.

Breaking commit: https://github.com/cakephp/cakephp/commit/ed139f76079d8be07ae32368559c38308200b818

### What happened
```php
        $this->belongsToMany('Hosttemplates', [
            'className'        => 'Hosttemplates',
            'foreignKey'       => 'hostgroup_id',
            'targetForeignKey' => 'hosttemplate_id',
            'joinTable'        => 'hosttemplates_to_hostgroups',
            'saveStrategy'     => 'replace'
        ]);

        $hostgroup = $this->find()
            ->contain([
                'hosttemplates'
            ])
            ->disableHydration()
            ->first();

        debug($hostgroup);

```

Throws
```
2020-07-06 17:20:42 Error: [InvalidArgumentException] The `hosttemplates` association is not defined on `Hostgroups`.
Valid associations are: Containers, Hosts, Hosttemplates, Mapitems, Maplines, Mapsummaryitems in /opt/openitc/frontend/vendor/cakephp/cakephp/src/ORM/Table.php on line 903
```

### What you expected to happen
Retrieving the data like with CakePHP 4.0.9.

Why are my contain()'s lower case you ask? This is because a find() also returns all association keys as lower key. The documentation is not clear on that. It's even not mentioned.

Due to the fact that this code was running since the 4.x-dev days - this is a breaking change in a dot release. Even if I was doing it wrong.

Full example: https://gist.github.com/nook24/1ca026b8dcada23fc36f558016a4f4ef

Please don't get me wrong. It's not about that I do not want to patch my code. Changing a behavior, even if it's wrong, should not be done from one release to another.

**Comment by dereuromark** [comment]
Refs documented part in migration guide https://book.cakephp.org/4/en/appendices/4-1-migration-guide.html#id3

**Comment by ADmad** [comment]
You are supposed to use the same casing in `contain()` call as the alias you have used when declaring your association. 

Since you have defined your association with alias `'Hosttemplates'` you are supposed to `contain(['Hosttemplates'])` not `contain(['hosttemplates'])`. While using mismatching aliases concentrically worked 4.0 it masked other issue as stated [https://github.com/cakephp/cakephp/issues/14554]. Hence the change was done in 4.1 to disallow mismatched aliases for contain and throw explicit error.

**Comment by nook24** [comment]
> Shouldnt this go at least into 4.next milestone?
> It can be quite bc breaking for people.

_Originally posted by @dereuromark in https://github.com/cakephp/cakephp/issues/14554#issuecomment-624518468_

Looks like it was a known fact that this change will break some code. I'm not saying that the change is bad or should be reverted.
It would have been good if an error message had added that lower case aliases in contain are deprecated and will be removed with 4.1.

My understanding before 4.1 was:
If the source code is going to lower case the alias anyway, then why capitalize in the first place.

This has change now, so there should be a big warning sign in the docs and it should also mentioned that the property names are completely independent from the alias defined in the association.

**Comment by ADmad** [comment]
> If the source code is going to lower case the alias anyway, then why capitalize in the first place...

You can't rely on internal behavior of code. Use of mismatched aliases is not documented anywhere.

**Comment by nook24** [comment]
I don't want to be meticulous, but it wasn't documented that it must be spelled the same way. ^^

**Comment by othercorey** [comment]
We can improve the migration documentation for this so it's more clear this affects `contain()` and table association creation.

**Comment by ADmad** [comment]
> I don't want to be meticulous, but it wasn't documented that it must be spelled the same way.

The documentation consistently shows use of same casing for association alias when [declaring associations](https://book.cakephp.org/4/en/orm/associations.html) and when using [contain()](https://book.cakephp.org/4/en/orm/retrieving-data-and-resultsets.html#eager-loading-associations).

You stumbled upon something which coincidentally worked and yielded correct results for your particular case (because of a less than ideal internal implementation) but there are other cases as shown in the diff in https://github.com/cakephp/cakephp/issues/14554 that using incorrect aliases causes problems and that's the reason we had to make the change.

Pull requests are already open to further clarify the correct usage, hence closing this issue.
