### ISSUE TITLE
Static method Router::extensions does not work.

### ISSUE THREAD

**Issue by menshutin** [cakephp/cakephp#15029]
This is a (multiple allowed):

* [x] bug

* CakePHP Version: 4.1.5
* Platform and Target: Apache, Linux.

Route extensions not being parsed when defined via `Router::extensions(['json', 'xml']);` in routes.php

At the same time defining route extensions inside routing scope via `$builder->setExtensions(['json', 'xml']);` works as expected.

**Comment by markstory** [comment]
@menshutin Could you provide a sample of routes that Router::extensions() is not working on? That method behaves as expected within our test suite and we'll need more context on when/what is not working to continue with this issue.

**Comment by ADmad** [comment]
The extensions set using `Router::extensions()` are passed to the `RouterBuilder` when it's constructed https://github.com/cakephp/cakephp/blob/d54bd7572581023c57ca751dd4780cb61c6e3e35/src/Routing/Router.php#L768-L771

After that setting extensions using `Router::extensions()` won't have any effect on the routes connection used the `RouterBuilder` instance.

So if one is using `Router::extensions()` in `routes.php` but using the `RouterBuilder` instance to connect routes `$routes->connect()` instead of the static method `Router::connect()` (which internally creates a new `RouterBuilder` instance, they experience the problem stated above.

**Comment by markstory** [comment]
Yes that's intentional behavior though. You either have to use the static methods or the builder ones. We didn't want to break backwards compatibility and the static/builder separation was a simple solution.

**Comment by menshutin** [comment]
After upgrade to 4.0 I also upgraded routes.php to the default one shipped with cake.It uses RouteBuilder to connect routes.

So, the right way to set extensions should be `$routes->setExtensions(['json', 'xml']);` istead `Router::extensions(['json', 'xml']);`.
I think the documentation should  be more direct on this, because now it it confusing.

**Comment by ADmad** [comment]
The manual have been updated https://github.com/cakephp/docs/pull/6812 and there's a PR open for the skeleton app too https://github.com/cakephp/app/pull/810.
