### ISSUE TITLE
Let SimpleCacheEngine allow integer "keys"

### ISSUE THREAD

**Issue by ethanpooley** [cakephp/cakephp#15218]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.9.4
* Platform and Target: n/a

### What you did
Model code like this fails after upgrade from 3.6.x:
```php
    public function afterSave($event, $entity, $options)
    {
        Cache::delete($entity->id, 'cars');
    }
```

### What happened
> Exception: A cache key must be a non-empty string. in [/home/vagrant/TransitScreen/vendor/cakephp/cakephp/src/Cache/SimpleCacheEngine.php, line 57]

### What you expected to happen
I see that PSR-16 requires string keys and that Cake's new PSR-16 shim, `SimpleCacheEngine`, does the same. On the surface that makes sense. However, the Cake `Cache` class mediates all cache keys. The first argument passed to a Cake `Cache` method is not itself a key, but only a portion of the key that will eventually be constructed and used. Can't we then allow it to be an integer? It seems to me that a common/ideal use of the `Cache` class is to name the cache configuration well and then use only the ID of each entity that will be going into it. These will commonly be integers, and having to explicitly cast them to strings every time the `Cache` class is used seems needless.

**Comment by ADmad** [comment]
> The first argument passed to a Cake Cache method is not itself a key, but only a portion of the key that will eventually be constructed and used.

That's an implementation detail of the cache engines. Public API should not rely on internal detail. On can easily have their own cache interface implementation which doesn't not modify the key before use.

The $key argument for all methods of `Cache` class are documented as string. It's just because of lack of strict typing in 3.x that you were able to get away with passing integers earlier. In 4.x the methods of `Cache` methods itself will throw type error.

So you should just type cast the value for $key argument if needed.

**Comment by ethanpooley** [comment]
@ADmad Understood. Thank you for the fast response!
