### ISSUE TITLE
Message::jsonSerialize() omits message body

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/cakephp#15290]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.3

### What you did
Tried to serialize and then unserialize fully composed email message.

### What happened
After unserialization the message misses the body.

### What you expected to happen
The unserialized message should keep the message body.

https://github.com/cakephp/cakephp/blob/master/src/Mailer/Message.php#L1852-L1856

Note that `$message`, `$textMessage` and `$htmlMessage` properties are missing here.

Is that intentional?

**Comment by markstory** [comment]
I suspect this is a relic of Message being split out from Mailer.

Have you considered regenerating the body after unserializing the message instead of storing the message contents in the serialized object? This would let you keep the serialized state small and not lose information. Any relative datetime information used in the message would be different between the serialized and unserialized states but that doesn't seem like a major problem to me.

**Comment by robertpustulka** [comment]
In 3.x the unserialized Email instance would keep the body intact.

I'm afraid I can't re-render the message body as the message is being unserialized in a queue handler.

 This issue came up after upgrading my old 3.x queue transport to 4.1

**Comment by ADmad** [comment]
`Email::jsonSerialize()` of `3.x` doesn't include the message properties either but it serializes the view builder which allows it to render the message later after unserialization.

In 4.x the view rendering is off loaded to `Mailer\Render` and the `Mailer` uses it to render the message and set the body for  `Message`. 

So I guess we can update `Message::jsonSerialize()` to include `$textMessage` and `$htmlMessage` too (which are set by `setBody()`).
