### ISSUE TITLE
FrozenDate construct with timezone return wrong date

### ISSUE THREAD

**Issue by mcsknp** [cakephp/cakephp#15418]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.3
* Platform and Target: MacOS, Nginx, PHP 7.4

### What you did
Create `FrozenDate` in `UTC` when default timezone is `Asia/Tokyo`
```
$date = new FrozenDate('2021/03/30', 'UTC');
```

### What happened
`$date` is `2021/03/30` in `Asia/Tokyo`

### What you expected to happen
`$date` is `2021/03/30` in `UTC`

**Comment by othercorey** [comment]
Please give us more detail of the issue.

**Comment by garas** [comment]
Chronos `Date::__construct` docs:

Date instances lack time components, however due to limitations in PHP's internal Datetime object the time will always be set to 00:00:00, and _the timezone will always be the server local time_. Normalizing the timezone allows for subtraction/addition to have deterministic results.

The only problem here is docs are not in sync, as `FrozenDate` docs say _UTC_, but parent Chronos `Date` docs say _server local time_.

https://github.com/cakephp/chronos/blob/2.1.1/src/Date.php#L84

https://github.com/cakephp/cakephp/blob/4.2.4/src/I18n/FrozenDate.php
