### ISSUE TITLE
PostgresSchemaDialect.php Please implement   if ($col === 'char' && $length === 36) => Uuid

### ISSUE THREAD

**Issue by jsm222** [cakephp/cakephp#15455]
The docs say that a character(36) will get auto filled with an uuid. This is not true for postgres at the moment.
Can that be changed?

**Comment by jsm222** [comment]
workaround convert char(36) to uuid type "manually"

**Comment by markstory** [comment]
>  Can that be changed?

You can write your own postgres driver/dialect that does that conversion. We no longer treat char(36) as uuid in postgres as postgres has a UUID type that is better suited for storing UUID values.

**Comment by CauanCabral** [comment]
Hi, could you link where docs said that? Tried here without success.

I found only [this one](https://book.cakephp.org/4/en/orm/database-basics.html#data-types):

> **uuid**
>    Maps to the UUID type if a database provides one, otherwise this will generate a CHAR(36) field.

Seems the opposite of what you want.

**Comment by jsm222** [comment]
Rather than using an auto-increment key as the primary key, you may also use char(36). CakePHP will then use a unique 36 character UUID (String::uuid) whenever you save a new record using the Model::save method 

But is guess it is outdated, sorry.. https://book.cakephp.org/2/en/getting-started/cakephp-conventions.html

**Comment by CauanCabral** [comment]
I got it.

On CakePHP 4, MysqlSchemaDialect still understand char(36) as a UUID, but Postgres has a proper column type for that.

If you really want that pattern (a char instead of a native uuid), you can override Postgres driver and PostgresSchemaDialect - I did it some days ago for [another purpuse](https://github.com/ionews/cakephp-pg-search/tree/main/src/Database).

**Comment by othercorey** [comment]
closing as the current behavior is as-designed.
