### ISSUE TITLE
Cache for Locales files

### ISSUE THREAD

**Issue by kicaj** [cakephp/cakephp#15463]
* CakePHP Version: 4.x

Any possible to generate/update cache just from .po files?

**Comment by markstory** [comment]
There isn't a command line tool for that yet. But it sounds like a useful addition.

**Comment by kicaj** [comment]
What do you think, it will be good to deploy cached translated files to production server without deploy content of Locales directory?

**Comment by markstory** [comment]
I think you would still want to deploy the po files. Having a command that would allow developers to warm caches would be helpful to prevent data races on building the message cache and prevent the handful of slow request that could happen with large message sets.

**Comment by hacheraw** [comment]
Sorry if this might be a little offtopic but it may be better to ask this here than to open an issue.


I've found that if I do (in `config/bootstrap.php`)

```php
Cache::setConfig(Configure::consume('Cache'));
```

before than

```php
ini_set('intl.default_locale', Configure::read('App.defaultLocale'));
```

I18n does use the system language instead of the one configured in `Configure::read('App.defaultLocale')`.

Is this an expected behavior?

If after doing that, I use `I18n::setLocale(Configure::read('App.defaultLocale'))` it works as expected.

**Comment by othercorey** [comment]
Please open an issue instead of posting here.
