### ISSUE TITLE
Bake produces duplicate validation rules

### ISSUE THREAD

**Issue by shahways** [cakephp/cakephp#15569]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.6
* Platform and Target: Apache / MySQL

### What you did
Baked a model for a users table with a unique index on the email column.

### What happened
A unique rule was added to both the UsersTable::validationDefault() and UsersTable::buildRules() methods.

### What you expected to happen
The unique validation is a part of the application rules, and therefore should only have been added to UsersTable::buildRules().

![Screenshot 2021-05-28 at 10 13 29](https://user-images.githubusercontent.com/4831009/120208872-47928180-c22e-11eb-8831-300a4f2473cb.png)

**Comment by dereuromark** [comment]
No, not really or necessarily.
The validation rule ensures that validation itself contains this check when sending the form.
So invalidating the form because of two fields and more happens at once, the user can enter the data and continue successfully.

If the domain rule would only be invoked, it is a user-unfriendly form as you get error 1, then error 2 after each other when submitting, making this less UXish.
Domain rules are basically often just on top to make sure that these constraints are still true even if the data has already been patched in (last gate of defence, and before any critical DB constraints cause a complete internal error).

**Comment by shahways** [comment]
> No, not really or necessarily.
> The validation rule ensures that validation itself contains this check when sending the form.
> So invalidating the form because of two fields and more happens at once, the user can enter the data and continue successfully.
> 
> If the domain rule would only be invoked, it is a user-unfriendly form as you get error 1, then error 2 after each other when submitting, making this less UXish.
> Domain rules are basically often just on top to make sure that these constraints are still true even if the data has already been patched in (last gate of defence, and before any critical DB constraints cause a complete internal error).
> 
> I personally don't use domain rules here, always only validation rules (for the reason above), so yeah, in my case I only use one of them, as well :) But my point is: The validation rule itself should be present no matter what, the other seems more like optional to me.

Thanks for your swift reply @dereuromark! I posted the issue here as [recommended by @ADmad](https://cakesf.slack.com/archives/C053DPNGT/p1622213757010500) following [my question on Slack](https://cakesf.slack.com/archives/C053DPNGT/p1622189623478800). 

As we are still quite new to 4.x, we're following the documentation, the core CakePHP codebase and Baked code rigorously as our guide in this new adventure. e were surprised to see that Bake added the unique rule both as a basic validation rule, as well as an application rule. At least, after reading more about the difference between both validation layers as [explained in the docs](https://book.cakephp.org/4/en/orm/validation.html#applying-application-rules).

I do agree with your explanation that the rule should always be checked, and it seems more consistent to put all the rules in the basic validation layer. But now my OCD is dissatisfied, as that would (apparently) leave a margin of error regarding data integrity, in case of bulk updates or concurrent data operations. Aaaargh, what should I do? ;-)

**Comment by dereuromark** [comment]
IMO then just keep both :)

**Comment by shahways** [comment]
Oh no, you've just awakened my other OCD that cares about performance :D 

Quite a challenge to balance this triangle : user experience vs. data integrity vs. performance. We perhaps will have to evaluate this on a case-per-case basis. Nonetheless, thanks for chiming in, much appreciated to hear how others approach this.

**Comment by dereuromark** [comment]
I can only speak about my case:
Having it in validation and then as last defense as DB constraint (usually never to be invoked), seems to suffice.
The domain rule doesn't serve any useful purpose - as for most of them (given the issues I mentioned above).

**Comment by dereuromark** [comment]
So given this, I would rather remove the domain rule here for bake and adjust documentation.

The docs should make a bit more clear when to add validation rules, and when domain rules.
The latter seem still fine when checking foreign key constraints for existence etc, since this is not part of the validation layer at this point.

**Comment by othercorey** [comment]
I've made changes to the app rules generated by bake. They now behave differently with multi-column unique indexes.

Closing since this isn't going to be resolved into one unified validation unless someone re-imagines how it works.
