### ISSUE TITLE
PHP 8.1: SessionHandlerInterface::gc must return int|false

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15576]
> PHP Fatal error:  During inheritance of SessionHandlerInterface: Uncaught Declaration of Cake\Http\Session\CacheSession::gc($maxlifetime): bool should be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false

This is throwing a fatal error instead of a deprecation notice so the `ReturnTypeWillChange` attribute won't suppress. Not sure if that should be suppressible or not.

The implementation probably needs to be changed to return the proper type.

**Comment by ADmad** [comment]
It seems the return type for [SessionHandler::gc()](https://www.php.net/manual/en/sessionhandlerinterface.gc.php) has changed since PHP 7.1

So we should update our session handler classes to match the same in 4.3. Since this method is used by PHP itself and not the users the return type change shouldn't cause any problem even though strictly speaking it would be a BC break.

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/15578
