### ISSUE TITLE
cake 5: BindingKeyTest::testBelongsto() fails on SQLServer

### ISSUE THREAD

**Issue by othercorey** [cakephp/cakephp#15606]
```1) Cake\Test\TestCase\ORM\BindingKeyTest::testBelongsto with data set #0 ('join')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    1 => 1
-    2 => 5
-    3 => 2
-    4 => 4
+    1 => 0
+    2 => 4
+    3 => 1
+    4 => 3
 )
```

Somehow the id for the first row in AuthUsers is 0.

**Comment by ndm2** [comment]
I've ran into this quite a few times now, it generally happens when inserting rows after [reseeding](https://github.com/cakephp/cakephp/blob/4.2.7/src/Database/Schema/SqlserverSchemaDialect.php#L652). If the table had no rows inserted before (eg, the table was just created), then the identity will start at `0`, if it _had_ rows inserted before, it will start at `1`.

**Comment by othercorey** [comment]
I was not aware of any dbs that started primary ids at 0.

**Comment by othercorey** [comment]
This should be fixed for all situations.
