### ISSUE TITLE
postgres not double-quoted Identifiers 

### ISSUE THREAD

**Issue by hekep** [cakephp/cakephp#15751]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Cakephp 4.2.6. 
Postgres DB, relativly new.

### What I  did

Case 1. I have 'order' column in 'account_visits' table, postgres DB.

$postgresDS = ConnectionManager::get('myPostGresDbConfig');
$postgresDS->insert('account_visits', [ 'id'  => null , 'order' => '#1234'  ]  , []);

Case 2. I have 'user_Firstname' column in 'users' table, postgres DB

$postgresDS->insert('account_visits', [ 'id'  => null , 'user_Firstname' => 'Adolf'  ]  , []);

### What happened

Cakephp produced SQL, which  has identifiers not double-quoted. These insert queries fail bacause

Case 1. 'order' is reserved in Postgres. Non double-quoted identifier causes error.
Case 2. Identifiers (including column names) that are not double-quoted are folded to lowercase in PostgreSQL. Column names that were created with double-quotes and thereby retained uppercase letters (and/or other syntax violations) have to be double-quoted for the rest of their life.  https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

### What you expected to happen

Cakephp should double-quote identifiers when using Postgres DB connection.
https://github.com/cakephp/cakephp/blob/22c5dd0659f4758bacea05ee9670fa3c7fac42f5/src/Database/Connection.php#L421

**Comment by othercorey** [comment]
https://book.cakephp.org/4/en/orm/database-basics.html#configuration

> quoteIdentifiers
Set to true if you are using reserved words or special characters in your table or column names. Enabling this setting will result in queries built using the Query Builder having identifiers quoted when creating SQL. It should be noted that this decreases performance because each query needs to be traversed and manipulated before being executed.
