### ISSUE TITLE
Put a instance of Application class inside a static method before initialization

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/cakephp#16202]
### Description

In some cases can be very useful have access to instance of Application class both in browser and console.
Eg. I have a cake.php command that can implements a interface in Application class and call it to do something like a configuration for example. Auth plugin already has a similar behavior.

This is one of many uses that can be done with this change.

Suggestion of implementation: save the instance on a static property and create a static method "getInstance()".

### CakePHP Version

4.4

**Comment by markstory** [comment]
> In some cases can be very useful have access to instance of Application class both in browser and console.
Eg. I have a cake.php command that can implements a interface in Application class and call it to do something like a configuration for example. Auth plugin already has a similar behavior.

Are there more details on these scenarios? So far `Application` helps wire the rest of the application code together and isn't accessible to other objects because it is supposed to create those things instead. You mentioned the authentication plugin which follows this pattern. The authentication and authorization plugins use `Application` interfaces/methods to provide 'hooks' for middleware to use.  Adding a `getInstance()` to Application makes another very large mutable global object which is a pattern we've been trying to reduce and avoid introducing more of as it creates harder to debug code.

**Comment by othercorey** [comment]
Closing because we don't want to support this.
