### ISSUE TITLE
belongsToMany through table with finder that contains table fails

### ISSUE THREAD

**Issue by Nexzer** [cakephp/cakephp#16252]
### Description

If you have the following relation setup in `ProductsTable.php`

```
$this->belongsToMany('VariantOptions', [
	'through'          => 'ProductVariantOptions',
	'targetForeignKey' => 'variant_option_id',
	'finder'           => 'forDomain',
]);
```

and the forDomain finder is located in `VariantOptionsTable.php` which looks like: 

```
public function findForDomain(Query $query, array $options)
{
	return $query->contain([
		'VariantOptionLocales' 
	]);
}
```

And then you try to save 

```
$product = $this->Products->newEntity([
	'variant_options'=>[
		[
			'description'=>1,
		]
	]
]);
$this->Products->save($product);
```

It then falls with the following error message: `The VariantOptionLocales association is not defined on ProductVariantOptions`.

This happens because in the `findForDomain` method, the `$query` objects `repository` property is an instance of the through table `ProductVariantOptions` which does not have a relation to `VariantOptionLocales`. 

The `repository` property should be an instance of the `VariantOptions` table instead. Thats how it worked in CakePHP 3.4 atleast

### CakePHP Version

4.3.0

### PHP Version

8.1

**Comment by markstory** [comment]
> It then falls with the following error message: The VariantOptionLocales association is not defined on ProductVariantOptions.

Sounds like your contain is not correct.

> This happens because in the findForDomain method, the $query objects repository property is an instance of the through table ProductVariantOptions which does not have a relation to VariantOptionLocales.

Isn't the finder you have defined invalid? If it is used independently wouldn't it fail because the association being used in `contain()` is not valid?

I believe the current behavior is better than the way it worked in 3.x because the finder behaves consistently when used on its own and when it is used in an association.

**Comment by Nexzer** [comment]
> Isn't the finder you have defined invalid? If it is used independently wouldn't it fail because the association being used in contain() is not valid? 

If i contain the data idependently like so, it works fine and contains the data i expect:

```
$product = $this->Products-find()->contain([
	'VariantOptions'
])->first();

```

if i debug `$product` it will now contain `variant_options` which contains `variant_option_locales`. 

It only fails when i attempt to save it.

> I believe the current behavior is better than the way it worked in 3.x because the finder behaves consistently when used on its own and when it is used in an association.

The issue i have is that it behavies differently when saving and fetching.

**Comment by markstory** [comment]
> If i contain the data idependently like so, it works fine and contains the data i expect:

Right, but this contain() is being applied to a query that comes from the `Products` table which has a relation with VariantOptions from what you've described.

If I'm understanding you, the problematic `contain()` comes from `forDomain` finder which exists in the junction table (ProductVariantOptions). The ProductVariantOptions model does not have a relation with VariantOptions which results in the contain() failing.

> The issue i have is that it behavies differently when saving and fetching.

Are you able to load products with variant options contained?

It might be helpful if you could include a minimal schema of the tables involved and how the relevant associations are defined as these issues are hard to talk about and diagnose with partial information.

**Comment by Nexzer** [comment]
Hi again and thanks for looking into this.

Please see this CakePHP plugin i created which showcases the issue:
https://github.com/Nexzer/issue

ive created the following urls you can test: /test/1, /test/2, /test/3, /test/4.

You can see the schema here: https://github.com/Nexzer/issue/blob/main/schema.sql

I have created some comments in the controller to attempt to describe the issue better https://github.com/Nexzer/issue/blob/main/src/Controller/IssuesController.php

Try to enable this debug here, and the repository property will be wrong on /test/3 and /test/4 https://github.com/Nexzer/issue/blob/main/src/Model/Table/IssueVariantOptionsTable.php#L32

**Comment by markstory** [comment]
Thank you. I'll take a look at the repository.

**Comment by markstory** [comment]
Thanks for the repository. I took a look and got the code running locally, but the `/test/1` route is raising a missing Table Exception. Do you have the code for the junction table as well? Without that I might not be seeing what you're seeing.

**Comment by Nexzer** [comment]
Hi. on my tests the auto-tables feature makes it work. Otherwise it would just be an empty table with no special code in it.

**Comment by markstory** [comment]
Thanks for taking the time to help in reproduce this.

I wanted to make sure you were using autoTables, as the internal paths are a bit different if its on or not. I was able to reproduce the problem you're seeing and the difference between 3.x and 4.x was introduced quite recently as a consequence of fixing #15977 (another long dormant bug). In this issue the reporter *has* a junction table instance.

The reporter of #15977 expects  (I agree with their view) that the query used to delete records on the junction table, should receive junction table entity instances in callbacks. As the query that that creates entities for callbacks is the *same* as the one that association finders are applied to.

Currently we call the BelongsToMany `finder` option on the target table and *then* pass that finder the query currently based on the junction table. This change in behavior has cause finders that use `contain()` to break as you've described.

One potential solution that *could* work is to revert most of the changes in #15985 and after the finder and conditions are built we can use that in a subquery select from the junction record table. This should let us get the correct entity type with all the required columns and have all the conditions driven by the subquery. This would require applying additional subquery conditions so that the joins to the junction table work, but we can do that with the ORM now. How does that sound as a solution to you? 

cc @cakephp/core

**Comment by Nexzer** [comment]
Hi and thank you for looking into this.
That sounds like a good soultion.
I also agree with the views of #15977.
To make it clear what i think:
Their `afterDelete` in `GroupTopics.php` should be an instance of `App\Model\Entity\GroupTopic` like they describe.
In my example `VariantOptionsTable` finder, `Query` should have the repository instance of `VariantOptions`.
To me this makes sense because it should contain the associated values:
`GroupTopics.php` -> `App\Model\Entity\GroupTopic`
`VariantOptionsTable` -> `VariantOptions` repository
I hope this makes sense.
