### ISSUE TITLE
Postlinks : first postlink <form> element missing

### ISSUE THREAD

**Issue by Soufiane974** [cakephp/cakephp#16515]
### Description

When using postlinks, the first postlink `<form>` element is missing for HTML generated. 

My PHP code : 

` <?= $this->Form->postLink(__('Supprimer'), ['controller' => 'Activities', 'action' => 'delete', $activity->id], ['block' => true,  'confirm' => __('Etes vous sûr de vouloir supprimer l\'activité ? L\'activité sera aussi retirée du planning.'), 'class' => 'btn btn-default btn-sm']) ?>
`

HTML table generated code : 
![image](https://user-images.githubusercontent.com/6583981/169980931-4cf2b0f6-6c10-4352-9bfd-6cab8f4cf865.png)

Below the generated postlink code : 
![image](https://user-images.githubusercontent.com/6583981/169980767-19b006d5-da38-4255-adc7-9fd3283a97e5.png)

The first link doesn't have <form> tag. A temporary solution is to add a first postlink with display none. The next links generates properly then.

### CakePHP Version

4.3.9

### PHP Version

7.4.0 / 8.1.4

**Comment by markstory** [comment]
Are you creating post link elements within another form? We have a few tests covering `postLink()` generating forms all the time. Have you checked with `view source` to make sure that the elements are there? Browsers will often 'fix' invalid HTML in documents, and since forms cannot be nested you could be running into that.

**Comment by othercorey** [comment]
@Soufiane974 Can you provide more information?
