### ISSUE TITLE
Query ->time -> max

### ISSUE THREAD

**Issue by CryptoMasterStallion** [cakephp/cakephp#16809]
### Description

When i do a query to a time datatype in mariadb. It returns a float instead a frozentime if i do a func->max.

My setup:

SQL:
` create table abc(totime time not null, ...`

bootstrap.php
`TypeFactory::map('time', StringType::class);`

table.php
```
$validator
    ->time('totime')
     ->notEmptyString('totime');
```

When i do a query like
`  $query->select(['totime' => $query->func()->max('Works.totime'), 'datum'])`

it returns a float for totime in the entity.

But when i do a query like

`        $query->select(['totime' => 'max(totime)', 'datum'])`

it returns a Frozentime as expected.

### CakePHP Version

4.4.6

### PHP Version

8.1

**Comment by othercorey** [comment]
Have you discussed this in the CakePHP support slack channel?

**Comment by CryptoMasterStallion** [comment]
no

**Comment by othercorey** [comment]
Join and post your question to see if it can be resolved first!

https://slack-invite.cakephp.org/

**Comment by markstory** [comment]
This is 'expected' behavior. The ORM uses column name matching to map results to their respective PHP types. Because the alias for your `max(totime)` function matches the name of an existing column, and there are no type mapping overloads being passed to `select()` the query maps `totime` to a datetime value.

If you want to fix this you can:

1. Change the alias of the function.
2. Provide type mapping information to `select(['totime' => 'max(totime)'], ['totime' => 'float'])` so that ORM can do what you want.

**Comment by ndm2** [comment]
I think OPs problem is the other way around, eg expecting `datetime` but receiving `float`, which is being dictated by the function expression's return type (which defaults to `float`). In that case a solution could be:

```php
$query->func()->max('Works.totime')->setReturnType('datetime')
```

Not sure if it's maybe worth adding a little bit of type inference to the functions builder?

**Comment by markstory** [comment]
My mistake, the issue is clearly written, I had the expected/unexpected cases flipped around.
