### ISSUE TITLE
[Database] `Error: Class 'Cake\Log\Engine\BaseLog' not found`

### ISSUE THREAD

**Issue by Sir-Will** [cakephp/cakephp#16824]
### Description

Hey,

I'm using the CakePHP Database library as standalone and I sometimes get the `Error: Class 'Cake\Log\Engine\BaseLog' not found` error.

Shouldn't the library work without the log library?

```
Error: Class 'Cake\Log\Engine\BaseLog' not found (Most recent call first)
File /var/www/_composer/vendor/cakephp/database/Log/QueryLogger.php:28
File /var/www/_composer/vendor/composer/ClassLoader.php:444 in include
File /var/www/_composer/vendor/composer/ClassLoader.php:322 in Composer\Autoload\includeFile
Show 2 non-project frames
File /var/www/_composer/vendor/cakephp/database/Connection.php:900 in class_exists
File /var/www/_composer/vendor/cakephp/database/Connection.php:920 in Cake\Database\Connection::getLogger
File /var/www/_composer/vendor/cakephp/database/Retry/ReconnectStrategy.php:113 in Cake\Database\Connection::log
File /var/www/_composer/vendor/cakephp/database/Retry/ReconnectStrategy.php:86 in Cake\Database\Retry\ReconnectStrategy::reconnect
File /var/www/_composer/vendor/cakephp/core/Retry/CommandRetry.php:74 in Cake\Database\Retry\ReconnectStrategy::shouldRetry
File /var/www/_composer/vendor/cakephp/database/Connection.php:287 in Cake\Core\Retry\CommandRetry::run
File /var/www/_composer/vendor/cakephp/database/Connection.php:335 in Cake\Database\Connection::prepare
File /var/www/_composer/vendor/cakephp/core/Retry/CommandRetry.php:70 in Cake\Database\Connection::Cake\Database\{closure}
File /var/www/_composer/vendor/cakephp/database/Connection.php:340 in Cake\Core\Retry\CommandRetry::run
File /var/www/_composer/vendor/cakephp/database/Query.php:250 in Cake\Database\Connection::run
```

### CakePHP Version

4.3.0

### PHP Version

7.4

**Comment by ndm2** [comment]
If you provide your own logger (which must implement `\Psr\Log\LoggerInterface`), then yes, it should work without `cakephp/log`, otherwise, no, it shouldn't.

You can set a custom logger via the connection's `setLogger()` method:

```php
$log = new \Monolog\Logger('name');
// ...

$connection->setLogger($log);
```

If you do not provide a logger, then you should receive a different error, one that clearly states that you either need to provide your own logger, or require `cakephp/log`. It appears that there's a problem with the code responsible for doing that. Also `cakephp/log` should probably be set as a composer suggestion.

**Comment by ndm2** [comment]
This was of course all assuming that you actually _want_ to use logging. If you do _not_ want to use logging, then it should work without any logging dependencies.

Looking at the stacktrace, it appears that you run into a situation where logging is unconditionally triggered, so that looks like another bug.

**Comment by Sir-Will** [comment]
I'm using the PHP's default error logging with Rollbar. So I could probably set Rollbar as the logger, though not sure if the error will show up in the nginx error log then.

**Comment by ndm2** [comment]
There would be no error, but the "query logging related" string that was trying to be logged (`[RECONNECT]` when trying to reconnect), which then caused the error as no logger was present.

Until a fix is merged and you can upgrade, using a dummy logger should be fine, as it's really just for query logging, so it wouldn't hide any error logs.
