### ISSUE TITLE
Translate Behavior generates SQL error

### ISSUE THREAD

**Issue by Soufiane974** [cakephp/cakephp#16862]
### Description

I got this error when I enable the translate behavior on a model :  

`SQLSTATE[HY000]: General error: 1364 Field 'libelle' doesn't have a default value`

Below the addBehavior in initialize callback of my model :

`
        $this->addBehavior('Translate', ['fields' => ['libelle']]);
`

The error occurs when I try to insert a row in my table : 

$i = $this->Indicators->newEmptyEntity();
$i->code = 'TESTI18N';
$i->libelle = "Mytest";
$this->Indicators->save($i);

The i18n is present and correctly created. You can not on the screenshot the sql query removes my field "libelle" from the request. 

![image](https://user-images.githubusercontent.com/6583981/201673886-593aeefc-dbbc-4183-8023-1dc4ac75e8dc.png)

### CakePHP Version

4.4.7

### PHP Version

8.1.11

**Comment by markstory** [comment]
Because you have `libelle` as a translated field it will *not* be saved in the `indicators` table as the text you've set is a stored as a field translation. 

If you'd like to have fields persisted into the `indicators` table you'll need to configure `defaultLocale` in the behavior and set `locale` on the entity that you're saving.

**Comment by Soufiane974** [comment]
@markstory Thank you, it works now.
