### ISSUE TITLE
Saving json array doesn't work

### ISSUE THREAD

**Issue by nitramxx** [cakephp/cakephp#17139]
### Description

Model with column type json to store json encoded array of values.

It's initiated as null and when there is first update (ie first value to array), it saves properly.

When there is an update (ie another value to the array), it is not saved. The update of the value is ignored.

It relies on core cakephp functionality to handle JSON type. Ie no encoding/decoding.

Although it's not an association, calling ->setDirty() method on the filed triggers the proper update in the database.

It seems that array considered as association. But it's not.

### CakePHP Version

4.4.13

### PHP Version

8.1.8

**Comment by garas** [comment]
If you change data using `$entity->json_data['key'] = 'value'`, data is updated in array directly, entity doesn't see this action and doesn't mark property as modified, and is skipped while building database query.

You should either use `$entity->json_data = $modifiedJSON` or call `setDirty()` or even use `$entity->json_data = $entity->json_data` to mark as modified.

**Comment by markstory** [comment]
How could someone reproduce the issue you're having?

**Comment by nitramxx** [comment]
Create table in DB:

```
use Migrations\AbstractMigration;

class Json extends AbstractMigration
{
	public function change(): void
	{
		$this->table('tests')
			->addColumn('foo', 'string')
			->addColumn('data', 'json', [
				'null' => true
			])
			->save();
	}
}

```
+ model src/Model/Table/TestsTable.php
```
<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class TestsTable extends Table
{
	public function initialize(array $config): void
	{
	}
}

```



Single purpose controller in src/Controller/TestsController.php:
```
<?php
namespace App\Controller;

class TestsController extends AppController
{

	public function run ()
	{
		$entity = $this->Tests->newEntity(['foo' => 'bar']);
		$entity = $this->Tests->save($entity);
		debug($entity);

		$data = [];
		$data[] = 'first';
		$entity->data = $data;
		$entity = $this->Tests->save($entity);
		debug($entity);

		$entity->data[] = 'second';
		$entity = $this->Tests->save($entity);
		debug($entity);

		$in_db = $this->Tests->find()
			->where(['id' => $entity->id])
			->first();

		debug($in_db);

		exit;
	}

}
```

when you open ../tests/run, you see:
1st debug initiating the entity
2nd debug entity after saving data for the first time (one element "first")
3rd debug entity after saving with updated data (two elements: "first" and "second")

but 4th debug shows what really is in the database, the saving with updated data didn't save it

I believe @garas explained why is it happening. But I still think it is a bug. Or it's at least worth highlighting this behaviour in the documentation.

**Comment by markusramsak** [comment]
This is regular object/array behavior in nearly every programming language therefore I think this is not a framework specific behavior or issue but a basic understanding how call by reference and call by value works.
If you program for example in Dart you could make the object or array as constant and modify the values of the object or array. The only thing you can't do is reassign a new array because than you would change the reference/object and would make it "dirty"/modified.
And setting a column of an entity automatically to "Dirty" means the object/reference changed or if it is a primitive type like string, int, float, bool that value changed. Dirty means simply reassignment of an value if not explicitly otherwise set dirty.

This has something to do with the memory. Sometimes the value changes in memory, sometimes the reference to an object/array and you have to be aware what happens when to be not surprised by the behavior of the language or framework.

**Comment by nitramxx** [comment]
@markusramsak I think you described very well one of main benefits of using framework - to not require thorough knowledge of what happens under the hood.

In my specific scenario:
- there is an updated value of one of the entity's attributes 
- explicit call to save the entity
- framework thinks there is no change 
- framework doesn't save the entity to the database

I think it's reasonable to expect the framework to save the entity when there are changes. And if it's more complicated to detect the change (like in this case with array), it's also reasonable that framework has that capability.

There is a functionality to decode/encode JSON type already. From architectural point, I think that when evaluating if there are any dirty attributes and therefor if the entity should be updated in the database, it would be quite clean to check if the arrays (JSONs) changed. But there might be better option.

**Comment by markusramsak** [comment]
I disagree with you but I understand your point. I think it is the same problem as having belongsTo or hasMany relationships in your model and expecting that the main entity is saved too (when only changes in the relationships were made and you call save() on the main model) so that the "modified" column could be updated.

Maybe there is a chance that the framework could save data in special cases (like json column) even though they are not marked as dirty ...
But I think this could make the ORM layer more complicated and maybe even less intuitive.
Maybe a new configuration option added in the model could be a solution so that the ORM layer does the extra work only if a special option is configured to make it backward compatible ...

**Comment by nitramxx** [comment]
I don't think it's the same. It's not a relationship, it's an attribute. The level of complexity is way lower than associated objects/entities.

There is no requirement to save main entity when there is change only in the associated one, I believe it is still valid to expect it when updating attribute.

**Comment by ADmad** [comment]
@nitramxx You are welcome to submit a PR which marks the property as dirty if a value within the array is updated.

**Comment by dereuromark** [comment]
> If you change data using `$entity->json_data['key'] = 'value'`, data is updated in array directly, entity doesn't see this action and doesn't mark property as modified, and is skipped while building database query.
> 
> You should either use `$entity->json_data = $modifiedJSON` or call `setDirty()` or even use `$entity->json_data = $entity->json_data` to mark as modified.

This is indeed how it needs to be handled. So far there seems no way to fix this, neither in 4.x nor 5.x.
So better we close this now and wait for a proposal as PR for further discussion then.
