### ISSUE TITLE
Feature Request for 5.x Controller::paginate getter (or suitable workaround)

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/cakephp#17148]
### Description

Now that `Controller::paginate` is protected, when it was previously public, any applications that were relying on accessing the public property for whatever needs cannot. Is there a suitable workaround to this or can a getter be put in place? My use-case is in this plugin https://github.com/cnizzardini/cakephp-swagger-bake where I rely on various meta-data such as the sortableFields for displaying OpenAPI data, but I can no longer access this.

Side note, the current 5.x documentation mentions that the paginate properties `sortableFields` key is still supported, but this does not appear in the doc block: https://github.com/cakephp/cakephp/blob/5.x/src/Controller/Controller.php#L150

P.s. Please let me know if there is a better forum for 5.x stuff like this.

### CakePHP Version

5.0

**Comment by markstory** [comment]
> Is there a suitable workaround to this or can a getter be put in place?

Some of the options I could see working are:

1. A trait in applications/plugins that compatible controllers need to implement in order to have this metadata extracted.
2. Using reflection to get read access to the `paginate`  property.
3. Having `Controller` expose a `getPaginate()`.

Having cake expose a method seems like the simplest solution as anyone can benefit from it. If you want to put together a pull request that would be greatly appreciated.

Edit: I misread the question and have revised my answer.

**Comment by cnizzardini** [comment]
I'm fine with the proposed workarounds. I'm not sure why I didn't think about reflection since I already use it a ton, thanks.
