### ISSUE TITLE
Cake\View\ViewBuilder implements the Serializable interface, which is deprecated in PHP 8

### ISSUE THREAD

**Issue by panwlodek** [cakephp/cakephp#17206]
### Description

Deprecated: Cake\View\ViewBuilder implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in src/View/ViewBuilder.php on line 37

My PHP Version 8.1.2-1ubuntu2.13

Do you have a newest version of cakephp, that do not use Serializable ? I downloaded the version 4.4.15 and checked the file View/ViewBuilder.php and saw, that there is still used Serialize in the line 37

### CakePHP Version

4.1.1

### PHP Version

8.1.2

**Comment by othercorey** [comment]
Serializable is not deprecated in PHP 8.

**Comment by dereuromark** [comment]
To clarify:
Since PHP 8.1, implementing the Serializable interface without implementing __serialize and __unserialize methods is deprecated.
Which we do ( https://github.com/cakephp/cakephp/blob/5e1a0222f9e570d9b9bbc0a7c65eed08d5c5d2d0/src/View/ViewBuilder.php#L699-L702 ), as such all is good.

For reference: https://github.com/cakephp/cakephp/pull/15538
And as per commit info part of CakePHP 4.3+
