### ISSUE TITLE
phpstan error when using FrozenDate::createFromFormat

### ISSUE THREAD

**Issue by thonhaus** [cakephp/cakephp#17229]
### Description

When using FrozenDate::createFromFormat() phpstan throws an error. This is due to the renaming of Date to ChronosDate in Chronos if Chronos is used in version 2.4.0. FrozenDate::createFromFormat() works fine, it just throws an error from phpstan.
 
Since the name "Date" is deprecated and removed in Chronos version 3.0.0, "ChronosDate" should be used directly and the dependency should be increased to 2.4. 

### CakePHP Version

4.4.16

### PHP Version

8.1

**Comment by LordSimal** [comment]
We discussed this in https://github.com/cakephp/cakephp/pull/17226#issuecomment-1671077156

We can't fix this via updating the version constraint to `^2.4` in a patch release because we could break apps which rely on chronos 2.2 or 2.3

But this is already fixed in `4.next` as you can see [here](https://github.com/cakephp/cakephp/blob/4.next/src/I18n/FrozenDate.php#L19-L29)

So you will have to wait till 4.5 or just ignore that stan error

**Comment by thonhaus** [comment]
Thank you for your answer. Sorry, I didn't see #17226 and the fix for 4.next before. However, I do not understand why it is not possible to bump Chronos to 2.4. According to the changelog it is backwards compatible. But anyway, I ignore the stan error and wait for 4.5.

Thanks for your work!
