### ISSUE TITLE
5.x: Small regression on extractOriginal()

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17266]
### Description

```php
$this->assertSame(['id' => null, 'body' => 'test save'], $entityBefore->extractOriginal(['id', 'body']));
```
This used to be true.

Now it is expected to be
```php
$this->assertSame(['body' => 'test save'], $entityBefore->extractOriginal(['id', 'body']));
```
It is weird that here, requesting two fields, one of them is dropped now

I wonder if we could revert here the original behavior?

### CakePHP Version

5.x

### PHP Version

8.1

**Comment by dereuromark** [comment]
PR open

**Comment by fabian-mcfly** [comment]
That change will now again return `null` for fields that aren't original fields, which is - imho - not a good way to handle them.

It would be simpler to change the if/else to:

```php
if ($this->hasOriginal($field)) {
    $result[$field] = $this->getOriginal($field);
} else {
    $result[$field] = $this->get($field);
}
```

This way, the property `requireFieldPresence` takes effect and throws an exception when requesting fields that aren't present if set to true, and returns null otherwise.
