### ISSUE TITLE
5.x PSR

### ISSUE THREAD

**Issue by zbindu** [cakephp/cakephp#17286]
### Description

Thie version of psr/http-message(^2.0) is too high, so it it is not compatible with many libraries. Suggest ^1.0 || ^2.0.
Other psr packages are similar. For example psr/log.

**Comment by LordSimal** [comment]
We bumped the minimum version here because it fit well with our general idea of adding native param and return types to the framework.

We _could_ try making it work with `^1.1 || ^2.0` because 1.1 at least has param types (but no return types).

**My personal opinion**: We are trying to go forward with the framework and this may also break compatibility with older versions of other libraries (like you explained here). CakePHP 4 will still be supported till September 2026 so if you need that library you are fine staying on that. But in the meantime, I would recommend encouraging those library maintainers to go with the time and update their libraries to current, recommended versions. PHP 8.0 is EOL this year, so there is no reason to forcibly hang on to old versions which still support < PHP 8.0 (`psr/http-message` 1.1 is PHP `^7.2`)

**Comment by othercorey** [comment]
The problem we have supporting multiple psr versions is overriding methods. Some packages simply take a logger as input and can support multiple versions. However, when we implement an interface then we are limited.

**Comment by ADmad** [comment]
Supporting multiple majors is feasible only when consuming objects, not when implementing the interface.
