### ISSUE TITLE
3.0 - Support for multiple pagination

### ISSUE THREAD

**Issue by lh-import** [cakephp/cakephp#1731]
Created by **cake_joe**, 11th Jan 2012. *(originally [Lighthouse ticket #102](http://cakephp.lighthouseapp.com/projects/42648/tickets/102))*:
- - - -

**Comment by dereuromark** [comment]
Didn't someone start multi-column support for 3.x? Can't find the ticket or PR anymore.
At least that would be quite handy. The multi-model thing is tricky and most likely not so trivial.

**Comment by krizSolution** [comment]
since it always help me to visualize a concept...
this is what it could look like:
![cake_paginator](https://cloud.githubusercontent.com/assets/3873814/5909910/2255d396-a5b5-11e4-9b4d-9ad715c571c8.jpg)

- clicking [ASC/DESC] sets the direction of the column
- clicking a column-name itself sets this column to first-to-order
(pseudo sql would look like "ORDER column3 ASC, column2 DESC, ...")

**Comment by lorenzo** [comment]
closing as there is a PR open
