### ISSUE TITLE
$this->request->trustProxy = true; has no effect on Router class

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/cakephp#17354]
### Description

My application is running behind a load balancer, hence in my `AppController` I have the following code according to the docs ( https://book.cakephp.org/4/en/controllers/request-response.html#trusting-proxy-headers ):

```
public function initialize(): void
{
    $this->request->trustProxy = true;
}
```

After this, if I run `$this->request->scheme()`, I get `https`, which is the expected result.

However, calling `Router::url('/', true)` gives me `http://www.mydomain.com` with **http** instead of **https**. Also calling `Router::setRequest($this->request)` didn't fix the issue.

Essentially, `$this->request->scheme()` and `$this->request->getUri()->getScheme()` give two different results. This can be fixed by calling `$this->request->setTrustedProxies([]);` instead of `$this->request->trustProxy = true;`, as this updates the protected variable `ServerRequest::$uri`.

Yet still `Router::url('/', true)` doesn't give me the URL with https and `Router::setRequest($this->request)` has no effect, because the code of this function ...

```
static::$_requestContext += [
    '_scheme' => $uri->getScheme(),
    '_host' => $uri->getHost(),
    '_port' => $uri->getPort(),
];
```

... doesn't update the already existing `_scheme` from `http` to `https`.

Where am I supposed to put `$this->request->trustProxy = true;` in order for this to work?

### CakePHP Version

4.4.14

**Comment by ndm2** [comment]
You'll have to enable that in your `config/bootstrap.php`, setting `$trustProxy` to `true` should be enough, assuming your load balancer sets `HTTP_X_FORWARDED_PROTO`.

https://github.com/cakephp/app/blob/b8948f8aeb1d1d5991b9eb74d21c197ee7f26011/config/bootstrap.php#L135-L165

Alternatively it's possible to manually set the full base URL via the `App.fullBaseUrl` config.

**Comment by gerhard-lechner** [comment]
Thanks for the prompt reply! Setting `$trustProxy` to `true` in `config/bootstrap.php` did the trick.

Does it make sense to move the "Trusting Proxy Headers" chapter from "Request & Response Objects" to "Configuration" in the docs as the method mentioned (`$this->request->trustProxy = true;`) which used to work in CakePHP 3 doesn't work like this in CakePHP 4 anymore.

**Comment by markstory** [comment]
> Does it make sense to move the "Trusting Proxy Headers" chapter from "Request & Response Objects" to "Configuration" in the docs as the method mentioned

I think that section of the documentation is still accurate. Without `trustProxy` set to `true` the request will not read proxy headers at all. Your issue is related to `trustProxy` bt also related to configuration. For applications operating behind a load balancer the recommended configuration is to define `App.fullBaseUrl` as deriving that value on each request is wasteful. I think it could be helpful to call out needing to set `App.fullBaseUrl` when your application is behind a load balancer in request & response chapter though. I've opened a pull request to the docs to help clarify this.

If an application cannot use the configuration value, they would need to enable `trustProxy` before `RoutingMiddleware` executes so that the request gets set into `Router` correctly the first time through.
