### ISSUE TITLE
Session.timeout does not override anything

### ISSUE THREAD

**Issue by utdrmac** [cakephp/cakephp#17513]
### Description

The Session.timeout configuration option does not actually override the Session handler timeout value. Looking here, we can see a config array value being set using 60 * _user override_:

https://github.com/cakephp/cakephp/blob/5.x/src/Http/Session.php#L222-L224

But a few lines down, the value created above is not used:

https://github.com/cakephp/cakephp/blob/5.x/src/Http/Session.php#L243

Because of this, sessions timeout regardless of what the users have set in their config/app.php for Session timeout.

```php
'Session' => [
        'defaults' => 'php',
        'timeout' => 0
    ],
```

### CakePHP Version

5.0.4

### PHP Version

8.2.11

**Comment by utdrmac** [comment]
I suggest replacing line 243:

Before:
```php
$this->_lifetime = (int)ini_get('session.gc_maxlifetime');
```

After:
```php
$this->_lifetime = $config['ini']['session.gc_maxlifetime'];
```

**Comment by markstory** [comment]
Wouldn't the call to `options()` here https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L235

set the generated value into PHP's runtime configuration, allowing the `ini_get` on 243 to read the correct value? The options method is currently implemented as https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L316-L329

**Comment by utdrmac** [comment]
@markstory I'd consider that a workaround. The documentation https://book.cakephp.org/5/en/development/sessions.html#built-in-session-handlers-configuration shows a clear example of how you can override the timeout, but it doesn't actually do that.

**Comment by markstory** [comment]
How is it a workaround? From reading the code reading from the ini config should yield the same value as your suggested change.

Are you finding that you are not able to extend the timeout of sessions?

**Comment by utdrmac** [comment]
I am not able to extend the timeout of the sessions using the officially documented method in the link above. This is the example given in the docs:

```
Configure::write('Session', [
    'defaults' => 'php',
    'cookie' => 'my_app',
    'timeout' => 4320 // 3 days
]);
```

This does not work. The `timeout` option is not used per the code lines I provided in the original bug report.

**Comment by markstory** [comment]
> The timeout option is not used per the code lines I provided in the original bug report.

What timeout are you hoping to have set? There are three different timeouts that impact session lifetimes.

The `Session.timeout` option defines a duration that is used to create an 'idle timeout' between requests while the cookie is still valid.

In addition to the `Session.timeout` configuration option there is also PHP ini configuration for the `session.cookie_lifetime`  which defines the expiry time of session cookies. The  `session.gc_maxlifetime` controls when PHP's session garbage collection should consider a session 'garbage'. The `Session.timeout` option will not change the cookie lifetime, but does influence the `gc_maxlifetime`. Changing the `gc_maxlifetime` only is odd but is historical behavior that is hard to change now.

It sounds like you might be trying to extend the cookie lifetime which you can do with

```php
'Session' => [
   'ini' => ['session.cookie_lifetime' => 4320],
]
```

Having the `Session.timeout` not influence cookie lifetime is an odd behavior, but often applications want to have the cookie lifetime exceed the idle timeout so that cookies don't need to be reissued as often. I can update the docs to better explain which timeout `Session.timeout` applies to.

**Comment by utdrmac** [comment]
> The Session.timeout option defines a duration that is used to create an 'idle timeout' between requests while the cookie is still valid.

Correct. This is what I'm trying to fix. If I'm logged into my app, and I leave it there for 20m, when I come back and do some action, I expect my session to continue and not be required to re-auth. This is the behavior of our old, non-cakephp, application and we need that behavior to continue.

The Session.timeout option defines a duration that is used to create an 'idle timeout' between requests while the cookie is still valid.

https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L676

In this line, I want `$this->_lifetime` to be 0 so that the result of this function returns false, thereby leaving the user logged in. The only location in this entire class where _lifetime is modified is here:

https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L243

This line uses the ini config of `session.gc_maxlifetime`. On this line,

https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L223

you can see the same "parameter" being modified. Clearly there was supposed to be a relationship here. Both the ini name and the array key are the same. Thus my original issue about the user-provided `timeout` value does not override _lifetime as it should.

If line 243 simply used the aforementioned $config key of the same name, this issue would be resolved.

Furthermore, `$config['ini']['session.gc_maxlifetime']` is not used anywhere else in this class. What is the purpose then of this value if it is never used?

**Comment by markstory** [comment]
> If line 243 simply used the aforementioned $config key of the same name, this issue would be resolved.

How? In my testing when `Session.timeout` is defined both values are the same. I don't understand how changing one for the other solves the problem. Furthermore, the change you're suggesting will introduce runtime errors when `Session.timeout` is `0` or undefined as the suggested key would not be set.

If you do not want any server side session idle timeouts applied, you can set `Session.timeout` to `0`. You will *also* need to configure PHP to have a very long `gc_maxlifetime` so that PHP doesn't garbage collect your sessions from underneath clients.

The [PHP docs](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime) state

>session.gc_maxlifetime specifies the number of seconds after which data will be seen as 'garbage' and potentially cleaned up. Garbage collection may occur during session start (depending on [session.gc_probability](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-probability) and [session.gc_divisor](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-divisor)). Defaults to 1440 (24 minutes).

> Note: If different scripts have different values of session.gc_maxlifetime but share the same place for storing the session data then the script with the minimum value will be cleaning the data. In this case, use this directive together with [session.save_path](https://www.php.net/manual/en/session.configuration.php#ini.session.save-path).

If you're having session timeout issues with `Session.timeout = 0` in CakePHP's config, then you might have a gc_maxlifetime that is too short for what you want. Have you tried increasing that?

> Furthermore, `$config['ini']['session.gc_maxlifetime']` is not used anywhere else in this class. What is the purpose then of this value if it is never used?

This option is set into PHP's runtime configuration. Depending on how PHP is configured, it can attempt to garbage collect session data at the end of a request.

**Comment by utdrmac** [comment]
> In my testing when Session.timeout is defined both values are the same.

Interesting, because in my testing, when I set Session.timeout = 0, the value of $_lifetime is never modified. Thus the _timedOut() function always returns true after the ini gc_maxlifetime value.

Please look through the entire Session.php and show me where `$config['ini']['session.gc_maxlifetime']` is used. It's not use anywhere. In fact, you can grep the entire cakephp codebase and you'll see it is not use anywhere. So, if it is not used anywhere, then what is the point of Session.timeout? It has none as the code currently stands.

This is why my original report still stands. This: `config/app.php:  'Session' => [ 'defaults' => 'php', 'timeout' => 0 ]` does absolutely nothing. You can see in the code in the lines from my comments above where the value of Session.timeout has absolutely no effect on the returned result of _timedOut().

> If you do not want any server side session idle timeouts applied, you can set Session.timeout to 0. 

That is incorrect because there is nothing in the code that this affects.

> You will also need to configure PHP to have a very long gc_maxlifetime 

I'm using the same PHP config from our old app and I've never modified that parameter and my old app has the session timeout behavior that I want.

This is 100% a cakephp issue. I know this because I made the following change:

```
       	#$this->_lifetime = (int)ini_get('session.gc_maxlifetime');
       	$this->_lifetime = 0;
```

and now it behaves exactly like my old app. And as I said above, there is no option to change the value of _lifetime because setting Session.timeout does nothing.

**Comment by markstory** [comment]
> Interesting, because in my testing, when I set Session.timeout = 0, the value of $_lifetime is never modified. Thus the _timedOut() function always returns true after the ini gc_maxlifetime value.

Yes in the case of `Session.timeout = 0` the values differ. However, when `Session.timeout = 0` the `ini` key is not set causing a runtime error in the suggested change.

> Please look through the entire Session.php and show me where $config['ini']['session.gc_maxlifetime'] is used. It's not use anywhere. In fact, you can grep the entire cakephp codebase and you'll see it is not use anywhere. So, if it is not used anywhere, then what is the point of Session.timeout? It has none as the code currently stands.

I can't show you that because it isn't used *by* CakePHP. CakePHP sets it as a runtime option *into* PHP to change how PHP handles sessions. This happens in the `options` method. https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L316-L329

>  You can see in the code in the lines from my comments above where the value of Session.timeout has absolutely no effect on the returned result of _timedOut().

I don't think you've considered the scenarios where `Session.timeout != 0` . For a non-zero values, `_timedOut()` enforces a server side idle timeout. When set to `0` session timeouts are limited by the `session.gc_maxlifetime` because once a session is older than that, they are likely be garbage collected by PHP creating a 'timeout' that gets enforced outside of application space.

What by chance is the value of `ini_get('session.gc_maxlifetime')` on your system?  The code in question here has been around for almost 10 years and this is the first issue that has been opened, which leads me to believe the issue is on your end. 

The change you've recommended emits runtime errors with other valid configurations like  `'Session' => ['defaults' => 'php']`, which would create issues for many other applications. Should we need to make a change the suggested one is also not correct.

**Comment by utdrmac** [comment]
Oh, I found the real issue here.

```
-- config/app.php
    'Session' => [
       	'defaults' => 'php',
        'timeout' => 0
    ],

-- vendor/cakephp/cakephp/src/Http/Session.php
        ...
        $this->_lifetime = (int)ini_get('session.gc_maxlifetime');
        $this->_isCLI = (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg');
        session_register_shutdown();
        var_dump($config);
        die(sprintf("lifetime: %d | config timeout: %d | config ini: %d", $this->_lifetime, $config['timeout'], $config['ini']['session.gc_maxlifetime']));
```
The above debug die results in this:

```
array(6) { ["ini"]=> array(5) { ["session.use_trans_sid"]=> int(0) ["session.cookie_samesite"]=> string(3) "Lax" ["session.use_strict_mode"]=> int(1) ["session.cookie_httponly"]=> int(1) ["session.cookie_path"]=> string(1) "/" } ["defaults"]=> string(3) "php" ["timeout"]=> int(0) ["cookiePath"]=> string(1) "/" ["cookie"]=> NULL ["handler"]=> array(0) { } }

[Warning (2) ](javascript:void(0);): Undefined array key "session.gc_maxlifetime" [in /var/www/mboehm-dev/dipper/vendor/cakephp/cakephp/src/Http/Session.php, line 248]
lifetime: 1440 | config timeout: 0 | config ini: 0
```

We can see that `session.gc_maxlifetime` does not exist in config['ini']. But why not? It's because of int(0) evaluating to false:

https://github.com/cakephp/cakephp/blob/e8601c848cfc92af5aebc3d13ed7434cb333e4e8/src/Http/Session.php#L222

I'm trying to set an int(0) timeout value, but `if ($config['timeout'])` evals to false, thus the line of code which should create `config['ini']['session.gc_maxlifetime']` does not run and thus `options()` does not modify the ini session.gc_maxlifetime and thus $_lifetime is never modified.

good grief. we both missed that. :)

I modified the check. The default value of timeout is null. If any other value is provided, the block executes and the ini override is set.

```
        if (!is_null($config['timeout'])) {
            $config['ini']['session.gc_maxlifetime'] = 60 * $config['timeout'];
        }
```

New result from above die(sprintf()):

```
array(6) { ["ini"]=> array(6) { ["session.use_trans_sid"]=> int(0) ["session.cookie_samesite"]=> string(3) "Lax" ["session.use_strict_mode"]=> int(1) ["session.cookie_httponly"]=> int(1) ["session.gc_maxlifetime"]=> int(0) ["session.cookie_path"]=> string(1) "/" } ["defaults"]=> string(3) "php" ["timeout"]=> int(0) ["cookiePath"]=> string(1) "/" ["cookie"]=> NULL ["handler"]=> array(0) { } }
 lifetime: 0 | config timeout: 0 | config ini: 0
```

And that works!

**Comment by markstory** [comment]
Good to see that the issue is related to how `session.gc_maxlifetime` is being determined. I'm not sure that setting that ini option to 0 will work well in all deployments though. The PHP docs state:

> session.gc_maxlifetime specifies the number of seconds after which data will be seen as 'garbage' and potentially cleaned up. Garbage collection may occur during session start (depending on [session.gc_probability](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-probability) and [session.gc_divisor](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-divisor)). Defaults to 1440 (24 minutes).

Having a 0 could result in all sessions being evicted once a GC sweep occurs. We could special case the `0` scenario and choose a long gc_maxlifetime value instead of 0 though. Perhaps 30 or 60 days?

**Comment by markstory** [comment]
@utdrmac Would you be able to apply the changes from #17525 locally and see if they solve your issue?

**Comment by utdrmac** [comment]
i applied it. also commented on the PR regarding a better default.

**Comment by othercorey** [comment]
> i applied it. also commented on the PR regarding a better default.

Does that mean it worked?
