### ISSUE TITLE
Extending base validation fails.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#17631]
### Description

It should be possible to use a different (extended) Validation class for all validators
https://book.cakephp.org/5/en/core-libraries/validation.html#adding-validation-providers

As per book in bootstrap:
```
// replacing core one with app
\Cake\Validation\Validator::addDefaultProvider('default', \App\Validation\Validation::class);
```
leads to
> [TypeError] Cake\Validation\Validation::decimal(): Argument # 3 ($regex) must be of type ?string, array given

But it is just
```php
namespace App\Validation;

use Cake\Validation\Validation as CakeValidation;

class Validation extends CakeValidation {}
```

### CakePHP Version

5.0

### PHP Version

8.2

**Comment by dereuromark** [comment]
The whole validation thing in Cake is quite buggy, as pointed out earlier ( https://github.com/cakephp/cakephp/issues/12697 ).
It doesn't help that the argument count can vary, and context can be at any position of validation rules, depending on what other arguments are available.

As soon as the validation provider is configured in any way, even core rules fail with the above.

The main reason seems to be that in this case, the 3rd arg is set with this array instead as $context instead of the expected $regex:
```php
[
'newRecord' => false,
'data' => [
    ...
],
'field' => 'weight',
'providers' => [ ],
]
```

**Comment by dereuromark** [comment]
My guess would be that because `?string $regexp = null` is an optional value, and possibly null here
that it messes up the count when passing them in
```php
if ($this->_pass) {
            $args = array_values(array_merge([$value], $this->_pass, [$context]));
            $result = $callable(...$args);
        } else {
            $result = $callable($value, $context);
        }
if ($this->_pass) {
            $args = array_values(array_merge([$value], $this->_pass, [$context]));
            $result = $callable(...$args);
        } else {
            $result = $callable($value, $context);
        }
```

**Comment by dereuromark** [comment]
This feels also somewhat related to https://github.com/cakephp/localized/issues/252#issuecomment-2097715729
I guess we could try to make the API a bit more straightforward in terms of args.

**Comment by ADmad** [comment]
> The main reason seems to be that in this case, the 3rd arg is set with this array instead as $context instead of the expected $regex

That's the case. `Validator::decimal()` uses only 1 argument with config like `'rule' => ['decimal', $places]`. Then because of `$args = array_values(array_merge([$value], $this->_pass, [$context]));` in `ValidationRule::process()` the context array gets passed as value for the 2nd argument `$regex` of `Validation::decimal()`.

So with the current implementation if a validation method has additional args you must either pass all the args or none to avoid this error. I can't think of any other way besides reflection to avoid this problem.

**Comment by dereuromark** [comment]
I didnt change any rules/code.
Even just replaced the addDefaultProvider() for default:
```php
namespace App\Validation;

use Cake\Validation\Validation as CoreValidation;
use PhpCollective\DecimalObject\Decimal;

class Validation extends CoreValidation {

	public static function decimal(mixed $check, int|bool|null $places = null, ?string $regex = null): bool {
		return parent::decimal($check, $places, $regex);
	}

}
```
is the exact same signature

and the validation rule is also the same as before:

		$validator
			->decimal('tax');

This would not work unfortunately.
It now also screws up other validation methods/fields:
```
Unable to call method `isScalar` in `default` provider for field `id`
```

**Comment by ADmad** [comment]
Something really wacky is going on. I am running just this test https://github.com/cakephp/cakephp/blob/e15d186e05e9e02231d53ba3bb6daa9290c3a470/tests/TestCase/Validation/ValidatorTest.php#L2347 and sure enough as this point https://github.com/cakephp/cakephp/blob/e15d186e05e9e02231d53ba3bb6daa9290c3a470/src/Validation/ValidationRule.php#L145 the `$args` array is 
```
[
  (int) 0 => (float) 10.1,
  (int) 1 => (int) 2,
  (int) 2 => [
    'newRecord' => true,
    'data' => [
      'username' => (float) 10.1
    ],
    'field' => 'username',
    'providers' => [
      'default' => object(Cake\Validation\RulesProvider) id:0 {
        [protected] _class => 'Cake\Validation\Validation'
        [protected] _reflection => object(ReflectionClass) id:1 {
          name => 'Cake\Validation\Validation'
        }
      }
    ]
  ]
]
```

But a `debug(func_get_args());` in `Validation::decimal()` gives
```
[
  (int) 0 => (float) 10.1,
  (int) 1 => (int) 2
]
```

The 3rd array value of `$args` vanishes! Does PHP auto skip the value due to type mismatch?  And if so why does the error show up only when you extend `Validation`?

**Comment by ADmad** [comment]
So the above magic happens due to this

https://github.com/cakephp/cakephp/blob/e15d186e05e9e02231d53ba3bb6daa9290c3a470/src/Validation/RulesProvider.php#L74-L76

**Comment by ADmad** [comment]
This is what alllows this magic

https://github.com/cakephp/cakephp/blob/e15d186e05e9e02231d53ba3bb6daa9290c3a470/src/Validation/Validator.php#L324-L333

So by default `getProvider('default')` will return an instance of `RulesProvider` which does the args juggling before calling the validation methods of `Validation`. But since you used `addDefaultProvider()` to set `default` to your own class all the magic was gone.

**The fix is to use**
```
 \Cake\Validation\Validator::addDefaultProvider('default', new \Cake\Validation\RulesProvider(\App\Validation\Validation::class));
```

**Comment by dereuromark** [comment]
I can confirm that the workaround works :)

I documented it for the CakeDecimal plugin: https://github.com/dereuromark/cakephp-decimal/commit/246a6c82a975b72f5d19ea41f5516c40e856cb79
