### ISSUE TITLE
FormHelper - input number doesn't work

### ISSUE THREAD

**Issue by lupainformatica** [cakephp/cakephp#17640]
### Description

The default config in FormHelper doesn't support type _Number_, and when is used the types _Integer_ or _Float_ they aren't properly converted to input type number and the preserve the "integer" and "float" as the input type.

```php
<?= $this->Form->control('ddd', [
            'label' => 'Ddd',
            'type' => 'integer',
            'max' => '99',
            'min' => '11',
            'required' => false,
        ])?>
<!-- Will output -->
<div class="input integer">
    <label for="ddd">Ddd</label>
    <input type="integer" name="ddd" max="99" min="11" id="ddd" value="48">
</div>

<!-- The expected output should be -->
<div class="input integer">
    <label for="ddd">Ddd</label>
    <input type="number" name="ddd" max="99" min="11" id="ddd" value="48">
</div>

```

### CakePHP Version

5.0.5

### PHP Version

8.1

**Comment by dereuromark** [comment]
A type integer (from DB column schema) will transform to type number of form helper control elements
https://github.com/cakephp/cakephp/blob/b56e0a0e71a000493cdea8f276bf80367fac8d7d/src/View/Helper/FormHelper.php#L93

But you are setting the form element type here to integer (instead of using `'type' => 'number'`).

So your expectation is not correct, as you are setting the form control type you actually get.

**Comment by lupainformatica** [comment]
Yes, but according to CakePHP 5 manual `https://book.cakephp.org/5/en/views/helpers/form.html` it should be mapped to number

**Comment by lupainformatica** [comment]
Thank you the assistance
