### ISSUE TITLE
BaseErrorHandler::$logger conflicts with PSR-3 $logger

### ISSUE THREAD

**Issue by bancer** [cakephp/cakephp#17693]
### Description

```
    /**
     * Exception logger instance.
     *
     * @var \Cake\Error\ErrorLoggerInterface|null
     */
    protected $logger;
```
https://github.com/cakephp/cakephp/blob/4.x/src/Error/BaseErrorHandler.php#L56C1-L61C23

This property conflicts with `\Psr\Log\LoggerAwareTrait::$logger` which is `LoggerInterface|null`. Therefore it is impossible for our custom error handler to implement PSR-3 LoggerAwareInterface https://www.php-fig.org/psr/psr-3/. The simplest fix would probably be to rename `$logger` to `$_logger` or something else in BaseErrorHandler class.

### CakePHP Version

4.x

**Comment by ADmad** [comment]
> Therefore it is impossible for our custom error handler to implement PSR-3 LoggerAwareInterface

How does it prevent you from implementing the interface? Just add a `setLogger()` function yourself instead of using the `\Psr\Log\LoggerAwareTrait`. It's a one liner function anyway.

**Comment by bancer** [comment]
Right, this makes it impossible to call `use LoggerAwareTrait;`.  

I can implement LoggerAwareTrait of course but having `$this->logger` an instance of LoggerInterface in hundreds of files where LoggerAwareTrait is used but an instance of ErrorLoggerInterface (which is not compatible with LoggerInterface) only in one file makes this inconsistent and quite confusing. I would prefer to be able to use LoggerAwareTrait per PSR-3:

![Screenshot from 2024-05-29 16-13-51](https://github.com/cakephp/cakephp/assets/3830106/188777bc-6959-45fb-a574-41642605d873)

Another option would be to make ErrorLoggerInterface compatible with LoggerInterface but that would require more changes I think.

**Comment by markstory** [comment]
> The simplest fix would probably be to rename $logger to $_logger or something else in BaseErrorHandler class.

This feels like a breaking change that we couldn't do in 4.x. We might be able to extend the `ErrorLoggerInterface` to be compatible with PSR loggers and its current interface as well.

It is worth pointing out that `Error\ErrorLogger` uses PSR loggers under the hood.

**Comment by markstory** [comment]
After some back and forth in other pull requests, we've made `ErrorLogger` into a PSR3 compatible logger. However, this doesn't help address your original goal of using a PSR3 logger with `BaseErrorHandler`.  However, I'm not sure that is a feasible goal based on how `BaseErrorHandler` uses loggers.

Instead of relying on the PSR standard interface, `BaseErrorHandler` calls `logMessage($level, $message, $context)` and `log($exception, $request)` and neither of these methods are part of the PSR interfaces. If we were to move the current property to `_logger` and you were to use `LogAwareTrait` to set a logger for an ErrorHandler subclass you would still hit runtime error unless you also implemented `logException` and `_logError` in your error handlers.

The entire `BaseErrorHandler` family of classes is deprecated as they are being replaced with `ErrorTrap` and `ExceptionTrap` which do not have the same property limitations. Have you considered switching to those classes instead of using `BaseErrorHandler`?

**Comment by bancer** [comment]
Yes, we will switch to ErrorTrap and ExceptionTrap when we are ready to upgrade to 4.5.
