### ISSUE TITLE
Have redirect use same uri  scheme as the request

### ISSUE THREAD

**Issue by MolbioUnige** [cakephp/cakephp#17924]
### Description

Would it be possible to have redirections use, by default, the same uri scheme as the request?

As it is now, all redirection are done over http, which causes issues with Chrome at least. As a work around, I use the `_https` special route element and set it to the same scheme as the request.

**Comment by dereuromark** [comment]
CakePHP always uses the same scheme 
What is your code here?

**Comment by ADmad** [comment]
@MolbioUnige Your app is most likely behind a proxy/load balancer and while the public access is over HTTPS the access from the proxy to your app is over HTTP which is why Cake doesn't auto use HTTPS. If that's the case set `$trustProxy = true`  in your [bootstrap.php](https://github.com/cakephp/app/blob/0af0d61b1b0baa8b0d6953199f20b99be3536d4e/config/bootstrap.php#L152).

**Comment by MolbioUnige** [comment]
@ADmad yes, you are right, that is what's happening. Sorry for the trouble.
