### ISSUE TITLE
Add type assertions for values in $defaults when connecting routes

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp#17931]
### Description

Refs #17927 

### CakePHP Version

5.1

**Comment by ryanolton** [comment]
@ADmad @markstory I performed and update today which exposed that I was using `'prefix' => false` in one of my configured routes, and changing this to `'prefix' => null` solved the issue, per the code changes I can see with this commit.

I'm curious though, should `Router::Url` and things that use `Router::Url`, such `HtmlHelper::link`, use `'prefix' => null` as well? The documentation for _prefix_ routing - https://book.cakephp.org/5/en/development/routing.html#prefix-routing (search for `// Leave a prefix` on the page) indicates that `prefix` should use `false` instead of `null`. I just want to be sure I'm setting `prefix` correctly when creating URLs (and per the commit here, `plugin` as well).
