### ISSUE TITLE
PaginatorHelper generates useless inline javascript 

### ISSUE THREAD

**Issue by michelgeny** [cakephp/cakephp#17933]
### Description

Hi
When using the links generated by the paginatorHelper to access the previous or next page of a collection of pages, the helper inserts an inline javascript onclick="return false;" in the link tag. This javascript seems to me to be of little use because the href attribute of the link contains an empty string and the button therefore has no action in this case. On the other hand, this inline script is not necessarily compatible with the user's CSP and generates a warning, which is certainly not serious but not useful either. Can you remove it?
Regards.
Mike

CakePHP Version 5

**Comment by dereuromark** [comment]
You are referring to https://github.com/cakephp/cakephp/blob/931fc16d80d16fbd910a83fabeacc30f3bb4dc8e/tests/TestCase/View/Helper/PaginatorHelperTest.php#L1095 I assume
Since those are links with empty string at least historically some browsers would have tried to follow that.
Maybe it is a relic of the past in the meantime.
