### ISSUE TITLE
Enum to string conversion in XML utility

### ISSUE THREAD

**Issue by marcdebus** [cakephp/cakephp#18016]
### Description

I’m getting the following error when parsing an enum to xml document:

“App\Model\Enum\MyEnum could not be converted to string”

It occures in this line (CakePHP 5.1.1):
CORE/src/Utility/Xml.php at line 344

`$child->appendChild(new DOMText((string)$value));`

Here is the example enum:

```
enum MyEnum: int
{
    case OFF = 0;
    case ON = 1;
    case ON_WITH_EXTENSION = 2;
}
```

When you try to add __toString() method to the enum, you get a fatal error:

“Fatal error: Enum App\Model\Enum\AutoAppointmentBooking cannot include magic method __toString”

### CakePHP Version

5.1.1

### PHP Version

8.3

**Comment by dereuromark** [comment]
Enums cannot implement this method.
But they also dont need to since you are not supposed to cast them to string. 
You should be using the value or label methods here in that case to translate them back to scalar.
See also
https://sandbox.dereuromark.de/sandbox/cake-examples/enums#serialization
Where this happens for JSON automatically.
Maybe we can also add an example for XML.

//edit I see that XML class internally could maybe fix this up.

**Comment by ADmad** [comment]
> When you try to add __toString() method to the enum, you get a fatal error

That's a PHP limitation, not CakePHP's.

**Comment by dereuromark** [comment]
I would actually say we should fix this up, as we do also for all other parts of the system now using enum.
It is an easy fix in the end.

**Comment by dereuromark** [comment]
PR open.

**Comment by dereuromark** [comment]
Quickest release ever: 5.1.2 contains it.

I also updated the sandbox to showcase it in real life:
https://sandbox.dereuromark.de/sandbox/cake-examples/enums#xml

**Comment by marcdebus** [comment]
Thank you for that quick release! :-)
