### ISSUE TITLE
3.0 RFC: Transaction Isolation Level Abstraction

### ISSUE THREAD

**Issue by ionas** [cakephp/cakephp#3136]
When using regular ```find()``` shortly followed by ```save()``` data might have changed in-between.

One option to counter this in some cases is to use ```updateAll()``` (atomic saves having conditions specified). Having a ```save()``` taking an optional ```'conditions'``` option may be an idea. Some DBA's might not support required Isolation Levels, so this might work for some cases.

The other way to counter this, as recommended on IRC, is to set the Isolation Level on the DataSource and then use SQL Transactions. Now http://book.cakephp.org/2.0/en/models/transactions.html does not mention the Isolation Level. I assume you can set it through ```Model::query()``` in 2.x.

Aside the optional ```'conditions'``` for ```save()``` two things might be improvable:

A.) The docs around ```save*()``` should mention that ```find()``` + ```save()``` does not handle possible race-conditions and point to the book's chapter on using transactions in cakephp. The docs around ```updateAll()``` should point there as well. The chapter about transactions should have a small paragraph around isolation levels, also linking to maybe, wikipedia's entry on database isolation levels: http://en.wikipedia.org/wiki/Isolation_%28database_systems%29#Isolation_levels

B.) There should be a way to get and set the Isolation level for the DataSource e.g.:
```php
$DataSource->isolationLevel('SERIALIZABLE'); // set isolationLevel for the Datasource to SERIALIZABLE
$DataSource->isolationLevel(); // get isolationLevel for the Datasource;
```

As a setter ```isolationLevel()``` should supply an abstraction across MySQL (InnoDB), MS SQLServer, PostGreSQL mapping a predefinded list of possible Isolation levels to the specific DBMS calls. If an equivalent IsolationLevel is not specified/possible, it should return ```false``` else it should return true.

Optional: A 2nd param could be set (```$options```) - the first option I can think of is SESSION vs GLOBAL (at least MySQL) supports that - where the isolationLevel is set GLOBAL or for the current SESSION only. Not sure if this is a good idea though.

As a getter (if no parameters are specified) it should simply return the current isolation level (per default specified by the DataSource's implementation) - maybe it should return an array which reports cake's isolation key as well as the internal isolation call executed and maybe also if it is a SESSION or GLOBAL setting (see below).

I can take care about the documentation changes, see point A.) (have to figure it out a bit, last time I worked on the book it had a web interface).

**Comment by half2me** [comment]
Any news on this? Just recently I decided to change the datasource for my test database to make my unit tests run faster. After I changed to in-memory sqlite, I immediately found that I had used MySQL specific code when I set the transaction isolation level. I would really prefer to abstract that out, instead of checking each time if the database is mysql or not... I really like @markstory 's idea. Is was just asking about the status of this, has any work been done, is there something I can do to help?

**Comment by lorenzo** [comment]
No work on this has been done, do you want to help? I can guide you through it

**Comment by half2me** [comment]
Well I have an application which extensively uses multiple isolation levels. I have used MySQL so far, but would like to have testing with Sqlite in-mem, and am thinking of migratiing to Postgres. :) So I would like to abstract as much of that out as possible.

So I could give it a shot sure :)

**Comment by berarma** [comment]
I've created issue #8899 because not only is this needed for portability but it's already overlooked in the `Table::save()` method when saving entities with multi-column primary keys.

The method proposed by @markstory and @lorenzo would be very useful, it would also allow fixing #8899 without the user having to know about isolation levels.

I think having a connection setting in the configuration files could be useful too, in case I want to use different isolation levels for different apps/databases.

**Comment by half2me** [comment]
@lorenzo I really need this functionality. I'd be glad to pitch in and help with this.

**Comment by lorenzo** [comment]
@half2me sure, you can just go ahead and do it :)

**Comment by lorenzo** [comment]
@half2me this should be the new API https://github.com/cakephp/cakephp/issues/3136#issuecomment-68341179

**Comment by half2me** [comment]
@lorenzo I agree with your API, also could I recommend what @Thuetar suggested, to have a default value in the config, and use that if nothing else is specified?

**Comment by Laykou** [comment]
Hi all, just a note from another developer: I worked on the use-case where I needed to select some data from database, do some calculation and save it. And when this happens in multi thread (multiple PHP web page requests) there always must be only one instance running at the time.

I tried it with the SERIALIZABLE transaction isolation level, but according to the Postgres definition this will fail every transaction but the first one. I needed some mechanism that would do the lock-wait function.

I eneded up with using: `LOCK TABLE barcodes IN SHARE ROW EXCLUSIVE MODE` which will lock the users table until COMMIT of transaction and the `SHARE ROW EXCLUSIVE` was the best I could found for postgres: https://www.postgresql.org/docs/9.1/static/explicit-locking.html

My code looks like:
```
$this->Barcodes->connection()->transactional(function () use ($barcode, $barcodeType) {
    $this->Barcodes->connection()->execute("LOCK TABLE barcodes IN SHARE ROW EXCLUSIVE MODE");

    $barcode->barcode = $barcodeType->nextBarcode();
    $saved = $this->Barcodes->save($barcode, ['atomic' => false]);
});
```

In `nextBarcode()` I do the select from database for the last barcode and increase it by one (this needs to be done in PHP as it contains strings as well).

This for me the most common use-case I can also find. PHP working in multi-threads is fine, but sometime developer needs to ensure there is only one job being executed at a time - e.g. in this case, when the app is incrementing the barcodes so that it does not happen there are duplicates.

Maybe something general like:
```
$this->Barcodes->connection()->transactional(function () use ($barcode, $barcodeType) {
    $this->Barcodes->connection()->singleThread();

    // Do some stuff here
});
```

where the `singleThread()` (or we can call it `excluiveLock()`) would do the same logic across different connections.
Or if there would be any mechanism directly in PHP for this, that would be greate. What do you think,@lorenzo @markstory ?

**Comment by markstory** [comment]
Where would you see the runSingleThread() method living? Offering mutexes could be useful and seems like something we could offer as a plugin/standalone library.

**Comment by lorenzo** [comment]
The nextBarCode() thing sounds like it could be done by drawing values from a sequence in Postgres instead of reading and then inserting. That way the complexity of the locking decreases drastically

**Comment by markstory** [comment]
Building a mutex that works across multiple hosts will require an external datastore that supports atomic operations. I am not sure that is the kind of thing that velongs in CakePHP on second thought.
