### ISSUE TITLE
3.0 Implement connection prefix

### ISSUE THREAD

**Issue by quickapps** [cakephp/cakephp#4118]
The "prefix" option does not seems to work properly, I think the [problem is on](https://github.com/quickapps/cakephp/commit/40ed2c498d1b8c74311e5043d321a5039ddd2d77) `\Cake\ORM\Table::table()`

**Comment by snelweg** [comment]
I will wait for 3.1 then. Do you guys even use this stuff yourselves?

**Comment by AD7six** [comment]
> I will wait for 3.1 then. 

Unless someone implements it, it won't exist in 3.1 either.

> Do you guys even use this stuff yourselves?

Connection prefixes? I don't. Don't think anyone else does either (otherwise, they/we would implement it as something needed).

I recommend you try [jose's suggestion](https://github.com/cakephp/cakephp/pull/4505#issuecomment-76154855).

**Comment by markstory** [comment]
@snelweg I have never used any form of connection/table prefixing, as I find making additional databases is much easier, safer and logical for me.

**Comment by snelweg** [comment]
@AD7six @markstory I primarily use Cake for existing databases, such as Prestashop or Wordpress. With Cake I used to be able to deliver a very fast 'dummy' application to my customers. I can not imagine that all the Cake users start from scratch and develop their own database structures. That we used to be able to use Cake in scenarios with an existing database structure, was one of Cakes major advantages. That this is no longer possible makes Cake a lot less flexible and in mu opinion you will lose a lot of developers.
It would be worth the effort to make the tablePrefix usable again with this great new CakePhp 3.0 version.
Just my 2c

**Comment by AD7six** [comment]
> That this is no longer possible

@snelweg [this doesn't work?](https://github.com/cakephp/cakephp/pull/4505#issuecomment-76154855) - What happens?

**Comment by snelweg** [comment]
@AD7six it al revolves around use Bake, that does not work anymore when using database tables with a prefix. All the automagical goodies stop functioning.
Wish there was a fix for this.

**Comment by AD7six** [comment]
@snelweg this ticket isn't about bake, and there aren't any tickets saying it's a problem. If it's a big deal for you: Time to step up to the plate I think =).

**Comment by snelweg** [comment]
Found the solution!
We dumped Cake and are using Laravel now. The Laravel people do keep their software usable for a lot of people and still maintain all the proper PSR's.
We used Cake for 2 years now, it became more and more unusable through time.
Anyway, good luck (and try to focus a lot more on your users, else everybody will run away from Cake)

**Comment by lorenzo** [comment]
@snelweg Thanks for the advice :)

**Comment by mtkocak** [comment]
I think this is the best solution, I guess their official back company is
not transphobic too.

2015-03-04 13:01 GMT+01:00 Ton <notifications@github.com>:

**Comment by markstory** [comment]
@snelweg Sorry to hear we weren't able to help you out. I'm happy to hear you found a solution that works for you. Unfortunately we haven't had time to implement table prefixes yet and the attempts so far haven't resulted in a holistic solution I'm comfortable shipping. The solution in 2.x was pretty leaky and incomplete, from reading laravel's code it doesn't look like they have completely solved the problem either.

@mtkocak I know you've had some bad experiences with CakeDC, but please keep in mind that CakeDC and the CakePHP project are entirely separate groups of people, and I hope your experiences with us haven't been as negative.

**Comment by jhli** [comment]
To rephrase markatory, I did as well think that table prefixes are there only cause of shared hosting environments, but when designing a set of ecommerce croogo (cake 2) plugins I considered to use them to avoid clashes.

We got php 5 namespaces now and cake pluhins. This allows the same table class in multiple places in cake3 but will by default use one and the same database.

prefixes can be used to namespace common model tables or to do prefixed revisioning etc.

I did tinker with bake and prefixes and ended up switching around the prefix on the connection and/or appmodel between baking and other use cases cause it is not holistic in cake2 ... dropping prefixes in the end until I have table colossions.

I'd love to see prefixes on connection level overwiteable within table / apptable / plugin app table initialize() respected throughout associations, querybuilder, joins, etc!

**Comment by markstory** [comment]
The desire to have both table and connection prefixes is one of the reasons I'd prefer to find out more about how people use prefixes before charging ahead with an implementation. They seem to solve different problems, and I'd really prefer to avoid implementing both connection and table prefixes as there is significant overlap in naming and possible use case scenarios.

If/when CakePHP gets prefixes it will likely be either table prefixes or connection prefixes, but not both.

**Comment by ionas** [comment]
Well for my use cases AppTable/Plugin AppTable prefixes are sufficient I think.
But for database revisions global prefixes might be an option... 
Connection prefixes really don't help with heavily pluralized apps like CMS frameworks (croogo, quickapps, etc)

**Comment by markstory** [comment]
Ok, but table prefixes are pretty easy to support/use today. Couldn't one use the `table()` method in the table classes' `initialize()` method to add the prefix?

**Comment by ionas** [comment]
Would it be enough to build a hack around table() within initialize() and build some AppTable class per plugin to insert prefixes, in current cake 3 rc2?

**Comment by rchavik** [comment]
I dislike table prefixes. I once dropped a `users` table because I forgot to configure the table prefix.

 I prefer to have it manually configured by devs.

**Comment by jhli** [comment]
So for instance in croogo if a plugin of mine features a products or users table and I want to use bake and Myplugin.Product etc. how would that work?

**Comment by zoghal** [comment]
i like table prefixes for plugin.
i think this   must adding a rules for Conventions plugin. 
example  the prefixes can very help  for uses database migrations  in plugin.

**Comment by Schlaefer** [comment]
> I once dropped a users table because I forgot to configure the table prefix.

I lost a minor production database with Cake 3 because a certain someone :innocent: did a copy paste error and set production and test to the same DB. `test_` prefix of Cake 2 would have saved the day.

Imho prefixes are still handy when there's only a limited number databases available. Not everyone wants to run a server and table prefixes are really helpful on shared hosting. It's not the the only feature I miss in Cake 3 so far.

**Comment by markstory** [comment]
I would like to avoid having both connection and table prefixes. Having both in 2.x was a big pain in terms of maintenance, and to this day I am not confident it all works properly.

@Schlaefer I usually avoid that by not having a test config in prod setups. Then the tests don't run :)

**Comment by HavokInspiration** [comment]
So basically, where does this leave us ?
Should I still work on implementing this on the Connection level ?
The implementation on #4505 is out of date, but the one on my fork (there's a pull request open if you want to check it out) is almost near completion. I currently have failing tests since the last rebase I did (2 weeks ago I think), but I haven't had the chance to look into it. After that I will have to do some polishing and clean up.
I was waiting to have something more polished than #4505 before submitting it.

The new implementation works with two main classes : a ``TableNameAwareTrait`` that implements specific methods to prefix strings and test if prefixing is needed. The second one is the ``TableNamePrefixer`` that works the same as the ``IdentifierQuoter``.
The other code modifications are to add prefixing action on Schema reflection, Database and ORM ``Table`` name configurations, and things such as that.
I also integrated the tests within the DatabaseSuite tests suite, where the entire Database and ORM classes are tested with prefix (with and without identifiers quoting).

It would work quite transparently. Just add the "prefix" key to your Connection object configuration with your prefix, and any query made with this Connection object will prefix table names.
It also allows Fixtures to be generated with a prefix (meaning that if your test Connection object has a prefix in its configuration, your test tables will be created with a prefix).

As for the two main questions the recent discussions brought :

**bake**
The implementation should not have any problem working with bake. Some modifications would be needed within bake (filtering the potential model by table names starting with the prefix and trim the prefix when class names are to be generated), but that **should** be fairly easy to implement (please note the emphasis on "should", I haven't started looking)

**plugins**
This is the one thing that's bothering me. I haven't had the chance to gave this a deep thinking, but I don't really know how this case would be handled... That would incompatible. Except by forcing to have a Connection configuration for each plugin, but that would be silly.

Or maybe having something like this in the Connection configuration :

```php
'default' => [
    'className' => 'Cake\Database\Connection',
    'driver' => 'Cake\Database\Driver\Mysql',
    //...
    'prefix' => [
        'app' => 'prefix_',
        'MyPlugin' => 'mypluginprefix_'
    ]
]
```
where ``app`` would be the one for the app, and ``MyPlugin`` the one for a specific plugin, etc. That might be something doable... Without having it on both Connection and Table level.
And if it is a string, it would be considered the app one.
This is just off the top of my head, while typing, I don't really know if that seems reasonnable or really doable.

So... That's where I am.
Should I still work on my implementation ? Has a decision been made on this ? 
Side note : I already tried (with the implementation of #4505) to convert this into a plugin which would avoid to add more complexity to the core, but failed as there was too much things to override. Since the new version is a bit more simpler, this might be doable. I can give it a shot if it can help.

**Comment by ionas** [comment]
I think on base of AppTable / Table it is very easy to go back and implement it on per connection (e.g. when you switch around connections, switch around AppTable public tablePrefix)... so that's a lot more flexible, isn't it?

**Comment by markstory** [comment]
@HavokInspiration I don't think a decision has been made unfortunately. From what I've heard here and in other issues some people want connection prefixes for dealing with shared hosting environments, and interoperability with applications like wordpress. Others want per model prefixes for so they can namespace their database tables per plugin.

I personally have no horse in this race, but would hate to implement one approach and find out we should have built the other approach. From the outside it would seem that connection prefixes allow you to solve both the table prefix and plugin situation by using additional connections. (I could be very wrong here though).

**Comment by ionas** [comment]
OT: Do plugins (in 3.0) support their own connections? E.g. can the issue be encapsulated at plugin level?

**Comment by ADmad** [comment]
> From the outside it would seem that connection prefixes allow you to solve both the table prefix and plugin situation by using additional connections. (I could be very wrong here though).

I agree with this. One can just create a new connection for plugin with required prefix. So my vote goes to connection prefix.

**Comment by ADmad** [comment]
> OT: Do plugins (in 3.0) support their own connections? E.g. can the issue be encapsulated at plugin level?

No

**Comment by ionas** [comment]
Personally I don't see much need to support shared hosts (hosting is cheap, development is expensive), while at the same time I see quite a lot of need to be able to prefix tables of plugins to have them live side by side like namespaces and plugin prefixes allow in php/cake world.

**Comment by mtkocak** [comment]
Dear All,

My problem is that, the "authake" plugin that I maintain was created using
table prefix. That was also useful to prevent naming clashes on the
database. Ie. I was using $this->users var but on the database that was
named authake_users. If there is some other method, (Yeah I am aware of
namespaces) on the database level it's ok, but I feel using
$this->authake_users is not so chic. Love you all

2015-03-17 10:48 GMT+01:00 Jonas <notifications@github.com>:

**Comment by ADmad** [comment]
@ionas I don't think we can be elitist and ignore shared hostings :)

**Comment by markstory** [comment]
If we went down the road of per-table prefixes it could be implemented as a method on the table class.

```php
abstract class AuthakeTable extends \Cake\ORM\Table {
  public function tablePrefix()
  {
    return 'authake_';
  }
}

class UsersTable extends AuthakeTable
{
}
```
This kind of approach allows 'application' prefixes, and per-plugin prefixes without defining additional connections. Fixtures could have a similar method. Perhaps trying to transparently handle fixtures and manual queries in the prefix implementation was a mistake?

**Comment by ionas** [comment]
@ADmad I don't think shared hosting should have a higher preference than making sure plugins run smooth side by side without additional hackery and "same" table names.

The abstract class AuthakeAppTable makes sense, but is this supported across the whole ORM (joins, etc) and cake bake?

**Comment by markstory** [comment]
@ionas It could be supported by bake. I don't think it would be supported by manually brewed queries, or in places where someone uses one of the join() methods on the query builder.

**Comment by ionas** [comment]
So the table name is not gotten by asking TableClass::tableName() ?

**Comment by mtkocak** [comment]
Can't be some piece of software like Inflector class to, maybe an Alias
class, using come configuration or a transform.ini to tranform a name like
authake_users to users app wide? By the way I am not sure something like
that increases inner request time and creates extra load. Also forgive my
ignorance if this is a very improper advice.

2015-03-17 15:44 GMT+01:00 Mark Story <notifications@github.com>:

**Comment by markstory** [comment]
@mtkocak That might be possible, if you only wanted one alias for users. From previous discussions it sounds like people want to have multiple classes named Users each going to a different prefixed table. In this scenario a config file and global mapping probably wouldn't work.

**Comment by HavokInspiration** [comment]
@markstory
> I personally have no horse in this race, but would hate to implement one approach and find out we should have built the other approach.

That's what I would like to avoid too.

> Perhaps trying to transparently handle fixtures and manual queries in the prefix implementation was a mistake?

Perhaps. It sounded like the more logical approach though. Less code within the app and full coverage whenever a query had to be made, whatever the way (except for raw SQL but that seems obvious).
But if that does not comply to what people expects, it indeed might not be the right way.

**Comment by ionas** [comment]
For comparison, table prefixes in rails:
General: http://apidock.com/rails/ActiveRecord/Base/table_name_prefix/class
Engines: http://stackoverflow.com/questions/19435214/rails-mountable-engine-with-isolate-namespace-but-without-prefixed-namespace-on (e.g. here the question is otherway around, per default rails engines prefix all their table names, as it seems)

**Comment by markstory** [comment]
@ionas Do you happen to know if that also applies to fixtures?

**Comment by icaroscherma** [comment]
Sorry if it seems kind of dumb... I read this page yesterday and today...
I was looking for table prefixes as a way to identify in the database itself which Module is using it.
I am developing a PSA (Professional Services Automation) software and I am doing it modular because I want to reuse the code and to keep the maintenance easier. I was thinking of doing like:
Financial Module -> Invoices table (fin_invoices), and things like login, profile which is from the main app I would leave without a prefix or with a "main_"... Is this a bad coding action? Would it be fine with just changing table name in  the model?
I only developed systems for small companies, like Real State Management, Restaurant Management, and the systems always were customized for them, with no reuse other than my knowledge and I'm looking to improve the way that I code by doing a "general" system that I can customize a bit (the database, layout ...) and what the client asks me to do.

**Comment by markstory** [comment]
@icaroscherma Unless you are reusing table names, or sharing a database with other applications, I personally don't think that prefixes add much value.

**Comment by icaroscherma** [comment]
@markstory I followed your advice and separated the project in different databases and yeah, seems more safe now. But I don't know if it is a bug, but when I use the bake command with the "--connection" parameter it starts baking but then stops saying that the table is not found in the default database, then I open the Model, add the `public static function defaultConnectionName()` and re-enter the same bake command to works. Isn't the Bake to be working based in the "--connection" parameter?

**Comment by jadb** [comment]
@icaroscherma - it is. Please submit an issue on the [cakephp/bake](/cakephp/bake) plugin repo.

**Comment by icaroscherma** [comment]
@jadb Done: cakephp/bake#63  =)

**Comment by burzum** [comment]
I'm the situation that I finally need to apply this prefix story because of a legacy app. So what's the status of this? When I want to bake my code for the old DB that uses a prefix, how can I tell bake and cake to use that prefix? I don't want to end up with everything in my app being prefix by `ho_`?

The way I see it for this situation is this: Let's modify bake to support --db-prefix. --db-prefix will make bake aware to use the prefix, for example my `ho_`. But bake won't use it in the generated code then. Bake will create the table() call with the prefix then but ignore it everywhere else. Sounds fine?

**Comment by snelweg** [comment]
I found the solution. I switched over with all my projects to YII, works great.

**Comment by burzum** [comment]
@snelweg :fish:

**Comment by vnt** [comment]
I hope that the team of CakePHP, insert management table prefix. Why without  tablePrefix I can not do the upgrade.

**Comment by dereuromark** [comment]
vnt: Why cant you upgrade? You can just remove the prefix from all tables for example.

**Comment by snelweg** [comment]
"You can just remove the prefix from all tables for example."

@dereuromark Are you serious in asking that?

**Comment by dereuromark** [comment]
That is not asking, that is proposing, and yes, this would need a few seconds of time (depending on the DB size).

**Comment by snelweg** [comment]
Ok, that's it. I had it with Cake. 
You people live in another world then the real world.

**Comment by mtkocak** [comment]
why we dont want to implement that? breaks some cconvention?

30 Haziran 2015 Salı tarihinde, Mark S. <notifications@github.com> yazdı:

**Comment by lorenzo** [comment]
@snelweg forgive my friend, he is very optimistic some times :D

On the other hand, @vnt how is this issue blocking your from upgrading? Have you seen all of the proposed solutions in this ticket?

**Comment by mtkocak** [comment]
what an attitude... there are some rules here and smart people to respect.
isnt it?

30 Haziran 2015 Salı tarihinde, Ton <notifications@github.com> yazdı:

**Comment by lorenzo** [comment]
@mtkocak because no one has had the motivation to finish a path for this. Most of the core team think it is a non-issue given how many different ways of solving the problem in an elegant way and with practically no lines of code we already have.

The only real problem that we can make better is making the bake tool trim prefixes if instructed. That would help a lot

**Comment by vnt** [comment]
I have two applications based on database prestashop PR_ and I can not remove the prefix.

**Comment by dereuromark** [comment]
@vnt 

And why does a simple `$this->table('PR_xyz')` not work for you then? To tell the Table class what your actual table including the prefix is?

**Comment by jhli** [comment]
@mtkocak well I share his view but this is OSS and if he did a sane PR and it got rejected THEN I would blame the devs BUT here @vnt you got several options:

- change the database table names
- write a wrapper around PDO
- PR for cake on connection level
- PR for cake on apptable/table level
- manually set table names in all table classes
- plead/beg a that some core contributer/dev does it
- pay a core dev or contributer to do it

I am sure you will find a way and I agree that for some prefixes are nice/required especially on shared hosts or integration with existing database backed apps.

**Comment by jhli** [comment]
@lorenzo so having a prefix method to read/write the prefix from an app table (irrelevant if derived from connection table or apptable) would really be cool. Cause that misses In cake2 I went without prefixes for a ton of croogo plugins' tables.

**Comment by mtkocak** [comment]
Actually I totally agree with this. It's seems similar to serialize some
object and save to database. A framework should be unaware of table names
or how persistence behaves . It was easy and good to use but, when we come
to use databases or persistence, prefixes are some kind of over specialized
thing. If we have another persistence layer without any database table
names, what is going to be? Or we should implement all table name rules
using some regexes or something? I think not. If you need some table
prefixes, with some relational databases using table names, someone can
implement special plugin for some special relational database, but if
mongodb? without any database tables, or any table names. No I don't think
this should be implemented at framework level. So you all are right.

2015-06-30 19:39 GMT+02:00 HT-Studios <notifications@github.com>:

**Comment by lorenzo** [comment]
@jhli You mean to change the prefix at run time? If not, wouldn't having a trait offering such method be as trivial as returning a property in the table class?

**Comment by vnt** [comment]
Ok, $this->table('PR_xyz') this works!
I have another question, if I want to create an application using Cake Bake, how do I manage the table prefixes? I do not want to see the prefix in my application!

**Comment by lorenzo** [comment]
@vnt as explained in this thread, that is a missing feature in bake. Maybe you want to help us implement it?

**Comment by vnt** [comment]
How can I do to help? I'm not a great expert!

**Comment by josephzidell** [comment]
@lorenzo My 2c is to document this as the 3.x way of doing prefixes, fix bake, and call it a day.

**Comment by vnt** [comment]
We can create a sponsorship for this feature? Who needs of this function for cake bake can make a donation?

**Comment by burzum** [comment]
[This solves it mostly for me](https://gist.github.com/burzum/3aaea92e13b70f66f514), except in bake. But it's easy to rename the files and class names.

The only thing you'll have to do this 

````php
class AppTable extends Table {
    use DbPrefixTrait;
}
``` 

This works fine with tests and you can keep the legacy `prefix` in the datasource config array.

The only issue with that are plugins that directly extend the Table class.

**Comment by ionas** [comment]
Had issues with this lately but a quick fix did not seem to be possible. If I get to setting up a PR, my suggested interfaces would be:
1. ```'table-prefix' => 'prefix_'``` optional hash key for ```app.php``` datasource configuration.
2. ```--datasource 'prefixed' ``` optional option for ```bake model``` and ```bake all```.
3. ```--table-prefix 'prefix_'``` optional option for ```bake model``` and ```bake all```.
4. ```--table-name 'table_name'``` optional table name that would point at a table where the model name supplied to ```bake model``` and ```bake all``` would specify the table and entity php class names - so that both things are decoupled.

Thus...
* Datasource ```'table-prefix'``` would assume the same table prefix for all the tables in the database if using that given data source configuration.
* The bake option ```--datasource 'prefixed'``` would allow specification of the data source to have one single and easy place to do table name prefixes or even switch databases.
* The bake option ```--table-prefix 'prefix_'``` would allow to specify a prefix for a single table. As you can easily chain multiple bake command calls in *nix re-baking is while respecting table prefixes on just a few tables is very easy.
* The ```--table-name 'table_name'``` is the most general approach at decoupling table names from php model/entity class names.

**Comment by burzum** [comment]
I've done some work on this.

* [Basic PR for Bake](https://github.com/cakephp/bake/pull/191)
* [Table Trait](https://gist.github.com/burzum/06a0037c7ad8bcaf3333)
* [Fixture Trait](https://gist.github.com/burzum/293b618bb2308f294d36)

Feel free to improve it and use it. Especially the bake PR.

**Comment by quimr** [comment]
Hi, burzum.

I am a beginner in PHP and CakePHP (only days) and i need you tell me where exactly which files should change to the code of "Table Trait" ou "Fixture Trait" work. The program is working but the tables will have a prefix when put on the server and need to know which files change and where to put the new files ... sorry, it is even very basic questions, but I appreciate any details you have patience to me through.

Thanks,

Marcos

**Comment by berarma** [comment]
I've worked with databases with prefixes and I haven't had any issue applying the simple solutions provided here. I just remove the prefixes or override the table names in the models. I guess the real issue comes when the prefix has to be dynamically configurable, but still nothing that couldn't be solved with a few lines of code, I guess.

Simply overriding the Table::table() method I can transform the table names in any way I want. Then I would stop using literal table names in manual queries and use Table::table() instead, not making any assumptions about table names.

This last step could be made easier by being able to use some placeholder wherever a table name could be used so that I could use the model name and it was later replaced by the actual table name, like "select * from {Users}". I don't know if that would be a real solution or how hard would it be to implement.

However it may be the new ORM is a huge improvement, with or without prefixes.

**Comment by alexsmonte** [comment]
We have a solution for prefixes? or we can come back to talk about it and find a solution ?

**Comment by lorenzo** [comment]
Check the previous answers, there are some options you can use today for implementing this.

**Comment by vnt** [comment]
Excuse me,
what is the official solution, to use the table prefix with Bake?

**Comment by lorenzo** [comment]
@vnt this is a good solution https://github.com/cakephp/cakephp/issues/4118#issuecomment-128700351

**Comment by lorenzo** [comment]
Sorry... I did not read the "Bake" part @vnt

There is no official solution for that. Ideally you would not have prefixes in your local database... I cannot think of a reason why that would be a good idea. Just don't use prefixes in your local database, use bake, and the enable prefixes in the server when you need to deploy, if you need prefixes

**Comment by alexsmonte** [comment]
Plugins to work very well, to identify the tables of a particular plugin Ex: prefix_categories

**Comment by lorenzo** [comment]
@alexsmonte The do this in your plugins:

```php
public function initialize(array $config = [])
{
    $this->table('my_plugin_categories');
}
```

No need for a generalise way of having global or per-plugin prefixes

**Comment by alexsmonte** [comment]
Applies to?

 $This-> belongsTo ('my_prefix_Categories', ['foreign key' => 'category_id', 'className' => 'Plugin.my_prefix_Categories']);

**Comment by lorenzo** [comment]
no, the `className` remains the same `className => Plugin.Categories`

**Comment by alexsmonte** [comment]
tks

**Comment by lorenzo** [comment]
Closing as plenty of good solutions have been shown already :)

**Comment by Ajithkumarpm** [comment]
uiuiii
