### ISSUE TITLE
Add function option to ConsoleOptionParser::addSubcommand()

### ISSUE THREAD

**Issue by bravo-kernel** [cakephp/cakephp#5145]
I am trying to implement the commonly used  subcommand "list" in my CakeShell but it does not seem possible atm due to :
- CakeShell::addSubcommand expecting a function corresponding to the $name parameter
- in this case it expects a list() function
- creating that list() function conflicts with the PHP reserved list() function

It would be great if an option could be passed to specify an alternative function (e.g. myList()). This way "list" could still be used as a subcommand without creating conflicts. Feels future-proof for other use-cases too.

I am willing to attempt a PR if I can get a pointer/confirmation that this is even desirable.

My current problem can be reproduced as follows:

```
<?php
namespace App\Shell;
use Cake\Console\Shell;

class SiteShell extends Shell {
    public function getOptionParser() {
        $parser = parent::getOptionParser();
        $parser->addSubcommand('list', [
            'help' => 'List all Nginx configuration files'
        ]);
        return $parser;
    }

    public function main() {
        $this->out('Running console with `cake site` command.');
    }

    public function list() {
        $this->out('Running console with `cake site list` command');
    }
}
```

**Comment by berarma** [comment]
When extensively using the shell to create semantically easy to remember subcommands it would desirable to be able to use reserved words. I'm resorting to using alternative names but it's weird sometimes.

An easy solution would be to use method names with the pattern doXXXX: doList(), doNew(),... I also like this because shell subcommand methods would be easily distinguishable from internal methods.

**Comment by dereuromark** [comment]
Or, if we ever rename controller actions to what other frameworks use, including a suffix Action: "indexAction", we could then also make the commands "listCommand".

This would also more clearly differentiate those actions and commands from other (protected) class methods.

**Comment by berarma** [comment]
Differentiating those methods by name isn't the goal, and it can be argued that it's a poor coding practice. I suggested it just because the way the current parser works, it's maybe the simplest approach using only inferred names (no new options).

Actually, I like @bravo-kernel suggestion, but @markstory's answer made me think it wasn't good to add a new option for this. I don't think I've really understood the question: "How would any new options work with inferred command names where there is no option parser step involved?".

In fact I tried using the "name" option (it's an internal one) and it almost did what I wanted but not fully. The subcommand name changed in the help text but everything else remained the same IIRC.

By the way, isn't the ConsoleOptionParser already some kind of router for shell commands? The only problem is that method names are hard-coded. Adding some flexibility in one way or another would already make good enough console routes without adding new components.

**Comment by markstory** [comment]
@berarma The ConsoleOptionParser is almost a router for shells. Full command paths are resolved by interacting with multiple option parsers.

I don't really understand my previous comment either, so perhaps the function aliasing won't be as troublesome as I had thought.

**Comment by dereuromark** [comment]
Due to accidental BC breaks ( https://github.com/cakephp/cakephp/pull/7883#issuecomment-181370693 ) I am still very much in favor of doing this the symfony (etc) way and suffix

- infoCommand: cake shellname info
- indexAction: /controller-name/index

Refs https://github.com/cakephp/cakephp/issues/4741 as mentioned above.

**Comment by dereuromark** [comment]
In light of https://github.com/cakephp/cakephp/issues/11137 : 
Does this change the scope of this? Can we maybe introduce some of the ideas already in 3.next?

**Comment by markstory** [comment]
With command classes, there won't *be* subcommands anymore. Nested commands are created by attaching commands to the collection with nested naming.

**Comment by dereuromark** [comment]
Then we can close this, but still have to revisit the issues around the commands and structuring/naming.
