### ISSUE TITLE
2.6 - Use 'include_once' instead of 'include' in App::load

### ISSUE THREAD

**Issue by vovkin** [cakephp/cakephp#5552]
I'm using namespaces for some of classes in model layer (I have kind of extended model layer with Model Utility and Model Services classes). And because **App::load** uses **include** for files including, when I run `cake i18n extract` I get next error for some of files which use namespaces, e.g.:

*Fatal error:  Cannot redeclare class App\Model\Service\ModelService*

After I changed **include** to **include_once** here
https://github.com/cakephp/cakephp/blob/master/lib/Cake/Core/App.php#L547
https://github.com/cakephp/cakephp/blob/master/lib/Cake/Core/App.php#L567

problem is gone.

I'm wonder if it's possible that you change **include** to **include_once**, not sure what is the reason to use **include** and hope it's possible to change.

Thanks.

**Comment by ionas** [comment]
Why is include being used over require?

**Comment by thaJeztah** [comment]
@ionas will `require` play nice with other AutoLoaders?

**Comment by markstory** [comment]
I am pretty sure we're using include as include_once is a bit slower in some versions of php.

**Comment by ravage84** [comment]
@markstory is this the only reason?
And if it is, do we know which versions of PHP are slower?
What market share do those versions have today?
If this leads to the conclusion that we are using ``include`` instead of ``include_once`` for a reason which is outdated/not relevant today, shouldn't we make use of this opportunity?

**Comment by dereuromark** [comment]
I am pretty sure include() insight a method usually makes more sense, as the scope/intension is a different than in bootstrap etc (which by definition is only called/included once).
If you use include_once() and call load() a second time it will most likely fail hard as the necessary/expected include doesn't happen, and the included PHP snippet is not available inside that function's body.

**Comment by markstory** [comment]
@dereuromark If you double load a file with a class definition you'll get a fatal error though, which is the original issue. I don't think App::load() can or should be used to load snippets of code.

**Comment by dereuromark** [comment]
Fair enough :) In this case it seems indeed to be smarter to use _once().

**Comment by jrbasso** [comment]
I agree with @markstory , the `App::load()` shouldn't be used for this case. Using `include_once` functions slow down the entire framework.

@vovkin That happens because your extended class has a `App::load()` call for the parent class? If so, why are you using `App::load()` instead of `App:uses()`?

**Comment by vovkin** [comment]
I don't use it directly. As I said in bug description, problem happens when I use i18n shell.
When I run `cake i18n extract` shell script tries to load all of classes of model layer to extract translation sources of validation errors, and right in this point it uses `include` and somehow error appears for classes with namespace (these classes placed in subfolders in *Model* folder, like *app/Model/Service/SomeService.php*).

The problem is that all this is part of core scripts, which I don't want to change and keep up to date with official CakePhp versions.

About `include_once`, is difference is really so noticeable comparing to `include`?

**Comment by dereuromark** [comment]
According to sources like https://robert.accettura.com/blog/2011/06/11/phps-include_once-is-insanely-expensive/ it is.
But I highly doubt that it makes any difference when using it only a few times per dispatching process.
So I would just change it to `*_once`.

**Comment by ionas** [comment]
What about doing it with a custom cake_include_once global function (like the link does)?

**Comment by markstory** [comment]
@dereuromark But App::load() is used to load _all_ the classes, so it will be called far more frequently than 'just a few times'.

**Comment by markstory** [comment]
Closing as the performance impact of include_once is measurable, and not something we can just change.

**Comment by garex** [comment]
Here are more adequate explain: https://web.archive.org/web/20080808221243/http://www.techyouruniverse.com/software/php-performance-tip-require-versus-require_once

But instead of just 'require'-ing can it be just checked on class existance?

Just `!isset(static::$_classMap[$className])` is not robust as class can be loaded outside this method or manually.
