### ISSUE TITLE
Require PHP 5.5 as minimum version

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#5602]
PHP 5.4 will receive no more support after June this year as version 5.5 was released almost 2 years ago. I'm not sure how the landscape of hosting providers will look like in 6 months, but I think we should start making a decision for the next milestone or two.

As an important decision factor, Symfony 3, which is due in October of this year, will also be requiring 5.5 as a minimum.

**Comment by sikker** [comment]
There was a ticket a while back about not hard-requiring ext-intl (and
suggesting symfony/intl as a fallback on the install page) to support
shitty 5.4 hosts. I don't really know how that all went, but just in case
that went through I'm mentioning it that it may be reversed if 5.5 does
indeed become the minimum requirement.

**Comment by dereuromark** [comment]
+1 for raising it to php5.5 with 3.1 or 3.2. It's time CakePHP is not left behind ever again but instead plays a key role again in cutting edge PHP framework technology.

**Comment by thaJeztah** [comment]
+1 for PHP 5.5. Although some of our servers are still on PHP 5.4, we need to push things forward, otherwise we're stuck with 5.4 until CakePHP 4.

^^ perhaps a roadmap should be created, stating up front that CakePHP 3.x will no longer support a specific version of PHP, based on the PHP end of support dates; http://php.net/supported-versions.php

**Comment by markstory** [comment]
Going to PHP5.5 as a recommended minimum makes sense to me. Currently the code is still compatible with 5.4, which is something I think is worth keeping as that is what we have very broadly communicated. It will feel like a bit of bait and switch if we suddenly start requiring php5.5 now.

**Comment by lorenzo** [comment]
@markstory I meant for one of the next point releases, 3.0.x should definitely still support 5.4

**Comment by thaJeztah** [comment]
Fwiw, I'm fine with 5.4 for 3.0.x, as long as the option stays open to change the requirements for 3.x ( and we're not stuck until Cake 4) :smile:

**Comment by bcrowe** [comment]
If anyone is curious about the PHP's shared-hosting/PaaS support landscape, this is a new thing to check out: http://phpversions.info/

**Comment by thaJeztah** [comment]
Interesting list. It really is a chicken and egg situation; providers don't upgrade in fear of breaking client's websites, clients don't upgrade their code because the provider doesn't yet support it.

Seriously though, providers offering 5.2/5.3 as a **default**? As a custom option, ok, fair, but as *default*. That's ridiculous. Feels like Internet Explorer 6 all over again.

**Comment by andtxr** [comment]
+1 for PHP 5.5 as minimum requirement for the next version update, ex 3.1. Due the proximity of the 3.0 stable release. @bcrowe pointed something important. I feel a little bit worried about shared hosting companies implementation speed and how it can harm less advanced PHP / CakePHP developers reducing its range of tools.

**Comment by thaJeztah** [comment]
@andtxr there's still Cake 2.x for the time being. IMO if a provider only offers an insecure, un-maintained hosting package, it's time to switch provider.

**Comment by dereuromark** [comment]
@andtxr The CakePHP min. requirements so far, as probably well in the future, mainly rather aline with the EOL times of each PHP version (kind of the "absolute minimum") and not the newest ones. (Shared) hosting companies that cannot comply with that should not be in business IMO - not only for security reasons (EOL also means no security patches anymore for those PHP versions).
It is worth spending a few bucks more per month to have at least that minimum requirement. It's really not that hard :)

**Comment by josegonzalez** [comment]
Fine, PHP 7 for next release? :P

**Comment by thaJeztah** [comment]
Next release will CakePHP 360? Or CakePHP Vista :smile:

**Comment by dakota** [comment]
@thaJeztah No, next version will be _CakePHP Black Forest_, or _Lemon Cheese CakePHP_

I'm :+1: for the next release being 5.5+ (Whether that is 3.1, or 4.0 doesn't matter too much)

**Comment by thaJeztah** [comment]
+1 on *recomending* PHP 5.5/5.6 now (for best practice and performance) and *requiring* 5.4 as minimum for CakePHP 3.0.x

**Comment by ravage84** [comment]
I like @dereuromark's idea that CakePHP's minimun requirement should align with PHP's EOL dates.

- PHP 5.4 supported until September 2015
- PHP 5.5 supported until June 2016
- PHP 5.6 supported until August 2017

How about we "deprecate" the support every time over at least two minor releases (still aligned to PHP's EOL dates by + 6 months)?

This *could* loiok like this, *for example*:
- CakePHP 3.0 minum: 5.4, recommended 5.4
- CakePHP 3.1 minimum 5.4, recommended 5.5
- CakePHP 3.2 minimum 5.5, recommended 5.5 (e.g. 6 month after 5.4 EOL)
- CakePHP 3.3 minimum 5.5, recommended 5.6
- CakePHP 3.4 minimum 5.6, recommended 5.6 (e.g. 6 month 5.5 EOL)
- CakePHP 3.5 minimum 5.6, recommended 5.6
- CakePHP 4.0 minimum 7.0, recommended 7.0 (major releases are freed from this rule)

In any way, we should
a) plan this now
b) communicate it as early as possible and
c) stay true to this plan.

People using CakePHP should be able to understand the supported PHP version roadmap and should be able to plan accordingly. One thing we don't want is them loosing trust into CakePHP because they can't plan with it.

As a framework we should go forward and be an example when it comes to good practices. And supporting an EOLed PHP version for the sake of "not leaving anybody behind" is not a good reason enough.

http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html

Yes not supprting an EOLed PHP version in a minior CakePHP release could mean some people can't upgrade to the next minor 3.x release. But it does not have to mean we have to include any API breaking changes. So we still stay true to the SemVer rule 
> MAJOR version when you make incompatible API changes,

And last but not least, yes version numbers are cheap but that does not mean we should play along in this ridiculous numbers game. And I would not trust a framework that does so. Also, a web application framework is no end user client application.
That **does not mean** we should wait years for the next major CakePHP version, but please be reasonable and keep a **major release** alive at least two years or something like that... Again, people want to have some planning certainty with a CakePHP version.

**Comment by thaJeztah** [comment]
@ravage84 +100. I think your post *exactly* echoes my thoughts! One "nit"; why not *recommend* PHP 5.5/5.6 already with 3.0? Recommending something shouldn't be a problem right?

**Comment by ceeram** [comment]
I am +1 on moving to 5.5 in a minor release. FWIW you can up php version
requirements without breaking semver.
Also people having require for cakephp as ~3.0 which would pull in all
bugfix and minor releases would not break their application when running
composer update. It simply will not install the minor cakephp release due
to missing requirement.

2015-01-08 13:02 GMT+01:00 Sebastiaan van Stijn <notifications@github.com>:

**Comment by kevinquinnyo** [comment]
I should also note (and this is critical) that all Fixture data for tests match as much as possible, the "Back to the Future Theme" that is currently implemented.  Example:

```php
<?php

namespace DeviceManager\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;

class DevicesFixture extends TestFixture
{
	public $import = [ 'table' => 'devices', 'connection' => 'inventory' ];

	public $records = [
		[
			// Time Machine Device
			'id' => '4',
			'asset_id' => null,
			'device_status_id' => null,
			'device_type_id' => null,
			'uuid' => '5819660a-2658-44d5-9c2a-c29ec23ba861',
			'parent_id' => null,
			'lft' => 1,
			'rght' => 4,
			'created' => '2015-01-06 17:30:00',
			'modified' => '2015-01-06 17:30:00',
			'name' => 'Time Machine',
			'description' => 'Allows for travel through time.'
		],
		[
			// Child Device
			'id' => '5',
			'asset_id' => null,
			'device_status_id' => null,
			'device_type_id' => null,
			'uuid' => 'c6443ee5-18b2-4137-9641-c938a0297791',
			'parent_id' => 4,
			'lft' => 2,
			'rght' => 3,
			'created' => '2015-01-06 17:31:00',
			'modified' => '2015-01-06 17:31:00',
			'name' => 'Flux Capacitor',
			'description' => 'Generates 1.21 Gigawatts'
		],
		
	];
}
```

**Comment by ionas** [comment]
I think 5.5 for 3.1 is pretty sane.

**Comment by markstory** [comment]
I did somw more thinking and reading (including zendframework/zf2#7095). Going to 5.5 for 3.1 or 3.2 is reasonable given we don't break any existing public APIs.

**Comment by burzum** [comment]
I agree with @markstory, if we've moving it up to 5.5 we should *already* start communicating this now in form of a comment in the roadmap or something and already put it in the 3.0 release notes or something.

**Comment by ionas** [comment]
Required: 5.4.x
Recommended: 5.5.x
?

**Comment by markstory** [comment]
@burzum I have added a wiki page for 3.1 and will update the issue milestone as well.

**Comment by TomasVotruba** [comment]
:+1:  for PHP 5.5, there `::class` really saves some time and typos

The stats from 2014/11 from composer might also help: http://seld.be/notes/my-view-of-php-version-adoption

**Comment by rchavik** [comment]
:-1: I prefer we bump up major version.

**Comment by ionas** [comment]
Personally I'd like to see 5.6 min-support as soon as required.
- It is there, available, stable, now.
- It will be there probably for ages, and is the real LTS considering the next version beyond is PHP 7. 
- php7/hhvm might drastically change things, again. The differences between 5.6, 5.5 and 5.4 ain't that big.
- If you core peeps like to utilize 5.5 or 5.6 features that make sense and can't because of minimum versions - then that's bad. If there is no need, why bump?

There are two ways to get cake to 5.5 or even 5.6.
- Either change how cake's versioning worked. Major versions are pretty stable and mostly BC and I like that. They are supported for years. BC does not imply that you need not upgrade your VM. It means you need not touch your app code (in any big/deep way).
- Or add it to some minor release, like 5.5 for 3.1

**Comment by markstory** [comment]
Moving to 'future'. We won't be changing the version requirements for 3.1, and we can revisit and discuss further when 3.2 comes around.

**Comment by rchavik** [comment]
Why not just bump-up to 4.x with PHP 5.5?

**Comment by ionas** [comment]
@rchavik my concern is if there are features in 5.5 or 5.6 that the core, especially ORM wants to use, I want to see them being used and not being delayed because of platform concerns. A the same time I loved how cakes major versions were supported for very long. If you just bump the version to 4.x BECAUSE of 5.5 this long term major version scheme will be broken. And then I don't see an increase in a required PHP version as an issue at all.

**Comment by ADmad** [comment]
Given that PHP 7 alpha 1 is already out we should be at least thinking of 5.6 not 5.5.

**Comment by dereuromark** [comment]
I agree, most "useful" OS like debian8 are also already shipped with PHP5.6 by default as of now. No one can complain he cannot run it unless he has a crappy provider.

**Comment by dakota** [comment]
Unfortunately most CakePHP (PHP in general) developers are using crappy providers and are not willing to switch, even if there are better providers for more or less the same cost.

**Comment by ADmad** [comment]
Not surprisingly even on centos 7 you need to use external repos to get php 5.6.

That said we won't bump the version till at least 3.2 which i think is at least 6 months away. So those who don't have 5.6 can just use cake 3.1 :)

**Comment by burzum** [comment]
@dakota I'm always for not going on bleeding edge versions because especially the big business moves slowly and prefers stability over fancy new versions. So do I as well.

But on the other side I don't see a reason to stick to 5.4 or 5.5 just because of some crappy developers or companies. It's not like 5.6 is a brand new version that was just released yesterday. The framework should keep an eye on being recognized as a professional tool for big enterprise class projects and not as a toy for some crappy devs. Actually I'm pretty amused how the usual suspects struggle with 3.0 because it applies more "advanced" concepts. :stuck_out_tongue: 

Announce now that Cake will go for 5.6 in roughly X month and people will have to to cry and update.

**Comment by ADmad** [comment]
> what's wrong with using external repos or compile it yourself?

Nothing, expect many web hosting providers might not. You are missing the point here. The issue is crappy webhosts not a server you control yourself. In which case one should just debian instead of centos :)

**Comment by burzum** [comment]
We could provide a list of cheap providers that offer 5.6 for example. I'm paying incredible expensive  $4/month for my VPS (https://www.vpscheap.net). A good but cheap host (https://ssl.planet-hosting.de) offers you php 5.6 for insane 1.49€/month. Seriously, I have to be rich to afford them!

If people want something cheaper screw them if it doesn't support 5.6. We could provide a list of providers that support 5.6. Or maybe we can make a deal with a provider and just recommend that one? Don't get stuck just because people want to stick with their crappy host, there *are* in fact cheap providers that support 5.6.

Other frameworks current versions require these php versions by the way:

* Laravel 5.5.9
* ZF 5.5
* SF2 5.3.9
* Yii 5.1.0

**Comment by ADmad** [comment]
> Yii 5.1.0

Classy :)

**Comment by lorenzo** [comment]
> Yii 5.1.0

Not true:
https://github.com/yiisoft/yii2/blob/master/composer.json#L59

**Comment by burzum** [comment]
@lorenzo Thanks, don't know from where I picked 5.1 up then... I've updated my previous post and linked the composer file.

**Comment by markstory** [comment]
>  what's wrong with using external repos or compile it yourself? That's normal and expected when using Linux, at least for me

I know that many big company IT departments won't use external package repos and will only pull in from suse's central repos for example. I know our friends at the dutch government had this exact issue.

**Comment by ADmad** [comment]
Those who can't strong arm their IT departments to upgrade can always keep using older cake version :smile:  Until now we have done a decent job providing fixes for any significant issues for older versions.

**Comment by kevinquinnyo** [comment]
As someone who works in the web hosting industry, my opinion is that this is really only a problem in shared hosting environments, which are dying out in favor of virtualization, containers, and cloud solutions.  There are even turn-key chroot-type solutions like cagefs/php-selector to run multiple php versions on a shared server these days, so the incompatibility issue is not as big as it used to be.  I also think web frameworks like Wordpress to a very large extent, and to a lesser extent frameworks like CakePHP and Laravel are actually pretty big drivers in moving the community toward new versions of php (which is a good thing).  Just my two cents if it's worth that.

**Comment by jhli** [comment]
I am using shared managed hosting for my small clients and 5.5/5.6 is no issue. The bigger clients run debian or red hat no prob and can basically decide what to use So :+1:

If there is need to make stuff easier for newbies there are other ways like virtual appliances, better cake bake styles, crud, web installers, prefixes working for bake and orm, cakeschool, etcetc.

**Comment by sebastienbarre** [comment]
Guys, sorry to piggy back on this thread, but could somebody tell me if the latest Cake 2.x (say 2.7) is fully compatible with PHP7? I saw somewhere that all 3.x tests were passing with PHP7, but couldn't find a similar statement for 2.x. Thanks.

**Comment by tanuck** [comment]
@sebastienbarre When I last tested it, which was around 6 weeks ago, 2.7 still had failing tests on php7. Compile one of the latest php7 release candidates and run the cake core test suite with it. Should give you a more up to date answer.

Regards

**Comment by sebastienbarre** [comment]
Thanks. I ultimately found the [Continuous Integration](https://travis-ci.org/cakephp/cakephp) page. Seems only 3.x is tested again PHP7. From the [branches](https://travis-ci.org/cakephp/cakephp/branches) page I see 2.x is tested against PHP 5.3 to 5.6 (see, for example, [this build](https://travis-ci.org/cakephp/cakephp/builds/87801567)). Would you guys (@markstory?) consider adding PHP7?

**Comment by dereuromark** [comment]
@sebastienbarre You could just add PHP7 yourself in your branch and see what happens when you let CI run.

**Comment by sebastienbarre** [comment]
@tanuck @dereuromark ok, will slowly get through it, see #7671 ; thanks.

**Comment by lorenzo** [comment]
Closing as this was decided as implemented already

**Comment by shridhar-patil** [comment]
Going to 5.5 is good but I had a situation where my client asked me to create cakephp 3.0 datasource for sql anywhere 16 . Sqlanywhere  does not have support for php 5.5, everything for the project just got stuck

**Comment by burzum** [comment]
@shridhar-patil a *really quick* search on Google shows that the sources for 5.6 are available. Download them and compile the php module.

**Comment by dereuromark** [comment]
But that is an Sqlanywhere (or any tool for that matter) issue, not a framework one.
Please consult with them and make sure they fix their things.

It is (IMO) inacceptable for such a tool - if still under development - not to provide current PHP support.
It is even vital for security, as PHP 5.4 is already EOL and should not even be used anymore anywhere, that includes your current production servers for the status quo app.
See http://php.net/supported-versions.php - even 5.5 should at this point not be used anymore for obvious reasons.
Maybe that tool is then not the right one if they do not care enough to support PHP5.6+ in a reasonable time-frame. Usually the changes involved are rather minor, especially inside the same major PHP version.

**Comment by inoas** [comment]
@shridhar-patil just pickup 3.0 or 3.1 branch then. Getting proper hosting is not a problem, usually.

**Comment by shridhar-patil** [comment]
I just want to connect sqlanywhere 16 from php 5.5  and once I am connected I will write the cakephp 3.x sybase datasource for my client , hosting is not a problem for me
