### ISSUE TITLE
Console cake i18n extract hangs in vagrant

### ISSUE THREAD

**Issue by tersmitten** [cakephp/cakephp#5604]
We're having trouble using the i18n extract task in vagrant. It always hangs at:

```
Processing /var/www/oefenweb.dev/app/public_html/app/Vendor/cakephp/cakephp/lib/Cake/Test/Case/BasicsTest.php...
```

Using the task on a regular machine does not result in failure.

We're using cakephp 2.5.8, but the problem was already present in earlier versions.

**Comment by lorenzo** [comment]
I use vagrant as well and constantly extract messages. Why do you think the problem happens in your environment?

**Comment by tersmitten** [comment]
I think it has something to do with the size of our project. I added some (more) path to `--exclude` and now it does finish.

**Comment by lorenzo** [comment]
Could it be symlinks and that it is looping around them?

**Comment by alecho** [comment]
It takes a long time for the VM to scan shared directories, especially when using the VirtualBox provider. You're right to exclude directories that won't need messages extracted. If you're excluding directories with messages just to speed up the process you may want to invest in one of the other Vagrant provider options as they tend to be faster with shared files.

**Comment by tersmitten** [comment]
Could be, but then it must be in one of our excludes, because it is working now...

**Comment by tersmitten** [comment]
@alecho I know that shared folders a slow, but it does not finish at all.

**Comment by alecho** [comment]
@tersmitten How long have you let it run for? Just an example; I can run a test suite on my Mac in about 2.5 seconds while the same test suite in Vagrant will take 1.96 minutes. Disabling code coverage in the Vagrant VM will speed this up significantly because it's no longer traversing every directory to build the exclude list for the coverage report. I still think your message extraction will complete, it will just take a _very_ long time. What is the longest time you have let it run before killing it?

**Comment by markstory** [comment]
Since it _does_ finish with fewer files, I suspect this is just a matter of not enough CPU/IO on the VM.

**Comment by tersmitten** [comment]
Probably, but it is a pretty heavy vm: 2GB RAM, 2 CPU cores (i7-2600 CPU @ 3.40GHz)

**Comment by tersmitten** [comment]
Thanks, I will look into it.
