### ISSUE TITLE
3.0 - Session timeout not working

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/cakephp#5664]
Hi guys. I'm pretty sure this worked at some point, but setting the timeout in Session config has no (or seems to not have any) effect right now.

In my config:
```
'Session' => [
	'timeout' => 60
]
```

In `Cake\Network\Session::create`, my `$sessionConfig` becomes:
```
Array
(
    [timeout] => 60
    [defaults] => php
    [cookiePath] => /cms/
)
```

When logging in on my cms, the set-cookie is:
```
Set-Cookie:CAKEPHP=fc9361ad8974ca167dff8d786bdc0a08; path=/cms/; HttpOnly
```

The reason I think this is more a bug than my config being wrong is that other keys work, I can do this:

```
'Session' => [
	'ini' => [
            'session.cookie_lifetime' => 60
        ]
]
...
```

And then my cookie is this, which reflects the timeout
```
Set-Cookie:CAKEPHP=78f3a8756ed5408497c28dc6a3912aed; expires=Wed, 14-Jan-2015 16:36:19 GMT; Max-Age=60; path=/cms/
```

**Comment by dereuromark** [comment]
'timeout' != `cookieTimeout` afaik. Did you try the latter? The first is usually a relative value, the second one an absolute one.

**Comment by patrickconroy** [comment]
Yeah I tried that one as well. No permutation of using both/either of these seems to work..

```
'Session' => [
	'timeout' => 62,
	'cookieTimeout' => 61
]
```

**Comment by markstory** [comment]
I can take a look, this _did_ work at some point.

**Comment by lorenzo** [comment]
What exactly is not working @patrickconroy? CakePHP 3 does not change the cookieLifetime, that is your responsibility.

**Comment by lorenzo** [comment]
Also, there is no `cookieTimeout` setting

**Comment by patrickconroy** [comment]
Are the docs wrong, then? http://book.cakephp.org/3.0/en/development/sessions.html

**Comment by patrickconroy** [comment]
If the docs are right - then setting Session.timeout doesn't affect Session.cookieTimeout, and neither of those things affects the actual expiration of the session cookie.

**Comment by lorenzo** [comment]
The docs are wrong. The values that are accepted are:

```php
     * - defaults: either 'php', 'database', 'cache' or 'cake' as explained above.
     * - handler: An array containing the handler configuration
     * - ini: A list of php.ini directives to set before the session starts.
     * - timeout: The time in minutes the session should stay active
```

I will submit a PR to fix the docs

**Comment by patrickconroy** [comment]
Thanks @lorenzo, I'll use the ini for the cookie_lifetime.

**Comment by mneil** [comment]
Sorry if I'm overlooking something but I have not been able to get an authentication cookie to persist past the session. I've read the session docs, I've looked through the core and read Cake\Network\Session.

Using Redis, my Cache configuration looks like:

```
'Cache' => [
  'session' => [
    'className' => 'Redis',
    'duration' => '+1 days',
    'engine' => 'Redis',
    'port' => 6379,
    'timeout' => 1440,
    'prefix' => 'dev:session:',
    'persistent' => true,
    'server' => '127.0.0.1'
  ],
]
```

My session configuration:

```
'Session' => [
  'defaults' => 'cache',
  'handler' => [
    'config' => 'session'
  ],
  'timeout' => 1440,
  'cookie_lifetime' => 1440
],
```

I've added `cookie_lifetime` only because I cannot get timeout to have any affect. I can't find `cookie_lifetime` used anywhere in cake core either even though it's mentioned in the docs. 

I'm using version `3.0.15` which I just updated from `3.0.12` thinking that might be the cause. Not sure if this is an issue with the Redis cache implementation for sessions, if my ini settings still need to be configured even though I'm using Redis, or if I'm just misunderstanding entirely?

But, no matter what I've tried my CAKEPHP cookie always have an `Expires/Max-Age` value of "session" in Chrome resource panel. In Cake 2 that cookie could persist for days by setting timeout.

I've also tried moving the timeout inside the handler property as well as setting the value directly using the Configure static class. 

Session::renew() explicitly defines the timeout
```
setcookie(
            session_name(),
            '',
            time() - 42000,
            $params['path'],
            $params['domain'],
            $params['secure'],
            $params['httponly']
        );
```

**Comment by markstory** [comment]
I'll see if I can reproduce locally.

**Comment by markstory** [comment]
@mneil Your configuration is invalid. You should have:

```php
'Session' => [
  'defaults' => 'cache',
  'handler' => [
    'config' => 'session'
  ],
  'timeout' => 1440,
  'ini' => [
    'session.cookie_lifetime' => 1440
  ]
],
```

**Comment by mneil** [comment]
Ahh okay thanks. I wasn't aware that the ini settings would need to be changed even with the session being in the cache. I thought maybe the timeout was handled in there. We opted for changing the settings in php.ini instead of in Cake since we have access to that configuration.

Thanks for you quick response and sorry for my delayed one!
