### ISSUE TITLE
"created' and "modified" receive unexpected datetime value.

### ISSUE THREAD

**Issue by jrobertsvml** [cakephp/cakephp#5846]
After upgrading to latest 3.0, tried to save a model that worked before the upgrade:
Error: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2014-12-09T18:13:54Z' for column 'created' at row 1 

Both "created" and "modified" fields are set to type datetime.

**Comment by markstory** [comment]
What driver are you using? Have you modified the format the DateTimeType uses?

**Comment by jrobertsvml** [comment]
'driver' => 'Cake\Database\Driver\Mysql'

I haven't modified the DateTimeType format.

**Comment by markstory** [comment]
Ok, how would someone reproduce this issue? I don't get the same problem locally.

**Comment by jrobertsvml** [comment]
I removed 'STRICT_TRANS_TABLES' from sql_mode in /etc/my.cnf, restarted mysqld and the problem went away.

# Recommended in standard MySQL setup
sql_mode=NO_ENGINE_SUBSTITUTION

**Comment by markstory** [comment]
Disabling strict_trans_tables shouldn't be required though. My local MySQL instance has:

```
mysql> show variables like 'sql_mode';
+---------------+--------------------------------------------+
| Variable_name | Value                                      |
+---------------+--------------------------------------------+
| sql_mode      | STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+---------------+--------------------------------------------+
1 row in set (0.00 sec)
```

And I've not see this error before with default configuration of CakePHP.

**Comment by Dave-Edwards** [comment]
I too have just had this problem using Cake 2.4.9 and  5.7.11 - MySQL Community Server (GPL).

Trying to save `mileage_in` = 'NULL' gives the following error - Error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'NULL' for column 'mileage_in' at row 1.

'mileage_in' field is an int(11) Yes NULL.

If I do a SELECT @@GLOBAL.sql_mode I get the following back STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION

I believe that is is because NULL is quoted?
