### ISSUE TITLE
Could identify() automatically call setUser()?

### ISSUE THREAD

**Issue by warriorkitty** [cakephp/cakephp#5868]
From docs:

![cake2](https://cloud.githubusercontent.com/assets/5781483/6125652/d065d35a-b118-11e4-9188-98f00bf456b2.png)

Could AuthComponent's identify() automatically call setUser() if the login is successful? I don't see a reason to do that manually.

Additionally, identify() should take a parameter "callSetUser" which is automatically set to true. If callSetUser is set to false, identify() won't call setUser().

**Comment by dereuromark** [comment]
I like the separation here, as the verbosity makes each step very clear.
We had login() do too much in 2.x, and it really confused people.
So making identify() simply return the (kind of boolean) result and then make an explicit setUser() call will not confuse anyone anymore.
Especially since this behavior will also be transparent when overwriting the user by manually invoking setUser() in edit forms.

That one more line in the very straight forward login action does not hurt IMO. The opposite in fact.

**Comment by ADmad** [comment]
Closing for reasons stated above.
