### ISSUE TITLE
Composer installers put plugins into Plugin folder

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5918]
I already reported this to the composer/installers#217 but in case someone else is having the same problem or we can figure out a workaround I want to inform you that the `composer/installers` plugin will put the plugins into the `Plugin` folder instead of `vendor` folder.

This happens for plugins marked with `"type": "cakephp-plugin"` in their `composer.json` file. It is beacuse of 2.x plugins however the behavior was changed in the 3.x.

This usage of vendor folder for third-party plugins was introduced in #5641.

---
I experienced this problem with Holt59/cakephp3-bootstrap3-helpers#10 where I already created a pull request to remove the `composer/installers` dependancy.

**Comment by AD7six** [comment]
3.x plugins shouldn't be requiring any installer packages (since they themselves don't actually depend on anything related to that) - the app will do so, and that's only to create the `cakephp-plugins.php` map.

Apart from being in the wrong place, it shouldn't have any adverse consequences though... unless it borks  the `cakephp-plugins.php` file somehow.

**Comment by Laykou** [comment]
.. and when I think about it I should create this issue in the [cakephp/app](https://github.com/cakephp/app) or [cakephp/plugin-installer](https://github.com/cakephp/plugin-installer). I don't want to create more duplicates. Sorry to everyone :smiley:

**Comment by Laykou** [comment]
Ok, so I will leave the solution on the `composer` side - the best would be to skip the CakePHP processing if the file `cakephp-plugins.php` exists.
