### ISSUE TITLE
Postgres Quoting Problem in ORM

### ISSUE THREAD

**Issue by atkrad** [cakephp/cakephp#5965]
I have some tables with names like namespaces in PHP. eg:
"**\Shopping\People\Orders**" or "**\Shopping\People\Invoices**"

But CakePHP ORM doesn't support these types of table names.

Regards.

**Comment by markstory** [comment]
Do the table names have `\` in them? What does your table class look like?

**Comment by burzum** [comment]
That's a *very* uncommon and not very well chosen naming convention for table names. Just because it works for the DB doesn't mean it makes sense in practice. I would not use any character in a database table name (or anywhere else) that could cause trouble with my programming language(s) or conventions.

I personally would say don't fix it, this will require very likely a bunch of code as a workaround just to fix this.

> But CakePHP ORM doesn't support these types of table names.

I'm interested if there is *any* other php ORM (or even in other languages) that support this. I *really* doubt there is. Do you know some @atkrad ?

**Comment by markstory** [comment]
I'm with @burzum on this. It sounds like this is a new database, and you should just avoid \ in your table names. `_` is a far safer character to us.
