### ISSUE TITLE
3.0 User logout - session object descruction failed

### ISSUE THREAD

**Issue by Laykou** [cakephp/cakephp#5988]
I got following warning when performing the logout as described in [the blog tutorial](http://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html#authentication-login-and-logout).

```
E_WARNING: session_regenerate_id(): Session object destruction failed

 1 File "C:\Applications\app\vendor\cakephp\cakephp\src\Network\Session.php" line 572 in _displayError
 2 File "C:\Applications\app\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php" line 137 in handleError
 3 File "<internal>" line 0 in session_regenerate_id
 4 File "C:\Applications\app\vendor\cakephp\cakephp\src\Network\Session.php" line 572 in renew
 5 File "C:\Applications\app\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php" line 625 in logout
 6 File "C:\Applications\app\src\Controller\UsersController.php" line 105 in logout
 7 File "<internal>" line 0 in call_user_func_array
 8 File "C:\Applications\app\vendor\cakephp\cakephp\src\Controller\Controller.php" line 405 in invokeAction
 9 File "C:\Applications\app\vendor\cakephp\cakephp\src\Routing\Dispatcher.php" line 114 in _invoke
10 File "C:\Applications\app\vendor\cakephp\cakephp\src\Routing\Dispatcher.php" line 87 in dispatch
11 File "C:\Applications\app\webroot\index.php" line 37 in require
12 File "C:\Applications\app\index.php" line 16 in <main>
```

My `UsersController@logout` method on line `105` looks like this:
```PHP
public function logout()
{
    return $this->redirect($this->Auth->logout());
}
```

The Auth component configuration in AppController:
```PHP
'Auth' => [
    'authenticate' => ['App\\Auth\\CustomAuthenticate'], // Does LDAP auth if the form auth fails
    'loginRedirect' => ['controller' => 'Pages', 'action' => 'home'],
    'logoutRedirect' => ['controller' => 'Pages', 'action' => 'home'],
    'authorize' => ['Controller'],
    'unauthorizedRedirect' => true,
    'authError' => 'Log in please.'
]
```

Do you know what could be the problem of that warning?
I'm running it on Windows 7 + PHP 5.6 + MSSQL 2014

**Comment by markstory** [comment]
How are you storing sessions? Is it possible that another object is closing/destroying the session before AuthComponent can?

**Comment by Laykou** [comment]
I'm storing the session as files in the `C:\Windows\Temp` which was the default path in some `php.production.ini` configuration.

```PHP
// from the config/app.php
'Session' => [
		'defaults' => 'php',
		'cookie' => 'MAPLESESSID',
		'timeout' => '43200' // 30 days
	],
```

I'm not aware of anyone else destroying the sessions. Not at that moment. Because user can normally work and everything and by logging out this warning appears. I see this warnings in the error logs, so I haven't directly see the behavior or anything... But you say that this could happen when the session files are edited by something else, correct?

**Comment by lorenzo** [comment]
Maybe we need a session_commit() before renewing the ids.

**Comment by lorenzo** [comment]
Closing as there was no more activity here and no similar reports have occurred. Please reopen if the problem persists.

**Comment by PhantomWatson** [comment]
I'm getting the same error intermittently upon logging in with [Xety's CookieAuth plugin](https://github.com/Xety/Cake3-CookieAuth).

Error stack trace:

    session_regenerate_id - [internal], line ??
    Cake\Network\Session::renew() - CORE\src\Network\Session.php, line 576
    Cake\Auth\Storage\SessionStorage::write() - CORE\src\Auth\Storage\SessionStorage.php, line 101
    Cake\Controller\Component\AuthComponent::setUser() - CORE\src\Controller\Component\AuthComponent.php, line 631
    App\Controller\AppController::beforeFilter() - APP/Controller\AppController.php, line 102
    Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
    Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
    Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
    Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
    Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
    Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
    [main] - ROOT\webroot\index.php, line 37

AppController.php, lines 100-102:

    $user = $this->Auth->identify();
    if ($user) {
        $this->Auth->setUser($user);

It's my understanding that this part of `Session::renew()`

    if (session_id()) {
        session_regenerate_id(true);
    }

is throwing the error because it can't find the current session object, which I would, perhaps naively, expect to be the case if the user is about to be logged in.

The closest I could find to a solution is [this ten-year-old comment](https://secure.php.net/manual/en/function.session-regenerate-id.php#46937) that says to make sure the page is reloaded after `session_regenerate_id()` is called, but if `session_regenerate_id()` is what's actually throwing the error, I don't get how that advice helps.

Is the problem that `SessionStorage::write()` assumes there's a session object but is being called before there actually is one? Is there some session-setup step that should be taken before `Auth::setUser()` is called?

**Comment by markstory** [comment]
I wonder if that isn't an internal php error. Have you tried looking in the php source for that error? Sometimes I find interesting answers there.

**Comment by Xety** [comment]
@PhantomWatson What PHP version are you using ? Because i also got this error, but only with PHP7, not PHP5.6.

**Comment by PhantomWatson** [comment]
@markstory I've search high and low and haven't found anything that seemed helpful. A lot of other people are reporting the same error in different contexts, but no definitive way to fix it. If there were no session object, I would guess that `session_id()` should be returning an empty string and `session_regenerate_id(true)` shouldn't be getting called at all.

@Xety This is with PHP 5.4.27.

**Comment by Xety** [comment]
After 2 months, the error is still here with PHP7 (latest release)... At every login/logout, i get this error.

![9cd70304d2ffde5beab12af7dd66dfa21](https://cloud.githubusercontent.com/assets/8210023/11691574/ec2d8738-9e9b-11e5-8037-c5d7d70cd22f.png)

I'm using the DatabaseSession. Config :
```php
'Session' => [
    'defaults' => 'database',
    'cookie' => 'FrenchModdingTeam',
    'handler' => [
        'model' => 'Sessions',
        'timeoutOnline' => 5
    ],
    'timeout' => 160
],
```

I have found that : https://bugs.php.net/bug.php?id=70520, but i don't know if the bug is coming from php itself or from Cake.
