### ISSUE TITLE
Improve FormHelper foreign key detection

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#5990]
3.0's FormHelper identifies foreign keys using

substr($fieldName, -3) === '_id'

why not a function that scans table associations? performance reasons?

**Comment by markstory** [comment]
Mostly because that has always been how FormHelper works. Looking at the table associations probably won't work well as it relies on the ORM internals. We'd have to figure out a way to abstract that so other context objects could continue to work.

**Comment by efanzini** [comment]
an isForeignKey() function in Entity would be nice too

**Comment by markstory** [comment]
Why in the Entity? That would require the entity to know way more about the schema than it really should.

**Comment by jhli** [comment]
There should be a way to configure fk patterns for a form helper, having a sane convention (like current) by default but reading it from the associations tighly couples form helper to this specific orm, dorsn't it?

Say you want to use cassandras tables as a dbms and skip the orm?

Maybe the schema uses _fk and _pk instead of _id? The orm part here is already configurable.

**Comment by markstory** [comment]
@jhli We could put key detection into the form context. That would allow it to be datastore independent.

**Comment by efanzini** [comment]
i don't think that fk patterns are a good idea, they sound too limitative to me

in my opinion FormHelper should scan the current table associations and mark fields that are used as foreign key

**Comment by ADmad** [comment]
Closing as the issue has gone stale. If someone is still interested in this enhancement a PR is welcome.
