### ISSUE TITLE
Validator should return more specific error messages

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#5996]
i'll prefer my ['rule => ['comparison', 'lesser', 50]] to return 'This value must be lesser than 50' by default, instead of a more criptic 'The provided value is invalid'

those message templates should be configurable as FormHelper's input templates

protected $_templates = [
    'comparison' => 'This value must be {{operator}} than {{check2}}',
    ...
];

**Comment by markstory** [comment]
Where would the default messages live?

**Comment by ADmad** [comment]
Instead of having the messages in a class they could be in a config file:

```php
return [
    'provider_name' => [
        'rule_name' => 'message'
    ]
];
```
This would allow user to set whatever message they need.

**Comment by efanzini** [comment]
i think the messages should live in the providers.

each provider should have an array 'rulename' => 'message' + a fallback message

**Comment by markstory** [comment]
@ADmad That looks a lot like an i18n file. Perhaps instead of a default catch-all error message, we could have a translation file per provider/domain. If that provider/domain is undefined, the current last resort method could be used. This would probably introduce additional dependencies which might not be desirable.

@efanzini How would an app developer replace the default messages if they were provided by the providers?

**Comment by ADmad** [comment]
@markstory Yes it does. My closed PR for I18ning validation messages allowed for the feature that is requested here :)

**Comment by dereuromark** [comment]
I had the same issue for "isUnique" and getting this message then makes not much sense :)
The scope part made this unique check not work as this "pair" already existed - hard to spot from the default message here.
Maybe we can revisit this for the near future.
