### ISSUE TITLE
CakePHP 2.x with PostgreSQL - SELECT typname

### ISSUE THREAD

**Issue by merorafael** [cakephp/cakephp#6036]
Hi. I have a problem in CakePHP 2.x with PostgreSQL. Several times the framework executes SELECT typname in my database. There would store that value in cache? My database is overloading because of these queries.

**Comment by merorafael** [comment]
File lib/Core/Model/Datasource/Database/Postgres.php in line 749 is called getColumnMeta(), method of PDO. This result could be cached.

**Comment by markstory** [comment]
If you have the time a patch to optimize that method would be greatly appreciated. It sounds like you already understand the problem and a possible solution.

**Comment by jbylund** [comment]
I've just submitted a pull request against php-src (https://github.com/php/php-src/pull/1534) to make this issue better.  It'll still require a round trip in the case of custom types, but I'd guess the majority of database columns are one of the core types (varchars, ints, floats, timestamps...).

**Comment by mfn** [comment]
I think the improvement by @jbylund are really great, it's much appreciated.

I just think that it's not enough for how CakePHP 2.x currently works.

In [Postgres.php](https://github.com/cakephp/cakephp/blob/a641d6a1eb449db54d6a9b1091ef683558e66f96/lib/Cake/Model/Datasource/Database/Postgres.php#L752-L753) `getColumnMeta()` is called *for every column*.

The implementation of the actual PHP c implementation for this is in [pgsql_statement.c](https://github.com/php/php-src/blob/5bc81620ef57cb7315f254531ccfaac9c523f97d/ext/pdo_pgsql/pgsql_statement.c#L652), which besides other stuff also does this
```C
table_name = pdo_pgsql_translate_oid_to_table(table_oid, S->H->server);
```
This causes the following scenario (from a Postgres 9.6 log):
```
<2017-01-18 19:18:51.711 UTC> [db@db] [127.0.0.1] [42032]: [617-1] LOG:  duration: 0.197 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.712 UTC> [db@db] [127.0.0.1] [42032]: [618-1] LOG:  duration: 0.104 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.713 UTC> [db@db] [127.0.0.1] [42032]: [619-1] LOG:  duration: 0.082 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.713 UTC> [db@db] [127.0.0.1] [42032]: [620-1] LOG:  duration: 0.089 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.714 UTC> [db@db] [127.0.0.1] [42032]: [621-1] LOG:  duration: 0.110 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.715 UTC> [db@db] [127.0.0.1] [42032]: [622-1] LOG:  duration: 0.079 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.715 UTC> [db@db] [127.0.0.1] [42032]: [623-1] LOG:  duration: 0.075 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.716 UTC> [db@db] [127.0.0.1] [42032]: [624-1] LOG:  duration: 0.098 ms  statement: SELECT TYPNAME FROM PG_TYPE WHERE OID=1184
<2017-01-18 19:18:51.716 UTC> [db@db] [127.0.0.1] [42032]: [625-1] LOG:  duration: 0.139 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.717 UTC> [db@db] [127.0.0.1] [42032]: [626-1] LOG:  duration: 0.110 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.718 UTC> [db@db] [127.0.0.1] [42032]: [627-1] LOG:  duration: 0.141 ms  statement: SELECT TYPNAME FROM PG_TYPE WHERE OID=1184
<2017-01-18 19:18:51.719 UTC> [db@db] [127.0.0.1] [42032]: [628-1] LOG:  duration: 0.096 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.719 UTC> [db@db] [127.0.0.1] [42032]: [629-1] LOG:  duration: 0.114 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.720 UTC> [db@db] [127.0.0.1] [42032]: [630-1] LOG:  duration: 0.087 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.721 UTC> [db@db] [127.0.0.1] [42032]: [631-1] LOG:  duration: 0.078 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.721 UTC> [db@db] [127.0.0.1] [42032]: [632-1] LOG:  duration: 0.075 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.722 UTC> [db@db] [127.0.0.1] [42032]: [633-1] LOG:  duration: 0.073 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.723 UTC> [db@db] [127.0.0.1] [42032]: [634-1] LOG:  duration: 0.101 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.724 UTC> [db@db] [127.0.0.1] [42032]: [635-1] LOG:  duration: 0.093 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.725 UTC> [db@db] [127.0.0.1] [42032]: [636-1] LOG:  duration: 0.114 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
<2017-01-18 19:18:51.725 UTC> [db@db] [127.0.0.1] [42032]: [637-1] LOG:  duration: 0.081 ms  statement: SELECT RELNAME FROM PG_CLASS WHERE OID=131643322
```
These statements are very quick, i.e. <1ms *but they add up*.

I kid you not, if I remove the whole `getColumnMeta` logic, I see up to 50% performance improvement in my benchmarks. For us, this is **huge**.

However, completely getting rid of reading out the meta makes it impossible for the following code in [Postgres::fetchResult()](https://github.com/cakephp/cakephp/blob/a641d6a1eb449db54d6a9b1091ef683558e66f96/lib/Cake/Model/Datasource/Database/Postgres.php#L776-L785) because the information in `$type` simply wouldn't be available anymore:
```PHP
<?php
switch ($type) {
  case 'bool':
    $resultRow[$table][$column] = $row[$index] === null ? null : $this->boolean($row[$index]);
    break;
  case 'binary':
  case 'bytea':
    $resultRow[$table][$column] = $row[$index] === null ? null : stream_get_contents($row[$index]);
    break;
  default:
    $resultRow[$table][$column] = $row[$index];
```
For our application I'm evaluating if I really need these cases.

For example,  Postgres supports real `boolean` types and in our case they are returned in PHP as native booleans too so from the above snippet at least the `bool` may not be necessary.

However I wouldn't know how the code could work with the remaining two binary types without the meta-introspection.

**Comment by mfn** [comment]
I forgot to add: I made a customized Postgres driver which removes the `getColumnMeta` call and uses `FETCH_ASSOC` in https://github.com/mfn/cakephp2-postgres-no-meta .

Nothing fancy, however it definitely won't support the binary types like the default driver (which is not an issue for us, we don't use them).

**Comment by ADmad** [comment]
Closing as the issue has gone stale and hasn't had any activity in almost a year.

**Comment by mfn** [comment]
FTR, I made a package with a slight modification to the Postgres driver which does not call `getColumnMeta()`: https://github.com/mfn/cakephp2-postgres-no-meta/

That call, at least for Postgres, is very expensive and still noticeable if you care about performance.
