### ISSUE TITLE
2.x (Q) How can I load a stub behaviour for testing?

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp#6060]
**Scenario**
I need to mock some functionality which calls a remote api as part of my behaviour. I've got a `fetchFromApi()` method in my behaviour, which I'd like to mock out using a stub class.

**Sidestep**
I created my stub class. `Plugin/ApiUpdatable/Test/Stubs/ApiUpdateStubBehavior.php`. Then I added the path to the my app.

```php
App::build(array('Model/Behavior' => array(CakePlugin::path('ApiUpdatable') . 'Test' . DS . 'Stubs' . DS)));
$this->Model->Behaviors->load('ApiUpdatable.ApiUpdateStub');

// MissingBehaviorException: Behavior class ApiUpdateStubBehavior could not be found.
```

**Why I think it broke**
https://github.com/cakephp/cakephp/blob/master/lib/Cake/Model/BehaviorCollection.php#L119
The loading of behaviours by the BehaviorCollection class doesn't care what App paths have been declared, which causes the class to not be found.

**Comment by jeremyharris** [comment]
Not that this addresses the possible bug, but another option would be to use [`ObjectCollection::set()`][1] to set the stub, which will be loaded when the alias is accessed from the collection.

To do this, Instead of loading the behavior and messing with app paths, you would set it on the collection. Whenever it is accessed in the future, it'll use the object you set. It might look something like this:

```php
$model = ClassRegistry::init('ModelWithBehavior');
// probably have some construct params to pass to the mock constructor
$stubBehavior = $this->getMock('ApiUpdatableBehavior', array('fetchFromApi'));
$stubBehavior->expects($this->once())->method('fetchFromApi');
$model->Behaviors->set('ApiUpdateable.ApiUpdate', $stubBehavior);
```

This way you're still loading the actual class when you construct the mock, just "aliasing" the calls that load it to use the stub object instead. For an example, check out how the controller test case sets mocked components in the same manner.

[1]: http://api.cakephp.org/2.6/class-ObjectCollection.html#_set

**Comment by markstory** [comment]
Alternatively you can use the `className` option to specify your stub class name.

**Comment by davidyell** [comment]
Do have a more verbose example @markstory ?

**Comment by davidyell** [comment]
Thanks @jeremyharris, I've worked it out now. Your advice worked great, and it removes the need for the stub class!

**Comment by jeremyharris** [comment]
@davidyell cool, glad you got it working :) DI ftw!
