### ISSUE TITLE
Route Elements not work

### ISSUE THREAD

**Issue by xinwo** [cakephp/cakephp#6129]
Router::connect(
    '/:controller/:id',
    array('action' => 'view'),
    array('id' => '[0-9]+')
);

does not work on 2.6.3.
have to do 

Router::connect(
    '/:controller/view/:id',
    array(),
    array('id' => '[0-9]+')
);

**Comment by markstory** [comment]
There are numerous tests showing that routes do work. Make sure you do not have other routes that also match the urls you are trying to cretae.

**Comment by xinwo** [comment]
```
        Router::connect('/', array('controller' => 'pages', 'action' => 'display', 'home'));
        Router::connect('/pages/*', array('controller' => 'pages', 'action' => 'display'));

        Router::connect(
                '/:controller/index/offset:offset',
                array(),
                array('offset' => '[\d]+')
        );

        Router::connect(
                '/hotkeywords/keyword:keyword',
                array('action' => 'add', '[method]' => 'POST'),
                array()
        );  

        Router::parseExtensions();

        CakePlugin::routes();

        require CAKE . 'Config' . DS . 'routes.php';
```
this is everything in my Config/routes.php, mostly from cakephp.git
and in Config/core.php, I added
```
Configure::write('Routing.prefixes', array('v1'));
```

and below is Controller/HotKeywordsController.php
```
<?php
App::uses('AppController', 'Controller');
class HotKeywordsController extends AppController {

        public $components = array('RequestHandler');

        public function v1_index() {
                $keywords = $this->HotKeyword->find('all', array(
                        'order' => array('count DESC'),
                        'limit' => 10,
                ));
                $this->set(array(
                        'keywords' => $keywords,
                        '_serialize' => array('keywords')
                ));
        }

        public function v1_add() {
                if ($this->request->is('post')) {
                        $this->HotKeyword->create();
                        if ($this->HotKeyword->save($this->request->data)) {
                                $this->set(array(
                                        'result' => 'OK',
                                        '_serialize' => array('result')
                                ));
                        }
                }
        }
}
```

when I POST access
http://api.local.buyyo.jp:8080/v1/hotkeywords.json
instead of v1_add(), v1_index() is got called.

I'll appreciate you can tell how I did wrong

**Comment by ADmad** [comment]
`/v1/hotkeywords.json` is not going to match the route you have set for url pattern `'/hotkeywords/keyword:keyword'` because it does not have the "keyword" part.

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
