### ISSUE TITLE
Cake3 ORM returns 0 when using postgresql money data type

### ISSUE THREAD

**Issue by cnizzdotcom** [cakephp/cakephp#6193]
Using postgresql money data type Cake3 ORM returns 0 instead of actually value. Workaround is using numeric data type instead.

**Comment by markstory** [comment]
Do you have the same issue with the Decimal type?

**Comment by cnizzdotcom** [comment]
PGAdmin doesn't even give me the option for decimal type. I should have given my system specs as well:

PostgreSQL 9.4.1 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1, 64-bit

**Comment by markstory** [comment]
Interesting. I will have to take a look as I have always stuck to more common datatypes.

**Comment by markstory** [comment]
Taking a look at a [few](http://stackoverflow.com/questions/15891507/using-postgresqls-money-type-instead-of-numeric) [different](http://postgresql.nabble.com/How-useful-is-the-money-datatype-td1925665.html) discussions make me believe that the money type should be avoided, and `numeric` used instead.

Given that money types come back from postgres with effectively arbitrary string data in front of the number, I'll remap the money type into a string instead of a float value.

**Comment by markstory** [comment]
I've put up a fix in #6273
