### ISSUE TITLE
CakeRequest undefined variable $baseUrl 

### ISSUE THREAD

**Issue by michaelmafort** [cakephp/cakephp#6215]
Please consider using isset() function in condition of check if variable exist instead of !$variableName.

I found an error in my test case when using Mocked Controller, the error is in cakephp/lib/Cake/Network/CakeRequest.php: 296

if (!$baseUrl) {

**Comment by dereuromark** [comment]
@michaelmafort Can you please be more specific in how the error shows?

Note that using isset() everywhere often times is bad practice and hides potential issues on a symptom-level rather than allowing it to be fixed at the root.
If we know a variable has to be declared prior to using it, not using isset() is the right practice IMO.
You would need isset()/!empty() when you cannot be certain of it.

**Comment by markstory** [comment]
Sounds like your configuration data is missing required data. `App.baseUrl` is a required key/value.
