### ISSUE TITLE
Singularize version of `sieves` is incorrect

### ISSUE THREAD

**Issue by jtyost2** [cakephp/cakephp#6240]
http://inflector.cakephp.org/sieves

**Comment by ADmad** [comment]
@jtyost2 You need to open a pull request for use to be able to merge your fix. You have opened an issue. Please consult the github doc on how to open a pull request.

**Comment by ADmad** [comment]
Closing in favor of #6241

**Comment by jtyost2** [comment]
@ADmad my understanding from the doc is that an issue is first requested: https://github.com/cakephp/cakephp/blob/master/CONTRIBUTING.md#how-to-contribute

Is that incorrect?

**Comment by ADmad** [comment]
You had already reported the problem in issue you originally created :)  Plus the "how to contribute" doc only states how to open an issue and/or create a pull request. It does not prevent you from directly creating a pull request.

**Comment by jtyost2** [comment]
Ok, fair enough. I'll leave it at this: I read it to mean that a PR should have an issue associated with it. As a suggestion perhaps the contributing guidelines should be clearer in this area.

I also didn't know for sure if I would be able to get around to the PRs for said issue tonight and wanted to be sure this stayed listed as an actual bug, since the other issue was closed, Which the other issue being closed is fine, that issue doesn't make sense anymore.

**Comment by beporter** [comment]
@ADmad In an ideal world, yes everyone would just submit a perfect PR the first time, every time. That would be a glorious thing, to be sure.

But better to have the issue at least logged up front and incur a second loop back around to address it than to leave it unspoken perhaps indefinitely. Unless you'd prefer people _didn't_ tell you when the software was broken. :wink:

**Comment by ADmad** [comment]
@beporter You seem to be taking my comment out of context. I am not discouraging opening of issues. All I am saying is an issue is not a prerequisite to a pull request. In this particular I had thought @jtyost2 opened this issue by mistake when he actually wanted to open a PR. I cannot guess how experienced an individual is with GH / git :)

Also in a pull request you can provide all the info you can through an issue along with code. So if someone is clear where the problem lies and confident he can provide a proper fix he/she can directly open a pull request with required problem description without opening an issue first.

Also at times some users are not very good with english in which cause it becomes difficult for us to understand the problem just based on description. In such case having code (even if it's not perfect) really helps.
