### ISSUE TITLE
Code Improvements

### ISSUE THREAD

**Issue by pirouet** [cakephp/cakephp#6287]
Hey,

I noticed there are a few places in the code that uses multiple exit points within the method (Controller.isAction for example). What are your thoughts on this before I attempt to change to single exit points? I would only use single exit points therefore ensuring that I know where the method is going to exit as opposed to "hunt the exit point" when looking from a debugging point of view.

Also, tied in with the example method named above is using exceptions as a way to control the flow (I.e. if exception then return false). Again, from my own experience this shouldn't be this way and I would ideally handle an exception as an exception such as writing to a log file only and not becoming a part of the methods functionality.

Any thoughts would be welcome on this before I think about coding away

Thanks!

**Comment by jadb** [comment]
Please include links to the files/lines you are referring to.

**Comment by pirouet** [comment]
Hi Jad,

The below code is from Controller.php in namespace Cake\Controller. As you can see there are four "return statements" which can be shortened to one with the catch block also acting as a return point. 

```php
public function isAction($action)
{
    try {
        $method = new ReflectionMethod($this, $action);
    } catch (ReflectionException $e) {
        return false;
    }
    if (!$method->isPublic()) {
        return false;
    }
    if ($method->getDeclaringClass()->name === 'Cake\Controller\Controller') {
        return false;
    }
    return true;
}
```

This could be rewritten as below. The advantages to this, for me, is you know where the code is going to exit and the exception catch block is intended to do only that (and not act as part of the method):
```php
public function isAction($action)
{
    $isAction = false;
    try {
        $method = new ReflectionMethod($this, $action);
        if($method->isPublic() && $method->getDeclaringClass()->name === 'Cake\Controller\Controller') {
            $isAction = true;
        }
    } catch (ReflectionException $ex) {
        // write the exception message to log file/database/etc ...
    }
    return $isAction;
}
```

I hope this makes things clearer :)

**Comment by pirouet** [comment]
This is only one file where this happens (just to show an example) but I have noticed multiple "return" elsewhere in the code that could be refactored

**Comment by markstory** [comment]
I like multiple returns personally. It lets you avoid a few other issues like:

* Longer methods - only having one return forces you to add more conditionals which increase the length of methods.
* Combined get/set - I don't think these are as efficient with a single return. It is arguable that combining get/set is a bad idea. But I don't buy that argument as jQuery - one of the most popular and emulated API's uses tons of combined get/set methods.
* More complexity - due to only having a single return you have to add additional variables, and conditions to ensure that your return hasn't already been populated.

I'm sure there are places where having fewer return statements would improve readability, but I don't think we can only ever use one return value without making other tradeoffs.

**Comment by pirouet** [comment]
@markstory appreciate your response and I completely agree/understand there are scenarios where it wouldn't make sense to increase the complexity for the sake of having fewer statements; it would have to be on a case-by-case basis as to whether or not it can be justified that any form of refactoring would improve the method(s).

**Comment by markstory** [comment]
Case-by-case sounds totally reasonable. If you think there are places where we can have shorter, more-readable code through a single return statement, pull requests would be awesome. Shortly after I replied, I noticed that you had done just that with `isAction()` :blush:
