### ISSUE TITLE
TestFixture with foreign keys failing with sqlite3 works with MySQL

### ISSUE THREAD

**Issue by MikeLees** [cakephp/cakephp#6323]
I use a MySQL database for production but usually use a sqlite3 memory database for running my unit tests since they execute more than 15 times faster.

I found a bug in my code that I thought should have been covered by a unit test. I found the test that should be failing and it failed when I ran it against a MySQL test database but passed when run against the sqlite3 database.

I figured out that sqlite3 doesn't check foreign keys by default. This one was fairly simply fixed by adding 'init' => ['PRAGMA foreign_keys = ON'] the the test database connection config in app.php.

But now all the tests blew up with an _Integrity constraint violation_ in  FixtureManager->unload() which was down to the nature of sqlite3 which does not defer foreign key constraints by default and the parent table was getting truncated before the child table.

The solution I eventually came up with was to change the order that the fixtures were processed in FixtureManager->unload() which amounted to changing line 318 of FixtureManager.php to 

           foreach (array_reverse($fixtures) as $fixture) {

Is this a reasonable fix or is there a better way of doing it?

I did look at other alternatives like using 'PRAGMA defer_foreign_keys = ON' on the sqlite3 connection but it had to be done per transaction rather than globally on the connection.

**Comment by lorenzo** [comment]
is this in CakePHP 2 or 3?

**Comment by MikeLees** [comment]
Sorry, I should have mentioned the version - CakePHP v3.0.1

**Comment by markstory** [comment]
You can also 'solve' this issue with careful ordering of your fixtures. I don't think that is a great solution either though and I've been mulling over a way to have the fixture manager calculate the correct order for fixtures based on foreign key relationships, but haven't put a ton of thought into it.

**Comment by MikeLees** [comment]
With my change in place, I still need to carefully order my fixtures. I'm not you can solve it *only* with careful ordering of the fixtures. Without my change in place, if I change the order of the fixtures so that the unload works then the load fails.

**Comment by markstory** [comment]
Interesting, would you be able to make the change you've proposed a pull request? If not I can probably sort it out.

**Comment by HavokInspiration** [comment]
What about having some kind of dependency management within fixtures ?
Something like :

```php
class ProductsFixture extends TestFixture
{
    public $require = [
        'core.categories'
    ];
}
```

This way, before doing anything, the ``FixtureManager`` needs to resolve the full dependencies graph based on the ``$require`` property that can be found in Fixture classes (here, CategoriesFixture should have priority for instance).
This might get tricky and might affect performances when there are a lot of dependencies involved. But since it is within tests, this might be something that can be accepted.

**Comment by lorenzo** [comment]
that's not a crazy idea

**Comment by markstory** [comment]
@HavokInspiration That could work, I was considering taking all the fixtures, and then sorting them based on the foreign key constraints. That would let app developers continue using simple syntax and not having to worry about order too much.

**Comment by HavokInspiration** [comment]
That's another solution. 
Your idea would be simpler to explain and would not require much work for app devs.

**Comment by markstory** [comment]
@HavokInspiration Simplicity for users was the main reason I considered going down that route. Forcing people to manually manage the dependency tree is tedious and error prone.

**Comment by HavokInspiration** [comment]
@markstory Plus it means every already built fixtures will work out of the box with the changes. I'm buying it :smile:

**Comment by HavokInspiration** [comment]
Should we also, for convenience, load possible missing fixtures ?
For instance, if you load the ArticlesTagsFixture, you also need to load the TagsFixture, otherwise, postgres will fail to create the records (missing constraint). sqlite and mysql doesn't seem to really care about this.
So while reading the constraint, it could check if needed fixtures are all here.

**Comment by markstory** [comment]
@HavokInspiration I think that might go too far down the clever/magic path. If we load fixtures for the developer, they have less control/visibility into how the fixtures work.

**Comment by HavokInspiration** [comment]
@markstory Ok. The line between magic and convenience was indeed very thin here.

**Comment by HavokInspiration** [comment]
Let's give this a try.

**Comment by HavokInspiration** [comment]
I started working on this and I have a working solution for MySQL.
I went with the same way FK constraints management is done in the migrations plugin : 
- foreign key constraints are added once all tables have been created
- those constraints are dropped before any table is truncated.

You can (see the diff here)[https://github.com/HavokInspiration/cakephp/compare/master...HavokInspiration:fixtures-order]

There is probably more tests to be added (specially to cover the ``FixtureManager::loadSingle()`` method, I currently don't know if it is working okay with the changes), but I'd like some opinion before continuing this implementation for the other db servers.

**Comment by markstory** [comment]
The new constraint methods on the fixture will need to be added to the FixtureInterface, or plugins like ElasticSearch will fail.

I like the general direction though.

**Comment by HavokInspiration** [comment]
While strugling with a test failure on the SQLite test suite, it came to my attention that when a ``ConnectionInterface`` was extracted, a ``disableConstraints`` method was added, turning off FK constraints check before running the queries.
So my question is simple : is a fix necessary ? Because with the ``disableConstraints`` call, all queries in the fixtures manager are done without FK check which leads to the test suite passing whatever the fixtures order.

**Comment by HavokInspiration** [comment]
PR #7503 was opened to propose a solution for this.

As for my previous question, it would have worked in Postgres was not ruining all the fun for everyone.
