### ISSUE TITLE
Rule to prevent deletion of records with associated data

### ISSUE THREAD

**Issue by efanzini** [cakephp/cakephp#6327]
It would be nice to have a built-in rule to prevent deletion of records with associated data, especially when working with dbs that doesn't support foreign key costraints (SQLite < 3.6)

**Comment by markstory** [comment]
Pull requests for these kinds of things are always welcome :smile:

**Comment by efanzini** [comment]
i'm a bit ashamed of my code... but that's what i did

```php
namespace App\Model\Rule;

use Cake\Datasource\EntityInterface;
use Cake\ORM\TableRegistry;

class NoAssociatedData
{
	
	protected $association;
	
	public function __construct($association)
	{
		$this->association = $association;
	}
	
	public function __invoke(EntityInterface $entity, array $options)
	{
		
		$associatedRecords = 
			TableRegistry::get($this->association->name())
				->find()
				->where([
					$this->association->foreignKey() => $entity->{TableRegistry::get($entity->source())->primaryKey()}
				])
				->count()
		;
		
		if ($associatedRecords > 0) {
			return false;
		}
		
		return true;
		
	}
	
}
```

i'm attaching this rule automatically 

```php
public function buildRules(RulesChecker $rules)
{
	foreach ($this->associations()->type('HasOne') + $this->associations()->type('HasMany') as $association) {
		if ($association->dependent() === 'notAssociated') {
			$rules->addDelete(new NoAssociatedData($association));
		}
	}
	return $rules;		
}
```

let me know

**Comment by markstory** [comment]
I'm not sure about re-purposing the dependent flag, but otherwise the general direction of the code is reasonable.

**Comment by efanzini** [comment]
that's just how i'm using it. i like automations :)

**Comment by lorenzo** [comment]
I'm with @markstory, using another option is a better idea.

**Comment by jhli** [comment]
What about the option name? noOrphans? leaveNoOrphans?

**Comment by efanzini** [comment]
@lorenzo @markstory i'll prefer to have a single variable that defines the behavior of records with childrens.

imagine the case where 'dependent' is false and 'leaveNoOrphans' is true

**Comment by markstory** [comment]
A separate option gives you more flexibility in the future though. Alternatively, we can just make the rule available and leave how it is integrated up to the application developers.

**Comment by lorenzo** [comment]
Closing all enhancement requests that were not actioned in a long time. If you still think this a good idea and would like to help making this happen, please leave a comment.

**Comment by ndm2** [comment]
I'm using such a rule for my projects as foreign key constraints are used on regular basis, and inspecting PDO exceptions that are normally thrown is rather tedious. Instead of returing a boolean, the rule throws custom exceptions which can easily be evaluated in the controller.

I can wrap it up and push a PR in case this would be of interest?

**Comment by lorenzo** [comment]
Sure, a PR would be nice... I'm not sure about making it throw exceptions, though

**Comment by markstory** [comment]
I'm not sure exceptions make sense in rules class, to signal situations other than logic/fatal errors. A foreign key rule should probably append errors like other rules.

**Comment by ndm2** [comment]
There are two main reasons why I settled with throwing exceptions.

1. When dependent associations are being deleted, errors are being swallowed, and one has no clue what actually failed. For example here: https://github.com/cakephp/cakephp/blob/3.2.9/src/ORM/Association/HasMany.php#L448-L452. The errors will be set on the entities that noone will ever see.

2. Ease of use. Instead of inspecting a lot of keys, even possibly nested ones, evaluating an exception is way more staight forward, it supplies the name of repository and its problematic association, which can be used to easily build meaningful responses.

@lorenzo you may remember point 1 from a discusson on IRC some time ago :) There was the idea of passing an error buffer object through the options to solve that issue.

It felt workaround-ish in the beginning, but after working with it for some time, I found it to be quite nice, and actually began missing similar behavior for the built in unique and exists in rules.

How about making it configurable?

**Comment by lorenzo** [comment]
My problem with exceptions is that they break from the stack and then it is easy to leave dirty state all over the place, that is why I much rather have an error buffer.

**Comment by ndm2** [comment]
I never really had any problems with it yet, but I can understand the reservations, such hard breaks can be problematic.

I don't really have a good idea for solving the main problem of this buffer solution though, that is, the problem that the developer either explicitly needs to pass a buffer object to the options, or pass the options as an array object so that possibly automatically set buffer objects can be retrieved afterwards.

The only other ways I could imagine right now, would be to make the table class hold the buffer object, and make it available via a method like `getLastErrorBuffer()`, but introducing such state doesn't feel good, and while the table class could for example inject the buffered erros into the entity, this feels kinda out of place.

Without the ability to overcome the error swallowing problem, such a rule doesn't seem to be overly helpful, as in the main use case, ie preventing deletion of data that would create orhpaned records (let aside that one should always additionally use real foreign key constraints to ultimately prevent that at DBMS level), things will just fail silently.
