### ISSUE TITLE
find TIME_TO_SEC error

### ISSUE THREAD

**Issue by zx4357685** [cakephp/cakephp#6347]
Hi,guys

When I want to find a field which type is 'time' and using mysql function 'TIME_TO_SEC'

    $query = $this->TestTimes->find('all',[
            'fields' => ['id','time'=>'TIME_TO_SEC(time)']
        ]);

It will show error 
    
    The separation symbol could not be found A two digit second could not be found

I can use it in CakePHP 2.x

So I think it may be a bug for CakePHP 3.0

**Comment by lorenzo** [comment]
`time` is probably part of your table schema. If you change the data type that this column is going to return you will get CakePHP confused. Use a different alias that is not `time` or use entity accessors for this. 

An alternative is to do `$entity->time->format('u')` which is the amount of seconds since epoch.

**Comment by zx4357685** [comment]
@lorenzo Ah~~ It's my fault
Thanks for your answer!
