### ISSUE TITLE
Time "00:00:00"

### ISSUE THREAD

**Issue by kailsazerland** [cakephp/cakephp#6402]
If in my database table I have field type TIME and I put value like "00:00:00" or "00:15:00" in, I have a trouble to get it by model. Cake\I18n\Time Object isn't created.

**Comment by icaroscherma** [comment]
Can you provide more details? I'm assuming that you are using CakePHP 3 since the error is ``Cake\I18n\Time``... but how are you trying to get the field in your model?
What usually happens to me is, when the field is stored as a ``TIME`` in the database and I try to view it with a regular ``echo`` (like ``<?= $object->field ?>``), the output is something like ``4/23/15, 6:03 AM``, and is stored only ``06:03:00``. But you can always format this.

Ps: In the ``Model\Table`` file the validator is like: ``$validator->add('FIELD_NAME', 'valid', ['rule' => 'time'])``.

**Comment by lorenzo** [comment]
I think this is a regression introduced in a recent commit, I'll take a look

**Comment by markstory** [comment]
@lorenzo Probably this 960d3dfb commit. Which added a int cast checking against 0. 

cc @dereuromark

**Comment by dereuromark** [comment]
Should 00:00:00 not be treated as null?

**Comment by ADmad** [comment]
@dereuromark No, that's a valid time, midnight.

**Comment by dereuromark** [comment]
Closing as a PR is now open.
