### ISSUE TITLE
Version 2.6.4 App::_map($file, $name, $plugin = null) does not differentiate plugin files

### ISSUE THREAD

**Issue by dilab** [cakephp/cakephp#6423]
## Facts
When CakePHP builds ** file_map ** cache, it use function below
https://github.com/cakephp/cakephp/blob/2.6.4/lib/Cake/Core/App.php#L788
```
protected static function _map($file, $name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key = 'plugin.'.$plugin.'.' . $name;
		}
		if ($plugin && empty(self::$_map[$name])) {
			self::$_map[$key] = $file;
		}
		if (!$plugin && empty(self::$_map['plugin.' . $name])) {
			self::$_map[$key] = $file;
		}
		if (!self::$bootstrapping) {
			self::$_cacheChange = true;
		}
	}
```

#### I have two UsersController classes sitting in different plugins:
+ app/Plugin/Members/Controller/UsersController.php
+ app/Plugin/Organizers/Controller/UsersController.php

#### CakePHP builds cache file_map as follow:

```
array(
   ...
  'plugin.UsersController' => '/path-to-app/Plugin/Members/Controller/UsersController.php',
   ...
)
```
(Output from ```debug(Cache::read('file_map','_cake_core_'));```)

Take note the $key **'plugin.UsersController** , it will point to either file **Members/Controller/UsersController.php/** or **Organizers/Controller/UsersController.php**. Which means it does not differentiate classes' files in different plugins, it uses a generic **plugin** as key.

This causes a lot of problem when cache is turned on when there are classes sitting in different plugins with the same name, as it loads incorrect classes .

**Comment by rchavik** [comment]
CakePHP 2.x does not support duplicate class names.

**Comment by eDesignBG** [comment]
The **file_map** cache holds the serialized content of the `App::$_map` variable (an associative array).
So changing the `App::_map()` and `App::_mapped()`, in a way that the keys for the map values actually include the plugin name and not just the `plugin.` string, will make it possible for the application to distinguish between files with the same name from different plugins.

**Old code:**
```
    protected static function _map($file, $name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key = 'plugin.' . $name;
		}
		if ($plugin && empty(self::$_map[$name])) {
			self::$_map[$key] = $file;
		}
		if (!$plugin && empty(self::$_map['plugin.' . $name])) {
			self::$_map[$key] = $file;
		}
		if (!self::$bootstrapping) {
			self::$_cacheChange = true;
		}
	}
	protected static function _mapped($name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key = 'plugin.' . $name;
		}
		return isset(self::$_map[$key]) ? self::$_map[$key] : false;
	}
```

**New code:**
```
	protected static function _map($file, $name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key =  $plugin . '.' . $name;
		}
		if ($plugin && empty(self::$_map[$name])) {
			self::$_map[$key] = $file;
		}
		if (!$plugin && empty(self::$_map['plugin.' . $name])) {
			self::$_map[$key] = $file;
		}
		if (!self::$bootstrapping) {
			self::$_cacheChange = true;
		}
	}

	protected static function _mapped($name, $plugin = null) {
		$key = $name;
		if ($plugin) {
			$key = 'plugin.' . $name;
		}
		return isset(self::$_map[$key]) ? self::$_map[$key] : false;
	}
```

As I see it, this is not a limitation of the framework, but an actual bug.

**Comment by markstory** [comment]
@eDesignBG The main reason this has never been 'fixed' is that while allowing the same class to co-exist in multiple plugins seems easy, it creates hidden bombs in an application where fatal errors can be introduced by attempting to load both User models for example. Because we feel this error poses a sizable risk we've intentionally not solved this issue.

**Comment by eDesignBG** [comment]
@markstory Thank you for the replay. I'll have in mind the possible implication such a fix can present. Still, I kind of prefer it to the other option, because it took me quite a while to figure out why sometimes the controller for one of my plugins was instantiated as a controller from an another one. The application was in debug mode, so the cache had an expiration life of 10 seconds and the second plugin was rarely used, unlike the first one. This led to the problem to be present only once in a while. 
While including files, containing the same class names, looks to me, will be easier to debug.

**Comment by AD7six** [comment]
> While including files, containing the same class names, looks to me, will be easier to debug.

Until you attempt to include two same-named classes in the same request, and you're left wondering why only one of the classes is actually used irrespective of the app config/cache. 

If you only have duplicate controller class names, it might work simply because outside of request action there's only one controller class typically loaded - but otherwise (and especially if there are duplicate _model_ class names) all the above solution is likely to do is move where the confusion is.

**Comment by dilab** [comment]
@markstory It this solved in Cake 3? Since we have namespace now.

**Comment by dereuromark** [comment]
@dilab Yes it is.
