### ISSUE TITLE
Hash::extract() + array with numeric/alphanumeric keys

### ISSUE THREAD

**Issue by codeworks** [cakephp/cakephp#6447]
I'm using CakePHP 2.6.4 and came across an unexpected behavior of Hash::extract() which might be a bug. I'm having a list like this one:

```php
$list = array(
  '02000009C5560001' => array('name' => 'Mr. Alphanumeric'),
  '2300000918020101' => array('name' => 'Mr. Numeric'),
  '390000096AB30001' => array('name' => 'Mrs. Alphanumeric'),
);
```

As you can see, the list is indexed with alphanumeric and numeric values - all of them are actually strings. Let's say I would like to convert this array to a simple list with all names, just like that:

```
$names = Hash::extract($list, '{s}.name');
```

Docs say: "{s} - Represents a string. Will match any string value including numeric string values."
So, what I would expect is a list with 3 names. But instead I'm getting a list of only 2 names:

```
Array
(
    [0] => Mr. Alphanumeric
    [1] => Mrs. Alphanumeric
)
```

Obviously "Mr. Numeric" gets filtered due to the fact, that the key is numeric, even though it's a numeric string value. So I guess either the docs are incorrect or Hash::extract() doesn't match the expression {s} like it's supposed to? :)

Btw: Using {n} instead of {s} returns ONLY "Mr. Numeric", which is also not quite what I expected, due to the description in the book: "{n} - Represents a numeric key. Will match any string or numeric key." -- What does "any string or numeric key" mean in this case? Isn't {n} supposed to match ONLY numeric keys, so in this case it should actually return an empty array, as all keys are strings?

**Comment by HavokInspiration** [comment]
"Any string or numeric key" means anything for which ``is_numeric`` returns ``true``.
So ``1234`` or ``'1234'`` will be matched.

As for your issue, it seems that even though you pass your second key as a string, PHP internally converts it to an integer. Since the token ``{s}`` is matched against ``is_string()``, it is stripped out.
One possible solution would be to make the token ``{s}`` matched against ``is_string()`` AND ``is_numeric()``.

**Comment by HavokInspiration** [comment]
"Any string or numeric key" means anything for which ``is_numeric`` returns ``true``.
So ``1234`` or ``'1234'`` will be matched (if you ``debug()`` your ``$list`` array, you should see your second key cast as an integer).

As for your issue, even though you pass your second key as a string, PHP internally converts it to an integer. Since the token ``{s}`` is matched against ``is_string()``, it is stripped out.
One possible solution would be to make the token ``{s}`` matched against ``is_string()`` OR ``is_numeric()``.

I could submit a fix but I'm waiting for the opinion of a core dev.

The problems also occurs on 3.X by the way.

**Comment by markstory** [comment]
@HavokInspiration I would prefer to have a `{*}` operator, or have `{s}` accept any string type data.

**Comment by codeworks** [comment]
Thank you for your reply. If keys containing only numbers are casted as integers internally, you actually can't get the result that one would expect, when reading the docs ("Will match any string value including numeric string values.") - right?

So personally I think {s} should definitely be a wildcard, as (in some cases) you might not be able to asure that ALL your (string-)keys contain at least one letter.

Of course, a {*} operator would offer a more specific control over the actual behavior of extract() and wouldn't break compatibility (at least if you consider the current behavior as a feature, not a bug :)), so that might as well be a good way to solve the issue.

**Comment by HavokInspiration** [comment]
@markstory The ``{*}`` operator is the best option in my opinion. A wild card would be a good addition.
I'm pretty sure I have ``extract()`` calls with ``{s}`` that are built around this behavior. This would probably break if we were to make ``{s}`` match more.

(BTW : I won't have the time to make a fix as I stated in my previous comment in the coming days...)

**Comment by markstory** [comment]
@HavokInspiration I think a wildcard is safer as well. I too worry about possibly breaking `{s}` by making it greedy.

**Comment by markstory** [comment]
The issue I'm seeing at least on PHP 5.4.38 is that the key for 'Mr. Numeric' is being converted into an integer by PHP.

```php
$data = array(
	'02000009C5560001' => array('name' => 'Mr. Alphanumeric'),
	'2300000918020101' => array('name' => 'Mr. Numeric'),
	'390000096AB30001' => array('name' => 'Mrs. Alphanumeric'),
);
var_dump($data);
```

Outputs

```
array(3) {
  ["02000009C5560001"]=>
  array(1) {
    ["name"]=>
    string(16) "Mr. Alphanumeric"
  }
  [2300000918020101]=>
  array(1) {
    ["name"]=>
    string(11) "Mr. Numeric"
  }
  ["390000096AB30001"]=>
  array(1) {
    ["name"]=>
    string(17) "Mrs. Alphanumeric"
  }
}
```

Because the data is being converted by PHP, there is no way for the `{s}` matcher to work. Adding a `{*}` matcher will be the only option I think.
