### ISSUE TITLE
3.x: calling a plugin element

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/cakephp#6556]
Hypothesis: I call a plugin element - **without** the plugin syntax - within a plugin template.

Thanks to [Cake\View\View::pluginSplit()](http://api.cakephp.org/3.0/class-Cake.View.View.html#_pluginSplit), since the element is called from within a plugin, the plugin name will still be added to the element name.

This doesn't seem normal for me: if I want to overwrite the element from my application, how should I do?
In my opinion, the element should be sought first within the application, then within the plugin in which it was called. Is it wrong?

**Comment by dereuromark** [comment]
I think this is how it always behaved - to also first look in the plugin, and then look in the app as fallback.
The other way around is not supported.

I had the idea for 2.x a while back to have `preferApp true/false` as config param like for I18n lookups added in 2.6.
So that you can have the fallback the other way around.

Either way, some use case will be broken with whatever decision we stick with.
Being forced to use the plugin syntax always to stay in the plugin would remove the overwrite/fallback possibility of how it currently works.

**Comment by mirko-pagliai** [comment]
I remember that in CakePHP 2.x, if the plugin syntax was not used, it looked at first whitin the app and then whitin the plugin, because I very often have overwritten elements plugins. I remember this, but now I have not checked.

The idea of a config parameter to allow this is great. Or an option for the `element()` method.

**Comment by dereuromark** [comment]
And I remember the trick/hack to make it work to use the `App.` prefix (or any other nonplugin one^^):
```php
$this->element('App.my_element'); // Now it is forced to use the app one.
```

**Comment by markstory** [comment]
View::pluginSplit() has been around since 2011-2012. So its in no way new.
