### ISSUE TITLE
[3.0] How to use requestAction in cakephp 3.0

### ISSUE THREAD

**Issue by macnie** [cakephp/cakephp#6713]
At 2.0, I use requestAction like this:

<?=$this->Form->input('list',array('options'=>$this->requestAction(……)?>

But At 3.0, I use requestAction nothing display. I don't know how write options data source.

**Comment by AD7six** [comment]
> At 2.0, I use requestAction like this:

> `<?=$this->Form->input('list',array('options'=>$this->requestAction(……)?>`

That's pretty awful - why were you doing that?

**Comment by macnie** [comment]
I don't know how to do it reasonably, can you tell me the reasonable solution? thx!

**Comment by AD7six** [comment]
Well, you pass options in, you don't look for them from a view/element. What you've done with that request action call is no better/different than putting:

    'options' => ClassRegistry::init('something')->find('list')

in a view. The specifics for your use case aren't going to change the principle that a view should be dumb, receive everything it needs, and not go looking for missing data (because there isn't any).

HTH - if you still have doubts please note:

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by macnie** [comment]
In China, you say these sites are not open, so I only come here to consult the problem。
Thank you very much for your patience, thank you very much.

**Comment by AD7six** [comment]
I/we don't want to leave you without a means of help. I may not understand - which sites can you not access?

**Comment by macnie** [comment]
The CakePHP Manual
The CakePHP online API
The CakePHP Google Group 
Stackoverflow

this website return 404 In China.

**Comment by antograssiot** [comment]
@macnie you could still go to the [doc repo](https://github.com/cakephp/docs) and the [api builder](https://github.com/cakephp/cakephp-api-docs) and follow the instruction in the readme to build the docs locally.

**Comment by AD7six** [comment]
> this website return 404 In China.

All 4 sites are inaccessible?

**Comment by majna** [comment]
Stackoverflow and CakePHP Manual/API should be accessible from China:

https://en.greatfire.org/book.cakephp.org
http://www.greatfirewallofchina.org/index.php?siteurl=http%3A%2F%2Fbook.cakephp.org
http://www.blockedinchina.net/?siteurl=http%3A%2F%2Fbook.cakephp.org

Try with opendns 8.8.8.8 or bypass DNS servers by adding this to your "hosts" file:

    173.203.218.184 book.cakephp.org
    198.252.206.16 stackoverflow.com

Good luck.
