### ISSUE TITLE
Empty uploaded file data on beforeSave()

### ISSUE THREAD

**Issue by Alirezaaa** [cakephp/cakephp#6714]
This is my form:
```
<?= $this->Form->create($set, ['type' => 'file', 'autocomplete' => 'off']) ?>
<?= $this->Form->file('preview', array('type' => 'file', 'accept' => 'image/jpeg,image/png')) ?>
<?= $this->Form->button(__('Add Stickers Set'), array('class' => 'btn btn-success')); ?>
<?= $this->Form->end() ?>
```
This is my controller:
```
$set = $this->Sets->newEntity();
$entity = $this->Sets->patchEntity($set, $this->request->data());
$this->Sets->save($entity)
```
And this is my table:
```
public function beforeSave(Event $event, Entity $entity, ArrayObject $options) {
        print_r($entity->get('preview')); // This line must print an array of the preview data but print an empty string!
    }
```
The preview data is okay in my controller and it prints an array of uploaded file data but on the beforeSave() method it just prints an empty array! How can I fix this?

**Comment by ADmad** [comment]
When patching the entity the marshaller converts / scrubs data based on database field type. Since your `preview` field is varchar in db the marhaller won't allow setting array to it.

To avoid this issue use a input name which is not a db field or use a custom database type for the class.

For more info visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[The CakePHP Google Group](http://groups.google.com/group/cake-php) 
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
