### ISSUE TITLE
HttpSocket support for oAuth 2

### ISSUE THREAD

**Issue by bobmulder** [cakephp/cakephp#6746]
Hey all,

At the docs (http://book.cakephp.org/3.0/en/core-libraries/httpclient.html#oauth-1-authentication) I saw that oAuth 1 is supported by the HttpSocket. Is there also a way for supporting oAuth2?
I am new to oAuth 2 so sorry if this is a stupid issue ;)

Greetz

Bob

**Comment by markstory** [comment]
There is no explicit support for oauth2 because in most cases all that is required of clients is to send an access token (usually as a header). I didn't think it was worth the indirection to save a tiny bit of typing.

For example:

```php
$http = new Client(['headers' => ['Authorization' => 'Bearer XXXX']]);
```

Is all that is needed to enable oauth2 tokens for many implementations.

**Comment by bobmulder** [comment]
Ah okay, thank you @markstory. I understand it's a tiny bit of typing ;).
Maybe you should extend the documentation with this piece of code to explain the use of OAuth2 for beginners?

**Comment by markstory** [comment]
Sure, I can do that.

**Comment by markstory** [comment]
cakephp/docs#2839 open now.
