### ISSUE TITLE
Why foreignKey in HasMay association is needed

### ISSUE THREAD

**Issue by cakephpman** [cakephp/cakephp#6862]
Hello,

I want to have multiple foreignKeys on my relationships table. Here is a sample of my database schema :

```
persons(id, ...)
relationships(id, person1_id, person2_id, ...)
```
In my PersonsTable.php : 

```php

<?php

public function initialize(array $config)
  {
    $this->hasMany('Relationships', [
                      'foreignKey' => false,
                      'conditions'  => ['person1_id' => 'Persons.id',
                        'OR' => ['person2_id' => 'Persons.id']
                      ]
                   ]);



  }

?>
```

I have this error when I perform a find and contain Relationships : 
```
Cannot have foreignKey = false for hasMany associations. You must provide a foreignKey column.
```

That is possible to make allow foreignKey set to false ?

**Comment by lorenzo** [comment]
Because the association is loaded using another query, so it is necessary to have a field linking both tables so that the result set can be constructed.

This kind of relationship between people tables are better modeled using a belongsToMany.

Closing as the issue tracker is reserved for possible defects in the framework and not just general help.

**Comment by Oxicode** [comment]
lol
