### ISSUE TITLE
PHP INTL Extension optional

### ISSUE THREAD

**Issue by iamdriz** [cakephp/cakephp#6908]
Can we make the INTL extension requirement optional?

As we use CakePHP for all our applications that we host on Media Temple but they don't support the INTL extension on their grid platform and require that you upgrade to a dedicated box with full root access in order to enable it.

This isn't really feasible for us... due to costs and the fact we'd need a server admin because Media Temple don't look after dedicated boxes without even greater costs.

Can we get a version of Cake WITHOUT the INTL extension? Otherwise we are a bit stuck.

**Comment by dereuromark** [comment]
Why don't they support it? On every server I know it is as simple as e.g. 

    apt-get install php5-intl

Problem solved. Super simple, super effective.

**Comment by markstory** [comment]
@iamdriz Not really, as both text translations, datetime formatting, and number formatting all rely on it.

You could maintain a fork that doesn't have these features, or replaces them with implementations that accommodate your environment.

**Comment by sikker** [comment]
Best guess would be that if Media Temple can get away with selling a bigger
plan and disavowing all support expenses in the process, they want to.

Which brings me to my proposed solution: Find a better host provider :0)

Otherwise I would suggest you maintain your own fork of Cake with
references to and dependency on intl removed (for starters I'd just remove
the intl-requirement in the composer file and then I'd just fix every
releated error one by one afterwards.)

**Comment by ADmad** [comment]
@iamdriz Do yourself a favor and switch to a better hosting provider. There are numerous affordable hosting providers which provide latest PHP version and common PHP extensions like intl.

**Comment by lorenzo** [comment]
@iamdriz it is possible in theory if you don't use any of the i18n features of cakephp, but I guess that is difficult to say. For example, someone did this https://github.com/hraq/cake-intl

**Comment by iamdriz** [comment]
@lorenzo What does that plugin do? Act as though PHP INTL is installed and give basic features to allow CakePHP 3.x to run without the extension?

**Comment by ADmad** [comment]
@iamdriz Did you read its readme? https://github.com/hraq/cake-intl#notes

**Comment by ADmad** [comment]
If you have more queries regarding that plugin please ask it's author.

**Comment by iamdriz** [comment]
@ADmad I did but it doesn't actually say what it does (it says it does nothing) but I'm presuming it allows CakePHP 3.x to run without INTL. Which is great if so.

**Comment by HavokInspiration** [comment]
@iamdriz The plugins really does _nothing_. It creates "placeholder" classes with **empty methods** that will be loaded (only if ``intl`` is disabled) to silent what would trigger errors.

**Comment by CodeBlastr** [comment]
I know this issue is closed and old, but I've just got to voice my opinion because the headache this has caused me and continues to cause me is absolutely ridiculous.  Because Mac has PHP installed with the OS, and CLI uses one PHP and the local server stack can use another, it's an crazy nightmare to try and get cake to recognize that php-intl is installed.  I've probably spent at least 20 hours on this problem over the past two weeks.  Forcing this as a requirement (IMO) is a horrible decision and is making a long time user of CakePHP start to regret the decision to not switch to another framework instead of upgrading to CakePHP 3.x (heck maybe I still will).  If you think this is not effecting adoption then please consider the decline in people using CakePHP and the number of times this issue shows up on StackOverflow and continues to show up on StackOverflow a year later.  It's easy to blame the user, but should Cake be easy to install or require 10 hours of research to try and solve a problem that you don't even care about when you don't care or need internationalization. You might think it's a small number of people with the error (as some of the comments say), but I doubt you're considering all of the people who try to install and give up and just never report the issue because there are too many options for other frameworks.

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=cakephp+intl&tbs=qdr:m

**Comment by markstory** [comment]
> Because Mac has PHP installed with the OS, and CLI uses one PHP and the local server stack can use another, it's an crazy nightmare to try and get cake to recognize that php-intl is installed. 

Have you considered using homebrew to install a PHP binary that is easier to get php-intl working with?

**Comment by CodeBlastr** [comment]
Sorry I meant to add the "no reply necessary" on the end of that message.  I have tried homebrew, and numerous other things (I've spent 20 hours working on it, so I've pretty much tried everything).  I have it working, and don't need help, I just wanted to voice my opinion that CakePHP would be a better easier to use framework without it being a requirement. 

It's just not as easy as you all think it is (going by comments on this thread and the other's related to it), where everyone generally says... "just do this command ____", but they say it without knowing if the user is using nginx or apache, or is on mac or on windows or if apt-get is available or it isn't, etc..  The point being the actual solution to this particular error is super-specific to the particular setup and everyone has a different setup. Covering all of the ways to solve the error could never be covered in CakePHP documentation, and it's still not completely covered with 1,080 issues filed about it on Stackoverflow.  Thus it should not be a requirement.  ( Here's a stackoverflow site search for "cakephp intl" 
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=cakephp%20intl%20site%3Astackoverflow.com )

No reply necessary, but please reconsider making a custom php setup a requirement to simply install and try out CakePHP.

**Comment by lorenzo** [comment]
Do you need help setting it up? I can help you

**Comment by jhli** [comment]
As he said twice - he did it bit considers it a major hurdle to get started with CakePHP. 

I can't judge on that, as I moved my development into vboxes and then vagrant long time ago. Maybe an official dev-only vbox that has everything to run composer and cakephp3 could help?

**Comment by bravo-kernel** [comment]
cakebox?

**Comment by jadb** [comment]
@bravo-kernel include link!

@CodeBlastr, his suggestion will help https://github.com/alt3/cakebox

**Comment by chinpei215** [comment]
I released [Intlless plugin](https://github.com/chinpei215/cakephp-intlless) yesterday, which allows you to install CakePHP3 without intl extension. Although this plugin has several [limitations](https://github.com/chinpei215/cakephp-intlless#limitations), but I am glad if you are interested in my plugin.

**Comment by inoas** [comment]
@chinpei215 is there a the rationale - aside having issues to install INTL, having cloud or whatever platforms that do not support it etc. - to utilise the plugin? Like say do you favour anything instead of INTL, say for number and currency formatting?

**Comment by chinpei215** [comment]
@ionas If you have intl extension, there is no reason to use this plugin. Only one benefit I can see is:  if your application really don't use any locale specific features and if `__()` function is called many times, it works a bit faster if you use this plugin. (But I don't recommend to use this plugin if you have intl extension)

**Comment by Irvinhoe** [comment]
@CodeBlastr made a lot of sense and his concerns ought to be considered. There's not reason a developer should abandon cakephp just because a much much superfluous feature is a requirement to use it.
