### ISSUE TITLE
Allow CakePHP to connect to MS SQL Server using the recommended PDO_ODBC

### ISSUE THREAD

**Issue by jhurdman** [cakephp/cakephp#6990]
Per php.net, "On Windows, PDO_ODBC is built into the PHP core by default. It is linked against the Windows ODBC Driver Manager so that PHP can connect to any database cataloged as a System DSN, and is the recommended driver for connecting to Microsoft SQL Server databases."

PDO_ODBC is a driver that can connect to SQL Server, and works under Linux and Windows. Furthermore, per the copied paragraph, it is the recommended driver for connecting to Microsoft SQL Server databases. As CakePHP is designed for use with PHP, not Windows, this would seem like it should be the preferred solution to allow for connections under the largest number of scenarios.

**Comment by markstory** [comment]
CakePHP works fine with windows. We already support SQLServer through pdo_sqlsrv. Are you suggesting we also support it through pdo_odbc as well?

**Comment by jhurdman** [comment]
Since CakePHP is a framework for PHP, and nowhere does it indicate that it is for Windows, I think it would be useful for it to support the ODBC connector for MS SQL Server. I will acknowledge that it has some limitations as compared to SQLSRV, so it may be useful to support both, but the language is the same.

**Comment by ADmad** [comment]
> Since CakePHP is a framework for PHP, and nowhere does it indicate that it is for Windows

Yes you made that clear the first time itself :)  Would you like to help adding a driver for pdo_odbc ?

**Comment by jhurdman** [comment]
Sorry, I was a little rushed. I would indeed be interested in helping with it. I can especially help with testing and documentation, but I have started to work on making it connect on my local copy. If I manage to get it to connect, I will definitely offer what I can, but beyond the connection itself, I am not sure everywhere it ties in to the framework.

**Comment by markstory** [comment]
Well using SQLServer kind of implies you are running at least _some_ windows servers. If you're willing to help, I don't see why we couldn't have an `OdbcSqlserver` driver.

**Comment by cpatter1** [comment]
It's disappointing that connecting an enterprise server (Linux/Apache/PHP) to an enterprise database (MSSQL) is not a priority for CakePHP 3. Yes, MySQL/MariaDB is simpler and easier, but not every developer, especially in enterprise level situations, can choose the database he has to work with. I'd write the thing myself if I had the requisite knowledge, but I don't which is why I prefer to use Cake.

**Comment by lorenzo** [comment]
Unfortunately Microsoft does not offer php drivers for their database that can be used in Linux, which makes things very difficult for us.

**Comment by raul338** [comment]
I guess you can use [Microsoft/msphpsql](https://github.com/Microsoft/msphpsql) once it reach some stability

**Comment by thinkingmedia** [comment]
*The following contains trolling comments and may not be suitable for all members to read.*

@cpatter1 Microsoft does not consider (Linux/Apache/PHP) to be an enterprise server.

@lorenzo Microsoft does supply drivers for Linux, and they can be downloaded via the below link. 

https://msdn.microsoft.com/en-us/library/hh568452

Running a Linux server with a Windows Database would be at best a hybrid setup, and introduces to many extra things that could break for us to test them all.

The majority of die hard MS-SQL fans would not use CakePHP as their web framework. As would any die hard Apply fan use PhoneGap over Swift or Objective-C.

CakePHP is best described a a RAPID development framework. Developers wanting to build things with Java, MS-SQL, C# or other "enterprise" level tools are not looking to get their projects done quickly or with a few people.

**Comment by lorenzo** [comment]
@thinkingmedia they are odbc drivers, though. They do not work in the same way as their official drivers form sqlserver

**Comment by josegonzalez** [comment]
@thinkingmedia That library is also in preview mode.

One potential blocker here is that many of the CakePHP core team members do not use Windows. Thats not universal of course[1], but that does limit the number of people that could feasibly start up a SqlServer somewhere and develop tests against it. For instance, I own 4 linux machines and have a home Macbook, but do not have a Windows machine, so even if I wanted to work on a database driver for SqlServer via ODBC[2], that would slow my progress for supporting the ODBC driver. I think that applies to all core members.

The workaround there would be if a community member would help pitch in and get an initial spike going. The following would also need to be figured out:

- Ongoing Maintenance
  - Given the scope - a database driver is pretty fundamental to an application - someone on the core team should be the steward of the feature. That can certainly be a community member who contributed the feature - assuming the collaboration goes well! - but my concern is that such functionality would fall by the wayside because no one on the core makes it their priority.
- Licensing issues
  - Is there a free SqlServer, and does it work the same as a paid version?
  - Are there base features we need to support in the core that the free version doesn't?
- Testing harness
  - Where are we running linux against sql server for all PRs? Travis does not support it.
  - How do we provide testing capabilities to CakePHP core team (and beyond) for running tests against the database?

One way this could work is similar to the [CakePHP 3 Driver for Oracle Database](https://github.com/CakeDC/cakephp-oracle-driver) maintained by CakeDC. I think that might be the best model, especially for any initial development. Once it hits a good standard, we would consider merging it - or making it a core plugin at least.

For the record, I'm am 👍 on someone (not it!) starting development of the driver, and I think the core team would be happy to help with feedback to push the driver in the right direction. Feel free to chat us up on IRC or Slack if you are interested in doing so.

---

<small>[1] hi @dereuromark!</small>
<small>[2] I don't want to, but I think it would be cool to write one for RethinkDB</small>

**Comment by cpatter1** [comment]
@lorenzo Isn't that the point? See first post re: PHP_ODBC

**Comment by lorenzo** [comment]
@cpatter1 The point would be to reuse all the code we have, without having to use different functions and constants.

**Comment by markstory** [comment]
> Where are we running linux against sql server for all PRs? Travis does not support it.

@josegonzalez We might be able to use AppVeyor to run odbc driver tests against SQLServer. 

@cpatter1 Sorry to disappoint you, but we're all doing this in our spare time, and doing the best we can. As @josegonzalez pointed out there are a bunch of challenges around supporting SqlServer from linux hosts that add enough friction to make this an uninteresting problem. If SqlServer & linux is a hard requirement of yours you'll have to look at other tools until someone in the community comes up with a solution.

**Comment by WebCOLT** [comment]
so pdo_sqlsrv is the one used by CakePHP ? what about the extension=php_sqlsrv.dll ? I'm asking because using PDO force us to install ODBC driver

**Comment by markstory** [comment]
We use the PDO driver provided by php_sqlsrv.dll.

**Comment by WebCOLT** [comment]
sorry, but I downloaded from Microsoft the php_sqlsrv.dll and the php_pdo_sqlsrv.dll,  from what I read on these days, I have to use only the php_pdo_sqlsrv.dll, but CakePHP throws me SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver 13 for SQL Server to communicate with SQL Server.  
So Cake is actually forcing me to get the ODBC driver, which I don't understand why.

**Comment by markstory** [comment]
What version of CakePHP are you using?

**Comment by ravage84** [comment]
@WebCOLT not sure why that error about ODBC comes up, but just to make sure, have you also installed the [SQL Server Native Client](https://www.microsoft.com/en-us/download/details.aspx?id=50402)?

**Comment by dakota** [comment]
@WebCOLT, that isn't CakePHP, but the Microsoft SQL PHP extension. It uses the ODBC driver for SQL Server. Read the Microsoft documentation on configuring the extension here: https://docs.microsoft.com/en-us/sql/connect/php/step-1-configure-development-environment-for-php-development

**Comment by ravage84** [comment]
Thanks, @dakota.
Seems Microsoft has replaced the "Native Client" with the "ODBC Driver" (probably just a different name for practically the same thing).

https://docs.microsoft.com/en-us/sql/connect/php/system-requirements-for-the-php-sql-driver

@WebCOLT CakePHP does not force you. Microsoft does. But it just normal that a (especially proprietary) RDBMS demands you to install some libraries to be able to connect.
For example, the PHP5/7-MySQL package on Debian/Ubuntu needs some MySQL client libraries to be able to connect.

@markstory 
I think the whole issue here is not relevant anymore.
Shouldn't we close?
If actual/new issues arise for SQL server & Linux, we probably should open a new issue for them...
