### ISSUE TITLE
CakePHP 2.6.x Containable behavior produces too much innecesary queries

### ISSUE THREAD

**Issue by Serginho** [cakephp/cakephp#7016]
If we have more that one level of depth, containable begins to execute innecesary queries.

it produces queries like

```
select * from table where id = 1;
select * from table where id = 2;
select * from table where id = 3;
...
```
intead of
```
select * from table where id in (1,2,3);
```

**Comment by lorenzo** [comment]
This is a known limitation of the behavior when containing too deeply nested associations. I would suggest not using the containable behavior for the problematic associations level and manually issuing the queries that will suit your need.

The limitation is very hard to fix without a big rewirte in the model layer, which is what happened for version 3.0. Closing as this was fixed in the most recent major version and due to the fact that it cannot possibly be fixed without breaking changes in 2.x

**Comment by chinpei215** [comment]
@Serginho For your information, I created a [plugin](https://github.com/chinpei215/cakephp-eager-loader) to solve this issue. I would be happy if you try it.
