### ISSUE TITLE
Entity accessors modifying data before being inserted into database

### ISSUE THREAD

**Issue by ArakTaiRoth** [cakephp/cakephp#7058]
So, this was tested with a datetime field, so perhaps there is more at work than I initially see, but I just wanted to see if this is an issue, or functioning as intended.

I have a `DateTime` column in MySQL. I am using the following code to convert a user entered `DateTime` field into a `Time` object:

```php
$this->Transactions->eventManager()->on('Model.beforeMarshal', function($event, $data) {
	if (!empty($data['purchase_time'])) {
		$data['purchase_time'] = Time::createFromFormat('F j, Y H:i', $data['purchase_time']);
	}
});
```
This is in my `beforeFilter` function of my `Controller`. This converts the data accurately into something like:

```php
'purchase_time' => object(Cake\I18n\Time) {
	'time' => '2015-07-10T12:00:00+0000',
	'timezone' => 'UTC',
	'fixedNowTime' => false	
}
```
But when I go to insert the data into the database, this accessor is being used before the data is being inserted:

```php
protected function _getPurchaseTime($purchase_time) {
  return date('F j, Y', strtotime($purchase_time));
}
```
Thus changing the data to a format that can't be saved as a `DateTime` field. Now, this is fine I guess, I can remove the accessor, but then I have to figure out a different method of changing the data to the format I want to display it in.

In addition, it seems weird to me that accessor's can modify the data before being inserted into the database, because what exactly is the point of an accessor then? I mean if it modified the data before being inserted into the database, then I don't need it any longer when I take the data out, I can just display the data the way it was inserted.

**Comment by markstory** [comment]
You shouldn't need to manually convert datetime columns. The orm does that as part of the marshalling process.

Acessors are supposed to be used when inserting data, as they define the entity's contract with the outside world. The saving process is part of that outside world which is why the accessors are used. Generally, I would avoid putting presentation logic in the entity classes. Instead I would focus entities on core data issues and tranformations related to the data your application needs everywhere. Presentation logic should ideally be kept in view elements, helpers and cells.

**Comment by ArakTaiRoth** [comment]
Okay, and that's where I misunderstood. I had thought accessors were used to manipulate the data into something different, like virtual properties. Not that they were used to change how data was inserted.

**Comment by markstory** [comment]
They can also be used to create virtual properties. As only properties that are in the schema will be persisted. For could have a formtted_purchase_time property that doees what ypou have now.
