### ISSUE TITLE
HttpSocket when 'ssl_verify_host' is false, set the 'verify_peer_name' context option to false.

### ISSUE THREAD

**Issue by nojimage** [cakephp/cakephp#7078]
In CakePHP 2.x.

PHP >= 5.6.0, SSL context options add the `verify_peer_name` and this default value is `TRUE`.

http://php.net/manual/en/context.ssl.php

When the actual hostname and the common name of the certificate is different (like during development), if I want to disable the check of the hostname of the certificate, it must be written as below:

```
$http = new HttpSocket([
   'ssl_verify_host' => false,
   'ssl_verify_peer_name' => false,
]);
```

This is redundant.
I without having to worry about the version of PHP, I want to finish by writing the only `'ssl_verify_host' = false`.

**Comment by markstory** [comment]
Seems pretty reasonable to me.

**Comment by DavidOliver** [comment]
Am I right in thinking this is a proposal to set `ssl_verify_peer_name` to false whenever `ssl_verify_host` is set to false? I'm no expert, but if so wouldn't that be creating a horrible, counterintuitive and almost malicious-seeming gotcha?

For example, because I'm currently running < PHP 5.6, I've had to set `ssl_verify_host` to false because PHP's wildcard matching for CN was broken. However, I don't want peer checking to be turned off, too.

The actual issue here seems to be the lack of an SSL certificate for a development server, or using TLS when it's not required in development.

**Comment by josegonzalez** [comment]
You should use an ssl certificate in development if you use one in production, so I'm :-1: on changing this.

If a developer needs the option, they can set it manually in their own code.

**Comment by markstory** [comment]
Good point @josegonzalez. Closing as forcing people to think about their security tradeoffs is important.

**Comment by nojimage** [comment]
I see. :+1:
