### ISSUE TITLE
2.7: Shortened version of plugin shells only works 2nd time

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#7149]
New in 2.7 is that the shells are supposed to work without the plugin prefix.
But in fact it only works after once called verbosely.

So (Setup.Maintenance shell)

    cake Maintenance

fails, but

    cake Setup.Maintenance
    cake Maintenance

works then.
Is there a way we can actually short-call it right from the beginning?
Otherwise the value of it is questionable.

v: 2.7.1 (latest)

**Comment by biesbjerg** [comment]
Is that supposed to work at all?

From the release 2.7 notes:
```
Plugin shells that share a name with their plugin can now be called without the plugin prefix. For example Console/cake MyPlugin.my_plugin can now be called with Console/cake my_plugin.
```
Source: http://bakery.cakephp.org/2015/07/11/cakephp_2_7_0_released.html

I read it like `cake Maintenance` should work only if `MaintenanceShell` is located in a plugin called `Maintenance`?

**Comment by dereuromark** [comment]
I think (or thought) the backport of 3.x aimed to to what 3.x can, any shell can work without the plugin prefix if there is no collision in naming.

**Comment by robertpustulka** [comment]
Sorry, it's my failt. I thought that the idea of 3.0 short shell calls is that the shell has the same name as the plugin it resides in.

**Comment by markstory** [comment]
What changes in the second run? Is the cache primed?

**Comment by markstory** [comment]
#5681 was the pull request that added the short aliases feature. While the code is correct, this issue is caused by the global class name index in `App`. Because on the second run the class cache has been primed, `App::uses()` can always find the shell class as it knows where to find it.

I don't think there is a way around this issue unfortunately. The behavior you've seen here was never intended to work, and the original feature of making short plugin names does work as intended.
