### ISSUE TITLE
sanitation issue of the Controller::header() function in library 

### ISSUE THREAD

**Issue by bharat27** [cakephp/cakephp#7154]
hey Team ,

My security team reviewed our new application code and found out that the function Controller::header() in the cakephp library not using any mechanism to sanitization the parameter. When investigate further found that header() is simply passing the parameter to "$this->response->header($status)" which return the array of parameter in response without sanitizing it.

Can you please let me know what will be the solution for this because security testing team will not pass our application without the proper solution or fix.

Thanks & Regards,
Bharat Bisht

**Comment by Oxicode** [comment]
Check http://www.elladodelmal.com/2014/10/x-xss-protection-http-header-y-los.html

**Comment by markstory** [comment]
I am not familiar with the type of issue your team is concerned about. Do you have an example of what they are concerned about? Generally headers don't contain user data outside of location and cookie data.

**Comment by markstory** [comment]
ping.

**Comment by Marlinc** [comment]
I'm very interested to know what could be sanitized in the response headers.

**Comment by ndm2** [comment]
Maybe the OP is refering to the fact that `Controller::header()` (which doesn't exist in 3.x anymore) says it would expect a string, but actually accepts an array too, as the value is passed directly to `CakeResponse::headers()`?

Given that someone passes user data to `Controller:header()` without checking whether it's in the expected format, this could lead to possible header injections. However this would of course only be an issue in case the user data is not just used for the value part of a header, but is passed _as is_, which in turn is a security issue itself anyways, as it allows a user to define at least one arbitrary header... so I guess in the end this is not that big of an issue, and more something that just needs to be documented properly.

Other than that I can't see why headers would need to be sanitized, the only exception that comes to my mind right now would be null bytes or `CRLF`, the latter could be used to inject headers, however PHP has built-in protection against that since 4.4.2/5.1.2, it will error out just like on null bytes.

The only possible problematic situation I could image, would be that when something like `foo\r\nbar` is being injected, it will cause that the complete header will not be sent (unlike with `foo\r\n`, which is sent but without `\r\n`), so in case something relies on the header being present, things could break.

**Comment by markstory** [comment]
Without any additional context or information, there isn't much that we can do.
