### ISSUE TITLE
3.0 - Debug mode influences json behaviour

### ISSUE THREAD

**Issue by thpar** [cakephp/cakephp#7360]
I have a page using jQuery (`$.getJSON()`) to repeatedly poll a JSON page to get a simple json response. I tried both the template method (`Template/Jobs/json/poll.ctp`) as the `_serialize` method. I have the RequestHandler component loaded.

In debug mode: `'debug' => true` (in `app.php`), both methods work just fine.

In production mode though (`'debug' => false`), neither of the methods work. Both yield a 500 response, because Cake is looking for a template file `Template/Jobs/poll.ctp` and cannot find it. It seems to ignore the `Accept: application/json` request header.

Workaround: enable Routing File Extensions in `routes.php`:
```
Router::extensions(['json']);
```

This seems like a bug in two ways:
 - As I don't use the `.json` extension, the routing file extensions should not be involved.
 - It is clearly not right when debug mode influences json responses.

**Comment by lorenzo** [comment]
@thpar What version of cakephp is this?

**Comment by thpar** [comment]
3.0.13

**Comment by lorenzo** [comment]
@thpar What is the url you are requesting to get the json data?

**Comment by thpar** [comment]
The url that gets to the action of the controller that fetches the data for the JSON reply.
In this example: `/jobs/poll/<job_id>`

where `<job_id>` specifies the 'job' that's being polled.
I construct the URL with `Url->build()`

**Comment by markstory** [comment]
The issue is not related to `debug = true`, but the presence of DebugKit. DebugKit adds the `json` extension in debug mode so that it can function. While DebugKit does use scopes to add the json extension only to the routes it uses, RequestHandlerComponent uses the presence of JSON anywhere to enable accepting JSON payloads.

I don't think there is anything to fix here, as you should be defining the extensions you want in each scope.

**Comment by lorenzo** [comment]
I can reproduce this problem. There is a bug in the RequestHandler component
