### ISSUE TITLE
form select shows error when optgroups is numeric

### ISSUE THREAD

**Issue by arilia** [cakephp/cakephp#7361]
I want to group options in a `find('list')` by year so I did something like

    find('list', ['groupField' => 'year])

And I  get an array like this

    $options = [
       2014 => [
          'Value 1' => 'Label 1',
          'Value 2' => 'Label 2'
       ],
       2015 => [
          'Value 3' => 'Label 3'
       ]
    ];

and in my view

    echo $this->Form->select('test', $options);

then I get this notice

Notice (8): Undefined index: text [CORE/src/View/Widget/SelectBoxWidget.php, line 256

**Comment by markstory** [comment]
While the notice error should not be there, you will likely have to convert your keys into strings. The reason is that with integer keys, the data you have is impossible to disambiguate from the 'complex' option format:

```php
['value' => 'a', 'text' => 'Albatross'],
['value' => 'b', 'text' => 'Budgie', 'data-foo' => 'bar'],
``` 

Because integer keys create ambiguity in the input types, we require that the keys for optgroups be strings, or if you cannot convert the keys to strings, you can also define the 'options' key for nested options:

```php
2014 => [
    'options' => [
        'beaver' => 'Beaver',
        'elk' => 'Elk',
    ]
]
```

**Comment by markstory** [comment]
I think I've got a solution to this, I'll post an update tomorrow.

**Comment by markstory** [comment]
Pull request up now.
