### ISSUE TITLE
3.0.13 - SQLSTATE[HY000] General error: 1 too many sql variables when loading a lot of fixtures.

### ISSUE THREAD

**Issue by Xety** [cakephp/cakephp#7373]
Hello,

While doing my testcases, i had this error `SQLSTATE[HY000] General error: 1 too many sql variables`  when i was running my tests.
This error come from SQLite where the request has more than 999 variables.
I'm using the ACL plugin, that means i have 3 fixtures :
Acos :170 records,
Aros : 6 records,
Acos/Aros : 70 records 
and in some test controllers i have a lot of fixtures (+ those ACLs fictures) and i got this error.

I finally solved my problem by using the cached files from the ACL plugin. (So i don't use the ACL fixtures = -250 records actually)

But my question is :
How can we do if we need a lot of fixtures in a test controller and we got this error ?
Because on big website, that can be a problem.

**Comment by markstory** [comment]
@Xety Don't use sqlite for the tests unless your app runs with sqlite normally. You can always override the insert method for troublesome fixtures and insert the rows in a way that won't hit placeholder limits.

**Comment by Xety** [comment]
Hello Mark,

Yes i switched my tests to MySQL instead of SQLite. But good to know that we can override the insert method, can be helpful in some case.

Thanks for your answer !

**Comment by joostdb** [comment]
I'm having this same error (SQLSTATE[HY000]: General error: 1 too many SQL variables) from time to time without any obvious reason. My DB is MySQL. When refreshing, the error disappears.
Any idea how to fix this?

**Comment by dereuromark** [comment]
I also encountered it once. Not sure how to reproduce it, though.

**Comment by saraer** [comment]
I guess this error belongs to debugkit, it sometimes try to clear cache query logs.
And if too many logs has been stocked, throws exception errors like that, till you delete sqlite file(tmp/debug_kit.sqlite) manually.
At least my problem solved after deleing file.

**Comment by ProFire** [comment]
I agree that this error occurs due to debugkit. When I checked my logs, this is what I noticed:

2015-10-12 05:50:10 Error: [PDOException] SQLSTATE[HY000]: General error: 1 too many SQL variables
Request URL: /pathtoapp/accounts/login.fyr
Stack Trace:
#0 C:\pathtoapp\vendor\cakephp\cakephp\src\Database\Driver\Sqlite.php(92): PDO->prepare('DELETE FROM pan...')
#1 C:\pathtoapp\vendor\cakephp\cakephp\src\Database\Connection.php(216): Cake\Database\Driver\Sqlite->prepare(Object(Cake\ORM\Query))
#2 C:\pathtoapp\vendor\cakephp\cakephp\src\Database\Connection.php(268): Cake\Database\Connection->prepare(Object(Cake\ORM\Query))
#3 C:\pathtoapp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#4 C:\pathtoapp\vendor\cakephp\debug_kit\src\Model\Table\RequestsTable.php(92): Cake\Database\Query->execute()
#5 C:\pathtoapp\vendor\cakephp\debug_kit\src\Routing\Filter\DebugBarFilter.php(187): DebugKit\Model\Table\RequestsTable->gc()
#6 C:\pathtoapp\vendor\cakephp\cakephp\src\Event\EventManager.php(389): DebugKit\Routing\Filter\DebugBarFilter->afterDispatch(Object(Cake\Event\Event), Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\pathtoapp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\pathtoapp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\pathtoapp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(92): Cake\Routing\Dispatcher->dispatchEvent('Dispatcher.afte...', Array)
#10 C:\pathtoapp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#11 {main}

**Comment by swiffer** [comment]
as @markstory noted it's possible to overwrite the insert method like so

```
    /**
     * {@inheritDoc}
     */
    public function insert(ConnectionInterface $db)
    {
        if (isset($this->records) && !empty($this->records)) {
            list($fields, $values, $types) = $this->_getRecords();
            $query = $db->newQuery()
                ->insert($fields, $types)
                ->into($this->table);

            if ($db->driver() instanceof Sqlite) {
                $maxRows = ceil(999 / count(Hash::get($this->records, '0')));
                $i = 0;
                foreach ($values as $row) {
                    $query->values($row);
                    $i++;
                    if ($i == $maxRows) {
                        $i = 0;
                        $statement = $query->execute();
                        $statement->closeCursor();

                        $query = $db->newQuery()
                            ->insert($fields, $types)
                            ->into($this->table);
                    }
                }
            } else {
                foreach ($values as $row) {
                    $query->values($row);
                }
            }
            $statement = $query->execute();
            $statement->closeCursor();

            return $statement;
        }

        return true;
    }
```
