### ISSUE TITLE
existsIn() fails on "empty" fields

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#7392]
I think it is a common use case to have optional selects with an empty field. When you submit that empty select the rule existsIn() will stop you from saving it because it won't be able to find the empty ` ` id.

Validation rules:
```php
		$validator
			->requirePresence('country_id', 'create')
			->allowEmpty('country_id');
```

Build rules:

```php
	public function buildRules(RulesChecker $rules) {
		$rules->add($rules->existsIn(['user_id'], 'Users'));
		$rules->add($rules->existsIn(['country_id'], 'Countries'));
		return $rules;
	}
```

Just in case somebody else needs this fixed or this doesn't get fixed in the core, here is my work-around for this in the entity object:

```php
	protected function _setCountryId($value) {
		if (is_string($value) && empty($value)) {
			$value = null;
		}
		return $value;
	}
```

But this should be addressed in the core, especially when the schema allows "null" for a field.

**Comment by markstory** [comment]
The ExistsIn rule already checks against `null` and doesn't trigger failures when nullable fields have `null` values. Are you suggesting that we apply the same behavior for `''` as well?

**Comment by jhli** [comment]
Should imho be named differently like existsInOrNull

**Comment by ADmad** [comment]
If ExistsIn does not fail when passing empty string to nullable field then imo no change is required.

**Comment by burzum** [comment]
@ADmad how do you get NULL from the `empty` option of the select?

```php
				echo $this->Form->input('country_id', [
					'empty' => __('Remote / Anywhere'),
					'label' => __('Country'),
					'type' => 'select',
					'options' => $countries
				]);
```

It's a string for me. So this in contradicting with the behavior of existsIn().

**Comment by jhli** [comment]
Again, I am suggesting that existsIn should do what it says and be strict and existsInOrNull / should be non-strict allowing '' and/or NULL and/or !isset.

bake should then set one or the other based on if NULL / NOT NULL is set. Not sane?

**Comment by ADmad** [comment]
> how do you get NULL from the empty option of the select?

You can't. I never said you could, you probably misread / misunderstood my comment.

**Comment by burzum** [comment]
@ADmad I'm aware of that you can't. That's why I've asked that rhetoric question. The problem as I see it is:

* existsIn() won't accept '' 
* input() "empty" doesn't allow me to set NULL for "empty"

Which makes it impossible to use the default CakePHP tools to bypass the problem. So either make existsIn() accept '' and turn it to NULL or add a possibility to change the value for the "empty" option.

**Comment by markstory** [comment]
I think treating '' and `null` similarly in the ExistsIn rule is reasonable. Both values will convert into `null` for integer fields. Treating '' and null the same may fall down for UUID fields though.

@burzum are you using integer columns?

**Comment by burzum** [comment]
@markstory no, it's a UUID in this case.

Why would this fall down for UUID fields? Pseudocode: If <field> allows null and data is empty turn data to null.

**Comment by dereuromark** [comment]
I agree with @burzum that this should be handled gracefully be the ORM, depending on the schema "default null" setting. Fields that are default null never want to store an empty string, especially not primary or foreign keys. Otherwise, having mixed strings and nulls makes searching for the empty value way more difficult and cumbersome.

**Comment by ionas** [comment]
:+1: for pointing out ```ExistsIn``` accepting ```NULL```.

**Should accept neither** ```NULL``` nor ```''``` by default independent of whether the SQL schema set the field to ```NULL``` or ```NOT NULL```, because if you set something in PHP world's model domain it should overwrite the magic defaults derived from the SQL schema.

From the book ```While you could rely on database errors to enforce constraints, using rules code can help provide a nicer user experience. Because of this CakePHP includes an ExistsIn rule class``` http://book.cakephp.org/3.0/en/orm/validation.html#foreign-key-rules

```ExistsIn``` is about enforcing schema constraints. So the method should be taken by word and not be build around fitting specific request data: "I want to have an optional related record select".

When bringing up my point of view on IRC another suggestion by burzum in regards to this was to have a ```'strict'``` option for the rule instead of also having ```ExistsInOrNull```. He suggested that this option could by default be set to ```false```. I suggest this option should default to ```true```, but for BC it could default to ```false```, interim.

This option could also help with differentiating if ```NULL``` nor/andor/xor ```''``` are allowed for UUID vs integer etc. by having other values besides ```true``` and ```false```.

As suggested by me (jhli) above, bake could generate this option value depending on if the SQL schema has it set to ```NULL``` or ```NOT NULL```.

**Comment by markstory** [comment]
@burzum '' won't be cast to null for a string column, and if that column has a proper foreign key constraint, that constraint will cause the insert to fail.

>  Fields that are default null never want to store an empty string.

@dereuromark While we can try to make that true, I'm am certain that there exist schema where both '' and null are stored.

@ionas Having a foreign key with a nullable field accept null values is far from 'magic defaults' in my opinion. Using the schema metadata to correctly generate the right type of constraint code seems very reasonable.

**Comment by jhli** [comment]
I do agree in regards to bake. I don't think I do agree in regards to EXPLICITLY setting ExistsIn. If set it must exist. I like if the php model layer takes precedence before the magic extracted from sql schema as it is the SAME with validation where if validation is set in the php model layer it overwrites non existing sql field constraints. But I think I made my point. Nvm.

**Comment by lorenzo** [comment]
Maybe we could skip marshalling empty strings foreign keys as we already do for primary keys?

**Comment by markstory** [comment]
@lorenzo That is a good option as well.

**Comment by dereuromark** [comment]
;) indeed.

**Comment by ionas** [comment]
:+1: for making foreign/primary keys treatment behave consistent.

**Comment by lorenzo** [comment]
I tried implementing my suggestion. But I realised that the logic for converting an integer to null when provided an empty string is already there.... Is your column an integer? If it is... how did an empty string get into that column?

**Comment by dereuromark** [comment]
@lorenzo I think burzum mentioned a UUID.

**Comment by burzum** [comment]
@markstory while working with this terrible legacy DB I ran into the same issue again. Can't we show an E_USER_WARNING when the schema is NOT NULL but an empty string is passed?

**Comment by markstory** [comment]
'' satisfies `NOT NULL` though.
