### ISSUE TITLE
Decrypt function return null

### ISSUE THREAD

**Issue by laxman1223** [cakephp/cakephp#7510]
$data=$conn->query("select Password,DoctorId from doctorsdata where Email='$DoctorLoginUserName' ");
	   $row = $data->fetchAll('assoc');
	   $EncryptPassword=$row[0]['Password'];
	   $key = 'wt1U5MACWJFTXGenFoZoiLwQGrLgdbHA';
	  $decryptPassword=Security::decrypt($EncryptPassword,$key);

**Comment by markstory** [comment]
I bet your data was truncated when saved, or has otherwise been mangled/has the wrong keys.

Beyond that this code has SQL injections, and passwords should be [hashed not encrypted](http://codahale.com/how-to-safely-store-a-password/).

Closing as the encrypt/decrypt functions have tests showing that they work when used correctly.
