### ISSUE TITLE
Retrieving data not the same in cakephp and in MySQL

### ISSUE THREAD

**Issue by titamrtn** [cakephp/cakephp#7519]
Hi,
I'm actually creating application with cakephp3. I have table employes (id, nom, prenom, cin)
CIN is unsigned BIGINT and is unique.
When i retrieve data in SQL i got something like this.

![db](https://cloud.githubusercontent.com/assets/5078563/10359589/a196a6a2-6da2-11e5-8b80-9dc9b9571bb0.PNG)
And in my apps i got this : 
![affichage](https://cloud.githubusercontent.com/assets/5078563/10359599/b731f098-6da2-11e5-8876-21368788af32.PNG)

I think it's php 32-bits issue but when i don't use cakephp i got a "true" result.
If someone can tell me how to fix it. Thanks

**Comment by ADmad** [comment]
phpMyAdmin must be showing the values of `cin` as string. 

CakePHP typecasts values to their proper type based on column's data type. Since your environment cannot handle bigint you need to force the date type for field `cin` to `string`. Check the example at bottom of [this](http://book.cakephp.org/3.0/en/orm/database-basics.html#data-types) in manual for info on how to customize datetype for a column.

**Comment by AD7six** [comment]
Why did you create this issue (issues are not for questions) after asking and having answered [the same question on stackoverflow](http://stackoverflow.com/q/32991775/761202) ?
