### ISSUE TITLE
Proposal: new built-in Exception (503 Service Unavailable)

### ISSUE THREAD

**Issue by volponi** [cakephp/cakephp#7530]
Hi,

Scanning through the list of built-in Exceptions on CakePHP 3, I missed the 503 Service Unavailable option. Is there a reason for just error 500 & 501 being implemented at 500-level?

**Comment by ADmad** [comment]
The framework itself has no use case for throwing a 503 exception which is why there is no specific exception class for it in the core. There nothing preventing you from creating a custom exception class in your app with the status code and message you need.

**Comment by volponi** [comment]
Allright. Thanks @ADmad.

**Comment by alexmcroberts** [comment]
I've come across this issue many times, with different http status codes not implemented. IMO, the Framework should support every HTTP Status Code currently defined at http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml - given the list isn't particularly big, and having them centralized would, I imagine help out a lot of developers who go through the same issue.

Happy to do the work and make a PR if it's likely to be accepted? /cc @ADmad

**Comment by ADmad** [comment]
Every [HTTP status code](http://api.cakephp.org/3.0/class-Cake.Network.Response.html#$_statusCodes) is already supported and you can use [Response::statusCode()](http://api.cakephp.org/3.0/class-Cake.Network.Response.html#_statusCode) to set the one you need.

**Comment by markstory** [comment]
Every status code seems a bit heavy. Would it be acceptable to have generic exception classes for 50x and 4xx errors? Or pehaps factory methods like `throw new HttpException::failure('oops', 503);` ?

**Comment by alexmcroberts** [comment]
Perhaps every status code is too heavy, but I have at one project which heavily reliant on status codes. The Network\Response.php contains every status code in an array already, so perhaps a factory method could use that as a source so

throw new HttpException(503);

Looks up the array in Network\Response.php and throws the already defined message

**Comment by volponi** [comment]
@alexmcroberts that's what I was thinking about when opened this issue. If we already have all the status codes on Response::statusCode() then the HttpException just have to relay this information.

**Comment by markstory** [comment]
Could a reasonable interface also be:

```php
$this->response->fail(503);
```

This new method would throw an exception halting the request.

**Comment by ravage84** [comment]
I would go with
```` php
$this->response->fail($statusCode, $message = null);
````
where the message is optional.

**Comment by markstory** [comment]
@ravage84 Seems reasonable to me.

**Comment by ADmad** [comment]
Can this be closed now since `ServiceUnavailableException` and other exceptions have been added in #7934?

**Comment by ionas** [comment]
* I'd not include more explicit error codes (e.g. all) just because, though there might be a reason to add specific ones - possibly 505 when HTTP2 becomes available more broadly.
* While I like the `response->fail()` interface and name. I'd go consistently with either having `throw exception ...` in your code or having it never for response errors. This suggested method breaks with this consistency unless all the specific HTTP exceptions are being removed. So :-1: from me.

Suggestion: Can't ```HttpException```, that is already in the core, but UNDOCUMENTED on http://book.cakephp.org/3.0/en/development/errors.html#using-http-exceptions-in-your-controllers be documented to be used for any other exception that changes the responses http status code?

Could this work? Should I add it to the book as an example to throw arbitrary Http Exceptions in case you don't want to add those as class files yourself? 
```php
throw new HttpException('HTTP Version Not Supported', 505), 
```
http://api.cakephp.org/3.1/class-Cake.Network.Exception.HttpException.html#___construct

**Comment by markstory** [comment]
@ionas Adding documentation sounds like a good idea to me. With the new set of exceptions and some additional documentation I think this can be closed.

**Comment by ionas** [comment]
**A)** Gave it a short try and calling ```HttpException``` does not work, because it is an ```abstract class```.
```php
throw new \Cake\Core\Exception\Exception('HTTP Version Not Supported', 505);
```
... however works.

**B)** Concerns:
1. It lays in a different namespace that seemingly has nothing to do with HTTP exceptions
2. Why do the core exceptions (\Cake\Core\Exception\Exception) support HTTP error status codes to begin with? As it is clearly intentional - **is it still good**? Should you not simply use ```HttpException``` instead and HttpException should be the Exception that supports HTTP status codes and sets responseHeaders not the core Exception?

**C)** In case this should be changed 4.x is a good target as it is a BC break. Interim I'd suggest taking away the abstract keyword in class HttpException. I gave it a try and afterwards this code runs flawlessly:
```php
throw new \Cake\Network\Exception\HttpException('HTTP Version Not Supported', 505);
```

**D)** Are there objections to just take away the ```abstract``` keyword from `\Cake\Core\Cake\Network\Exception\HttpException` (e.g. src/Network/Exception/HttpException.php)?

**E)** **For a future milestone** I'd also like to suggest ```Http4xxException extends HttpException``` and ```Http5xxException extends HttpException```. That way it is easy for a developer to differentiate between internal and external (request related) exceptions. Http4xx would take any (valid?) http code starting with 4??, the Http5xx one with 5??.

**Comment by ADmad** [comment]
Closing as related PRs have been merged.
