### ISSUE TITLE
Adopting a Code of Conduct

### ISSUE THREAD

**Issue by josegonzalez** [cakephp/cakephp#7682]
Even though I think we're already pretty good open source participants, having a code of conduct would - imo - be a way of solidifying our approach to community involvement.

I more or less want to have a document we can point at that will cover cases both in issue trackers, chat, and elsewhere that says how we want people to interact with/treat each other.

This is what I use in dokku: [Contributor Covenant](http://contributor-covenant.org/). Does anyone have any thoughts on the matter/additions they'd like to add to such a doc?

**Comment by phpnut** [comment]
I was recently look at http://opensourcebridge.org/about/code-of-conduct/ as a COC for us to use. Either one of these could be used.

**Comment by lorenzo** [comment]
:+1:

**Comment by josegonzalez** [comment]
What email should we have people send stuff to?

**Comment by jippi** [comment]
It's so american to have COC if you ask me.. all those things mentioned in those are always a no-brainer, normal decency, well behaved behavior ... I'm for it, but fear it could be a zealot goto for complains when people, like Danes / Europeans, go nuts with their dark humor or irony.. seen how other projects has been attacked for stuff that really is nothing but a non-issue due to COC makes me worry a bit about it..

Can't we just add "Don't be a dick/cunt/penis-vagina" as our CCC and move on ? :)

**Comment by josegonzalez** [comment]
Like I said before, I think we've been good in the past - you and I included! - so I really doubt that will be an issue. This is more about having something in writing, similar to how we document that the issue tracker isn't a help forum, or the kind of information we want in a good bug report.

**Comment by josegonzalez** [comment]
Also yeah, don't be a dick.

**Comment by jhli** [comment]
I ll raise some points. OSB = open source bridge, cc = contributor covenant.

Cc seems muss less focussing on gender than osb. Osb though has a lot of things it should not have. First of all a guideline of should-dos. That is not good at all as it imposes regulated behaviour (models). Coming from social sciens as a major, havimg written a diploma thesis about self management in short this is a drawback of non-reflective humanism.

A don't-do list is much better. As for the don't do list the osb looks good aside that it touches some topics that have nothing much to do with online collaborative software development, like the no touch before consent note. And especially that notion but also the desire to regulate social behavior in a juridical form is very non-euroish imho. The do not touch note might be perfectly okay for physical workplace but in general is already weirdo (best bring a contract before you do the first kiss - says a soon married man).

Also saddening are the big brother aspects in osb relating to "reporting to superiors".

I am fine with a dont do list but - cc misses that. The biggest gripe with cc is that it does not speak about lesbs/gays, trans, age, language which are the strongest non economically issues.

Economical issues trump anything still. If you look at the top female facebook developers (hhvm, reactjs/flex) things are fine for them compared to some 14 years old boy that barely speaks english and has bad hardware. Recently I have also worked a bit eith stew eucen (fertile forest) and the language barrier just makes it hard and rather put things "on ignore". But instead of reporting that, (to whom anyway) Imchose to support himmon the language issues.

Long short: dont do lists okay - rest.... Too much orwell.

**Comment by markstory** [comment]
Taking a look at the [babel coc](https://github.com/babel/babel/blob/master/CODE_OF_CONDUCT.md) it seems quite reasonable and has a short list of the dont's that @jhli mentioned.

**Comment by ADmad** [comment]
> But instead of reporting that, (to whom anyway) I chose to support him on the language issues.

@jhli I appreciate that. 

Things like this is what we should concentrate on: helping those with language and other barriers and not worry about potentially offending the touchy ones.

**Comment by beporter** [comment]
I think it's worth pointing out that this thread is a bunch of dudes discussing something that disproportionately affects not-us. Myself included. Our lived experiences are not representative of those a CoC is partially designed to help and protect. We are not subject matter experts here.

**I am strongly for a CoC and I am partial to the Contributor Covenant.** Beyond that, my opinion is coming from the least helpful background possible so I'm going to set an example and **shut up**.

**Comment by jhli** [comment]
To get back to a productive discussion: what about a minimal don't do list?

**Comment by markstory** [comment]
@beporter I totally agree that we are likely not the best folks to decide this in isolation. I hope that we can leverage the great work others have done with projects like Contributor Convenant to get a baseline.

**Comment by ionas** [comment]
**Why CoC is rather ineffective?**
The primary issues with open source software IMHO are:
- Equality: Not everyone is equal despite that I wish it was the case economically and in terms of education. Some people will require more help to become members of open source projects that also contribute, others don't. This depends on economical (money, time), language, education, religion/culture and gender issues. A code of conduct does not solve this.
- Licenses: Licensing issues. MIT etc. enforces free riding and focus on proprietary development, (L)GPL enforces lawsuits and will exclude some who need to benefit from their closed source work to be able to contribute to MIT based open source. Code of conduct does not solve this.
- Missing rewards: There are usually no monetary incentives if you are not being payed through other channels (companies, projects, own software). This goes so far that in case some core developers change or lose positions in terms of economical configurations, their contributions will stop. Funding is a problem codes of conduct does not solve.
- Social exclusion: (Open source) Communities always work via social exclusion. If you have little reputation and make big suggestions, you will get ignored. If you have a grown and good reputation even if your suggestions are mediocre they might become mainstream. Code of conduct does not solve this. Strictly speaking, this has nothing to do with rational choices.
- Meritocracy: If meritocracy ain't fake, e.g. those having the most work and doing the hardest improvements are also those listened to and making decisions, it is a good thing. Codes of conduct may go against that, which is bad. Code of conduct hurts here. While at the same time...
- Fake meritocracy: There are also cases of fake meritocracy for example if people joined projects ages ago but don't really contribute much nowadays and still their reputation is big despite that the code base is mostly not based on their work anymore. In these cases reputation is big but does not match meritocracy. Code of conduct does not solve this.
- Getting into OSS is hard: Laravel's (and Rail's) success does IMHO mostly exist because of free video tutorials and awesome application (how to use the tool in practise) documentation. Whatever the economical drives are (behind Railscasts, a guy with burnout now, behind codeschool, behind lara casts, etc), this is one absolutely mandatory thing to have an open source project being successful and growing. Code of conduct does not solve this.
- Contributing is hard: There is a certain entry barrier for contributing because of big tool chains and little documentation on them. A code of conduct does not solve this.
- Implicit discrimination: The strongest way to discriminate is ignoring, disregarding and disencouraging people that want to contribute. I don't mean demands for features that people don't want to implement. What I mean is that if you have no (or a bad) reputation, even good changes might get rejected. A code of conduct won't help here. If that rejection is implicitly based on language, culture, religion or gender - A code of conduct won't change this. 

These are the issues we should focus on primarily to have a striving and welcoming open source community.

Aside those issues, a CoC is worse than law. Laws are something that are best kept at a minimum. If not you will have experts interpreting and juggling law to benefits of those being able to pay these experts (de-facto practise).
Laws (in comparison to contracts) usually only govern what you should NOT do. Worse than that are contracts. Contracts, to have an effect, also need to be explicitly signed. Contracts require you to comply. The suggested CoCs are contracts. They require you to comply and fit your behavior to the requirements. For every sentence and statement, every comment and PR, every answer, ever facebook like, you will have to think: Does this comply with the 3 pages requirements of the CoC? IF YOU DON'T DO THAT then you don't comply with the CoC and break the contract. My assumption is, most people won't do that even if they say "Yeah, CoC is a great idea" - that's CoC as a marketing effort. Something I won't subscribe to.

A code of conduct is a "contract" not a "law". It is a document enforcing certain behaviour. This takes away freedom and makes things unnecessarily complex and regulated. A modern trend is deregulation economics and regulating social life. I'd rather see things go exactly(!) the other way around which helps people being FREE (as in freedom and as in beer :p).

Over regulating social behaviour while under regulating economical issues creates a generation of people "gaining" burnout, depression and personality disorders (you can dig up tons of research papers from social, medical and psychological sciences on these issues). In short this is because following, by internalizing, requirements is much harder than obeying prohibitions. If you are not happy with a prohibition there is an easy "surface" to struggle with (the ones saying: this is forbidden, and that as well). If you are not happy with requirements you do usually resign from the social group that sets those up, or fail to comply and suffer.

I will say that I had my gripes with OSS development and the "offensive" behaviour that happened a very few times did not hurt more than the implicit one where communities mostly work by social exclusion and reputation.

After those words - so why is a CoC or something similar useful in any way then?

**CoC and where behavioural guidelines are useful?**

CoCs *can* be simple marketing. I don't see the point of adopting a CoC if it for marketing purposes only. If you take a CoC seriously you will have to check EVERY SENTENCE and statement you do on Github, IRC, Facebook and Google groups that is within the boundaries of the cakephp community against a list of behavioural requirements. I'll be honest and say that even "this is not a help forum" can be interpreted as being discriminating then.

Behavioural guidelines are much more useful as a set of prohibitions. DON'T DOs: Short, don't be a jackass.

So if there is a strong will to adopt community guide lines or a CoC I, despite my mediocre reputation, suggest a compromise, adopt a DON'T DO LIST, setup a body to report to and to execute sanctions. Without sanctions it is nothing but words - if you don't specify who is in charge it is nothing but arbitrariness.

As I could not find a prohibition list but only requirement lists when looking up CoC I did try to get an inspiration but transform things from DOs (German: Gebot) to DON'Ts (German: Verbot). The second issue with relying on work of others as @markstory suggested is: Who is that authority "build upon works of others". Do you know for certain that the people setting up CoCs to be used by 3rd parties represent the groups their claim to represent. The biggest discriminations won't be stopped by a CoC (see above), and the availability of a specific CoC only in English says it all, not to speak about weightening issues of culture/gender/religion above economical ones (as if FB's female top developers will be discriminated more than some muslim boy from Banglasdesh that barely speaks English and has a very slow internet connection). Yes discrimination on gender happens, and the biggest impact is wage. We don't pay wages and we should not discriminate on gender either.

So what now? I suggest DON'T DO! And I suggest to look at CoCs and see which DON'T DOs can be extracted and make sense for this community.

Sadly all of us experienced how a "don't be evil" did not work for Google, because 'evil' is undefined.

I suggest we do use the term (in memory of how it should be), and I do suggest this PARTIAL list of don't dos:

**Don't be Evil, where...**
- 'Evil' is: Discriminating others because of their language, gender, religion or reputation. Don't do that.
- 'Evil' is: Disregarding works of others because of their language, gender, religion or reputation. Don't do that.
- 'Evil' is: Harassing individuals or groups on Github, google groups or public IRC chat. Don't do that.
- 'Evil' is: Insulting others (limited amounts of swearing are tolerated, as long as the target are dead things, not beings). Don't do that.
- 'Evil' is: Intimidation and threats of violence. Don't do that.
- 'Evil' is: Being impatient and demanding. Don't do that.
- ...

(This list is loosely inspired by http://todogroup.org/opencodeofconduct/ but sets prohibition rules instead of behavioural requirements)

This setup of prohibition rules should not state what to do and how to behave but rather should only limit what you do as part of this community.
It should be a minimal set of laws that helps as both: A guideline of prohibited behaviour and a basis for explicit exclusions of those not following along.

If there is an agreement (I'd suggest voting on CoC vs Don't Do and then in a next step about what Don't do or CoC specifically) reached, it should be translated at least to a few major languages (Spanish, French, Russian, Chinese, to name a few etc.).
An english only community guideline or CoC is a total joke out of the box (self-delegitimating and thus self-defeating).

It should be transparent whom to report to and why that body is in charge of making decisions (altering or removing comments on Github, silencing, kicking or banning from IRC and google groups).
In case of this, a small council (voted) should be setup, the question rises who gets a voice and who does not (core, official contributors, in-official contributors, non-contributors/others).

p.s.: I do also think that if there are real world meetings (driven by CakeDC?) there might be the need to define practical behavioural prohibitions. This suggestion is meant for the online collaborative open source development of all the projects related to cakephp.org.

**Comment by Spriz** [comment]
I think somebody should throw some arguments on why one should include a CoC at all - if there's not really any need for it, why then have the trouble of making it?

**Comment by davidyell** [comment]
Needing a code of conduct implies that there is a problem in the community.

**Comment by hmic** [comment]
I'd not even read that lenghly text or a final CoC at all.

I am who I am, I am wrong and unfair at times, just like anybody else is.
If there is someone out there having trouble with it, (s)he needs to talk to me about it.
I might say sorry and consider behaving differently if I see fit, I might not.
I will not accept any third persons stand in such cases nor their judgement.
If the community I tend to be with does not accept this from the start, there is no point in beeing with it.

This is my Code of Commitment.

But let's refer to something I like to tell everybody about live in any society:

###  "All I Really Need To Know I Learned In Kindergarten"
> by Robert Fulghum

Most of what I really need
To know about how to live
And what to do and how to be
I learned in kindergarten.
Wisdom was not at the top
Of the graduate school mountain,
But there in the sandpile at Sunday school.

These are the things I learned:

Share everything.
Play fair.
Don't hit people.
Put things back where you found them.
Clean up your own mess.
Don't take things that aren't yours.
Say you're sorry when you hurt somebody.
Wash your hands before you eat.
Flush.
Warm cookies and cold milk are good for you.
Live a balanced life -
Learn some and think some
And draw and paint and sing and dance
And play and work everyday some.
Take a nap every afternoon.
When you go out into the world,
Watch out for traffic,
Hold hands and stick together.
Be aware of wonder.

**Comment by Spriz** [comment]
Aye @davidyell - and that might be true (I'm still new after all) - but I just didn't realise this problem yet maybe?

**Comment by AD7six** [comment]
> Needing a code of conduct implies that there is a problem in the community.

@davidyell  A code of conduct gives guidance on how to act and what to do when there _is_ a problem - it doesn't imply there is a pre-existing problem (by this comment I am not passing an opinion on that).

**Comment by markstory** [comment]
@davidyell I think we have to operate under the assumption that there is a problem. We don't know what we don't know. Presently if people don't feel comfortable we have no way of knowing. By having a reference of how we would like people to behave, and how others should be expected to behave we can hopefully make others feel comfortable, and give some guidelines/don'ts around what is not acceptable. 

@ionas I agree we cannot actually police people, but we have to start somewhere.

**Comment by hmic** [comment]
@markstory could this notion be related to this http://www.theatlantic.com/magazine/archive/2015/09/the-coddling-of-the-american-mind/399356/
Why would you imply a problem where there is none? Do you do that in your everyday live? Everytime? Everywhere? Do you know the monk tv series maybe? :p
Nobody does feel comfortable because (s)he knows how others *should* behave or are expected to behave, but because they actually **DO** behave like that! Only thing this does is threaten people to behave like expected, which obviously is neighter the reasoning nor wanted, because it causes exactly the opposite! Kind and well doing people start asking themselves if they are doing good, maybe even ask others about it, which will likely lead to discussions about the already good beeing. Which likely does bring more things up that could be done even better... Which is absolutely not neccessary **AS LONG AS NOBODY IS THREATENED IN THE FIRST PLACE**.

Please do read the article I have linked, do you want to build a society like that? - Just go on!
If you don't, stop it right away, please!

**Comment by josegonzalez** [comment]
For the record, I am a *strong* :+1: on us having at least this minimal code of conduct. Arguing about whether we should have one or not feels like arguing over whether we should use tabs vs spaces - we won't get anywhere.

Since there is a PR open, can we close this issue, @markstory ?

**Comment by AD7six** [comment]
Personally I feel that arguing against a COC demonstrates the need for one.

**Comment by hmic** [comment]
@AD7six the point is on the other side: it makes no difference if you have one.
Thats my first statement: I do not bother to even read. I do what I do like I always do, you may go with it or without me - which will not hurt anyone in any case.
The very same thing would happen without a CoC, wouldn't it?
The bad boys would not care a sh** anyways, it's only the good you do harm!

**Comment by hmic** [comment]
If there is a problem, fix it. - If there is a continuos problem on a daily basis, maybe one would need to start thinking of rules like that, I can follow till this point, just maybe.

 But don't make potential problems out of thin air! 

Thats stupid behaviour and superflous at best and it causes lots of additional harm in the long run - read the article I linked if you are interested...

**Comment by AD7six** [comment]
> The very same thing would happen without a CoC, wouldn't it?

You seem to be taking this very personally - do you feel your actions breach a code of conduct, or that it can be used against you?

> The bad boys would not care a sh** anyways, it's only the good you do harm!

I don't see how a code of conduct affects "the good" in any way; it simply establishes accepted limits to behavior.

> read the article I linked if you are interested...

TBH I'm not interested =).

**Comment by hmic** [comment]
So you are not interested in the topic? Well...

It affects the good by making them ask themselves about their actions and not acting as they would have without that limit like you call it. Which is a loss of diversity at least. How do you think a discussion can take place if you are not allowed to express your point, because it's against a point that's already been taken? - Yes this is an extreme, but that is where it leads to in the long run.

Yes, I take this issue personally, because it wants to harm my personal freedom. I took my stand on this already. I do but want to prevent others from the case in the first place.

Think about the past, think about when @lorenzo entered the project. Do you think he would have been accepted by a group of people living to that limits? Do you think he would have *liked* to invest his effort on it? - Well I can actually ask him! @lorenzo whats your opinion? I might very well be completely wrong on this an a total dick myself.

Just make me shutup if you think so, anyone!

**Comment by ionas** [comment]
AD7six I feel that *personally* I can either benefit from a CoC myself or it will make no difference for me and still tend to be against the suggested PR (the reason for that can be found in the PR's comments).

The lack of discussion, and will to shut down the discussion speaks for itself (and a CoC won't help here either, even if I wish it did).

**Comment by josegonzalez** [comment]
@ionas I think we're all for discussion here, just that it be constructive. The argument against a `CoC` is basically "I don't think we have any problems, so we are wasting time here.".

It might be that you all haven't experienced or seen nasty conduct on IRC, issues, at conferences, etc. I have, and it's not fun. I do think our community as a whole has been :+1: , but I'd also like something written down that I can point people to - especially on IRC where sometimes things get heated.

By a similar token, the argument against a Code of Conduct here would be the same as saying CakeFest doesn't need one. Having been a party to issues that _should never even have occurred_, I'm quite happy we have one for CakeFest, and think it's been overall positive for the conference.

I doubt I would have joined the core team had CakePHP been full of assholes spouting bullshit at every turn. I also doubt I would have dug into CakePHP in the first place if all the online posts about it felt pompous - I certainly felt that way about other framework communities 7+ years ago. 

I'm all for being yourself online - you'll find me under the section D for Drunk - and don't think this is targeted to anyone who is aggressive about their programming opinions (except @jippi, that clown owes me shipping :D ). I'd be surprised if anyone on the core team feels differently.

**Comment by AD7six** [comment]
> It affects the good by making them ask themselves about their actions and not acting as they would have without that limit like you call it.

I encourage you to think about that a little more.

> The lack of discussion, and will to shut down the discussion speaks for itself (and a CoC won't help here either, even if I wish it did).

@ionas I'm not attempting to shut down discussion, I'm (personally) just not willing to read a lengthy article which at a glance amounts to supporting abusive behavior and just pretending there isn't really a problem anywhere to allow continuing to act as you wish in ignorance.

**Comment by ionas** [comment]
@AD7six did you read my comment then? There is already a suggestion prepared in that comment, to handle the issues where there are/could be problems and handle them in a minimal, prohibitive, explicitly specified, transparent and authorized way.

In case there is a serious interest in improving community feeling one can PM me on IRC any time (I wish I had more time to setup something like laracasts :)!

**Comment by hmic** [comment]
@AD7six you should read the article! It is exactly about this and your behaviour!
"We are only doing good with this and give people better feelings" - This is the real bullshit at this point:
You are not!

Well meant if often the opposite of well done!

@josegonzalez regarding cakefests CoCs: I did really doubt if I can attend cakefest with this in place! I have asked for help and got the answer: Just ignore it, you are a nice guy and it will not hurt anyone. Without this nice and warm words I would not have attended at all!
And I need to say: almost half the people there, including core developers, would have needed to be removed from the cakefest after the first night IF this CoC would have been enforced!

Thank you very much. Not a world I do like to live in at all!

There are serious threads, harrassment and other things in live that needs to be addressed. But this does nothing to them at all!

**Comment by josegonzalez** [comment]
@ionas I sent you a message on IRC. If you'd like to do some community stuff, feel free to PM me and we'll see if we can get some stuff going :)

**Comment by markstory** [comment]
@hmic What points in #7725 do you think are objectionable? I completely accept that we may have been a bit rough in the past. I know I have. However, that doesn't mean we can't hold ourselves to higher standards and try to do better in the future, which is what I think this is about.

**Comment by hmic** [comment]
@markstory The point is exactly this: There is no point in trying to archvie any higher standards as are required or do any better than neccessary!
The other way it makes more sense: I absolutely liked the event, I absolute liked all the people there. I had a lot of fun and a great time!
I doubt there are any people that would say otherwise!

It would have been a big loss if everybody would have been threatened to obey to the given rules as nobody got harmed or felt harrassed. We just all had a good time - maybe it really was a little rough. Nether the less it was a great time! It would have been much less fun if everybody would have been stiff as a poker because of the CoC.

This kind of things don't do any good most of the time! And the time they could do any good, they are useless too!

So you should only state to have this, if you do actually like to enforce it at any given time. I don't!

The comunity as a hole can do good or bad - like at the cakefest, if there would have been a problem, there would have been more than only one person that would have stood up and done the right thing, just because this is a good comunity. No CoC will change that! Neighter for bad communities where there would be no one standing up and intervening, even with a CoC in place. 

But be warned: With this in place and the people willing to enforce what is stated at all costs, there will be costs!

Given the worse communities, who is to decide what is an harrassment or is discrimitating or in conflict with the CoC at all? - In my opinion this only can be the person in question!
Or will the core developers stand for it and decide, or will there happen some votes? Can you bear that burden?

**Comment by davidyell** [comment]
What an interesting discussion, it's certainly covered many aspects of behaviour. I do agree with @hmic but I also agree with @josegonzalez.

I think that the content proposed in the PR is acceptable. It shows a formal degree of openness which hopefully new CakePHP users will find welcoming. To me that's important. Bringing more developers into the community is goal worth aiming for, and I think adopting something which outlines how people can expect to be treated and act, as a guideline, is a positive step for the project.

To being yourself @hmic, I completely agree, really I do. I have mental health issues which can cause me to react and behave in certain ways. I'm in no way ashamed of that fact, it's part of who I am, but having a code of conduct works both ways for me. It will make me think more about my behaviour and hopefully cause me to react less, however, the flip side of that coin is hopefully getting understanding from the rest of the community that I'm not a bad guy, just sometimes situations get away from me, and with a short break, things will be back to normal.

Please don't try to see it as an attack, or a way to control your behaviour. I've found chatting with you in IRC to be wholly beneficial and fun. You're a clever chap and have *far* more patience than I do, that's for sure. Take solace in the fact that you're well within the code, as I'm sure you know. Most of us know. We've been following the "Don't be a dick." rule for ages, but for the face and branding of the framework I do think it's important to have something written down for those edge cases.

**Comment by markstory** [comment]
@davidyell I totally agree that having some guidelines written down helps encourage more thoughtful discussions for all parties.

@hmic Given that you've been operating under the "don't be a jerk" house rule, I don't think you'd have issues with the proposed guidelines. From my experience, when there are issues related to codes of conduct, being direct and honest with the 'naughty' person tends to correct the behavior. I agree with you that in general people are good, but I feel it is important for people who are uncomfortable, or threatened to voice that concern, and be heard. Open source is at its best when we can incorporate folks from all walks of life, and I feel that codes of conduct help encourage more folks to participate.

**Comment by dakota** [comment]
I am very strongly :+1: for something like this. One thing to remember is that just because we have a code of conduct, does not mean that the code of conduct is unchangeable once decided on.

> There is no point in trying to archvie any higher standards as are required or do any better than neccessary!

@hmic I'm going ot have to disagree with you here. Any community or project that does not strive to continuously achieve higher standards or do better than necessary is one that is going to die out quickly. Afterall, the whole point for us being here is to continuously improving CakePHP, both as a project and as a community.

**Comment by hmic** [comment]
@dakota It's not about the projects standards or goals. It's about the standards people are required to fullfill to help the project to get to it's goals of getting better! the higher these are, the less people are willing to accept them and contribute at all. This limits should be lowered!
Exactly this limits are way up in the sky for CakePHP already, this are the things that a community and a project do break upon on - not that this would have happened to especially this very project in the past almost already...

It's about the people, not the project!

**Comment by dakota** [comment]
I don't see how

> pledge to respect all people who contribute through reporting issues, posting feature requests, updating  
documentation, submitting pull requests or patches, and other activities.

or

> We are committed to making participation in this project a harassment-free  experience for everyone, regardless of level of experience, gender, gender  identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.

or anything else mentioned in the [Contributor Covenant](http://contributor-covenant.org/version/1/3/0/code_of_conduct.md) is in any way a bad thing. In fact, having these things written down where people can read them is a net positive.

**Comment by hmic** [comment]
<MegsLalk> Hi Hmic, I please ask that you respect others in the channel and please refrain from bashing the community CoC - Swearing is considered as unprofessional behaviour and the channel is public and falls within our CoC. Being a long time CakePHP Community member, please would you be supportive of myself as the community manager as well as supportive of the CoC and the community.
<hmic> I did not behave unrespectull (this time), nor did i bash the coc. i think that we, the community - thank you for calling me a long time part of it, which i very much appreciate (despite *me* beeing the one that's occasionally misbehaving) - can very well handle the case on our own. this is what i am complaining about: *we* beeing treated like children in kindergarden. *this* is what i protest against! 
<hmic> nobody did feel offended by the actions, nor were they indented to do so or cause any harm. if you dont respect us as group of grown up individuals beeing very well able to take good care of themselves (or at least me personally, if i should be on my own with this standpoint), i'm very sorry to need to tell you, that this (beeing treated and corrected like children in kindergarden) is offending behaviour 
<hmic> actually (to me).

IRC today:
13:29 	hmic 	dereuromark: i dont think we exclude newbies by any means. we try to put them to the right directions, answering even the most basic questions and pointing out where to get more information, all the time... there are people that do really want to be spoon feeded and ask basic and obvious (if reading things up and not copying only) question again and again... not everybody is sattisfied with what they get, sometimes its
13:16 	dereuromark 	I still hope though, that spoon feeding (and asking for obvious basics) stays the exception and that each dev also tries the best to first resolve issues by googling than to just let themselves get the answer dictated. After all, that is also part of being responsible and part of the community. Or in other words: This can offend the ones that actually do those things beforehand. So everyone just needs to work on himself, the beginners, t
13:16 	slackebot1 	intermediate and the advanced.
13:14 	dereuromark 	I will also welcome more newbies to participate.
13:12 	dereuromark 	@hmic I think we all forget once in a while that there are a) devs that dont speak english that well b) that this is all recorded. If someone later finds those and doesnt see them in context it might indeed be a problem for the community if we are keeping a tone that is close to the "kitchen example" you mentioned. Thus, for the whole community, we should all try to be better, and don't open ourselves for possible "reputation issues" in 
...
11:47 	hmic 	dereuromark: have you ever worked in a kitchen maybe? - the tone is really rough, have you ever heard anybody complain?
11:46 	hmic 	megan, to put it clear: *i* do actually feel personally offended by this behaviour, which is: as a third, not even involved, party, call others (beeing involved) to obey to rules the third party might think beeing, from their standpoint, apropriate. as i am not given the right to decide on my own, what kind of talk i consider apropriate.
11:45 	dereuromark 	@hmic @spriz All jokes (and sad truths) aside. I think megan was referring more to the general tone here. I think we should (including myself) all take a few steps back and be a bit less personal in the addresses.
11:41 	dereuromark 	We could replace "our fuck ups" with "our pussy grabs" :P According to the new leader of the free world this is OK not inappropriate at all :trollface:
11:35 	hmic 	i cannot at this topic! as, like i said, i do think we can handle that ourselves. if anyone should feel like he needs help, there are pleanty people around that would provide support immediately. so, again: please stop it!
11:34 	hmic 	we know each other for some time too. this is superfluous and annoying!
11:34 	spriz 	Only user I'm not respectful to, in this sentence is myself - so can we all take a chill-pill :slightly_smiling_face:
11:33 	spriz 	I actually read it through (I guess I'm even a part of the minority here, heh) - and I don't see anything about swearing.
11:33 	hmic 	we are grown ups and we can speak for ourselves, or take apropriate action, if neccessary.
11:32 	megan 	@spriz and hmic we just ask that you are respectful to other users please
11:32 	hmic 	+1
11:32 	spriz 	Eh @megan I think that *that* is the reason why there's a bunch of people that hates CoC's :slightly_smiling_face:
11:31 	hmic 	megan: can you stop it please?
11:31 	hmic 	i'm not complaining about you. but the slack&lt;&gt;irc split, like usual ;-)
11:30 	megan 	@spriz please read our code of conduct and familiarize yourself with it - swearing and foul language are not permitted in the channel https://github.com/cakephp/code-of-conduct
11:29 	spriz 	was my best suggestion to fix my fuck up :,)
11:29 	spriz 	@hmic sorry :( :)
...
11:17 	megan 	Iamtrying - Please read our code of conduct and familiarize yourself with it https://github.com/cakephp/code-of-conduct
11:17 	IamTrying 	slackebot1: why the email is not sent out to the receiver ?? when the email is more then 1 recipient according to there API?
11:16 	spriz 	IamTrying: we send lots of attachments and to multiple users at once - as I said I think you should rethink your approach
11:16 	hmic 	thats the thing likely @dakota...
11:16 	IamTrying 	slackebot1: we also dont send spam, we send meetings email, invitation mail for enterprises
11:15 	dakota 	but then again, we don't send out unsolicited spammy mails
11:15 	IamTrying 	Mandrill i am using for 4 years. 4 f...king years.. and still they cant send Attachment and multi user at once
11:15 	dakota 	spriz we use either SES or sendgrid. Never had an issue
11:15 	hmic 	within my country, if a mailserver answers you with "queued", it is legaly *required* to deliver the mail to the mailbox in question, not to get sued! so this is as good as it gets...
11:15 	spriz 	(at least that's my conclusion :) )
11:15 	spriz 	so that means all services should be perfectly viable :slightly_smiling_face:
11:14 	spriz 	@dakota we're using Mandrill - and we havn't had problems neither - neither have I personally with Sendgrid
11:14 	dakota 	Yup, queing is how email works :)
11:14 	dakota 	And, please mind your language
11:14 	hmic 	IamTrying, queing is a normal process when sending out mail!
11:14 	dakota 	If you don't want to pay, then you should probably use your own smtp server as hmic suggested
11:13 	IamTrying 	slackebot1: no those bastards only know pay, pay them and when you are sending email with attachment they are sending "queued status" instead of explaining it in detail or giving solution to that
11:13 	hmic 	it's not "providers", it's botnet operators you are looking for!
11:13 	dakota 	We use SES for all our emailing needs, never had an issue with attachments
11:13 	IamTrying 	hmic: better Russians then Amazon and Mandrill/Mailchimp bastards. how to get russians providers for paid services to use, do you know some??
11:12 	hmic 	*fg*
11:12 	spriz 	@IAmTrying if all the services are such bitches, maybe you should rethink your approach
11:12 	spriz 	:,)
11:11 	hmic 	make sure you have access to bitcouns though. they dont take credit cards any longer :p
11:11 	IamTrying 	Does Send Grid allow you to send multiple mails with Attachment slackebot1? (my Amazon, Mandrill was worstest experience yet)
11:11 	hmic 	you can easily pay the russians, they controll enough clients capable of sending mail of any quality and size :p
11:11 	IamTrying 	Amazon is another bitch service, steal money and when its about support you cant find anyone. i hate them from my past experience. i will try Send Grid
11:10 	dakota 	IamTrying, Amazon SES or SendGrid are probably the two best options
11:10 	hmic 	there rather should be NO (paid) smtp service for sending bulk mail *at all*
11:10 	hmic 	IamTrying, because!
11:10 	IamTrying 	only this bullshit mailchimp and mandrill exist?
11:09 	IamTrying 	Why is there not a single paid SMTP services for sending bulk email and attachments?
11:09 	hmic 	if thats your business - good luck!
11:09 	IamTrying 	hmic: its bulk mail with attachment. Mandrill/Mailchimp bloody bastards you cant communicate with them for support, only thing you can do is pay blindly.
11:09 	asunay 	go you guys using (for end project) cakephp Bake templates or Themes? (http://book.cakephp.org/3.0/en/views/themes.html)
11:08 	IamTrying 	hmic: then it fail to reach inbox. i need paid SMTP servers so that i can send many email with attachments
11:08 	dorxy 	you could try mailjet?
11:08 	hmic 	if you dont send bulk mails, this usually works out well :d
11:08 	hmic 	IamTrying, install an smtp server :p
11:07 	IamTrying 	mother fuckers do not allow me to send mail with attachment. Why is there any alternative of Mailchimp/mandrill?
11:07 	IamTrying 	Is there any other alternative of Mail chimp bastards?
11:02 	IamTrying 	Mailchimp/mandrill Send email and getting this: "status":"queued","_id":"fdd54974b291427783b2c768f00a47c0"
