### ISSUE TITLE
3.1. Not works $this->fetch() from element - $this->element()

### ISSUE THREAD

**Issue by Cheren** [cakephp/cakephp#7741]
$this->Html->css('base.css', ['block' => 'css']);
$this->Html->css('cake.css', ['block' => 'css']);

In any elements no works. $this->fetch('css') - is set in layout. See screenshot:
http://llfl.ru/images/10/41i6.png

**Comment by ionas** [comment]
At least the docs make the implication that it should work:
http://book.cakephp.org/3.0/en/views/helpers/html.html#linking-to-css-files
For meta tags in 2.x 'inline' => false as an option key worked, might still work.

Also http://api.cakephp.org/3.1/class-Cake.View.Helper.HtmlHelper.html#_css
Try 'block' => true

Probably a question rather than a bug/feature ticket.

**Comment by Cheren** [comment]
Yes, it's not a bug as I thought. But your variant will not run because the loading elements happen later. Need use beforeRender callback.

**Comment by ionas** [comment]
If you found a solution:
1. Check the official book if it is transparent to newbies how to proceed. If it is not, I do encourage you to create a PR in cakephp/docs
2. Close this ticket ;-)

**Comment by markstory** [comment]
Where is your element being included from? Blocks totally work from elements with the caveat that the element *must* be executed before you try and output the block contents.
