### ISSUE TITLE
Time::timeAgoInWords() Localization past/future tense

### ISSUE THREAD

**Issue by btaens** [cakephp/cakephp#7747]
I extracted cake's core for translation to hungarian.
However, hungarian uses different word formats for the different units of time depending on past/present/future tense. My guess is there are other languages with the same problem.

The unit translations (second, hour, day, month, year) should be given context with __x as future, present or past tense.

**Comment by lorenzo** [comment]
@btaens would you like to provide a patch for this?

**Comment by btaens** [comment]
Sure, just a bit snowed in at the moment. I'll do it on the weekend.

**Comment by phpnut** [comment]
@btaens do you have more details on this issue? Examples of what is expected?

**Comment by btaens** [comment]
Well, for example:
Day in hungarian is Nap.
3 days ago translates as 3 napja, as the past tense elapsed is shown with the affix -ja (this changes depending on the word).
So if you wanted to translate the phrase `2 years, 3 months, 2 hours` as in future tense, it would translate as `2 év, 3 hónap, 2 óra múlva`, pretty straightforward. Now if you translate `2 years, 3 months, 2 hours ago`, it would translate as `2 éve, 3 hónapja, 2 órája`.

So, while a single translation for the word `day` might be enough in english, in hungarian you have to contextualize the past tense separately.

**Comment by markstory** [comment]
Having different message strings for past/present tense sounds reasonable to me. Could we have different message lookup 'dictionaries' for past/future tense?

**Comment by ndm2** [comment]
I thought I'd shift further discussion over here to get some more input, given that #11143 is kind of a duplicate.

Reading this thread, it looks like to properly cover all possible cases for all the different languages, would require four contexts for `diffFormHumans()` (past, future, against now, against given object), and at least two contexts for `time/dateAgoInWords()` (past, future), resulting in blowing up the currently 14 messages to 84 :open_mouth:. That's quite a lot to solve such a small problem, not sure if and how that could be simplified.

Implement it in a backwards compatible way should be possible, but I guess it probably wouldn't be overly nice. One way would might be to put the time stuff into a separate domain (not sure if that is what you ment by "dictionaries" @markstory), and then check whether that domain, respectively messages for that domain exist, and if not fall back to the current way.

**Comment by ravage84** [comment]
Since this has existed unsolved long enough without somebody providing/mentioning either a fully BC  compatible (and nice) solution or a solution living outside of the core, I would advocate to look forward only.

I guess if we invite enough developers from different language backgrounds and analyze the languages for their systematic similarities, we will be able to find a solution that works for many more than today without going way too crazy.

Having Japanese, Hungarian and German is a good start.
Some other good candidates:
- Mandarin
- Spanish/Portuguese
- Hindi
- Arabic
- Russian

https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers#Top_languages_by_population

**Comment by dereuromark** [comment]
Is there still something to be done here, or can we close this for now?
