### ISSUE TITLE
CakePHP3 'contain' doesn't retrieve data from belongsTo

### ISSUE THREAD

**Issue by ricardohenriq** [cakephp/cakephp#7762]
I'm using a query builder provided by CakePHP 3 to retrive one table from database with Linked records from others table using: 'contain' => ['Products', 'OfferBanners'] but only 'OfferBanners' (hasMany) is retrieved, 'Products' (belongsTo) not, how can I resolve this problem?

Put the full source code on Stackoverflow: http://stackoverflow.com/questions/33998718/cakephp3-contain-doesnt-retrieve-data

Any error in the error.log file

**Comment by AD7six** [comment]
This looks more like a misunderstanding rather than a problem

```
$setting = [
            'fields' => ['id', 'product_id', 'date_start', 'date_end', 'name', 'description'], # <- 
            'contain' => ['Products', 'OfferBanners']
        ];
$offers = TableRegistry::get('Offers')
       ->find('all', $setting)->hydrate(false)->toArray();
```

If a query has fields defined, the contained object, if it's also a join, is basically ignored (look at the executed sql). Removing the fields (i.e. relying on auto fields) would probably give you what you expect - or just adding `Products.*` to the fields array.

**Comment by lorenzo** [comment]
Using the * will not work, just for the record

**Comment by ADmad** [comment]
The SO post has been answered.
