### ISSUE TITLE
Cache::clearGroup() not working as expected (I think)

### ISSUE THREAD

**Issue by aledefreitas** [cakephp/cakephp#7963]
Hi,

I was reading about group caching in CakePHP, and decided testing it in an application which would use multiple groups inside its Cache.

So, let's assume my application uses the following configuration for cache:
```php
        'global' => [
            'className' => 'Memcached',
			'duration' => '+1 hour',
			'serialize' => "php",
			'compress' => true,
			'prefix' => 'app_global_cache_',
			'groups' => [ 'Domains', 'Ads', 'Session' ]
        ],
```

Whenever I write a new cache entry, using Cache::write(), CakePHP will generate a key with [CacheEngine::_key()](https://github.com/cakephp/cakephp/blob/master/src/Cache/CacheEngine.php#L243) and [CacheEngine::key()](https://github.com/cakephp/cakephp/blob/master/src/Cache/CacheEngine.php#L243). The key would become something like: 
```Domains0_Ads0_Session0_mykey``` (right?)

Now, when I do a ```Cache::clearGroup("Session")```, the new keys for my cache entry would become: 
``` Domains0_Ads0_Session1_mykey ```

So, let's assume I created two entries to my cache: 
```php
    Cache::write("Ads.ads_data", "global"); // Becomes something like: Domains0_Ads0_Session0_Ads_ads_data
    Cache::write("Session.user_7dsa717237vf", "global"); // Becomes something like: Domains0_Ads0_Session0_Session_user_7dsa717237vf
```

Then I would go ```Cache::clearGroup("Session", "global");```, and try to get data from my Ads.ads_data entry:

```php
    Cache::read("Ads.ads_data", "global"); // Tries to get from key: Domains0_Ads0_Session1_Ads_ads_data
```

Notice how the cache key would change? clearGroup simulates a clear in all keys, not only the group's keys.

Please correct me if I'm wrong or if I have a misconception about clearGroup()'s functionality, but I had this problem in my application.

If it is indeed a problem for everyone, I'd be glad to share my solution (which I did coding a custom cache engine extending MemcachedEngine)

**Comment by markstory** [comment]
What you're seeing is how the code is supposed to work. When a cache configuration has multiple groups, the union of those groups becomes part of the cache entry's 'identity'. Clearing a group invalidates keys set with the previous group generation. Because your keys share 3 groups, invalidating any group will invalidate all of the entries.

Groups are most useful when they are shared across multiple cache configurations. For example if you also had memcache configurations for 5min, 5 hours and 5 days, groups would yield more benefits as you could clear keys across all the cache configurations at once.
