### ISSUE TITLE
Issue with Cakephp 3.0 Unit testing Behavior

### ISSUE THREAD

**Issue by ravikanthhtnakivar** [cakephp/cakephp#8016]
when i execute the test cases the following error is cause.please address the issue

1) TestApp\Test\TestCase\Controller\SamplesControllerTest::test
Index
Cake\View\Exception\MissingHelperException: Helper class ShrinkHelper could not
be found.

D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\View\HelperRegistry.php:123
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php:91
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\View\View.php:1015
D:\xampp\htdocs\TestApp\src\View\AppView.php:27
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\View\View.php:336
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\View\ViewBuilder.php:350
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\View\ViewVarsTrait.php:119
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php:356
D:\xampp\htdocs\TestApp\cakephp\cakephp\src\Error\ExceptionRenderer.php:337
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php:194
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:374
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:330
D:\xampp\htdocs\TestApp\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:233
D:\xampp\htdocs\TestApp\plugins\Discount\tests\TestCase\Controller\SamplesControllerTest.php:29
D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129

**Comment by ADmad** [comment]
All your problems are caused by user error, there's nothing wrong with CakePHP core. Please stop opening multiple issues. 

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
