### ISSUE TITLE
Upgrading from 3.1 to 3.2 breaks plugins

### ISSUE THREAD

**Issue by alexdd55** [cakephp/cakephp#8129]
i just copied the delivered files into their folders, after that plugins couldn't be found anymore.
i did not overwrite any custom files and i did not changed filed that came with the package.

does not feel right...

**Comment by dereuromark** [comment]
You are not using composer?

**Comment by alexdd55** [comment]
actually not, is it mandatory?

**Comment by dereuromark** [comment]
The only change related to plugin loading I can see is https://github.com/cakephp/cakephp/compare/3.2.0-RC1...master#diff-7997caf44fa801d62e790043f405bd34L189
But it does not look like it would have this effect.

We would need a little bit more info on how to reproduce.
Also make sure you clear your complete cache after such a change.

No only highly recommended. Since everyone uses composer (and it works this way) though, no one probably checked the non-recommended way of upgrading.

**Comment by alexdd55** [comment]
i just did this `update` with composer, which did the trick.
appearently composer is the "new way" doing those things... and i need to get used to this 

Thanks for the help :+1:

**Comment by ADmad** [comment]
The "new way" of using composer is the officially recommended way since 3.0.

**Comment by alexdd55** [comment]
i didn't do a lot of PHP development the last 2 years, so it seems i was missing some changes :D
