### ISSUE TITLE
Having problem setting the template inside a cell

### ISSUE THREAD

**Issue by damianoporta** [cakephp/cakephp#8163]
Hello,
i just have upgraded to cake 3.2, i am having a problem with a cell. Basically i cannot change the template inside the method of the cell.

Before (cake 3.1) i was using 

`$this->template = "new_template"; 
`
and it was ok, now i also tried with 

`$this->viewBuilder()->template('new_template');`

 but cake is still calling a template with the same name of the method.

Any workaround?

**Comment by markstory** [comment]
Using the viewBuilder() should work. I'm not sure why its not.

**Comment by HavokInspiration** [comment]
I can confirm the issue.
l'll try to find a fix.

**Comment by HavokInspiration** [comment]
Looking at the history, ``viewBuilder()`` was never supposed to work.
That aside, setting the template directly from the action is not possible anymore since that commit : https://github.com/cakephp/cakephp/commit/515c42e96f8006abc9257f93833c39ae40b7a241

The template name resolution was moved before the action of the Cell is run in order to leverage the cache and avoid running the action of the Cell if the caching cell mechanism is enabled (and because the template name is part of the cache key).

**Comment by HavokInspiration** [comment]
PR #8182 opened.
