### ISSUE TITLE
Problems to write in Session after upgrade cakephp from 2.7.9 to 2.8.0

### ISSUE THREAD

**Issue by jdiefenbach83** [cakephp/cakephp#8239]
Hello, I'm facing a problem to write stuff in Session. My project is set to save all session in database, through the lines below:
```
Configure::write('Session', [
            'defaults' => 'database'            
	]); 
```
It was ran sessions.php in Schema folder. I'm not using Customized classes for holding sessions. 

I was using 2.7.9 version before upgrade it to 2.8.0. 

The erros has being shown:

Warning (2): Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp/) [Unknown, line 0]

I have had changed my configuration to cakephp hold the sessions.

Could you please help me?
Thank you in advance

**Comment by markstory** [comment]
I wasn't able to reproduce this issue. I used a new 2.8.2 application and configured sessions to use 'database' storage. I was able to read and write data to the session without any issues. Given that this issue hasn't seen any other activity since the release of 2.8 I suspect it was an issue on your side.

**Comment by marcdelisle52** [comment]
I had a very similar issue (upgrading from 2.4->2.8)   No problem with php sessions that I could see, just with database as the session storage.  Short term solution is to patch function renew in CakeSession.php to check for $_SESSION being set and executing session_destroy if it is.

**Comment by piotrpoz** [comment]
Hello,

I was facing exactly the same issue which was very very bogus. I have a common cakePHP lib for many projects, using the same codebase, no custom Session handler, etc. It appeared after upgrading to 2.4.x -> 2.8.2 (then to 2.8.6 but it did not resolve the problem), but despite the fact more people had the problem with the session after upgrading, I think it is more related to PHP itself than cakePHP but I do not have any data to confirm my theory. The issue is not easily replicable- it just suddenly occur in one of many projects. Clearing tmp/cache, apache restart and other tricks found in google did not solve the problem (and clearing the web browsers cache neither).

I was playing with Session configuration in core.php and accidentally discovered that after changing "Session.cookie" to a different name the problem disappeared...  I suggest @marcdelisle52  and @jdiefenbach83 to check whether change of this option "fixes" the problem.

PHP 5.5.30-1+deb.sury.org~precise+1

**Comment by kenan-maidea** [comment]
Just to chime in and necro this issue, we had this same issue, so maybe it helps someone some day (v2.9.9.)

Turns out we had code in AppModel.php beforeSave method which did some general utility saving - and tried to save some data while the session was still not loaded in cake (Auth user id still null), and the current model was Session.

After fixing the timing on that (skipping our operation), the error is now gone.
