### ISSUE TITLE
Caching static assets

### ISSUE THREAD

**Issue by QuanticPotato** [cakephp/cakephp#8302]
#### Preamble
* [x] bug
* [x] feature-discussion (RFC)

## How to cache static assets
CakePHP Version: 2.2
Platform : Apache 2

Is it wanted that caching static assets (in the /webroot directory, not in plugins !) using CakePHP is impossible ?

Indeed, it seems that src/Routing/Filter/AssetFilter.php only handle assets of plugins :
```
protected function _getAssetFile($url)
    {
        $parts = explode('/', $url);
        $pluginPart = [];
        for ($i = 0; $i < 2; $i++) {
            if (!isset($parts[$i])) {
                break;
            }
            $pluginPart[] = Inflector::camelize($parts[$i]);
            $plugin = implode('/', $pluginPart);
            if ($plugin && Plugin::loaded($plugin)) {
                $parts = array_slice($parts, $i + 1);
                $fileFragment = implode(DS, $parts);
                $pluginWebroot = Plugin::path($plugin) . 'webroot' . DS;
                return $pluginWebroot . $fileFragment;
            }
        }
    }
```
This function can't handle files like /css/style.css ...

Moreover (this is related, but not the "issue" itself), the default .htaccess file (in the cakephp/app repository) uses
```
RewriteCond %{REQUEST_FILENAME} !-f
```
Then CakePHP cannot handle static assets in the webroot directory.

All of this may be wanted behavior, but in this case I don't really understand the AssetFilter role ?

**Comment by ADmad** [comment]
The `AssetFilter` is only meant for serving plugin assets, that too primarily during development. When deploying your app to production, it's recommended to copy / symlink your assets into the webroot folder as stated in [manual](http://book.cakephp.org/3.0/en/deployment.html#improve-your-application-s-performance) so that they can be directly served by your webserver, since serving static assets through PHP is pointless and inefficient. Configure you webserver to set whatever caching related headers you need for static assets.
