### ISSUE TITLE
3.2.x UTF-8 routing

### ISSUE THREAD

**Issue by codercms** [cakephp/cakephp#8332]
Hello, i have a following route
```php
$routes->connect('/test/:slug', ['controller' => 'Pages', 'action' => 'display', 'test'], [
    'pass' => ['slug'],
    'slug' => '[A-zА-я\-\ ]+'
]);
```
So, when i trying to access this URL - `/test/слог` or `/test/bla-blan-тест`
I get an error - `Error: A route matching "/test/%D1%81%D0%BB%D0%BE%D0%B3" could not be found.` or `Error: A route matching "/test/bla-bla-%D1%82%D0%B5%D1%81%D1%82" could not be found.`

So, maybe router should `urldecode` URL before parsing?
P.S. I am using DashedRoute

**Comment by ndm2** [comment]
The URL already is being URL decoded, but it's being passed unencoded to the exception.

The actual problem is more likely your `А-я` range. Not sure whether and how PCRE is ment to support this when not using the `u` flag, but given that it works fine with the `u` flag, and that `A-я` for example seems to work (where `A` is ASCII), I'd guess that such ranges simply cannot be relied on when not using the unicode mode.

**Comment by codercms** [comment]
@ndm2 
```php
preg_match('/[А-яA-z\-\ ]+/', 'test/bla-blan-тест')
```
Returns - 1.

**Comment by ndm2** [comment]
The final regex for your route will look like

```
#^/test(?:/(?P<slug>[A-zА-я\-\ ]+))[/]*$#
```

The problem starts to appear when using start and ending delimiters, which again leads me to suspect an unicode problem, which might even depend on the PCRE version in use.

The following should fail

```
'/^[А-яA-z\-\ ]+$/
```

while this may work (ASCII A)

```
'/^[A-яA-z\-\ ]+$/
```

**Comment by markstory** [comment]
Given that a bare PCRE pattern doesn't work, I don't think this issue is specifically caused by CakePHP.

**Comment by ndm2** [comment]
@markstory Since it works fine with the `u` modifier, maybe the core should make use of it?

Putting aside whether the non-unicode mode behavior is correct or not, it would generally offer users more freedom in defining route element patterns.

There may also be further problems even when the pattern doesn't contain any unicode, for example when using `.` it seems to match only the first byte of a multi byte sequence.

**Comment by codercms** [comment]
> I guess you ment to say 1, not (something that looks like) -1, right?

@ndm2 Yes, it returns 1.

**Comment by markstory** [comment]
@ndm2 Enabling unicode mode sounds reasonable.

**Comment by markstory** [comment]
Pull request up to add multibyte pattern support.
