### ISSUE TITLE
Unit tests fail with MySQL 5.7 due to change in default sql-mode value

### ISSUE THREAD

**Issue by tharlinsmith** [cakephp/cakephp#8479]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: 2.x, 61b09024b035c3cd68832a2807a6e6737838f820

Related to #8393.  There are a large number of broken tests due to the change in the default value for sql-mode in MySQL 5.7. The ONLY_FULL_GROUP_BY option being enabled by default causes a number of these:

> SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cake_test.Thread.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by lorenzo** [comment]
Yes, thanks for reporting. This is a known problem that we have scheduled to fix soon in the core unit tests

**Comment by lorenzo** [comment]
Btw, there is nothing cake can do for you in this area. You need to either disable that feature in mysql or add the `ANY(field)` to all the fields you are selecting that are no part of the group by

**Comment by tharlinsmith** [comment]
Yes, it's the latter that should probably be incorporated into the unit tests so they run cleanly.  The app is the developer's problem :).  Thanks.

**Comment by AdamDomafoldi** [comment]
Could you please show me an example how can I use ANY_VALUE() in cakephp3 query builder?

**Comment by cleptric** [comment]
@lorenzo Is this still the case?

**Comment by lorenzo** [comment]
yes

**Comment by cleptric** [comment]
@lorenzo ok, but to be sure, this is a cake 2.x issue? Because the assigned milestones says 3.x but tharlinsmith reported this for 2.x

**Comment by bancer** [comment]
@cleptric This is a general MySQL issue documented in the [manual](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html).

**Comment by cleptric** [comment]
This question was targeted to clarify the issue a little bit more so I can give it a try to fix it :)

**Comment by 2ndGAB** [comment]
@bancer maybe this issue is explained but in some situations, the problem is not so easy to solve as the ORM creates intermediate queries.
This is the case when we use join tables like below:

	Articles {
	    'id',
	    'name',
	}

	Categories {
	    'id',
	    'name'
	}

	ArticlesCategories {
	    'article_id',
	    'category_id'
	}

	$categories = $this->Categories->find()
	->contain([
	    'Articles' => function ($q) {
	        return $q->distinct(['Articles.id']);
	    }
	])
	->where([
	    'Categories.name IN' => $themeNames,
	->all();

In that case the error is:

Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'base.ArticlesCategories.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in [/var/www/mySite/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 36]


How do you solve this?

**Comment by ADmad** [comment]
I hope by now people have learned how to properly deal with the `ONLY_FULL_GROUP_BY` option :slightly_smiling_face:.
