### ISSUE TITLE
RFC: back-porting ViewCells to 2.x

### ISSUE THREAD

**Issue by garethellis36** [cakephp/cakephp#8569]
As someone who manages a somewhat monolithic 2.x application with quite liberal use of `requestAction()`, the prospect of being able to use 3.x's View Cell functionality is appealing.

I was thinking through how this might be back-ported to 2.x. Firstly, are there any technical reasons why this couldn't or shouldn't be attempted?

Secondly, I see that the 3.x implementation makes use of traits to provide controller-like functionality (i.e. set, loadModel, etc) to cell classes. As traits are a PHP 5.4 feature and 2.8+ supports 5.3, an alternative approach would have to be found. As far as I can tell, the only options for this would be:
- have the `AbstractViewCell` class extend from `Controller` (yuck)
- copy-paste the required methods from `Controller` to `AbstractViewCell` (also yuck)

Any other ideas or thoughts on this? Perhaps it's already been attempted or addressed. I did a search but couldn't find anything. Thanks!

**Comment by markstory** [comment]
> I was thinking through how this might be back-ported to 2.x. Firstly, are there any technical reasons why this couldn't or shouldn't be attempted?

No technical reasons. I suspect the main reason it hasn't been done so far are time/motivation based. But it sounds like you might have enough of both to see this through.

Copying and pasting code might be the easiest way to get the same functionality in multiple classes. We currently do that for the `set()` method that is in both View, Controller and Shell.

**Comment by garethellis36** [comment]
OK I'll take a crack at this.

**Comment by garethellis36** [comment]
Hi @markstory - I've only just gotten around to thinking about this (and typically, I'm going on holiday tomorrow). I was discussing with a colleague and we were wondering if we could compose the functionality of the shared methods (e.g. set, loadModel) into separate classes that could be proxied through to by the classes that need them?

e.g.
```php
<?php
//Controller.php

function loadModel($class) {
   return $this->modelLoader->loadModel($class);
}

function set($varName, $varValue) {
  return $this->viewVarSetter->set($varName, $varValue);
}

**Comment by markstory** [comment]
@garethellis36 Sounds like you want traits. I would just copy the methods for now.

**Comment by ravage84** [comment]
@markstory what if we bump the PHP minmum requirement to 5.4?
With this step, we could introduce stuff like the traits in question into 2.x.

There have been two minor 2.,x releases now requiring PHP 5.3, spanning over more than 12 months.

2.8.0 - 2016-02-07 requiring PHP **5.3**
https://github.com/cakephp/cakephp/releases/tag/2.8.0

2.7.0 - 2015-07-12 requiring PHP **5.3**
https://github.com/cakephp/cakephp/releases/tag/2.7.0

2.6.0 - 2014-12-23 requiring PHP **5.2**
https://github.com/cakephp/cakephp/releases/tag/2.6.0

**Comment by dereuromark** [comment]
I think that makes Sense. Even 5.4 is already eol. You shouldn't even be using that on Servers anymore.

**Comment by ADmad** [comment]
I am not too sure about bumping PHP version for 2.x. Those stuck with maintaining a 2.x app might also be stuck with a particular PHP version. Let's not deprive them of 2.9 which might potentially be the last minor release in 2.x series.

For this particular issue of view cells, some code duplication due to copying of methods isn't a big problem IMO.

**Comment by dereuromark** [comment]
But those actively developing on a 2.x project also most likely are only using 2.9 (and the effort to upgrade) if they have an adequate infrastructure and handling of things.
Otherwise why bother upgrading to 2.9 in the first place?
They want to have the cool new features without being able to 3.x upgrade due to the intense pain involved.
But keeping the server up to date is an absolute requirement and minimum effort here they can do with ease (and should for a good reason).

We also didnt get any negative feedback from 5.2 to 5.3.
And as I said: It is to be expected everyone already moved away even from 5.4 these days.

**Comment by josegonzalez** [comment]
I'm a 👎 on upgrading.

- We aren't upgrading to fix a bug, we would be upgrading to use a new feature of PHP.
- Before the 3.x release, we made it a goal to stick to a php version for the length of the release. We only bumped for a bug, and I still think that people expect us to continue following that path.
- As @ADmad said, copying a few methods isn't a big deal.
- No one is forced to upgrade to a minor, but if there is a bugfix in that minor/patch and we're with-holding it because of this feature, that seems like a pain. Especially since 2.x is more or less in maintenance mode.

**Comment by chinpei215** [comment]
By the way, @garethellis36 is not talking about traits. He is talking about composition pattern. We can do it in 5.3.

**Comment by josegonzalez** [comment]
@chinpei215 yeah that works, I'm just 👎 on us moving 2.x to 5.4 for trait usage, as then that will invite a ton more "refactoring" type work that would be better spent on Making Cake3 Great (Again?).

**Comment by chinpei215** [comment]
@josegonzalez Yeah. Simply, I thought we should go back to @garethellis36's idea. Both traits and copy&paste are not his idea. 
I think it is a nice idea. At the moment, `Controller::set()` is little different from `View::set()`. But I don't think there are good reasons. If we introduce ViewVarSetter class, they can be merged into a single method, and we can use it in ViewCell too.

**Comment by markstory** [comment]
Extracting the common code and reusing it via composition sounds like a good approach. I am not too keen on changing PHP veraions for similar reasons as the one @josegonzalez had.

**Comment by bancer** [comment]
According to [the recent research](https://seld.be/notes/php-versions-stats-2016-1-edition) in May 2016 PHP 5.3 was used by 2.43% of active composer installs. So active projects use higher PHP versions. Bumping PHP version to 5.4 would have a minimum effect on them. On the other hand in general PHP 5.3 is used by 27.2% of all websites according to [w3techs](https://w3techs.com/technologies/details/pl-php/5/all). 

In general it seems that using traits in Cake 2 would ease the future migration to Cake 3.

**Comment by josephzidell** [comment]
@garethellis36 We (enterprise-level app) need this too. Are you doing this? If yes, I can assist. If not, I can do it.

**Comment by garethellis36** [comment]
We ended up writing our own implementation that uses PHP7 stuff.

**Comment by josephzidell** [comment]
Can you share it? A PHP7 implementation would be awesome!

**Comment by josegonzalez** [comment]
Note: any implementation merged into the 2.x series would need to support the correct PHP versions for that version of the framework (PHP 5.3 now? idk). Shouldn't be hard, I actually ported this to Symfony a few years ago.

**Comment by josephzidell** [comment]
I did this is my system, and can give someone the code. Don't have time for a full PR. Is anyone interested?

**Comment by markstory** [comment]
Closing as 2.10 was the last feature release for 2.x and this wasn't ready for that release.
