### ISSUE TITLE
Login with any password when hashed password is empty

### ISSUE THREAD

**Issue by janmuennich** [cakephp/cakephp#8650]
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 2.8.3

### What you did
When an empty password is hashed the _crypt function produces a salt error and returns an empty string. If a user has an empty password in the database it will be validated and login is possible without any password.

### Expected Behavior
When a user has an empty password login should be denied.

**Comment by janmuennich** [comment]
Fix proposal: https://github.com/janmuennich/cakephp/commit/52abb5c2ec961652683c4209424b3eb5d205accc

**Comment by davidyell** [comment]
Crypt isn't a hash?

**Comment by janmuennich** [comment]
_crypt() is used in hash() to generate a blowfish hash.

**Comment by mahhashish** [comment]
don't use md5
may be crypt or mcrypt

**Comment by mahhashish** [comment]
password_hash is the preferred one with of course crypt

**Comment by janmuennich** [comment]
I'm not talking about the system crypt() but _crypt() in Core Security Utility :)

**Comment by janmuennich** [comment]
Please check https://github.com/janmuennich/cakephp/commit/52abb5c2ec961652683c4209424b3eb5d205accc

**Comment by berarma** [comment]
@janmuennich, if you want to deny access to users with empty passwords, it could be handled in the controller using form validation. It could be done in the authentication component too, but I don't think there's any problem in the _crypt() function.

**Comment by janmuennich** [comment]
To clarify:
The problem is in BlowfishPasswordHasher where the empty string from database is compared to the return value of _crypt(). Since the string from database is used as a salt _crypt() returns an empty string. So an empty string is compared to an empty string and returns true.

`return $hashedPassword === Security::hash($password, 'blowfish', $hashedPassword);`

**Comment by janmuennich** [comment]
@berarma I just think the expected behaviour of an empty password is not that you can login with any password.

**Comment by markstory** [comment]
Why do you have empty passwords in the first place?

**Comment by janmuennich** [comment]
In a current project all users are in a different data source and need to be migrated. When they log in their passwords are hashed and stored in the new database. This not a real problem, I just catch the empty password field in the controller. But in my opinion this is not expected behaviour.

**Comment by thinkingmedia** [comment]
@markstory social authentication can result in a user record that has an email address and empty password. If the developer has not restricted that user to oauth only access it's possible this issue can allow that email access. I can think of two popular Cake 3 plugins for oauth that likely introduce this issue. If this bug is real. I need to update my apps.

**Comment by markstory** [comment]
Ok. It sounds like a series of unfortunate events, but I can see how this could be an issue. Instead of changing the return type of the function it might be better to treat `$salt = ''` and `$salt = null` as we treat `$salt = false`. Generating a new salt will avoid the triggered error and ensure that a hashed password of '' never matches anything.

**Comment by markstory** [comment]
Closing as a pull request is open now. Until this change is released a workaround would be to update the blank passwords to `!` which will always fail comparisons.
