### ISSUE TITLE
Mailer exceptions misleading

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp#8706]
When a Mailer action/template does not exist the exception messages are

```php
The action confirmation is not defined in

Error:

Notice (8): Undefined variable: controller [CORE\src\Template\Error\missing_action.ctp, line 48]Create ::confirmation() in file: src\Controller\.php.
Notice (8): Undefined variable: controller [CORE\src\Template\Error\missing_action.ctp, line 58]

<?php
namespace App\Controller;

use App\Controller\AppController;

class  extends AppController
{

    public function confirmation()
    {

    }
}
```

I think there was sth forgotten when writing the new mailer class.

**Comment by lorenzo** [comment]
How can someone reproduce this?

**Comment by lorenzo** [comment]
Is it just by not having the template file for the email?

**Comment by ADmad** [comment]
The problem is that `Cake\Mailer\Exception\MissingActionException` has name similar to `Cake\Controller\Exception\MissingActionException` and hence it ends up using the `missing_action.ctp` with is meant for the latter.

So `missing_action.ctp` needs to be customized to check the fully namespaced exception name and act accordingly.
