### ISSUE TITLE
Selectively apply autoIncrement to baked fixtures

### ISSUE THREAD

**Issue by emersonthis** [cakephp/cakephp#8884]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: v3.2
- Platform and Target: Postgres.

Related to: #8799 
### Actual Behavior

When fixtures are generated by the `bake` tool (for an app using Postgres) they will have a sub-optimal default setting... Primary ID sequences will have `autoIncrement => true`, but if this is left in place, tests that insert records will throw `Unique constraint` violation errors. The resulting error is not particularly helpful for deducing the problem...
### Expected Behavior

It would be better if the bake command knew not to set `autoIncrement` to true when the DB is Postgres. Almost as good would be a more informative error, perhaps suggesting the user of `autoIncrement` as the source of the problem.

**Comment by markstory** [comment]
Do you mean `autoIncrement` instead of `autoComplete`?

**Comment by emersonthis** [comment]
Sorry yes!

**Comment by ethanpooley** [comment]
#8799 concludes that `id` elements should be absent from `$records` arrays and that in combination with an `autoIncrement => false` setting this will avoid unique constraint / duplicate key problems on Postgres.

It seems to me that removing hard-coded IDs from fixtures would preclude reliable associates between fixture tables. How can I associate an author with an article if I don't enter an `id` property for the author? What do I put in the article's `author_id` property? I can't know that the first author will get an ID of 1, because of the same situation that is causing our current symptoms: I don't know the state of the table's ID sequence.

If this is correct, then:
- fixtures must hard-code their IDs (and relationships, using those IDs)
- the fixture restoration system must take positive control of the database's auto-increment plans to ensure they remain compatible with the hard-coded IDs after restoration is complete

This can be accomplished by a drop/truncate/etc. prior to restoration, as some users have noted, but that's heavy-handed during testing. So I think it has to be done in a vendor-specific way via an adapter structure that I assume already exists in the Cake or Phinx stack somewhere. We do it like this in a `TestCase` when necessary:
```
public $fixtures = [
    'app.articles',
    'app.authors',
];

...

public function setUp()
{
    $connection = \Cake\Datasource\ConnectionManager::get('test');
    foreach ($this->fixtures as $fixture) {
        $tableName = explode('.', $fixture)[1];
        $connection->execute("
            SELECT setval(
                pg_get_serial_sequence('$tableName', 'id'),
                (SELECT MAX(id) FROM $tableName)
            )");
    }
}
```

This sets the sequence as far ahead as necessary to ensure that auto-incremented inserts will not collide with any existing records. When rolled into framework code this query could also take a dynamic field name.

**Comment by ankr** [comment]
Does the cake team have any answer for the correct solution for this? Currently I'm using @ethanpooley's fix, but would like to do it the proper way.

My issue is also that I also would like to be able to have relations between my fixtures.

**Comment by markstory** [comment]
@ankr All of the core tests don't specify IDs and instead rely on the IDs to be naturally assigned. We've never had issues building associations as @ethanpooley theorized.

You can use the core fixtures as example solution for this. I'd long forgotten about this issue, but am going to close it now as I don't think anything _needs_ to be fixed.
