### ISSUE TITLE
Remove surplus SELECT query for fetching association while given association is already present in JOINed result.

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8953]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Lets say we have relation Applicants hasMany Audits. Audits may be empty.
Now lest query for Applicants with Audits and lets hydrate Audits into Applicants:

`$this->Applicants->find()->innerJoinWith("Audits")->contain("Audits")->toArray();`

This will generate 2 queries - 1 for Applicant selection INNER JOIN Audits, and second the SELECT query for Audits hydration. In this case, second query is surplus as required data has been already fetched with inner join. I think that we could ommit additional "hydration select" if the same relation is already in joined result.

**Comment by ionas** [comment]
`contain()` can be used without `innerJoinWith()`. If you are using Inner Join you will have duplications of Applicants in the case of Applicants hasMany Audits. 

You can use `matching()` as far as I understood the problem.

I am not sure I want to see a (dark?) magic that stops `contain()` from running because there is some innerJoinWith on the same Assoc.

**Comment by lorenzo** [comment]
This cannot happen, `contain` and `innerJoinWith` are two different things. When you use both, you are literally telling the framework that you care about this difference. If you don't care about it, then use one or the other.

**Comment by Antoniossss** [comment]
Allright, littlebit guide on how to query for non-empty `hasMany` relations with `matching`?

**Comment by lorenzo** [comment]
You need either an  `INNER JOIN` or a subquery to check for non-empty relations. I personally prefer the inner join
