### ISSUE TITLE
Xml::fromArray not creating proper tags for empty keys

### ISSUE THREAD

**Issue by half2me** [cakephp/cakephp#8963]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: PHP7

### What you did
```php
echo Xml::fromArray(Xml::toArray(Xml::build('<tag></tag>')))->asXML();
```

### Expected Behavior
If I build an array from an XML, then turn it back into XML, it should stay the same.
```
<?xml version="1.0" encoding="UTF-8"?>
<tag></tag>
```

### Actual Behavior
```
<?xml version="1.0" encoding="UTF-8"?>
<tag/>
```

The array its building looks like this:
```php
[
	'tag' => ''
]
```

If I use `['tag' => [] ]` it will do the same thing. It creates a self-closing tag, instead of two tags with no content in-between.

**Comment by ndm2** [comment]
Technically it _is_ the same, as in XML, self-closing tags are identical to tags that hold no content. It's pretty much impossible, respectively overly complicated to do what you are suggesting, as the information about the original state is not being kept.

If you don't want self-closing tags, you could for example use `domdocument` instead of `simplexmlelement`, and generate the XML with the `LIBXML_NOEMPTYTAG` flag.

```php
$data = Xml::toArray(Xml::build('<tag></tag>'));
echo Xml::fromArray($data, ['return' => 'domdocument'])->saveXML(null, LIBXML_NOEMPTYTAG);
```

**Comment by half2me** [comment]
@ndm2 Thanks for the info. The XML I am generating is being used by an API. I use a foreach() loop to add items, and in some cases, no items get added, so I'm left with nothing between the XML tags. But if those two representations are compatible, then all should be good. Thanks :)
