### ISSUE TITLE
Add support for custom <tr> attributes in HtmlHelper#tableCells like for <td> tags.

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#8995]
This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)

HtmlHelper#tableCells has the ability to add custom attributes to every cell single cell (to every <td>). It can be usefull in some cases to have the same feature for rows.

In my use case it would be for example adding `title` attribute to whole row `<tr>` tag insteed of adding the same `title` attribute to every cell (table is approx 30x109 so approximetyly 29x109 duplicating title attributes in <td> tags here).

**Comment by dereuromark** [comment]
Feel free to provide a PR with this, otherwise it will probably be in the back log for quite some time.
It is always good to jump into it and realize it yourself if you need/want this feature.

**Comment by mattmemmesheimer** [comment]
I like what @burzum did in #9062.  I was thinking about taking a stab at completing this, but I'm having trouble coming up with a way that does not break backwards compatibility in `HtmlHelper::tableCells`. This looked a lot simpler at first glance...

Specifying attributes for each `<td>` in the `$data` parameter is simple because the `<td>` content is expected to be a `string` or an `array`.  If it is not a `string`, but rather an `array`, it is easy to infer that one entry is the cell content and the other is the cell attributes.

However, each entry (row) in the `$data` parameter is always expected to be an `array` whose contents are the cells (and possibly their attributes).  Thus, specifying the attributes for each row is difficult to do in the `$data` parameter.  We can't just simply assume the first item is the content and the second is the attributes, as is done with the cells. 

The `HtmlHelper::tableCells` method already has a good amount of parameters with default values, so specifying the `<tr>` attributes as an additional parameter to this method seems less than ideal.

Does anyone have any ideas on how approach this?  A new method just for this purpose seems overkill.

**Comment by burzum** [comment]
@mattmemmesheimer maybe the best would be to come up with a dedicated Table or HtmlTableHelper. I wrote one for CakePHP 2.x some time ago with a fluid interface.

See https://github.com/burzum/cakephp-bz-utils/blob/master/View/Helper/TableHelper.php

This could be done for Cake3 as well. We would ensure that the Html helper doesn't break BC and can make the table helper itself a lot more flexible and powerful.

But before we introduce a new helper I would like to hear the opinion of other core members. @dereuromark  @markstory

**Comment by ADmad** [comment]
IMO helpers for generating complex tables and other html blocks belong in a community plugin not core. I would prefer keeping core helpers simple and thus keep maintenance overhead minimal.

**Comment by burzum** [comment]
@mattmemmesheimer see @ADmad comment. Feel free to implement it as a plugin.

**Comment by mattmemmesheimer** [comment]
I think that's a good call.  This issue is of no particular importance to me, it just looked like some low hanging fruit that I can use to get more comfortable contributing.  Perhaps I will take the time to write a plugin.  Thanks guys

**Comment by ADmad** [comment]
As commented above this is better suited for a community plugin. We want to keep the HTML generation helpers in core simple.
