### ISSUE TITLE
AuthComponent - Add special ajax handling for unauthorized request scenario just like it is done for unauthenticated scenario

### ISSUE THREAD

**Issue by Antoniossss** [cakephp/cakephp#9078]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Right now AuthComponent allows different behaviour if user is not logged in and the ajax call is made
and different behavior for normal calls. This can be configured vvia `ajaxLogin` config. (Unauthenticated scenario)

However if user is logged in, but he is not authorised to perform some action I would like to "render" custom element eg. with flash message to the user but as json response so the client side can actually notify user that he is not authorised to do what he wanted to do. (OFC 403 will be returned so client know the main reason of error - and this is Unauthorised scenario) 

Right now, `ForbiddenException` is thrown on ajax calls, and whole ErrorHandler response is beeing rendered. This is fine for "standard" view but not for ajax calls. 
I would thinl that much more reasonable would be to eg. render custom element that may simply echo structured json message for the client to handle without pushing all the unesessery HTML response.

**Comment by markstory** [comment]
Couldn't the `ajaxLogin` element be used to render JSON?

**Comment by Antoniossss** [comment]
I did check it in the code and unauthorised and unauthenticaded scenarios
are handled differenlty. Unauthorised throws exception.
Maybe some sort of AjaxView manipupation would do the trick but this is a
workaround imho.

8 lip 2016 04:36 "Mark Story" <notifications@github.com> napisał(a):

**Comment by ADmad** [comment]
I am not a fan of the "ajaxLogin" option but at least in cause of unauthenticated requests server can return a form with appropriate login fields. I really don't see a need for special response in case of unauthorized request. The client can just check for `403` code and show the message sent for the exception or show it's own message.

The issue @Antoniossss is experiencing is probably a more general one, where in case of exception since a new response instance is generated often response type configured in controller (or by RequestHandler) is lost and you end up with HTML response instead of JSON response.

**Comment by dereuromark** [comment]
That's why I always say use the appropriate extensions.
In this case for AJAX as JSON always use `.json` extension for the URL.
Then the response would never be anything else :)

But I had to deal with the new response object created a few times myself in the past (I bet there are some github complain tickets from me about a similar thing as well^^).

**Comment by markstory** [comment]
@ADmad I'm with you, HTTP status codes and generic JSON responses are how I handle these scenarios.

**Comment by markstory** [comment]
Closing as `ajaxLogin` is deprecated as of ae5e255d1ba545a7fad93c642ae29a4d8060d5a2 and I don't see a point in adding an unauthenticated flavour of a deprecated feature.
