### ISSUE TITLE
3.3 Multiple Pagination / Consistency (scope vs model/defaultModel)

### ISSUE THREAD

**Issue by htstudios** [cakephp/cakephp#9211]
Why is it `scope` for the Controller context but `model`/`defaultModel` for the View/Helper context @ http://book.cakephp.org/3.0/en/views/helpers/paginator.html#paginating-multiple-results? Shouldn't it be `scope` everywhere for consistency?

**Comment by markstory** [comment]
`defaultModel()` and `model()` predate the component supporting for multiple Pagination. They date back to the 1.2 days, where multiple pagination could be done through Ajax. Instead of adding more methods that did similar but not quite the same things leveraging the current methods made more sense.

I'm open to adding aliases to the existing methods/options though. I agree that having consistent names would be nice.

**Comment by inoas** [comment]
If I don't do this within a month, please ping me again (I forgot it then, its low prior, but I love consistency and I can do it).

**Comment by htstudios** [comment]
Closing as PR is open.
