### ISSUE TITLE
Undefined method Memcached::getAllKeys()

### ISSUE THREAD

**Issue by SirbitoX** [cakephp/cakephp#9252]
This is a:
* [ ] bug
* [x] enhancement

* [ ] feature-discussion (RFC)
* CakePHP Version: 2.6.4 but I see the related issue in all versions of CakePHP.
* Platform and Target: CentOS, memcached 1.4.29

### What you did
I tried to clear cached data with memcached engine. So I used the code below:
```php
...
Cache::clear(false, 'MemcachedConfig');
...
```
And I ran the action I wrote to clear the cache.

### Expected Behavior
To clear the cached data without any problem.

### Actual Behavior
I got:
``` 
Error: Call to undefined method Memcached::getAllKeys()	
File: /path/to/CakePHP/lib/Cake/Cache/Engine/MemcachedEngine.php	
Line: 285
```
I checked every where to solve the problem but I didn't find anything rated to may situation.

### Suggestion
I found we also have one issue before on this function:
#7546
Why we don't use the code below easily? (in `MemcachedEngine.php`)
```php
public function clear($check) {
	if ($check) {
		return true;
	}
	
	return $this->_Memcached->flush();
}
```
Based on [PHP Documentation](http://php.net/manual/en/memcached.flush.php), the **flush** does what we need here without any other overhead. And it also fixed my problem.

**Comment by josegonzalez** [comment]
What version of memcached do you have installed?

**Comment by SirbitoX** [comment]
@josegonzalez I mentioned it on `Platform and Target` section. 1.4.29.

**Comment by josegonzalez** [comment]
Ah missed that, sorry.

I believe the intention is that the MemcachedEngine be used with the `Memcached 2.x+` extension. The following two methods are used that wouldn't be available for 1.x:

- `setSaslAuthData`: We throw an exception if a user wants auth but doesn't have this method available
- `getAllKeys`: The issue you are running into.

The reason why we can't just naively call `->flush()` is because we use a prefix when saving data to Memcached. If we just called flush, keys stored in Memcached that *aren't* managed by the current CakePHP application would also be dropped, which certainly isn't the correct behavior. Since we cannot guarantee that an application will "own" a Memcached server, calling `flush` might result in undesirable results for the user.

If you use a Memcached server for *just* your app and no others, you can just subclass the MemcachedEngine and use your custom one with just that method replaced.

I think we should probably just return false if the method doesn't exist on the client, as at least that way there aren't any Errors being thrown and the user can dive into the code and figure out why `false` is being thrown - and potentially upgrade.

**Comment by SirbitoX** [comment]
I read about the Memcached versions but I have another VPS that runs 1.4.25 version of Memcached and `->getAllKeys()` works without any problem!

I missed the line that we check the prefix for each key. You're totally right about `->flush()`.

> ... figure out why false is being thrown - and potentially upgrade. 

:+1:

**Comment by markstory** [comment]
You need to upgrade your extension, we don't support the 1.x extension.

**Comment by SirbitoX** [comment]
@markstory: 
As @josegonzalez said, we need to mention it somewhere.

**Comment by markstory** [comment]
API documentation updated now. @SirbitoX

**Comment by mesiarm** [comment]
Is there any workaround to Clear all cache with old version of memcached ?

**Comment by markstory** [comment]
Not that I'm aware of.

**Comment by mesiarm** [comment]
If someone would need there is way you can clear memcached on server:
https://serverfault.com/questions/259114/how-to-restart-clear-memcache-without-restarting-the-whole-web-server
