### ISSUE TITLE
2.8: deleteAll generates bad query when "<>" condition is used

### ISSUE THREAD

**Issue by watermark** [cakephp/cakephp#9253]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.8.6
* Platform and Target: Apache 2.4.18, PHP 7.0.9, MySQL 5.5.50

### What you did
```php
$this->MenuItem->deleteAll(array(
	'MenuItem.menu_id'=>4,
	'MenuItem.id <>'=>array(25)
));
```

### Expected Behavior
Generate a working query

### Actual Behavior
Generates a query with the condition section 

```
WHERE `MenuItem`.`menu_id` = 4 AND `MenuItem`.`id` <> = (25)
```

Note the "<> =". Using "!=" works as expected, it just seems to be "<>" that's borked

**Comment by markstory** [comment]
I'm not sure `<>` is not a supported operator. Does it work in other operations?

**Comment by watermark** [comment]
It does work in other operations.

https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Test/Case/Model/Datasource/Database/MysqlTest.php#L2503

**Comment by markstory** [comment]
Ok. I'll take a look into why it is not working in deleteAll()

**Comment by markstory** [comment]
I added a test (which passes against MySQL) in 3e16f8911d3caaddb629e403fcda3d0abf0cae72. I think your problem is stemming from the value being an array. `<>` unlike `!=` does not automatically get converted into a `NOT IN` operator. If you need to handle both scalar and array values you will need to use `!=`.
