### ISSUE TITLE
Null values are marked as dirty when patching Entities

### ISSUE THREAD

**Issue by EuMMCR** [cakephp/cakephp#9381]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

CakePHP Version: 3.3.2

### What you did
I have an entity where some properties are not set or NULL.
Now I am patching the entity with another entity by
`$model->patchEntity($entity, $otherEntity->toArray());`

### Expected Behavior
If values are NULL before and after patching, they should not be marked as dirty.

### Actual Behavior
Let's say the entities have a property "prop" that is NULL in both entities.
However, the "prop" is marked as dirty after patching like above.

### Solution?
I think this is because of the changes to the ORM\Marshaller.php, where in the "merge" method properties are now checked for "is_scalar", but is_scalar() does not consider NULL to be scalar, as mentioned here: [http://php.net/manual/en/function.is-scalar.php](url)
Before version 3.3.2 I was using 3.2.x and there the behaviour was like expected.

Thank you!
EuMMCR

**Comment by thinkingmedia** [comment]
I've suspected this was an issue. I've seen SQL statements UPDATE columns that I knew had not changed.

**Comment by thinkingmedia** [comment]
The code is marking all fields being set as dirty without checking if the value has changed. This might be difficult to fix because of the magic setters. Which can mutate the value or contain business logic. The code cannot ignore values that are the same because `null` might have significant meaning for the magic setter.

With that said, I think that makes for extra work for the majority of developers since setters are less common.

Cake does not have events for the `patchEntity` and `newEntity` methods. If it did have events you could add a behavior to handle edge cases like this. It's something I've could have used on other projects as well. The only thing we have now to manage entity life cycle is validation.

**Comment by EuMMCR** [comment]
In the code all scalars and objects are checked if the value has changed. Only arrays are not checked.
See here: [Marshaller.php](https://github.com/cakephp/cakephp/blob/master/src/ORM/Marshaller.php) Line 554.
So, if scalars and objects are checked, why not additionally compare NULL values?

**Comment by markstory** [comment]
I'll take a look and get a fix together.

**Comment by markstory** [comment]
Pull request up now.
