### ISSUE TITLE
Documention Updating cakephp example 3.2 to 3.3.3

### ISSUE THREAD

**Issue by jimgwhit** [cakephp/cakephp#9508]
This is a (multiple allowed):
* [] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.3.
* Platform and Target: YOUR WEB-SERVER, Any.

### What you did
NA

### Expected Behavior
Better explaination of how to properly update (not upgrade)

### Actual Behavior
NA

I have searched the Docs and do not understand the proper way to update cakephp.  I know composer update, updates, but there is  

https://github.com/cakephp/cakephp  and  

https://github.com/cakephp/app  
So I am guessing that a composer update updates https://github.com/cakephp/cakephp but how is https://github.com/cakephp/app supposed to be properly maintained / updated. I am new to cake php came from laravel.  I think cake is more stable now but need to know this stuff as I have production sites I am migrating to cakephp.  Upgrade is in docs, not updating which is a big difference.

**Comment by saeideng** [comment]
You need update cakephp/app manually if you want
 like other app
Cakephp/App is just skeleton
cakephp/cakephp is core for that and you can use composer update for updates

**Comment by jimgwhit** [comment]
Thanks @saeideng but I notice on a new composer install of cakephp there is a
```
config\app.php file
```
that file is not in https://github.com/cakephp/cakephp  

So I guess it is created during install.  Is there a list somewhere of "other" files that aren't in https://github.com/cakephp/cakephp but are created during an install?  Likewise how does one know if one of these "not in the https://github.com/cakephp/cakephp" files need attention or otherwise a modification after a composer update?  

And as I understand your answer, Cakephp/App is just skeleton, and has nothing to do with a cakephp composer install.  There has to be a way to "know" what files need updating that composer doesn't update.  Perhaps you could share how you deal with it.

**Comment by inoas** [comment]
The app skeleton is meant to be frozen against your app. Yes you can update parts of it once in a while. Like, say when 3.3 game out with PSR-7 support.

The app.php file is just a configuration file. It is not closely linked to the framework. You could setup the framework through other means. the app skeleton is just a quick way to get new application development started.

When you run composer install it looks at the roots composer.json as far as I know, that is also part of the skeleton, but it will also reference vendor/cakephp/cakephp... and inside there lives another composer file that is as far as I know then processed.

**Comment by jimgwhit** [comment]
@inoas I have cake working in dev and testing on production, I use a program called winmerge, compares files in folders.  I have compared a downloaded https://github.com/cakephp/cakephp with my working dev,  not counting vendor NOTHING matches.  Seems there are files in one folder that don't exist in the other and vice versa.  So according to winmerge (which is accurate) cakephp shouldn't even be working, but it is.  

I don't care about vendor, but where do I acquire a list of other files I need to pay attention to, and how do I even know if a file was deleted and no longer needed?  There has to be a way.  And I never installed https://github.com/cakephp/app I don't even have an app folder, I did a composer install. Where is the respository to the "other" files that a cakephp install installs?

**Comment by saeideng** [comment]
See composer.json in root , section " scripts " for more information
Your issue not related to cakephp

Also for use of middleware (for update from 3.2 to 3.3) see middleware section on cookbook

**Comment by inoas** [comment]
cakephp/cakephp has nothign to do with cakephp/app. If you want to update your application you do it through `composer update` - that will update all referenced libraries (but not the app skeleton itself.

As for cakephp/app it is your responsiblity to take care about EVERY SINGLE FILE because it is YOUR application. Only the stuff in vendor you don't have to take care about.

**Comment by inoas** [comment]
Also: This is not a help forum. I'd suggest you read the book THOROUGHLY. Not just look for stuff you want to know (it is not reference but a real book). Then when you have questions, try #cakephp on irc, stackoverflow etc. When you want to improve the docs you create PRs at cakephp/docs.

**Comment by jimgwhit** [comment]
Will do, but something strange about 9 days ago a cake install created a config\app.php file, I tryed a new install just now but no config\app.php was created.  But the docs should cover all files to keep track of one way or the other.

**Comment by inoas** [comment]
If you followed the docs and installed via composer create + cakephp/app like in the docs, it will work!

**Comment by josegonzalez** [comment]
I just ran the `create-project` compose command to verify that the `app.php` file is created with a new repository:

```
$ composer create-project --prefer-dist cakephp/app test-app
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Installing cakephp/app (3.3.1)
  - Installing cakephp/app (3.3.1)
    Downloading: 100%

Created project in test-app
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing aura/installer-default (1.0.0)
    Downloading: 100%

  - Installing cakephp/plugin-installer (0.0.15)
    Loading from cache

  - Installing psr/log (1.0.0)
    Downloading: 100%

  - Installing cakephp/chronos (1.0.0)
    Loading from cache

  - Installing mobiledetect/mobiledetectlib (2.8.22)
    Loading from cache

  - Installing psr/http-message (1.0.1)
    Loading from cache

  - Installing zendframework/zend-diactoros (1.3.6)
    Loading from cache

  - Installing aura/intl (1.1.1)
    Downloading: 100%

  - Installing cakephp/cakephp (3.3.3)
    Loading from cache

  - Installing symfony/yaml (v3.1.4)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v3.1.4)
    Loading from cache

  - Installing symfony/filesystem (v3.1.4)
    Loading from cache

  - Installing symfony/config (v3.1.4)
    Loading from cache

  - Installing robmorgan/phinx (v0.5.3)
    Loading from cache

  - Installing cakephp/migrations (1.6.3)
    Loading from cache

  - Installing jakub-onderka/php-console-color (0.1)
    Downloading: 100%

  - Installing jakub-onderka/php-console-highlighter (v0.3.2)
    Downloading: 100%

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Downloading: 100%

  - Installing nikic/php-parser (v2.1.1)
    Downloading: 100%

  - Installing symfony/var-dumper (v3.1.4)
    Loading from cache

  - Installing psy/psysh (v0.7.2)
    Downloading: 100%

  - Installing jdorn/sql-formatter (v1.2.17)
    Downloading: 100%

  - Installing cakephp/debug_kit (3.3.3)
    Downloading: 100%

  - Installing cakephp/bake (1.2.8)
    Loading from cache

cakephp/app suggests installing markstory/asset_compress (An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.)
cakephp/app suggests installing phpunit/phpunit (Allows automated tests to be run without system-wide install.)
cakephp/app suggests installing cakephp/cakephp-codesniffer (Allows to check the code against the coding standards used in CakePHP.)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
cakephp/debug_kit suggests installing ext-sqlite (DebugKit needs to store panel data in a database. SQLite is simple and easy to use.)
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> App\Console\Installer::postInstall
Created `config/app.php` file
Set Folder Permissions ? (Default to Y) [Y,n]? y
Permissions set on /Users/jose/src/test-app/tmp/cache
Permissions set on /Users/jose/src/test-app/tmp/cache/models
Permissions set on /Users/jose/src/test-app/tmp/cache/persistent
Permissions set on /Users/jose/src/test-app/tmp/cache/views
Permissions set on /Users/jose/src/test-app/tmp/sessions
Permissions set on /Users/jose/src/test-app/tmp/tests
Permissions set on /Users/jose/src/test-app/tmp
Permissions set on /Users/jose/src/test-app/logs
Updated Security.salt value in config/app.php
jose@mactaku:~/src  $ cd test-app/
jose@mactaku:~/src/test-app  $ ls config/ap
app.default.php  app.php
jose@mactaku:~/src/test-app  $ ls config/app.php
config/app.php
```

For existing projects, we recommend taking a look at the [migration guides](http://book.cakephp.org/3.0/en/appendices/3-x-migration-guide.html) when moving between versions. Some changes are non-trivial to perform automatically - especially those that change classes/files users may have already modified - so we document those in the migration guide as necessary, and otherwise try to keep it to a minimum.

The `config/app.php` file just returns an array, and isn't in `cakephp/cakephp` as it is intended to be modified by the user's application. It wouldn't make sense to have that file in a `vendor` directory. As this file is autogenerated on application creation, you can follow changes to what it is based on [here](https://github.com/cakephp/app/blob/master/config/app.default.php).

The `app` folder is basically the directory containing your `[config, src, vendor]` etc. directories. This `app` folder is based on the `cakephp/app` project, for which we make releases that you can follow along and grab any necessary changes for your application. Breaking changes to `cakephp/cakephp` that may affect your application will always be documented in the [migration guides](http://book.cakephp.org/3.0/en/appendices/3-x-migration-guide.html). For the same test application above, this is mine:

```
jose@mactaku:~/src/test-app  $ ls -lah
total 84K
drwxr-xr-x 21 jose staff  714 Sep 22 15:56 .
drwxr-xr-x 13 jose staff  442 Sep 22 15:55 ..
-rw-r--r--  1 jose staff  329 Aug 26 19:32 .editorconfig
-rw-r--r--  1 jose staff  772 Aug 26 19:32 .gitattributes
-rw-r--r--  1 jose staff   41 Aug 26 19:32 .gitignore
-rw-r--r--  1 jose staff  303 Aug 26 19:32 .htaccess
-rw-r--r--  1 jose staff  623 Aug 26 19:32 .travis.yml
-rw-r--r--  1 jose staff 1015 Aug 26 19:32 README.md
drwxr-xr-x  5 jose staff  170 Aug 26 19:32 bin
-rw-r--r--  1 jose staff 1.5K Aug 26 19:32 composer.json
-rw-r--r--  1 jose staff  47K Sep 22 15:56 composer.lock
drwxr-xr-x  9 jose staff  306 Sep 22 15:56 config
-rw-r--r--  1 jose staff  648 Aug 26 19:32 index.php
drwxr-xrwx  3 jose staff  102 Aug 26 19:32 logs
-rw-r--r--  1 jose staff 1.2K Aug 26 19:32 phpunit.xml.dist
drwxr-xr-x  3 jose staff  102 Aug 26 19:32 plugins
drwxr-xr-x  9 jose staff  306 Aug 26 19:32 src
drwxr-xr-x  5 jose staff  170 Aug 26 19:32 tests
drwxr-xrwx  5 jose staff  170 Aug 26 19:32 tmp
drwxr-xr-x 19 jose staff  646 Sep 22 15:56 vendor
drwxr-xr-x  8 jose staff  272 Aug 26 19:32 webroot
```

If you did not use the `create-project` composer command and simply downloaded a compiled base cake project from one of our releases, that is functionally equivalent to the output of the `create-project` composer command against the `cakephp/app` project. Consider that repository scaffolding, similar to `laravel/laravel`, whereas our `cakephp/cakephp` is like `laravel/framework`.

If you created a new directory and simply ran `composer require cakephp/cakephp` to start off your project, you are on your own in regards to upgrading the core of your application.

Hope that helps. If not, I think this is better suited for for our [Slack channel](http://cakesf.herokuapp.com/) or `irc.freenode.net/#cakephp` - both of which are mirrored to one another. If there is an issue with documentation, we can better sort it out over chat and then either file the issue in [cakephp/docs](https://github.com/cakephp/docs) or make a pull request directly to where it is necessary.

---

As an aside, I know everyone gets excited about this and that, or likes to posture about how awesome a developer they are, or how they are excellent at reading documentation/writing great code, but let us all please behave in a civilized manner. It's frustrating as a core developer to see conversations derailed, as it reflects poorly on the framework (and therefore our own work). I can't say I speak for every core dev, but lets all get along :)
