### ISSUE TITLE
Custom patcher pattern for Table

### ISSUE THREAD

**Issue by cjquinn** [cakephp/cakephp#9746]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.next

### Problem

With the ability to configure `patchEntity` with a lot more options now I sometimes end up with something like the following.

```
$this->Articles->patchEntity($article, $this->request->data, [
    'accessibleFields' => [
        'author' => true,
        'images' => true,
    ]
    'associated' => [
        'Authors' => [
             'validate' => 'nondefault'
        ],
        'Images' => [
            'validate' => 'nondefault'
        ]
    ]
]);
```

These kind of patch statements are starting to chunk up my controllers, but if you want to be have explicit control like this its necessary.

### Solution

Implement a similar design pattern to custom finder methods, allowing user to encapsulate configuration and other marshalling steps. An implementation I've toyed with is allowing the `$options` array to accept a string and if so call the appropriate custom patcher method.

```
$this->Articles->patchEntity($article, $this->request->data, 'editing');
// Would call
$this->Articles->patchEntityEditing($article, $data, $options = []);
```

**Comment by markstory** [comment]
Is there a reason you don't implement methods on your table classes that package up your commonly used `patchEntity` calls? That seems like something you could do with no extra framework code.

**Comment by cjquinn** [comment]
Yeah I could and do! I often end up with methods like `prepareEntity` in an attempt to make it still feel like its the "cake" way. Otherwise the call to `patchEntity` is encapsulated elsewhere potentially making controllers less readable.

I suppose the existing functionality that I am drawing inspiration for this feature from is custom finder methods which could also be accomplished without any extra framework code.

**Comment by markstory** [comment]
`find()` does a bit of footwork though. It builds the query, curries in options and a few other tasks. If we were going to an extensible way to define entity patching what would the extensible system the framework provides add value wise?

**Comment by cjquinn** [comment]
I think it would be the design pattern, giving users a pre-baked way to solve a common problem. `patchEntity`'s option array seems to be constantly growing due to the fact that there are so many use cases for this action.

**Comment by dereuromark** [comment]
Why not the other way around for you?
You call

    $this->Articles->patchEntityEditing($article, $this->request->data())

which then internally calls

    $this->Articles->patchEntity($article, $data, $superHugeOptions)

**Comment by cjquinn** [comment]
That is pretty much what I end up doing :) - The point I'm making is that I dig the design pattern behind custom finder methods and wanted to see what people thought about applying that to this. Its nice and clean and any other cake developer knows what you're doing.

**Comment by dereuromark** [comment]
But for finders it makes sense because you can stack them etc.
For your use case going from calling the specific ones first and internally calling them main wrapper makes maybe more sense, since stacking is not really something you would ever do with patching, if anything only with the preparation of data (which you can handle on your model level).

**Comment by ADmad** [comment]
I too am not sold on the idea of having a special design pattern for entity patching. You can just override `patchEntity` or use custom methods as suggested.

**Comment by thinkingmedia** [comment]
The custom finder patterns works, because it uses a chainable query object that can be modified via the a callback in the table object.

To make patching work the same we would need to do something like this.

```
    $this->Articles->patch($article)
              ->with($this-request->data())
              ->allow(['authors','images'])
              ->contain(['Authors', 'Images'])
              ->execute();
```

With a custom patch you could do the above as follows.

```
     class ArticlesTable extends AppTable {
             public function patchWithImages(Patcher $patch) {
                    return $patch->allow(['authors','images'])
                           ->contain(['Authors','Images']);
             }
     }

     // later
    $this->Articles->patch('withImages', $article)
              ->with($this->request->data())
              ->execute();
```

The problem I have with this is as follows.

- it doesn't represent something that needs to be *built*, but it uses the builder pattern.
- it adds to the learning curve of cake but offers little of value back to the developer.
- it requires a lot more code be written for a feature that already works fine the way it is.
- if a patch goes wrong it'll be harder to find out why and where in the code is the bug.

As you can see, I understand what you're asking for and it's a cool idea. We just need to apply that pattern in spots where it makes sense. I think patching is nothing more then a fancy merging of data. Why make it more complicated?

**Comment by cjquinn** [comment]
Fair points well made 👍
