### ISSUE TITLE
i18n - Specified key was too long

### ISSUE THREAD

**Issue by BassemN** [cakephp/cakephp#9876]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10.
* Platform and Target: Linux with MySQL version: 5.1.45p1-log - PHP Version 5.5.17 - 

### What you did
I run i18n.sql 
```sql
CREATE TABLE i18n (
    id int NOT NULL auto_increment,
    locale varchar(6) NOT NULL,
    model varchar(255) NOT NULL,
    foreign_key int(10) NOT NULL,
    field varchar(255) NOT NULL,
    content text,
    PRIMARY KEY (id),
    UNIQUE INDEX I18N_LOCALE_FIELD(locale, model, foreign_key, field),
    INDEX I18N_FIELD(model, foreign_key, field)
)
```

### What happened
I got this error
```Error in query (1071): Specified key was too long; max key length is 1000 bytes```

### What you expected to happen
I expect that the i18n table should be created.

**Comment by chinpei215** [comment]
You should use InnoDB, instead of MyISAM. Also, please don't use this issue tracker as a help forum. Instead, please visit one of the following:
- [The CakePHP Manual](http://book.cakephp.org)
- [The CakePHP online API](http://api.cakephp.org)
- [CakePHP Official Forum](http://discourse.cakephp.org)
- [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
- [Slack channel](http://cakesf.herokuapp.com/)
