### ISSUE TITLE
$this->viewBuilder()->templatePath() limits to prefix/controller path only

### ISSUE THREAD

**Issue by dvlprs** [cakephp/cakephp#9909]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.10
* Platform and Target: Linux

### What I did
1. 
    ```
    $this->viewBuilder()->layout(false);
    $this->viewBuilder()->template('blank');
    $this->viewBuilder()->templatePath('');
    ```
2.
    ```
    $this->viewBuilder()->layout(false);
    $this->viewBuilder()->template('blank');
    $this->viewBuilder()->templatePath('/');
    ```

### What happened
1.
    > Confirm you have created the file: "Admin/Articles/blank.ctp" in one of the following paths:
    >  - /var/www/src/Template/Admin/Articles/blank.ctp

2.
    > Confirm you have created the file: "//blank.ctp" in one of the following paths: 
    >  - /var/www/src/Template///blank.ctp

### What I expected to happen
Render `/var/www/src/Template/blank.ctp`

**Comment by dvlprs** [comment]
I've just tried `$this->viewBuilder()->templatePath('.')` and it actually worked. Unsure whether to keep this open.

**Comment by ADmad** [comment]
There really is no good reason to put your templates directly under `src/Template`. If you have common templates used across multiple controller you can for e.g. put them in `src/Template/Common` and set templates path to `Common`.

Regardless since you can already you `'.'` to achieve what you want there's nothing to be done here. Hence closing the issue.
