### ISSUE TITLE
 How to use the Search plugin with the TranslateBehavior

### ISSUE THREAD

**Issue by djonatanb** [cakephp/cakephp#9980]
* CakePHP Version: 3.3.9
* Platform and Target: CakeDC Plugin, Native TranslateBehavior

### What you did
Followed the guidance on how to setup and use the translate behavior defined here: https://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-multiple-translations
Followed the guidance for CadeDC/search as here:
https://github.com/CakeDC/search/blob/master/Docs/Home.md

### What you expected to happen
Was expecting I would be able to apply the same search logic to the translated content, is there an stablished way of doing it or I will have to throw everything out and deal with the Shadow translate plugin to be able to search ?
Should I try overwriting the Translate Behavior ?

**Comment by robertpustulka** [comment]
`TranslateBehavior` does not substitute find conditions.

For `foo` translated field on `Bars` table you should search through `Bars_foo_translation.content` instead of `Bars.foo`.

Also try [FOF's Search plugin](https://github.com/FriendsOfCake/search) - I believe it's a more flexible implementation of a search feature.
